### ISSUE TITLE
Android - New Chat and New Group is broken - list of users is blank

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10079]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with expensifail account
3. Tap on Fub menu

## Expected Result:
New Chat and New Group is broken - list of users should appear

## Actual Result:
New Chat and New Group is broken - list of users is blank

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.86.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** expensifail account

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/180845726-c782c47d-a9b4-41d3-821d-2bba26411f6c.mp4

https://user-images.githubusercontent.com/93399543/180846058-039d8bd0-d5e5-4d94-8ae1-9cb8e6c818bd.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
This happens when the keyboard is open but if the keyboard is closed, you can see the member list.

**Comment by pecanoro** [comment]
I think this [PR](https://github.com/Expensify/App/pull/9895) might have broken this when changing the KeyboardAvoidingView. cc/ @jasperhuangg @marcaaron @iwiznia @arosiclair

**Comment by jasperhuangg** [comment]
Ahh, the missing options list under new chat must be because of how views and flexbox are platform dependent; the view that contains the options list probably isn't growing to fill the flex container. 


As for the missing FAB options I don't think they would be affected by my PR. 

Regardless, I'll take a look at this first thing tomorrow when I'm back from OOO. Thanks for catching this!

**Comment by iwiznia** [comment]
Let's revert the PR then?

**Comment by pecanoro** [comment]
There are no missing FAB options, the problem is only the keyboard opening, I tried on my phone and I was able to reproduce so unless we want all phones with the bug I am with Ioni, we should revert the PR until we get to fix it.

**Comment by luacmartins** [comment]
@jasperhuangg can we revert [this PR](https://github.com/Expensify/App/pull/9895) since it seems to be causing this issue?

**Comment by luacmartins** [comment]
@kbecciv we reverted the PR that may have caused this issue. Can we retest and close this issue if it's a pass? Thank you!

**Comment by luacmartins** [comment]
This seems to have been fixed by the [revert](https://github.com/Expensify/App/pull/10113). Closing!

**Comment by kbecciv** [comment]
@luacmartins Issue is still exist in Android app on  build 1.1.86.8
![Screenshot_20220802-165203_New Expensify](https://user-images.githubusercontent.com/93399543/182473446-2401de6c-d122-4ca0-877c-0fd816ba17b2.jpg)
![Screenshot_20220802-165209_New Expensify](https://user-images.githubusercontent.com/93399543/182473450-04ac1440-678f-4d6f-a189-5d457b4e9c57.jpg)

**Comment by luacmartins** [comment]
Hmm I'll reopen it to investigate then, but I don't think it's a blocker anymore

**Comment by jasperhuangg** [comment]
> There are no missing FAB options, the problem is only the keyboard opening

@kbecciv @pecanoro mentioned that there aren't any missing FAB options, the main bug here is the problem with displaying the list of users in the New Chat and New Group pages, which both have been resolved in https://github.com/Expensify/App/pull/10140

Therefore I'm going to close this out.
