### ISSUE TITLE
[HOLD for payment 2022-11-08] [$250] VBA - Error message not dismissed after selecting address from autofill option

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12122]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #11611
## Action Performed:
1. Launch the app and login
2. Select a workspace > Connect a bank account > Proceed to company info page
3. Click save and continue without entering any info
4. Enter company name
5.Type an address and select from the auto fill option

## Expected Result:
Validation error message dismissed for city and zip code field

## Actual Result:
Validation error message not dismissed for city and zip code field

## Workaround:
unknown
## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.19-1
**Reproducible in staging?:** y
**Reproducible in production?:** Could not check in production
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5791732_Screen_Shot_2022-10-25_at_10 52 26_AM](https://user-images.githubusercontent.com/43996225/197810061-411fc3a1-3806-428a-b61e-b2dc55770351.png)

https://user-images.githubusercontent.com/43996225/197810065-8314c2e0-0a0b-4ebd-85b7-139d4cd9b882.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
Added Blocker label since we are not able to verify in PROD. Pls remove if you think this is not a blocker

**Comment by arosiclair** [comment]
@kavimuru was there any issue submitting the form even with this error message problem?

**Comment by kavimuru** [comment]
@arosiclair We didn't have any issue in submitting the form.

**Comment by thesahindia** [comment]
Not a deploy blocker. It is reproducible on production. I had reported it on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1665916218609839).

**Comment by arosiclair** [comment]
Reproduced on web in **staging v1.2.19-2** and **prod v1.2.18-10**. This also seems to be purely cosmetic since you can still submit the form with the error message not dismissed so not a deploy blocker IMO. Removing deploy blocker label and marking as external.

**Comment by mallenexpensify** [comment]
@arosiclair , before adding the `External` label, unassign yourself, otherwise GH can glitch and remove folks like it did here https://github.com/Expensify/App/issues/12122#event-7675203513

Job is posted https://www.upwork.com/jobs/~01e2ce2fe9a4806aec

**Comment by Uros787** [comment]
### Proposal
RCA:
The error is happening on [CompanyStep.js](https://github.com/Expensify/App/blob/586ecbdfb743b7ba64e84d3fcba617f79bb0101b/src/pages/ReimbursementAccount/CompanyStep.js)
On lines:
https://github.com/Expensify/App/blob/586ecbdfb743b7ba64e84d3fcba617f79bb0101b/src/pages/ReimbursementAccount/CompanyStep.js#L215-L230
The commit that introduced this error is this one: https://github.com/Expensify/App/commit/a224f664118e8c5abade6966cfae1fd5908a3bb2#
Someone wanted to reuse the already implemented clearErrorAndSetValue, which tbh makes sense and I liked it at first. But then I realised that this way of using the function updates the state at least 3 or 4 times more. Which we can all agree on is not desirable.
Now this multiple state updating messes with the form helper and somehow doesn't clear the error message from FormHelper state, although it is called properly. React states am I right

**Solution:**
Now my idea is to just reduce the state updating calls, which improves performance and fixes the bug. We can revert on how it was done previously before this commit.

**Code changes:**
Change `onFieldChange` on line 215 to look like this.
```
const renamedFields = {
  street: "addressStreet",
  state: "addressState",
  city: "addressCity",
  zipCode: "addressZipCode",
};
const renamedValues = {};
_.each(values, (value, inputKey) => {
  const renamedInputKey = lodashGet(renamedFields, inputKey, inputKey);
  renamedValues[renamedInputKey] = value;
});
this.setState(renamedValues);
this.clearErrors(_.keys(renamedValues));
ReimbursementAccount.updateReimbursementAccountDraft(renamedValues);
```

After fix:

https://user-images.githubusercontent.com/70144379/198145708-486d4e6c-0bfc-4911-a1c5-4a21eb162d48.mov

**Comment by jasperhuangg** [comment]
@Uros787 thanks for the investigation, if this is a regression then I'm confident that you've found the issue to the problem, feel free to start implementing and I'll get @mallenexpensify to create a job on Upwork for ya. Please request me for review on your PR once you've submitted it.

**Comment by mallenexpensify** [comment]
Assigned to @Uros787 and created job, please apply. 
https://www.upwork.com/jobs/~0169752bebd6f85148

**Comment by Uros787** [comment]
@jasperhuangg Thanks, ill get on it. Hopefully ill get it out today
@mallenexpensify thanks, applied

**Comment by mallenexpensify** [comment]
Ir looks like this hit production on 2022-11-04
https://github.com/Expensify/App/pull/12239#issuecomment-1303898627

Going to pay tomorrow unless @sobitneupane or @jasperhuangg says I shouldn't (tomorrow instead of waiting 7 days because I'm OOO for a while)

**Comment by thesahindia** [comment]
I believe I am eligible for the reporting compensation since I had reported this issue on 16 Oct ([slack post](https://expensify.slack.com/archives/C01GTK53T8Q/p1665916218609839))

**Comment by jasperhuangg** [comment]
hey @thesahindia thanks for the bump we'll make sure to get you paid out as well, thanks for reporting! cc @mallenexpensify

**Comment by mallenexpensify** [comment]
@thesahindia for potential payment for reporting, would this issue have been fixed with the refactor from https://github.com/Expensify/App/issues/10738 had you not reported it?   I'm guessing not cuz that's why this issue was worked on.   Gut checking myself before paying to make sure I'm not missing anything

**Comment by thesahindia** [comment]
> I'm guessing not cuz that's why this issue was worked on.

Correct. PR for https://github.com/Expensify/App/issues/10738 was already merged 18 days ago and didn't fix this.

**Comment by mallenexpensify** [comment]
@thesahindia and @Uros787 have been hired.  Please comment once you've accepted and @kevinksullivan will pay (I'll be OOO).  Thanks Kev
https://www.upwork.com/jobs/~0169752bebd6f85148

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by thesahindia** [comment]
Accepted, thanks!

**Comment by kevinksullivan** [comment]
All set! Thanks everyone.
