### ISSUE TITLE
[$250] In additional details page can't clear the first name/ last name field reported by @thesahindia

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12807]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Make sure you have a name set at profile page
2. Visit https://staging.new.expensify.com/enable-payments
3. Try deleting the whole name

## Expected Result: 
User should be able to clear the name completely .

## Actual Result: 
You can't clear the name completely.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.28-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/202326678-2ed58e00-acd1-4a8a-b273-28a3469ad9a3.mov

https://user-images.githubusercontent.com/43996225/202326693-daee7bc4-7040-4125-95c2-aa35887d627b.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652192776856909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~013826c459732f8dcc
- Upwork Job ID: 1593389710349824000

**Comment by hungvu193** [comment]
<b>Proposal</b>
In `AdditionalDetailsStep.js` the problem came from the way we calculated the value for first name and last name fields.
In this case, when we tried to delete the first name field and when it became empty, the `getFirstName()` function will return the firstName from `PersonalDetails.extractFirstAndLastNameFromAvailableDetails(this.props.currentUserPersonalDetails)` and made us couldn't edited the field anymore because the prop `this.props.walletAdditionalDetailsDraft.legalFirstName` was still empty so it always return `firstName`.
```javascript
    getFirstName() {
        const {firstName} = PersonalDetails.extractFirstAndLastNameFromAvailableDetails(this.props.currentUserPersonalDetails);
        return this.props.walletAdditionalDetailsDraft.legalFirstName || firstName;
    }

  <TextInput
      containerStyles={[styles.mt4]}
      label={this.props.translate(this.fieldNameTranslationKeys.legalFirstName)}
      onChangeText={val => this.clearErrorAndSetValue('legalFirstName', val)}
      value={this.getFirstName()}
      errorText={this.getErrorText('legalFirstName')}
  />
```

<b>Solution</b>
Give the TextInput `defaultValue` prop and let the `value` prop to the prop that we updated in Onyx.
```diff
                                <TextInput
                                    containerStyles={[styles.mt4]}
                                    label={this.props.translate(this.fieldNameTranslationKeys.legalFirstName)}
                                    onChangeText={val => this.clearErrorAndSetValue('legalFirstName', val)}
-                                 value={this.getFirstName()}
+                                  value={this.props.walletAdditionalDetailsDraft.legalFirstName}
+                                  defaultValue={this.getFirstName()}
                                    errorText={this.getErrorText('legalFirstName')}
                                />



                             <TextInput
                                    containerStyles={[styles.mt4]}
                                    label={this.props.translate(this.fieldNameTranslationKeys.legalLastName)}
                                    onChangeText={val => this.clearErrorAndSetValue('legalLastName', val)}
-                                   value={this.getLastName()}
+                                  value={this.props.walletAdditionalDetailsDraft.legalLastName}
+                                  defaultValue={this.getLastName()}
                                    errorText={this.getErrorText('legalLastName')}
                                />
```

**Comment by Emz27** [comment]
### Proposal
- use state for textinput values where the api values are the default values, we dont need to listen to api values after that to prevent slow/lag on input change

I have this kind of bug in our project where we used redux form in our textinputs, redux form was slow thats why it keeps repeating the values

**Comment by thesahindia** [comment]
I believe it's a good opportunity to refactor this page to use `Form` and the issue can be solved in that. Let's update the issue description unless someone disagrees.

**Comment by hungvu193** [comment]
I agree, I remember we already have plan to refactor existing form to use Form component right?

**Comment by thesahindia** [comment]
Just adding some other ways to reach additional details page (Because the mentioned steps only work when you have a bank account)

Change the code at [ModalStackNavigators.js] and visit search page (https://github.com/Expensify/App/blob/ff2454962dd10327e52d8f9fd4906585ca5521c6/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L174)
```diff
 const SearchModalStackNavigator = createModalStackNavigator([{
     getComponent: () => {
-        const SearchPage = require('../../../pages/SearchPage').default;
-        return SearchPage;
+        const EnablePaymentsPage = require('../../../pages/EnablePayments/EnablePaymentsPage').default;
+        return EnablePaymentsPage;
     },
     name: 'Search_Root',
```

On web you can just visit http://localhost:8080/enable-payments

**Comment by sobitneupane** [comment]
> I believe it's a good opportunity to refactor this page to use Form and the issue can be solved in that. Let's update the issue description unless someone disagrees.

Waiting for decision on this before reviewing proposal.

**Comment by MitchExpensify** [comment]
[Asked in #contributor-plus for more eyes](https://expensify.slack.com/archives/C02NK2DQWUX/p1669065942914629)

**Comment by tylerkaraszewski** [comment]
Letting @joelbettner take this one.

**Comment by joelbettner** [comment]
I've been tackling this. I'm refactoring the page to use our Form functionality.

**Comment by MitchExpensify** [comment]
This was handled internally, and @sobitneupane held on any reviews, so I believe the only payment due is the reporting bonus to @thesahindia - Invited you to the [Upwork Job](https://www.upwork.com/jobs/~013826c459732f8dcc) here for that payment! 

Also reapplying the External label as I'm heading ooo and this will need a new CM to complete the payment mentioned above

**Comment by thesahindia** [comment]
@davidcardoza, I have accepted the offer. Please settle this at upwork so that we can close this issue.

**Comment by davidcardoza** [comment]
Done

**Comment by joelbettner** [comment]
This issue still needs to be open because the refactor PR is still in review.
