### ISSUE TITLE
mWeb / Safari - Keyboard covers the composer

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13658]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a chat
2. Tap the composer to open the keyboard
3. Tap the send icon to dismiss the keyboard
4.  Repeat  3-4 times step 2 and 3

## Expected Result:
Keyboard should not cover the composer

## Actual Result:
Keyboard covers the composer

## Workaround:
unknown

## Platform:

Where is this issue occurring?
 
- Mobile Web (iOS safari)

**Version Number:** 1.2.41-1
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/208123101-c6e5fc9e-9727-4ee3-b2cc-d39d2e09e9ec.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @hungvu193 
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1671119487071469
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
pausing on this until[ this thread ](https://expensify.slack.com/archives/C049HHMV9SM/p1671119487071469)is resolved

**Comment by tgolen** [comment]
That thread isn't resolved and there has been no update from the contributor who said they would look into it. I personally think we should just close this. There are all kinds of known bugs with mobile safari and the keyboard, and I think this is one of the least impactful ones. Especially since it won't happen under normal use of the app, so I am just going to close this.
