### ISSUE TITLE
[HOLD for payment 2023-02-08] [$2000] iOS/Android - Unable to attach some accepted file types

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13938]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Launch the app
2. Open any chat.
3. Press the "plus" button on the bottom left
4. Press "Add attachment" button
5. Press "Choose document" so that platform-specific file picker opens
6. Choose any of the bugged filetypes (list provided below), for example - txt

## Expected Result:
Able to add attach the accepted file types

## Actual Result:
File is not attached, receiving an error message with supported filetypes, despite the file being one of the supported file types

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native

- [ ] iOS / native

**Version Number:** 1.2.47-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210274710-b2164531-631e-4db9-8618-5b83cc008d43.mov

https://user-images.githubusercontent.com/43996225/210274820-c7a4b2e7-f4d7-48db-b806-d193d8fb9bd3.MP4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672678836780029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f23499178f3f7d95</li>
        <li>Upwork Job ID: 1615044739958951936</li>
        <li>Last Price Increase: 2023-01-23</li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
Please can you attach the attachment you're trying to upload here so I can try to reproduce because this is not happening for me at a local level with the file types I have tried.

**Comment by zanyrenney** [comment]
bump @kavimuru

**Comment by kavimuru** [comment]
@zanyrenney any .doc file will work

**Comment by zanyrenney** [comment]
Thanks @kavimuru , let me test this out today!

**Comment by zanyrenney** [comment]
Thanks! reproduced. I think this one is worth fixing because docx is a standard Microsoft doc type.

**Comment by esh-g** [comment]
## Proposal

**Problem**
This is because native platforms add some additional extensions like `vnd.openxmlformats-officedocument.wordprocessingml.document` so `1.docx` becomes `1.docx.vnd.openxmlformats-officedocument.wordprocessingml.document`

**Solution**
Option 1:
We can go with this classification of native platforms and just add the `.document` extension to the allowed extensions

```diff
diff --git a/src/CONST.js b/src/CONST.js
index ddfae9690..65ae3bd47 100755
--- a/src/CONST.js
+++ b/src/CONST.js
@@ -16,7 +16,7 @@ const CONST = {
 
     API_ATTACHMENT_VALIDATIONS: {
         // Same as the PHP layer allows
-        ALLOWED_EXTENSIONS: ['jpg', 'jpeg', 'png', 'gif', 'pdf', 'html', 'txt', 'rtf', 'doc', 'docx', 'htm', 'tiff', 'tif', 'xml', 'mp3', 'mp4', 'mov'],
+        ALLOWED_EXTENSIONS: ['jpg', 'jpeg', 'png', 'gif', 'pdf', 'html', 'txt', 'rtf', 'doc', 'docx', 'document', 'htm', 'tiff', 'tif', 'xml', 'mp3', 'mp4', 'mov'],
 
         // 24 megabytes in bytes, this is limit set on servers, do not update without wider internal discussion
         MAX_SIZE: 25165824,

```

Option 2:
We can modify the `src/libs/fileDownload/FileUtils.js` to extract the `non vnd` extension.

**Comment by esh-g** [comment]
I think option 1 would be a better choice as this is expected native behaviour and office has some MIME_TYPES special to itself:
```
Extension MIME Type
.doc      application/msword
.dot      application/msword

.docx     application/vnd.openxmlformats-officedocument.wordprocessingml.document
.dotx     application/vnd.openxmlformats-officedocument.wordprocessingml.template
.docm     application/vnd.ms-word.document.macroEnabled.12
.dotm     application/vnd.ms-word.template.macroEnabled.12

.xls      application/vnd.ms-excel
.xlt      application/vnd.ms-excel
.xla      application/vnd.ms-excel

.xlsx     application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
.xltx     application/vnd.openxmlformats-officedocument.spreadsheetml.template
.xlsm     application/vnd.ms-excel.sheet.macroEnabled.12
.xltm     application/vnd.ms-excel.template.macroEnabled.12
.xlam     application/vnd.ms-excel.addin.macroEnabled.12
.xlsb     application/vnd.ms-excel.sheet.binary.macroEnabled.12

.ppt      application/vnd.ms-powerpoint
.pot      application/vnd.ms-powerpoint
.pps      application/vnd.ms-powerpoint
.ppa      application/vnd.ms-powerpoint

.pptx     application/vnd.openxmlformats-officedocument.presentationml.presentation
.potx     application/vnd.openxmlformats-officedocument.presentationml.template
.ppsx     application/vnd.openxmlformats-officedocument.presentationml.slideshow
.ppam     application/vnd.ms-powerpoint.addin.macroEnabled.12
.pptm     application/vnd.ms-powerpoint.presentation.macroEnabled.12
.potm     application/vnd.ms-powerpoint.template.macroEnabled.12
.ppsm     application/vnd.ms-powerpoint.slideshow.macroEnabled.12

.mdb      application/vnd.ms-access
```

**Comment by oesayan** [comment]
### Proposal

As @0xmiroslav correctly stated, this is a regression from #9422. 

The #9422 logic of correcting the filename is flawed - it confuses the mime-type and the extension and sometimes breaks the file uploading pipeline by adding the second part of the mime-type (e.g. application/msword - it adds msword) to the filename, renaming the file from proper abc.doc to incorrect abc.doc.msword - which causes the further checks to fail.

**Solution**



I think we should make a separate AttachmentPicker index file for Android that will have the logic. The #9422 was fixing just one issue - uploading video files from Android, now we have another issue because of that. For me it makes no sense - it is a platform specific issue that breaks other platform behaviour. It is simple to leave this logic for Android in separate file and implement a separate logic for iOS (probably something like this - 

```diff
function getDataForUpload(fileData) {
     let fileName = fileData.fileName || fileData.name || 'chat_attachment';
-    const fileExtension = `.${_.last(fileData.type.split('/'))}`;
+    const fileExtension = `.${_.last((fileData.fileCopyUri || fileData.uri).split('.'))}`;
     if (!Str.endsWith(fileName, fileExtension)) {
         fileName = `${fileName}${fileExtension}`;
     }
```

The solutions that propose adding msword and other mime types to allowed extensions are not fighting the issue at its root and do not solve the issue of other mimetypes. They also cause the incorrect filename and extension to propagate further as seen at the top of the screenshots by @dhairyasenjaliya 

@0xmiroslav solution is good and mine is similar, however I still think we should separate the logic for iOS and Android so there will be no regressions anymore. 

However, I can recall from the Slack that there are plans to actually allow uploading any filetypes - may be we should get some info about that? That would make this issue redundant.

**Comment by mollfpr** [comment]
Thank you guys for the proposals! I’ll review it tonight.

**Comment by bernhardoj** [comment]
### **Proposal**
Agree with the others problem explanation, but I would like to propose a different approach which is to change how we check if the file has an extension and get the extension from the mime type. We can use the mime library (no need to install) to do both.

```diff
diff --git a/src/components/AttachmentPicker/index.native.js b/src/components/AttachmentPicker/index.native.js
index 6944f75fd..39c5f5902 100644
--- a/src/components/AttachmentPicker/index.native.js
+++ b/src/components/AttachmentPicker/index.native.js
@@ -18,6 +18,7 @@ import withLocalize, {withLocalizePropTypes} from '../withLocalize';
 import compose from '../../libs/compose';
 import launchCamera from './launchCamera';
 import CONST from '../../CONST';
+import mime from 'mime'
 
 const propTypes = {
     ...basePropTypes,
@@ -67,9 +68,9 @@ const documentPickerOptions = {
   */
 function getDataForUpload(fileData) {
     let fileName = fileData.fileName || fileData.name || 'chat_attachment';
-    const fileExtension = `.${_.last(fileData.type.split('/'))}`;
-    if (!Str.endsWith(fileName, fileExtension)) {
+    const fileExtension = `.${mime.getExtension(fileData.type)}`;
+    if (!mime.getType(fileName)) {
        fileName = `${fileName}${fileExtension }`;
     }
     const fileResult = {
         name: fileName,

```

`mime.getType()` will return null if the file name does not have an extension, and `mime.getExtension()` will get the extension from the mime type, no need to manually map it again.

**Comment by mollfpr** [comment]
@dhairyasenjaliya @esh-g I think we don't want to add others valid extensions just to cover the issue.

**Comment by mollfpr** [comment]
I'm still testing out the other proposals...

**Comment by mollfpr** [comment]
Does anyone able to send images or videos on the iOS simulator from the latest `main` branch?

<img width="458" alt="Screen Shot 2023-01-18 at 18 50 56" src="https://user-images.githubusercontent.com/25520267/213164409-b0b69022-dc75-4c64-9f5f-5c4a3a1cfba8.png">

**Comment by mollfpr** [comment]
<img width="472" alt="Screen Shot 2023-01-18 at 18 40 17" src="https://user-images.githubusercontent.com/25520267/213164879-07206148-1410-4c22-b6c3-200f9fb048fa.png">

@0xmiroslav I got the above error when trying your proposal.

**Comment by mollfpr** [comment]
Thanks for the investigation and updated proposal @0xmiroslav!


Do you think it’s safe to use `mime` library? No I have concern about it, it’s just I haven’t use it before. cc @aldo-expensify

**Comment by oesayan** [comment]
@0xmiroslav the flower is probably a HEIC image

**Comment by bernhardoj** [comment]
### **Updated Proposal**

I am updating my proposal to handle the empty file type. It is not there is an error if we use my previous proposal, but the file name will have `.null` as the extension and eventually will be rejected when we are trying to upload the file.

```diff
diff --git a/src/components/AttachmentPicker/index.native.js b/src/components/AttachmentPicker/index.native.js
index 6944f75fd..9eda8d33c 100644
--- a/src/components/AttachmentPicker/index.native.js
+++ b/src/components/AttachmentPicker/index.native.js
@@ -18,6 +18,7 @@ import withLocalize, {withLocalizePropTypes} from '../withLocalize';
 import compose from '../../libs/compose';
 import launchCamera from './launchCamera';
 import CONST from '../../CONST';
+import mime from 'mime';
 
 const propTypes = {
     ...basePropTypes,
@@ -67,9 +68,9 @@ const documentPickerOptions = {
   */
 function getDataForUpload(fileData) {
     let fileName = fileData.fileName || fileData.name || 'chat_attachment';
-    const fileExtension = `.${_.last(fileData.type.split('/'))}`;
-    if (!Str.endsWith(fileName, fileExtension)) {
-        fileName = `${fileName}${fileExtension}`;
+    const fileExtension = mime.getExtension(fileData.type);
+    if (fileExtension && !mime.getType(fileName)) {
+        fileName = `${fileName}.${fileExtension}`;
     }
     const fileResult = {
         name: fileName,

```

I'm still using `mime.getType` to check if the file has an extension or not. If we rely on checking the end of the string, there will be a case where the file ends with `.jpg` will becomes `.jpg.jpeg`. Why can this happen? Both .jpg and .jpeg have the same mime type, which is `image/jpeg` and `image/jpg` is not a valid mime type.

Reference: https://stackoverflow.com/questions/33692835/is-the-mime-type-image-jpg-the-same-as-image-jpeg

I also personally think it is safe to use the package.

**Comment by mollfpr** [comment]
>@mollfpr your 1st issue only happens from 1 image (flower) among 6 images in iOS simulator. Other 5 images work fine. Same to you?

Ahh, yes works for the other's image! Thank you!

**Comment by mollfpr** [comment]
Thank you guys for the updated proposals, I will review them again!

**Comment by mollfpr** [comment]
Asking on Slack channel for the `mime` usage https://expensify.slack.com/archives/C01GTK53T8Q/p1674143010153149

**Comment by s77rt** [comment]
### Proposal
```diff
diff --git a/src/components/AttachmentPicker/index.native.js b/src/components/AttachmentPicker/index.native.js
index 6944f75fd2..2de50914ea 100644
--- a/src/components/AttachmentPicker/index.native.js
+++ b/src/components/AttachmentPicker/index.native.js
@@ -67,10 +67,6 @@ const documentPickerOptions = {
   */
 function getDataForUpload(fileData) {
     let fileName = fileData.fileName || fileData.name || 'chat_attachment';
-    const fileExtension = `.${_.last(fileData.type.split('/'))}`;
-    if (!Str.endsWith(fileName, fileExtension)) {
-        fileName = `${fileName}${fileExtension}`;
-    }
     const fileResult = {
         name: fileName,
         type: fileData.type,
```

The original issue reported here https://github.com/Expensify/App/issues/9422 has been fixed recently by https://github.com/react-native-image-picker/react-native-image-picker/commit/fcb8aa641fd3bc05a68228c3c4e6a88f2bbd034c so we can safely remove that code and just upgrade `react-native-image-picker`

**Comment by mollfpr** [comment]
Reviewing @s77rt proposal!

**Comment by mollfpr** [comment]
@s77rt I did try your [proposal](https://github.com/Expensify/App/issues/13938#issuecomment-1399534757) and upgraded the `react-native-image-picker` to `4.10.3` while it's fixing this issue but now I can't send video (.mp4) from _Choose from gallery_

**Android**

https://user-images.githubusercontent.com/25520267/214059648-acd34c16-d626-4d13-8af9-1c165d45fa69.mov

**iOS**

https://user-images.githubusercontent.com/25520267/214059692-19682c81-0d5f-49ca-8892-9b79ae462da0.mov

Is your proposal in your test for sending `docx` and video?

**Comment by s77rt** [comment]
@mollfpr You had to upgrade to at least v5.0.0 (v5.0.1 is the latest)

**Comment by mollfpr** [comment]
@s77rt Ahh my bad. I don't know why my npm `@latest` is installing the `4.0.3`. Testing it again.

**Comment by mollfpr** [comment]
It's working on Android for uploading videos from `Choose from gallery` and `Choose document`.

> One thing that I have noticed after upgrading is the file names all start with rn_image_picker_lib_temp_

Yes, I got the same result on Android.

On iOS I still got the same error when choosing from the gallery. It's already reported https://github.com/react-native-image-picker/react-native-image-picker/issues/1994 but it's still unclear whether this only reproduces only on the iOS simulator or also on a real device.

**Comment by s77rt** [comment]
@mollfpr You didn't try with the flower image did you? That image is broken on the simulator, please test using another

**Comment by mollfpr** [comment]
@s77rt As I said before that I test sending a video.

https://user-images.githubusercontent.com/25520267/214065125-3d4eb05e-299e-4362-8c70-cfbf3af39750.mov

**Comment by s77rt** [comment]
@mollfpr I can't reproduce the issue on iOS. Is this a regression after applying my proposal? (was it working before applying the proposal?)


https://user-images.githubusercontent.com/16493223/214070353-2c9e835b-5f66-46e5-a5d9-cf70474621df.mp4

**Comment by s77rt** [comment]
@mollfpr iPhone 14 - iOS 16.2
Maybe the issue is with the video that you are trying to use

**Comment by mollfpr** [comment]
@s77rt Still not working with different video files. Although, I change my iOS simulator to iPhone 14 - iOS 16.2 and it's working sending a video with or without your proposal. I guess that's a simulator problem.

**Comment by s77rt** [comment]
@mollfpr Okay now that the iOS issue has been addressed. What should we do regarding the file name issue in Android? Technically it's a regression, should we just include that in the opened issue?

**Comment by mollfpr** [comment]
@s77rt Well, both camera uploads and gallery uploads are using `react-native-image-picker` so it could be related. It's still not clear what name we use for the attachment but I think that will need to update your proposal when it's decided.

**Comment by s77rt** [comment]
@mollfpr If the name must match the name of your local file which is I think the best thing to do then this must be fixed upstream.
Honestly, I'm not sure what we should do, I think maybe consider this as a new issue even technically it's a regression in  `react-native-image-picker` after the upgrade

**Comment by mollfpr** [comment]
@s77rt Yeah, it should be fixed from upstream or at least they provide an option to change the prefix. I’ll test more your proposal with the other allowed extensions we have.

**Comment by s77rt** [comment]
@mollfpr What's the status / next move?
Regarding the filename issue on android (the prefix thing), it's really weird, I think it will be auto fixed somehow?
- v4.10.3: everything is prefixed with `rn_image_picker_lib_temp_`
- v4.10.2 (current): image fie names are correct
- v4.10.1: everything is prefixed with `rn_image_picker_lib_temp_`
- reinstalled v4.10.2 and now everything is prefixed with `rn_image_picker_lib_temp_`

So I think we should just proceed with the upgrade as the issue does not seem coming from the upgrade

**Comment by mollfpr** [comment]
@s77rt I have a problem sending some images ext with `Choose from gallery`.

Android:
- tif
- tiff

iOS:
- _png_ image change to _jpg_
- jpg
- jpeg

Besides that, all the attachments upload with `Choose document` is working.

**Comment by s77rt** [comment]
@mollfpr The recent changes introduced in the lib are only android related, thus any iOS issue is probably not something new. I have tried sending images on iOS seems working fine, I didn't test the png to jpg behaviour. If possible include a video.
As for Android, I can't even load the tiff image in android itself, so maybe it's the reason it's failing, I don't think Android support tiff images.


@Prince-Mendiratta Did you rebuild the app?

**Comment by s77rt** [comment]
@Prince-Mendiratta Is this happening after upgrading `react-native-image-picker`?

**Comment by aldo-expensify** [comment]
This is a lengthy thread hehe. Thanks for carrying the conversation and investigation so far and sorry for my absence! I just started looking at this.

After a first look at the conversation, I get the feeling that the ideal solution is this: https://github.com/Expensify/App/issues/13938#issuecomment-1399534757, but it may not work for some cases because of bugs in the external libraries, is this correct? if it is correct, where is it failing? Android?

If the above option is of no use because of bugs in external libraries, I'm leaning toward a solution using the `mime` external library like this: https://github.com/Expensify/App/issues/13938#issuecomment-1385410336

The proposed solutions extending `ALLOWED_EXTENSIONS` won't be considered because they are really not fixing the cause, and the regression caused by https://github.com/Expensify/App/issues/9422 remains there. Correct?

**Comment by s77rt** [comment]
@aldo-expensify You are correct however my proposal works fine. There is no new introduced bugs after the upgrade. I'm just waiting for @mollfpr to confirm the same.

**Comment by aldo-expensify** [comment]
@s77rt which version do you recommend me to test with? [v4.10.3](https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v4.10.3)?

What about [v5.0.1](https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v5.0.1)?

**Comment by mollfpr** [comment]
@aldo-expensify v5.0.0 above has the fixes.

I’m testing again my above issue. 

For now, I just try to send a tiff image on NewDot iOS and choose it from the gallery it’s converted to jpg (same as the png). So I guess it’s already there.

**Comment by mollfpr** [comment]
The tested download `.jpg` image on iOS is showing no information on the info and maybe that lead to the error. This also happens on NewDot iOS so not introduced by the @s77rt proposal.

<img width="401" alt="Screen Shot 2023-01-26 at 09 43 17" src="https://user-images.githubusercontent.com/25520267/214737491-6f8cee0e-ee98-4d1f-8f5e-b1277fe641a2.png">

My concern about the iOS part is clear now. Moving on to the Android part...

**Comment by mollfpr** [comment]
I tested again on Android regarding the _tif/tiff_ images that can't be uploaded on the NewDot production, so it's not the problem from the @s77rt proposal. I guess it's because we can't view the _tif/tiff_ on Android. But the _tif/tiff_ file still can be uploaded via `Choose document`.

If we continue with @s77rt [proposal](https://github.com/Expensify/App/issues/13938#issuecomment-1399534757) IMO the plan is to hold https://github.com/Expensify/App/issues/11085 and wait until the PR is merged to avoid the conflict.

cc @aldo-expensify

**Comment by aldo-expensify** [comment]
I have tested this lightly uploading images and a .mov video in Android and IOS:

### `react-native-image-picker` version `4.10.2`:

- IOS: seem to work just fine?
- Android:
    - Extensions get messed up
    - Filename look like: `1000000018`


### `react-native-image-picker` version `5.0.1`:

- IOS: seem to work just fine?
- Android:
    - Extensions look fine!
    - Filename look like: `rn_image_picker_lib_temp_`

**Regarding the Filename prefix changing in Android between versions:**

I'm notsure if the change in filename was related to this or something else, because @s77rt also got the `rn_image_picker_lib_temp_` using older versions ([here](https://github.com/Expensify/App/issues/13938#issuecomment-1402752376)) and in the screenshot from [this GH issue](https://github.com/Expensify/App/issues/11085#issue-1377386582) which was using the old version we can also see these long names. In summary, I don't know why I got `1000000018` when testing `react-native-image-picker` version `4.10.2` 🤷

**Comment by s77rt** [comment]
@aldo-expensify the filename issues on android is still a bit of a [mystery](https://github.com/Expensify/App/issues/13938#issuecomment-1402752376) I didn't want to bring this here since it's an existing upstream [bug](https://github.com/react-native-image-picker/react-native-image-picker/issues/1569) and also because we have the other [issue](https://github.com/Expensify/App/issues/11085) that will deal with file name eventually.

**Comment by s77rt** [comment]
@Prince-Mendiratta That raises the question, why are we using `react-native-image-picker`?

**Comment by s77rt** [comment]
@Prince-Mendiratta I really don't know much here, I just find using the image picker is more convenient as you will only get media, while document picker will list everything. I think most texting apps have two options image picker and file picker.

**Comment by s77rt** [comment]
FWIW The filename issue is reported [here](https://github.com/react-native-image-picker/react-native-image-picker/issues/1569). I tried to get this working but I think it will require a little more work than I thought.

Android image picker does not return the real path of the image that you pick and instead you will get something like: `/sdcard/.transforms/synthetic/picker/0/com.android.providers.media.photopicker/media/1000000020.jpg` trying to extract the filename from this will leave you with `1000000020.jpg` and this explains what @aldo-expensify experienced.

I would image we would first need to get the absolute path of the image then get it's name.

___

I think we may be getting a little off-topic here, readers wouldn't have enough context unless they refer to both issues.

**Comment by s77rt** [comment]
@Prince-Mendiratta Personally I think greyed out is not good enough. It just feel that the image picker is a more natural choose.

**Comment by aldo-expensify** [comment]
@Prince-Mendiratta thanks for the new proposal. I lean toward keep using `react-native-image-picker` because I think it offers a better user experience and I see little importance in the filename bug. In the ideal solution, the filename bug should be fixed at the level of the external library... has this bug been reported there?

That's my opinion on it, but I can see that there are pros/cons in both approach, so I'll ask in slack to confirm the direction we want to take.

**Comment by aldo-expensify** [comment]
Gave this a bit more thought. I think we should just proceed with https://github.com/Expensify/App/issues/13938#issuecomment-1399534757 (@s77rt proposal). @Prince-Mendiratta proposal here is trying to solve the naming issue and at the same time the extension issue. There is no need to do this in one step.

@Prince-Mendiratta you should move the part of your proposal that is related to improving names to the issue https://github.com/Expensify/App/issues/11085

**Comment by aldo-expensify** [comment]
@s77rt please make the PR for: https://github.com/Expensify/App/issues/13938#issuecomment-1399534757 so we can start reviewing

**Comment by s77rt** [comment]
@aldo-expensify 

> has this bug been reported there?

Yes,  https://github.com/react-native-image-picker/react-native-image-picker/issues/1569

> please make the PR 

Will do asap.

___

@Prince-Mendiratta 

This issue is related to file extension failure not file names. The other is related to the file names. Post your proposal there

**Comment by aldo-expensify** [comment]
> @aldo-expensify I'm working on a proposal that'll have upstream changes for react-native-image-picker to include the real filenames as well, if they're present. Can you please wait for me to update the proposal based on that?

Yes, but as @s77rt , do it in the other issue please 🙏

**Comment by s77rt** [comment]
Applied in [Upwork](https://www.upwork.com/jobs/~01f23499178f3f7d95).
[PR](https://github.com/Expensify/App/pull/14640) is ready.

**Comment by zanyrenney** [comment]
Have hired you in upwork @s77rt !

**Comment by zanyrenney** [comment]
@aldo-expensify PR is ready for review!

**Comment by mollfpr** [comment]
@zanyrenney The PR is merged and waiting to hit the staging.

**Comment by priya-zha** [comment]
Hi @zanyrenney . I wanted to ask whether am I also eligible for reporting bonus for this issue? I'm new to the channel, so I don't know the rules. It would be great if you could clear my doubts.
Thank you

**Comment by s77rt** [comment]
@zanyrenney I think I'm eligible for 50% timeline bonus. (@mollfpr too)

**Comment by mollfpr** [comment]
> [@mollfpr / @aldo-expensify] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/10467

> [@mollfpr / @aldo-expensify] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/10467#issuecomment-1413612799

>[@s77rt] Propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

@s77rt Could you help me with this? Thanks!

**Comment by s77rt** [comment]
@mollfpr I think the regression steps are the same as the reproduction steps:
1. Go to any report
2. Click the grey plus button
3. Click on add attachment
4. Click on choose from gallery
5. Select a .mp4 file
6. Verify that you can upload the file
7. Repeat steps 1 to 3
8. Click on choose document
9. Select a .docx file
10. Verify that you can upload the file

**Comment by aldo-expensify** [comment]
Requested new test to be added. Thanks @s77rt !

**Comment by aldo-expensify** [comment]
@zanyrenney has the reporting payment been handled for @priya-zha ?

**Comment by priya-zha** [comment]
@aldo-expensify I haven't got my reporting payment.

**Comment by zanyrenney** [comment]
Hey @aldo-expensify the original job is now closed - I don't know why. I can remake one for the reporting. Please confirm the following -
 - $250 price for reporting?
- any bonus for merge time?

**Comment by aldo-expensify** [comment]
> $250 price for reporting?

yes

> any bonus for merge time?

I don't think it applies to the reporting payment. The documentation [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#proposing-a-job-that-expensify-hasnt-posted) uses the word "bonus", but I think it is referring the $250 for reporting an not the % bonus in the PR section because it talks about who should receive it if there are two reporters.

![image](https://user-images.githubusercontent.com/87341702/218544884-b554a403-a202-42c5-bced-c4da0ac8656e.png)

**Comment by s77rt** [comment]
@aldo-expensify I think @zanyrenney is referring to the C/C+ bonus (timeline bonus). Looks like both @mollfpr and I are eligible for the bonus. 

- Assigned: Friday, 27 January 2023, 21:00:00
- Merged: Monday, 30 January 2023, 21:27:00
- Difference: 3 days, 0 hours, 27 minutes and 0 seconds
- Difference (excluding the weekend): 1 days, 0 hours, 27 minutes and 0 seconds

**Comment by s77rt** [comment]
@zanyrenney I just received the payment, I think this was done automatically by Upwork. Can you please confirm? Also It's missing the timeline bonus 😁

**Comment by zanyrenney** [comment]
Bonus has been paid to you @s77rt.

**Comment by zanyrenney** [comment]
@mollfpr I have sent you the bonus via the job hire - please accept it so I can pay.

**Comment by mollfpr** [comment]
@zanyrenney Yup, accepted thank you!

**Comment by zanyrenney** [comment]
Thanks @mollfpr

**Comment by zanyrenney** [comment]
Great, all paid now! closing!

**Comment by priya-zha** [comment]
Hi @zanyrenney . I haven't been hired yet for the reporting bonus.

**Comment by mollfpr** [comment]
@zanyrenney Sorry, I do not see the offer amount before. I think you have mistaken me as the reporter 😅

**Comment by s77rt** [comment]
@zanyrenney Same thing as @mollfpr I got $250. It should have been $1000 😅

**Comment by zanyrenney** [comment]
@s77rt @mollfpr - updated amount sent.

**Comment by s77rt** [comment]
@zanyrenney All good from my side. Thanks!

**Comment by priya-zha** [comment]
Hi @zanyrenney. Yes, I received the offer. Thanks.

**Comment by zanyrenney** [comment]
all are paid! thanks for your patience.

**Comment by mollfpr** [comment]
@zanyrenney Sorry again, I only receive $1000 I assume it's for the merge time bonus? But I'm haven't got the payment for the C+ role 😅

**Comment by zanyrenney** [comment]
C+ role paid @mollfpr
