### ISSUE TITLE
[Tracking] WishList

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#13969]
This issue is a placeholder for Margelo's WishList project. WIP design doc [here](https://docs.google.com/document/d/19TJzmdnu7X-yuVR5SxGvNyXqetKfH_PtbAyZRLd-VLI/edit#heading=h.aj1p1g4afz1y).

**Comment by roryabraham** [comment]
cc @mrousavy would you please comment on this issue so I can co-assign you?

**Comment by roryabraham** [comment]
@Szymon20000 you too 😉

**Comment by mrousavy** [comment]
👋

**Comment by Szymon20000** [comment]
It's not related to Expensify integration but just to keep everyone up to date. We are currently working on simplifying our architecture and implementing async rendering so that we are sure that even the most challenging lists can work on 60/120FPS.
At the same time @janicduplessis is simplifying API so that you don't need to use "ref" to update Wishlist data.

**Comment by roryabraham** [comment]
No Expensify-facing update, but I see steady movement in the wishlist room

**Comment by roryabraham** [comment]
Seeing lots of movement in the wishlist room still, no update on the Expensify-facing design doc just now.

**Comment by roryabraham** [comment]
Asked for a high-level update in slack [here](https://expensify.slack.com/archives/C035J5C9FAP/p1675715785532209?thread_ts=1675277724.921019&cid=C035J5C9FAP)

**Comment by roryabraham** [comment]
No update right now. Margelo is still making progress on the WishList Android implementation

**Comment by roryabraham** [comment]
Looks like WishList is rendering on Android now. Still has some bugs to work through, but progress!

**Comment by roryabraham** [comment]
Last update was on Feb 28th, and it seems like many of the Android bugs are fixed

**Comment by mrousavy** [comment]
Yep - we're focusing a bit more on stability and polishing some of the native platform features (e.g. bouncing/overscroll on iOS is still missing), and then we can do another round of testing/integrating it into Expensify App :)

Once everything seems stable with the current (pretty verbose) API, we will focus on the Babel plugin next.

**Comment by roryabraham** [comment]
Looks like this just went 🟢 as @janicduplessis is back from OOO

**Comment by roryabraham** [comment]
This project came up again in [this thread](https://expensify.slack.com/archives/C035J5C9FAP/p1684776433166779), and we agreed to double down on WishList for now. Hopefully we'll get to the point soon where we can do more testing of WishList in the New Expensify app.

**Comment by roryabraham** [comment]
Also asked for more updates [here](https://expensify.slack.com/archives/C035J5C9FAP/p1684403796633899) because it seems like progress has been quite limited since around February or March. I'd love to see us clear Margelo's plates a bit so we can get more focus on this issue

**Comment by roryabraham** [comment]
Latest update [here](https://expensify.slack.com/archives/C035J5C9FAP/p1685638019402269). Margelo is starting to look into incorporating WishList in E/App again now that its implementation is complete on Android

**Comment by roryabraham** [comment]
Implementation is more active now. Latest update [here](https://expensify.slack.com/archives/C035J5C9FAP/p1686323012984939)

**Comment by roryabraham** [comment]
Still 🟢 in slack: https://expensify.slack.com/archives/C035J5C9FAP/p1686838573329929

**Comment by roryabraham** [comment]
Still 🟢 – @janicduplessis is working on implementing react-native-render-html support in WishList

**Comment by roryabraham** [comment]
Still 🟢 – https://expensify.slack.com/archives/C035J5C9FAP/p1688727740876599

**Comment by roryabraham** [comment]
Some recent discussions in the #react-native-wishlist slack room regarding the differences in the way JSI objects are cached in different implementations (TurboModules v.s. react-native-worklets v.s. Reanimated v3 worklets).

Doesn't seem like any substantive change resulted from the discussion, but maybe you guys are still talking about it @mrousavy @Szymon20000 @janicduplessis ?

**Comment by mrousavy** [comment]
Yea we just chatted about REA V3 Worklets - they _might_ be faster in Worklet creation (when you first pass a Worklet to a native module, like WishList) since they do more on JS side than in the C++/JSI layer, but we think that this performance difference might not be noticeable in our case.
Of course it's good to also improve the speed here, but the compromise of depending on Reanimated instead of a minimal, core Worklet library (react-native-worklets) is not worth it as I've seen many Reanimated updates completely break the VisionCamera <> Reanimated integration. Also Reanimated is a large dependency and they don't expose the Worklet API in their latest version (REA V3).

We will continue to build on react-native-worklets for WishList as well as VisionCamera V3.
Since this now means we will have two Worklet implementations (react-native-worklets and Reanimated), we are hoping to work towards a future where we only have one core Worklets library for the RN ecosystem that gets maintained from both us and Software Mansion :)

**Comment by roryabraham** [comment]
@janicduplessis posted a new demo of WishList [here](https://expensify.slack.com/archives/C035J5C9FAP/p1690230549194329) on Monday

**Comment by roryabraham** [comment]
Working demo of WishList on the report screen! https://expensify.slack.com/archives/C035J5C9FAP/p1691161161183939

**Comment by danieldoglas** [comment]
Adding this to the [New Expensify Performance Improvements](https://github.com/orgs/Expensify/projects/71) project

**Comment by roryabraham** [comment]
There was some recent movement here, @mrousavy mentioned that they'll start thinking about a simpler declarative API soon.

**Comment by roryabraham** [comment]
@mrousavy It seems like perhaps your workation has begun. Maybe you guys can provide daily updates if integrating WishList into Expensify is one of your main priorities this week?

**Comment by mrousavy** [comment]
Yo Rory - yep we arrived in Spain yesterday! 👋🇪🇸 
We'll be prioritizing WishList this week as a group, we'll try to do daily updates!

**Comment by mountiny** [comment]
@roryabraham @mrousavy should we close this issue?
