### ISSUE TITLE
[Fabric] - Android - Bank Account - "Something went wrong" page instead of Onfido during KYC flow

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18740]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot with new expensifail account (no any bank accounts are added)
2. Send direct message
3. Go to chat an send select send money
4. Input any amount in USD and tap Pay with Expensify
5. Tap bank account
6. Proceed further with Wells Fargo credentials
7. Add bank account page is displayed with dropdown to choose account
8. Select any account f.e. 1111
9. Go back to chat again
10. Select end money again
11. Input any amount in USD and tap Pay with Expensify
12. Additional details page is displayed. Use name Alberta Charleson with SSN 3333 and submit
13. Verify Identity page is displayed
14. Click Continue

## Expected Result:
Onfido verification flow should be displayed

## Actual Result:
"Uh-oh, something went wrong!" page is displayed with options to Refresh or sign out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6bb3e68a-e290-4580-9258-e326c62fb0fe

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
I'll be working on this issue.

**Comment by WoLewicki** [comment]
I'll be working on this issue.

**Comment by j-piasecki** [comment]
Fixed in https://github.com/WoLewicki/App/commit/8ba1842f7a1680105e41a885f82bc14d6e7166b1

**Comment by kavimuru** [comment]
Issue is still reproducible. App is crashing. Attaching evidences.

https://github.com/Expensify/App/assets/43996225/4395327e-7d8f-4083-8842-a2ad3f3393ff

https://github.com/Expensify/App/assets/43996225/58ae3a92-425f-4f38-8b2e-7d696031784c

**Comment by j-piasecki** [comment]
https://github.com/Expensify/App/pull/13767/commits/9dd828a9091d1e1b4eb28c7b79411dc0c8ebb260 should fix it on both platforms
