### ISSUE TITLE
[$1000] Web- Request Money - Deleting the IOU reply still shows "1 reply"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19743]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report
2. Request some money
3. Go to the IOU chat
4. Click on the IOU preview to open its thread
5. Reply in the IOU thread
6. Delete the reply

## Expected Result:
IOU preview does not show "1 reply"

## Actual Result:
IOU preview shows "1 reply" even though there is no reply

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dbfeca15-3a06-41ab-9c84-456aa4dcd9a5

https://github.com/Expensify/App/assets/93399543/e9a4cf60-5da0-4e43-9a8f-86d030fa271b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @adeel0202 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685006754281609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b749d33ad94a9382</li>
        <li>Upwork Job ID: 1663650767389597696</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by sakluger** [comment]
Reproduced, adding external label.

**Comment by payal-lathidadiya** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request Money - Deleting the IOU reply still thread shows incorrect reply count in IOU report i.e. "1 reply"

### What is the root cause of that problem?
We're not receiving correct value for `childVisibleActionCount` in report [code here](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.js#L323)

Even after threads comment is deleted, it is counted as in visible child action count for parent report.

<details>
  <summary>API returning incorrect value for parent report</summary>

![image](https://github.com/Expensify/App/assets/130229379/13f92aed-8a79-4b37-95b0-cf9ce432cf7a)
  
</details>

<details>
  <summary>API response of child report showing deleted comments in report actions</summary>

![image](https://github.com/Expensify/App/assets/130229379/ad494496-2c25-43bc-bd31-e69c5e6734eb)
  
</details>


### What changes do you think we should make in order to solve the problem?
Fix backend logic for `childVisibleActionCount` field to return correct value by filtering out deleted report actions.

### What alternative solutions did you explore? (Optional)
None

**Comment by sakluger** [comment]
I'm OOO all next week, so I'm going to assign another BZ member to manage.

**Comment by MariaHCD** [comment]
I'm working on an internal fix for this

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by MariaHCD** [comment]
Still working on the [internal fix](https://github.com/Expensify/Auth/pull/8050) but not posting any details here since this is an issue on our external repo.

**Comment by MariaHCD** [comment]
Internal PR is in review: https://github.com/Expensify/Auth/pull/8050

**Comment by MariaHCD** [comment]
The internal fix has been merged. We can retest this once it's been deployed.

**Comment by kadiealexander** [comment]
This seems to be fixed? It's not quite how it's described in the OP (it still shows 1 reply because the original request is now considered a reply) but it increases to 2 replies when I add a comment and decreases back to 1 when the comment is removed:

https://github.com/Expensify/App/assets/59587260/1aa33dac-c95b-48b2-9e71-22cd0ed94992

**Comment by MariaHCD** [comment]
> it still shows 1 reply because the original request is now considered a reply

Yes, that's expected. You'll have to create a thread from the IOU report. 

I retested it on staging and I think we're good here!

https://github.com/Expensify/App/assets/12268372/6afbb1ba-caf3-463d-9ec5-a3b3fce9c12f

**Comment by MariaHCD** [comment]
@kbecciv could you retest this and let us know if you find any issues?

**Comment by kbecciv** [comment]
Checking

**Comment by kbecciv** [comment]
No issue, work as expected.

https://github.com/Expensify/App/assets/93399543/81f0beb1-f7de-4e89-b2d3-d9c4de2e29c7

**Comment by sakluger** [comment]
Awesome, thanks for fixing @MariaHCD!

@adeel0202 I just sent you an offer for reporting this bug.

**Comment by payal-lathidadiya** [comment]
@sakluger 
This was previously labeled as External and Help wanted. 

Though this was fixed by internal team after identitying backend issue, does participant with valid proposal get any componesation for their effort on analysis and identifying root cause?

**Comment by kadiealexander** [comment]
Assigning as I'm going OOO, seems like you're on top of this Sasha!

**Comment by sakluger** [comment]
@payal-lathidadiya if a contributor's proposal informed the solution significantly then we do consider conpensating. @MariaHCD did you use the research done by @payal-lathidadiya in your fix?

**Comment by MariaHCD** [comment]
@sakluger, @payal-lathidadiya's proposal helped me get started in the right direction for the backend fix.

**Comment by sakluger** [comment]
Thanks @MariaHCD. Would you say that @payal-lathidadiya's proposal reduced your work on this issue by 25%? 50%?

**Comment by MariaHCD** [comment]
I would say 25%, the proposal helped me to look in the right place but I still had to do quite a bit of digging in the backend to identify the root cause.

**Comment by sakluger** [comment]
Perfect, thanks! I paid out @adeel0202 for the reporting bonus, and sent an offer to @payal-lathidadiya for 25% of the contract amount for their help identifying the root cause. @payal-lathidadiya let me know once you've accepted, thanks.

**Comment by payal-lathidadiya** [comment]
@sakluger I accepted offer. thanks

**Comment by sakluger** [comment]
Thanks everyone!
