### ISSUE TITLE
The keybaord is seen for a small period of time after clicking on Invite button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19931]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to android
2. Go to any workspace
3. Go to invite members
4. Select a user
5. Make sure you are on the message page
6. Click on invite and notice that it navigates you back and keyboard is still opened for a very small period of time
7. If you follow the same steps on workspace general settings by changing the name of the workspace OR on the user's profile page , you'll see that on clicking the save button, it dismisses the keyboard immediately.
8. Since the new invite members page was created few days ago, we get to see the problem
## Expected Result: 
Keyboard should be closed before going back to the members page
##Actual Result: 
Keyboard is still opened for a small period of time on going back to the members page also

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ac14c382-182c-4b82-87d0-981028f9455f

https://github.com/Expensify/App/assets/43996225/cff21594-e918-4563-84a6-2f5a2e04dabc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685355341457599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by priya-zha** [comment]
NOTE: A similar issue was solved here before : https://github.com/Expensify/App/issues/15919 , but seems like it didn't address the keyboard dismissal in new invite members page

**Comment by francoisl** [comment]
I can still experience the issue on `main`. It's pretty subtle, but you can tell the keyboard remains visible for a short amount of time.


https://github.com/Expensify/App/assets/2229301/af80da67-0d91-4b02-84e7-25ad92ea81e9


I don't know if using `Keyboard.dismiss()` is necessary the best and most generic solution, but it fixes the issue for me.

**Comment by francoisl** [comment]
@rushatgabhane what do you think? Should we go with this simple fix, or do you think we should look for alternative proposals?

**Comment by johncschuster** [comment]
@rushatgabhane friendly bump on the question above

**Comment by johncschuster** [comment]
Bumped in Slack for a review.

**Comment by johncschuster** [comment]
@rushatgabhane is there another way to dismiss the keyboard that would resolve this behavior? Said another way, if dismissing the keyboard on a `goBack` action is not the best move, is there a different action we can associate dismissing the keyboard with?

**Comment by francoisl** [comment]
I agree we should not dismiss the keyboard in `Navigation.goBack`, in case the previous page has a text input, as @rushatgabhane mentions.

But I feel like we can still add a `Keyboard.dismiss()` specifically for in the `sendInvitation` function, like @hungvu193 [proposes](https://github.com/Expensify/App/issues/19931#issuecomment-1571311909). That function redirects to the Workspace Members page, which doesn't have any focused input by default, so it's safe to hide the keyboard.

If you think about it, it's kind of the same thing we do [here](https://github.com/Expensify/App/blob/7b00c47ee7debf7137417ac768efe8d4c6b872d0/src/pages/workspace/WorkspaceSettingsPage.js#L62-L63) in the WorkspaceSettings page.


That said, @hungvu193 I see you edited your proposal and added this:

> 2. Use `shouldDismissKeyboardBeforeClose` from ScreenWrapper.

Can you expand on that please? How would you use that props? Would it be in addition to adding `Keyboard.dismiss();` in `sendInvitation()`? The prop `shouldDismissKeyboardBeforeClose` is already `true` by default, so I don't understand what would change.

**Comment by francoisl** [comment]
Cool, thanks @hungvu193. Can you please edit your proposal and remove that bullet point number 2, to make sure the proposal reflects the actual changes we'd be making.

---

I think adding the `Keyboard.dismiss()` in `sendInvitation()` would be the most straightforward solution here, and again, it's also what we do in other components. Does that sound good to you @rushatgabhane, or do you have any other thoughts?

**Comment by francoisl** [comment]
Thank you. Let's go with your [proposal](https://github.com/Expensify/App/issues/19931#issuecomment-1571311909) then @hungvu193 🚀

**Comment by johncschuster** [comment]
@priya-zha / @rushatgabhane / @hungvu193 can you apply to the Upwork job above when you get a moment?

**Comment by priya-zha** [comment]
@johncschuster Can you please send me an offer on upwork. Actually, I don't have enough connects to apply. :sweat_smile: 
Here's my profile: https://www.upwork.com/freelancers/~011e32317dbbd489e0

**Comment by johncschuster** [comment]
Thanks for the heads up and your receipt of payment, @rushatgabhane! That's super helpful!

**Comment by johncschuster** [comment]
@hungvu193 I've just issued payment. 🎉 

@priya-zha I've just sent the offer. Can you accept that so I can issue payment? Thank you!

**Comment by priya-zha** [comment]
Thanks. Accepted.

**Comment by johncschuster** [comment]
Thanks, @priya-zha! I've just issued payment 👍
