### ISSUE TITLE
[$1000] On "Split Bill" page, the display name doesn't sync on other devices after renaming it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20010]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into Account A
2. Split a bill with multiple accounts, including Account B
3. While on the split bill page, rename the display name on Account B

## Expected Result:
Account B's display name on device A should synchronously update just after it has been renamed on account B's device

## Actual Result:
Renaming doesn't synchronously update on device A.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2b2aa9a4-0e90-4033-8f19-1d262717036b

https://github.com/Expensify/App/assets/93399543/a4bd99e5-81ad-45e7-a3c2-6dbd80db080b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685512857055539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01182a1297b99a7cd4</li>
        <li>Upwork Job ID: 1664733315940458496</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by namhihi237** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Account B's display name on device A should synchronously update just after it has been renamed on account B's device
### What is the root cause of that problem?
The problem here is that when we initialize commponent `MoneyRequestConfirmationList ` `this.state.participants` is initialized in constructor with value calculated from `this.getParticipantsWithAmount(props.participants)`. Therefore, if `props.participants` changes, `this.state.participants` is not updated accordingly.

And similarly in the `MoneyRequestModal ` component, the `selectedOptions`is initialized with the return value from `OptionsListUtils.getPolicyExpenseReportOptions(props.report)` or `OptionsListUtils.getParticipantsOptions(props.report, props.personalDetails)`. Therefore, if `props.report` or `props.personalDetails` changes, the value of `selectedOptions` will change accordingly. if props.report or `props.personalDetails` changes after the `MoneyRequestModal` component is initialized, `selectedOptions` will not change accordingly.
### What changes do you think we should make in order to solve the problem?
1. With `MoneyRequestConfirmationList` we will add.
```
componentDidUpdate(prevProps) {
    if (prevProps.participants !== this.props.participants) {
        const formattedParticipants = _.map(this.getParticipantsWithAmount(this.props.participants), (participant) => ({
            ...participant,
            selected: true,
        }));

        this.setState({ participants: formattedParticipants });
    }
}

```
2. With `MoneyRequestModal`:
```
useEffect(() => {
    setSelectedOptions(
        ReportUtils.isPolicyExpenseChat(props.report)
            ? OptionsListUtils.getPolicyExpenseReportOptions(props.report)
            : OptionsListUtils.getParticipantsOptions(props.report, props.personalDetails),
    );
}, [props.report, props.personalDetails]);

```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by bernhardoj** [comment]
We have a refactor PR [here](https://github.com/Expensify/App/pull/17964/) that will handle the name/avatar changes in confirmation page. [Here](https://github.com/Expensify/App/pull/17964/files#diff-36ce762672f28ae8eb68ed94b2d3707e161579f9912ed6aa9c07e607c6be489fR124-R132) is the specific changes that handle that. It's not final yet though, so I guess we can hold this one.

**Comment by MonilBhavsar** [comment]
Thanks! Let's put it on HOLD as the code coincides and might be fixed. 
Putting it on HOLD on issue https://github.com/Expensify/App/issues/17662

**Comment by MonilBhavsar** [comment]
still on hold

**Comment by s77rt** [comment]
No longer on hold. https://github.com/Expensify/App/issues/17662 is resolved.

**Comment by MonilBhavsar** [comment]
@namhihi237 and @honnamkuan do you want to update your proposal we have refactored the code.
@abdulrahuman5196 could you help to review the proposals here, thanks!

**Comment by Nathan-Mulugeta** [comment]
Hey @honnamkuan I just tested it right now, it is still reproducible, I will attach a video down below. It would help if you would share a screen recording with us to identify if there are any missed steps. 

https://github.com/Expensify/App/assets/111440031/fe2527d8-372c-4885-9c1f-d4920874d260

**Comment by maddylewis** [comment]
thanks for that breakdown @bernhardoj! to confirm, was the issue fixed via https://github.com/Expensify/App/issues/17662, or do we still need to address something here?

**Comment by abdulrahuman5196** [comment]
@MonilBhavsar 

@bernhardoj 's response here is correct https://github.com/Expensify/App/issues/20010#issuecomment-1623052679

This issue is now happening only for user who you have never chatted with. What the expectation here? Should the display name change? AFAIK no, correct me if wrong.

**Comment by MonilBhavsar** [comment]
This doesn't seem like issue to me https://github.com/Expensify/App/issues/20010#issuecomment-1621778418
If there is not chat between users, we won't send pusher events for name update and it won't get updated.
Not an issue IMO. cc @Beamanator @Puneet-here buddy check please 🙏

**Comment by Beamanator** [comment]
Agreed @MonilBhavsar 👍

**Comment by MonilBhavsar** [comment]
Yoo, thanks Alex 🙌

**Comment by MonilBhavsar** [comment]
@maddylewis, we can close this issue now. It will be great to add regression testing steps for this flow.
Reported issue was fixed by https://github.com/Expensify/App/pull/17964/
So, we need to pay reporting bonus to @Nathan-Mulugeta

**Comment by maddylewis** [comment]
tomorrow morning i will pay the $250 reporting bonus to @Nathan-Mulugeta and then close the issue!

**Comment by MonilBhavsar** [comment]
@maddylewis is processing payment

**Comment by maddylewis** [comment]
offer sent to @Nathan-Mulugeta

**Comment by Nathan-Mulugeta** [comment]
Just accepted offer @maddylewis

**Comment by maddylewis** [comment]
paid!
