### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] Able to invite logged in phone number to WS and throws error message for all other invited members

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20233]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Login with phone number
3. Open settings
4. Open workspaces
5. Open any workspace
6. Open members
7. Click in invite
8. Search for same number (with which you are logged in ) with @expensify.sms in end.
9. Select the result, select other users too and invite
## Expected Result: 

Display “not found” for invalid phone numbers that are submitted with @expensify.sms.
Display “not found” or a generic error for other emails with the @expensify.sms domain.
Display valid phone numbers for @expensify.sms.

## Actual Result: 
App allows to add current logged in phone number user in workspace if we add @expensify.sms behind it and after invite, provides the error.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/27210fdb-4618-4c25-b650-0078787f89e2

https://github.com/Expensify/App/assets/43996225/055da175-c802-4493-93af-10b27f314ee2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685700872311559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018cc2e6b38ce41553</li>
        <li>Upwork Job ID: 1673286555517894656</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by muttmuure** [comment]
@expensify.sms is not a public facing account name, so while this is probably unexpected, it is an extreme edge case.

I'm going to think about it a bit moer

**Comment by muttmuure** [comment]
I can't reproduce this one - it might have been fixed already.

**Comment by dhanashree-sawant** [comment]
Hi @muttmuure , I can still reproduce the issue on staging.

https://github.com/Expensify/App/assets/87513216/8e4ba4e4-30c7-4f52-a80b-58c9c5adccad

**Comment by muttmuure** [comment]
OK I can reproduce this

**Comment by muttmuure** [comment]
not overdue

**Comment by ShogunFire** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In the invite page, if we try to invite someone with @expensify.sms it can show options that shouldn't be there:
- invalid numbers
- numbers of already existing members

### What is the root cause of that problem?

When we retrieve the options of the list here: 
https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/libs/OptionsListUtils.js#L623-L624

We add the international code to the search value and then we validate if it's a valid phone number.

When we have @expensify.sms in the search value, it is not recognized as a phone number so we keep the original seach value without the international code.

Then we filter the list with that final value. The filter doesn't work for phone numbers if they don't have the international code.

### What changes do you think we should make in order to solve the problem?


In getOptions we should get rid of @expensify.sms like this:
`searchInputValue = Str.removeSMSDomain(searchInputValue);`

so it will act like a phone number, the international code will be added and the list will filter bad options.

Result:


https://github.com/Expensify/App/assets/19537677/7e5ff144-99a2-4023-914c-18a1c2f0fc13


### What alternative solutions did you explore? (Optional)

This is a detail but I suggest we also return without options if we have an @expensify.sms that is not a valid phone number because for example if the search value is 
toto@expensify.sms

with my proposal it will act like if the search value is just toto and might return a member which email is tototiti@gmail.com which may be weird

**Comment by muttmuure** [comment]
@fedirjh @ShogunFire's solution sounds interesting. What do you think?

**Comment by ShogunFire** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/20233#issuecomment-1616772807)

**Comment by ShogunFire** [comment]
Thanks @fedirjh , for me it makes sense so I updated my proposal already. Is this what you had in mind ?

**Comment by ShogunFire** [comment]
Hello @fedirjh the advantage of your method compared to mine is that it keeps the @expensify.sms in the search value but the problem is that we never add the international code to it so the issue we are trying to resolve still happens.
without international code:
![image](https://github.com/Expensify/App/assets/19537677/e360d0e8-7993-480e-9a20-f56eadcf7257)

with international code:
![image](https://github.com/Expensify/App/assets/19537677/586df34a-c409-4e32-b9f3-f994272fee19)


Maybe we can do the best of the two method: Keep the @expensify.sms but also add the internation code to the search value, do you think that would be the right way ?

**Comment by ShogunFire** [comment]
@fedirjh That was my proposal. if you want I can check if I can improve the code to match what you had in mind

**Comment by ShogunFire** [comment]
But my proposal is working fine and the code is pretty clear, can you tell me what you didn't like about it ?

**Comment by ShogunFire** [comment]
Ahh got it, this was my getEmptyOptionsObject
```

function getEmptyOptionsObject(){
    return {
        personalDetails: [],
        recentReports: [],
        userToInvite: null,
        currentUserOption: null,
    };
}
```

i just created this function because we had the same code here
https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/libs/OptionsListUtils.js#L605-L612

+

**Comment by ShogunFire** [comment]
I just tested your solution and it works fine too, can I update my proposal and still be assigned ?

**Comment by ShogunFire** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/20233#issuecomment-1616772807)

**Comment by dangrous** [comment]
huh, didn't get the automessage. Well, @ShogunFire, you can go ahead and start on the PR, I'll try to figure out Melvin

**Comment by dangrous** [comment]
There we go! This issue was marked as internal - that was the problem

**Comment by ShogunFire** [comment]
Hello @dangrous , I just applied to the upwork job, I hope my upwork id has been stored because 16 connects is a lot 😭 Expected date of paiement is today I think

**Comment by dangrous** [comment]
In 8, the option that appears should not have the `@expensify.sms` on it, right? Otherwise that works for me!

**Comment by dangrous** [comment]
Great! All set from me! I think we're just waiting on payment now?

**Comment by ShogunFire** [comment]
Can we ping the one supposed to make the payment ? I am not sure who it is

**Comment by dangrous** [comment]
Ah, bad timing on our part! @muttmuure is out of office but will be back tomorrow, and we can handle the payment then.

As for the connects/etc. - I think we can invite you to the job, so you don't have to use the connects? Not 100% on that but @muttmuure will know when he's back.

**Comment by ShogunFire** [comment]
@muttmuure Friendly bump

**Comment by muttmuure** [comment]
Offer sent to @ShogunFire

**Comment by muttmuure** [comment]
Paid @fedirjh

**Comment by muttmuure** [comment]
@dhanashree-sawant invited

**Comment by ShogunFire** [comment]
Hello @muttmuure I have accepted the offer, can you do the paiement ?

**Comment by muttmuure** [comment]
@ShogunFire - $1500
@dhanashree-sawant - $250

**Comment by muttmuure** [comment]
Everyone is paid
