### ISSUE TITLE
[HOLD for payment 2023-06-28] [$1000] Email is missing in "Invite new members to workspace" page

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20803]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings >Workspaces > Members
2.click on invite

## Expected Result:
email showing for all members

## Actual Result:
email is missing for all members

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** `main`
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan / @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686828770758129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131ca05869a50a814</li>
        <li>Upwork Job ID: 1670861674705686528</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by Beamanator** [comment]
@tjferriss I don't know if we need an engineer on this - @fedirjh made the PR & i merged it - technically @fedirjh is a C+ but they didn't do C+ duties, they fixed the bug 😅 👍

**Comment by tjferriss** [comment]
@Beamanator thanks. It sounds like we should @fedirjh as the contributor and you're the reviewer. 

As for the reporting bounty, I see the bug was first reported by @gadhiyamanan so I would assume we give them the reporting bonus over @priya-zha.

**Comment by priya-zha** [comment]
> @Beamanator thanks. It sounds like we should @fedirjh as the contributor and you're the reviewer.
> 
> As for the reporting bounty, I see the bug was first reported by @gadhiyamanan so I would assume we give them the reporting bonus over @priya-zha.

@tjferriss I reported the same bug on June 12 whereas this issue was reported on June 15. Here's the slack convo: https://expensify.slack.com/archives/C049HHMV9SM/p1686588133599859

It would be great if you could look at this and let me know your thoughts on this. :grinning: :grinning: 

Thanks

**Comment by gadhiyamanan** [comment]
@priya-zha you reported that bug for PR testing which was fixed and for that reporting bonus will be handled [here](https://github.com/Expensify/App/issues/20757) and i reported after it merged with main

**Comment by priya-zha** [comment]
It's still reproducible, so was it really fixed? If a bug has been reported for a specific build, do we need to create the same bug report again and again if the PR merges with the main or hits the staging ? Actually, i don't have much idea on this , so if someone could clarify.  I'll leave this on the team. Whatever the team decides , I'm okay with it.  😄😄😄😄

Also a related conversation here https://expensify.slack.com/archives/C049HHMV9SM/p1686659432203249?thread_ts=1686648377.836269&cid=C049HHMV9SM

**Comment by gadhiyamanan** [comment]
>It's still reproducible, so was it really fixed? 

I am not able to reproduce, are you?

**Comment by priya-zha** [comment]
@gadhiyamanan No not today. It was reproducible when the PR merged with the main. If it was already solved before the PR merged with the main , then why did the issue appear again? Also, I  have a question, Can you please let me know if we create different bug reports for the same bug if it gets reproduced on a different build? I'm sorry I don't know much about this. Or is it like we just create a single bug report for a specific bug no matter what the build is? Here's where my doubt is. It would be great if you could answer this. :smiley: :smiley: 

If we create different bug reports for the same bug which depends on the build/platform we use , then no doubt, you should be the one to be the reporter for this bug. But,  according to [this](https://expensify.slack.com/archives/C049HHMV9SM/p1686659432203249?thread_ts=1686648377.836269&cid=C049HHMV9SM) slack convo, I felt no multiple bug reports are created for the same issue. I don't know what's the procedure here. :confused: :question:  Confused totally.

**Comment by gadhiyamanan** [comment]
> according to [this](https://expensify.slack.com/archives/C049HHMV9SM/p1686659432203249?thread_ts=1686648377.836269&cid=C049HHMV9SM) slack convo, I felt no multiple bug reports are created for the same issue

the above bug which you mention is general bug which was reproducible in staging and not related to [PR](https://github.com/Expensify/App/pull/20473) according to [this](https://expensify.slack.com/archives/C049HHMV9SM/p1686659744342099?thread_ts=1686648377.836269&cid=C049HHMV9SM). the bug which was [reported](https://expensify.slack.com/archives/C049HHMV9SM/p1686588133599859) by you is related to [PR](https://github.com/Expensify/App/pull/20473) and which was solver according to [this](https://expensify.slack.com/archives/C049HHMV9SM/p1686754841555579?thread_ts=1686588133.599859&cid=C049HHMV9SM)

the bug which was reported by me and created in [GitHub](https://github.com/Expensify/App/issues/20803) was reported after merged with main

**Comment by Beamanator** [comment]
Ready for payment 👍

**Comment by Beamanator** [comment]
Bump @tjferriss

**Comment by Beamanator** [comment]
Bump again @tjferriss :D

**Comment by tjferriss** [comment]
Sorry for the delay here. I meant to re-assign before heading out on vacation. Offers have been sent to @fedirjh and @gadhiyamanan for the reporting bonus.

**Comment by gadhiyamanan** [comment]
@tjferriss accepted, thanks!

**Comment by tjferriss** [comment]
Payments have been sent.
