### ISSUE TITLE
[$1000] Sign In - Logo is displayed instead Abracadabra page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20999]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20706
## Action Performed:

1. Download, install and sign in to the Mac OSX desktop app using account A
2. Open NewDot in incognito
3. Create a new account (account B)
4. Open the email for account B, right-click the link and copy the link
5.  Go to magic link in a new tab in your web browser, and paste in the link to go

## Expected Result:
Verify that the welcome menu shows up in the original tab while the new tab shows the abracadebra page without welcome menu

## Actual Result:
Logo is displayed instead Abracadabra page when open a new tab and paste the link in the URL

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7ee4370e-3ed4-4fd6-b59b-420bd473d411

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109792789cebb3834</li>
        <li>Upwork Job ID: 1670735591088058368</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment]
I reproduced on Production, through an incognito Chrome window using conor+20999@expensifail.com

Pasting the validate URL brings the logo, and no abracadabra: 

<img width="1239" alt="image" src="https://github.com/Expensify/App/assets/5802477/e837e499-e4b5-4a38-b413-79fe5797c422">


And the original tab just sits there: 

<img width="1322" alt="image" src="https://github.com/Expensify/App/assets/5802477/48d6bc74-3868-46c9-95f3-fb49c573efbf">

**Comment by conorpendergrast** [comment]
@tienifr @hungvu193 You were retesting on Staging, or Production?

**Comment by conorpendergrast** [comment]
Yeah I have no idea - I'm copy-pasting the link from my email, and have reproduced this issue on Staging and Production. It just gets stuck on this page after I paste in the URL: 

<img width="1083" alt="image" src="https://github.com/Expensify/App/assets/5802477/1c1dc4c5-ef11-4cba-a637-a1f63e7ebe3c">

**Comment by mgotz607** [comment]
Somehow, I think it is fixed. 

<img width="1711" alt="Screenshot 2023-06-19 at 11 32 49 AM" src="https://github.com/Expensify/App/assets/137103566/ed5c4875-0aef-475c-87f4-43dbac60c5f7">

**Comment by mgotz607** [comment]
Contributor details
My Expensify account email: mgotz607@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011ee0eb36f925924f

**Comment by conorpendergrast** [comment]
Still not fixed for me, weirdly. Exactly what I'm doing: 

1. Open NewDot in incognito
2. Create a new account
3. Open the email, right-click the link and copy the link
4.  Go to magic link in a new tab, and paste in the link to go

**Comment by jeet-dhandha** [comment]
Issue is basically on cancel of alert of `Open - The Desktop App` its not moving forward.

**Comment by twisterdotcom** [comment]
I also recreated this:

https://github.com/Expensify/App/assets/9133401/9b27b1b1-911a-4e07-81ab-05d628c168e3

Outside of that window, it throws me to the desktop app and that appears to work fine:
<img width="1200" alt="image" src="https://github.com/Expensify/App/assets/9133401/051aae47-f9d9-43dd-8957-639a0305dea2">

**Comment by mountiny** [comment]
@allroundexperts @mollfpr coming from the linked PR, are you able to reproduce this?

**Comment by dangrous** [comment]
Yeah I think this is an existing bug - https://github.com/Expensify/App/issues/20136 - but supposedly it was fixed?

**Comment by conorpendergrast** [comment]
Is it a regression caused by https://github.com/Expensify/App/issues/20136, then?

**Comment by mollfpr** [comment]
Checking

**Comment by luacmartins** [comment]
I reproduced the issue. That being said, after refreshing 3-4 times the abracadabra page did show up once 🤔 This is happening both on staging and production for me.

**Comment by mountiny** [comment]
@BeeMargarida or @koko57 Would you be able to look at this issue tomorrow?  Seems like this is in the flow you are familiar with.

**Comment by koko57** [comment]
Investigating. I see we have some problem here with hiding the Splash Screen - I guess one of the conditions to render SplashScreenHider is not met and the `BootSplash.hide()` is not called. It's not reproducible locally on dev.

**Comment by arthurmfgtab** [comment]
Hey all, @koko57 just passed this over to me, I'll keep the investigation going from now on :)

**Comment by arthurmfgtab** [comment]
I tried to replicate it on my own but it seems to be working fine 🤔


https://github.com/Expensify/App/assets/55854142/f87c1da9-2a27-4957-aefe-682cbb8205f8

**Comment by twisterdotcom** [comment]
I think the key to reproducing this is that you need the desktop app installed at the same time, already signed in to another account. At least, that is how I reproduced it.

**Comment by conorpendergrast** [comment]
I updated the reproduction steps on the assumption that @twisterdotcom is right that the desktop app is the key factor here (he's usually right)

**Comment by twisterdotcom** [comment]
Yes!

**Comment by conorpendergrast** [comment]
@hoangzinh If you see "External" and "Help Wanted" as the labels, that means we're still looking for proposals

**Comment by conorpendergrast** [comment]
Waiting for @sobitneupane to review the existing proposal, and to see any other proposals too!

**Comment by conorpendergrast** [comment]
Ok, that works for me! Setting on hold and weekly for https://github.com/Expensify/App/pull/17452

**Comment by conorpendergrast** [comment]
Still on hold. Removing the labels to make sure it's clear we aren't looking for help yet

**Comment by conorpendergrast** [comment]
Still held on https://github.com/Expensify/App/pull/17452

**Comment by conorpendergrast** [comment]
#17452 is now on production. Time to check if it's still reproducible!

**Comment by conorpendergrast** [comment]
I couldn't reproduce this, so I think https://github.com/Expensify/App/pull/17452 fixed it! 

Closing tout
