### ISSUE TITLE
 Split bill - Can't select more than few users under specific Gmail account login

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21002]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with Gmail account with a lot of chats (always reproduced with [yuriy.turbo+ch7@gmail.com](mailto:yuriy.turbo+ch7@gmail.com)
2. Try to Split bill with 8 users

## Expected Result:
The user should be able to select Split bill users without any issues

## Actual Result:
As soon as a few users are selected - all the others disappear, the search also does not work.
Only for specific Gmail accounts

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/65618b61-cb06-4b5e-8a76-332c1de07e56

https://github.com/Expensify/App/assets/78819774/dcc2f393-c10d-49c5-b738-5f57cdd22d27

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Yes looking 👀

**Comment by marcaaron** [comment]
Yikes this flow seems _super broken_...

**Comment by marcaaron** [comment]
**Crashing here:** 

https://github.com/Expensify/App/blob/f1b37bb8f78952266dc32096b7d55cf99f0fc29b/src/libs/OptionsListUtils.js#L745-L748

**Last touched here:**

https://github.com/Expensify/App/pull/19515

possibly related to this one: https://github.com/Expensify/App/pull/20371/files 

Still looking...

**Comment by marcaaron** [comment]
Fix incoming. I think we will maybe want to look into fixing this in Web-E based on the conversation here: https://expensify.slack.com/archives/C07J32337/p1687199748385919?thread_ts=1687190209.326479&cid=C07J32337 cc @Beamanator

**Comment by marcaaron** [comment]
After the crash is fixed there is an issue related to duplicate accounts showing up. Caused by report options and personal details options not having `login` fields at all here:

https://github.com/Expensify/App/blob/55e3cb9ddadde1e7ca3c60d1586343a84ffc9754/src/libs/OptionsListUtils.js#L730-L734

I am going to presume it's because we removed them in Auth/Web-Expensify without first migrating the App code, but will continue to help investigate tomorrow if required!

@Beamanator @puneetlath I think whatever we did in Auth/Web is really a "web deploy blocker" in that once it goes to production it will break the current App because the code expects `login` to exist on all these fields. I tested this issue on staging app + production web and it doesn't exist there.

Probably a safer rollout would be to update the App code to work for all cases then introduce changes in Auth and Web-Expensify.

**Comment by aldo-expensify** [comment]
I'm also seeing the crashes in dev, and my own account multiple times in the result list when searching for a chat.

<img width="1032" alt="image" src="https://github.com/Expensify/App/assets/87341702/8fcd60f2-e3bd-4a0a-a5c4-24c5a7d87c5e">

**Comment by luacmartins** [comment]
This is still a bug, but I'm removing the blocker label as per [this comment](https://expensify.slack.com/archives/C05E4M0QHLY/p1687297845827569?thread_ts=1687297728.940939&cid=C05E4M0QHLY).

**Comment by marcaaron** [comment]
@lanitochka17 can we get a retest on this one? I think it's been fixed maybe?

**Comment by youssef-lr** [comment]
This seems to have been fixed, I can't reproduce it on staging.

**Comment by lanitochka17** [comment]
@marcaaron Hello, still reproducible, in search dialog a lot of old chats, but in Split bill - no. Checked with yuriy.turbo+ch7@gmail.com “problematic” account

https://github.com/Expensify/App/assets/78819774/a6cc22f9-097e-43ed-8705-b7db06acb1a8

**Comment by marcaaron** [comment]
Can you sign out and sign back in to see if the issue persists? I am suspecting this is due to some bad data stored.
