### ISSUE TITLE
[HOLD #15212] Web -  Green "New" line indicator does not disappear after marking as read from LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21453]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat and right click on one of the posted comments
2. Right click on the chat from the LHN and click on mark as read

## Expected Result:
The green "New" line indicator should disappear

## Actual Result:
The indicator line does not disappear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**

**Reproducible in staging?:**

**Reproducible in production?:**

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c0d8f5e7-d143-4a11-8bf2-b2d6e7326dd1

https://github.com/Expensify/App/assets/93399543/e8d36946-360d-459f-9be8-c6ff38062956

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686942669583659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Green "New" line indicator does not disappear after marking as read from LHN.

### What is the root cause of that problem?

After marking report as read, `newMarkerReportActionID` in `ReportActionsView` is not updated, so the green new line indicator does not disappear.

### What changes do you think we should make in order to solve the problem?

We should update `newMarkerReportActionID` after `lastReadTime` is changed in `shouldComponentUpdate` of `ReportActionsView`.
```
	shouldComponentUpdate(nextProps, nextState) {
        ...
        if (nextProps.report.lastReadTime !== this.props.report.lastReadTime) {
            this.setState({newMarkerReportActionID: ''});
            return true;
        }
        ...
}
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by JmillsExpensify** [comment]
@MonilBhavsar I think we should put this issue on hold and tie it to the master issue for the unread marker, right? I'm going to go ahead and proactively do that now, though I'd like your confirmation either way!

**Comment by MonilBhavsar** [comment]
Yes please, thanks 👍

**Comment by DanutGavrus** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Web - Green "New" line indicator does not disappear after marking as read from LHN.

### What is the root cause of that problem?
1. If we mark as read from LHN, the `report's lastReadTime` updates to a new value;
2. In `ReportUtils.js`, the method `isUnread` does `return lastReadTime < lastVisibleActionCreated`, so it would retun false;
3. But, in `ReportActionsView.js` inside `componentDidUpdate`, we do not check if the report automatically became `read` in order to clear `this.state.newMarkerReportActionID`.

### What changes do you think we should make in order to solve the problem?
1. We should use the already existing method `isUnread` from `ReportUtils.js` in order to not repeat the code;
2. We should add this logic inside `componentDidUpdate` in `ReportActionsView.js`;
```js
if (!ReportUtils.isUnread(this.props.report) && this.state.newMarkerReportActionID != '') {
    this.setState({
        newMarkerReportActionID: '',
    });
}
```
3. `this.state.newMarkerReportActionID` is important in order to prevent unnecessary re-renders.

**Comment by JmillsExpensify** [comment]
Still on hold for larger unread factor.

**Comment by JmillsExpensify** [comment]
Still on hold for larger unread refactor.

**Comment by JmillsExpensify** [comment]
hold

**Comment by JmillsExpensify** [comment]
Hold

**Comment by JmillsExpensify** [comment]
Same

**Comment by JmillsExpensify** [comment]
Same

**Comment by JmillsExpensify** [comment]
Just-retested and it's still an issue.

**Comment by JmillsExpensify** [comment]
Still held on linked issue.

**Comment by MonilBhavsar** [comment]
This should be fixed! We can retest and close this issue

**Comment by Nathan-Mulugeta** [comment]
Hey @MonilBhavsar I just retested this and the issue is still reproducible.
https://github.com/Expensify/App/assets/111440031/3e9be3c9-8b76-4df6-bdb7-2f1f0f8818aa

**Comment by MonilBhavsar** [comment]
The issue is for web and actions performed states for a read comment
> Open a chat and right click on one of the posted comments
> Right click on the chat from the LHN and click on mark as read

Perhaps we can update it to "For mark as unread case and for Mobile"

**Comment by Nathan-Mulugeta** [comment]
Hey @MonilBhavsar I just retested this again on web and followed the exact steps on the OP. I still am able to reproduce the issue. I will attach a screen recording below. 
[Screencast from 11-21-2023 09:50:36 PM.webm](https://github.com/Expensify/App/assets/111440031/f678c3dc-33f1-43c3-bbda-4361a7a1e0fb)

**Comment by MonilBhavsar** [comment]
This is the expected behavior. The new marker line should persist and will only be removed when user redirects to another chat.

**Comment by JmillsExpensify** [comment]
Based on that, I'm good to close this issue and pay @Nathan-Mulugeta via Upwork.

**Comment by JmillsExpensify** [comment]
Offer sent.

**Comment by Nathan-Mulugeta** [comment]
Just accepted the offer @JmillsExpensify
