### ISSUE TITLE
[HOLD for payment 2023-11-21][$1000]  Offline -  Create task in a room with admin only

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22608]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to two accounts, Alice and Bob, in two separate browser tabs.
1. Alice creates a workspace and invites Bob as a non-Admin member.
1. Bob goes to the `#announce` room for the new workspace.
1. Bob goes offline.
1. Alice goes to the `#announce` room for the new workspace, opens room settings, and under `Who can post`, sets `Admins only`.
1. Since Bob is offline, he does not receive an update that the room has become read-only for non-admins. Therefore, he can still attempt to create a task offline in the `#announce` room.

## Expected result
When Bob comes back online, the task should appear "greyed out" with a "red brick road" error. Any actions Bob attempted to take on that task (such as leaving a reaction), should fail.

## Actual Result: 
The task appears to have been completed normally for Bob, unless he tries to create a thread with that task as the root, in which case he'll see a 404 page.

## Workaround:
Don't do that, Bob!

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1983e5a9-e67b-4a0f-9736-7fbea6a98fa5

https://github.com/Expensify/App/assets/43996225/7e1602b3-b70a-43ce-9722-c66a23fd0a93

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689010436307099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01afb147c594f572e5</li>
        <li>Upwork Job ID: 1679478215688933376</li>
        <li>Last Price Increase: 2023-07-13</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 26516237</li>
<li>namhihi237 | Reporter | 26516238</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
 The task should not be displayed in user B if creation fails or gives an error when back online with room setting admins only
### What is the root cause of that problem?
When the user creates a task when offline `optimisticData` is saved in Onyx with reportAction create a task. But after API returns data with an error after back online, `failureData` doesn't update the error for this reportAction to explain why the user cannot create a task.
### What changes do you think we should make in order to solve the problem?
- When the back online API create task will be called, after API returns an error `failureData` should update the error for report action instead of updating pending action is null like this.
```
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${optimisticTaskReport.reportID}`,
    value: {
        [optimisticTaskCreatedAction.reportActionID]: {
            errors: ErrorUtils.getMicroSecondOnyxError('task.error.genericCreateFailureMessage'),
        }
    },
```
- we also need to create a new translation for this error.
```
genericCreateFailureMessage: "Unexpected error create a task, please try again later"
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by thienlnam** [comment]
We should also remove the admins only room from the selector if you are not an admin

**Comment by thienlnam** [comment]
Oh I see, the task was created by going offline and not getting the update that it's an admin only room

**Comment by thienlnam** [comment]
Let's also address the split bill case in this issue
https://expensify.slack.com/archives/C049HHMV9SM/p1689011065028709

**Comment by thienlnam** [comment]
Hmm, we should be displaying an error in the reportAction - but maybe this should be set via pusher in the back-end

**Comment by thienlnam** [comment]
Yeah I'm aware, this will likely have to be an internal issue

**Comment by isabelastisser** [comment]
Not overdue, internal.

**Comment by isabelastisser** [comment]
@parasharrajat @Gonals is someone currently working on this?

**Comment by Gonals** [comment]
Not right now. I haven't been able to start on this yet. Hopefully in a day or two

**Comment by isabelastisser** [comment]
Any updates @Gonals ?

**Comment by Gonals** [comment]
Starting on this today! I'll have something ready tomorrow!

**Comment by Gonals** [comment]
> Starting on this today! I'll have something ready tomorrow!

I lied. W4 is going to take over my day once again 😅

**Comment by isabelastisser** [comment]
Internal, no progress yet.

**Comment by Gonals** [comment]
I'm going OOO tomorrow, so you may want to gran another engineer! Otherwise, I'll jump into it when I'm back (after a week)

**Comment by isabelastisser** [comment]
@Gonals is on parental leave, so I will re-apply the engineering label now.

**Comment by roryabraham** [comment]
In my opinion the reproduction steps are not clear. I will start by writing clearer reproduction steps here.

**Comment by roryabraham** [comment]
> A go room setting => set Admins only

Also, I'm not sure if this should be allowed for the `#announce` room, I will ask in the #product slack room.

**Comment by isabelastisser** [comment]
Not overdue, internal.

**Comment by isabelastisser** [comment]
Not overdue, internal.

**Comment by thienlnam** [comment]
Let's see if we can reproduce this - this might have already been resolved in a different PR

**Comment by isabelastisser** [comment]
@parasharrajat, thanks for confirming!

Hey @thienlnam, the issue is still reproducible; what are the next steps here?

**Comment by thienlnam** [comment]
@namhihi237 Does the task get created successfully? Or does it just error out

Because this should be blocked on the BE from happening

**Comment by thienlnam** [comment]
Yeah that looks like some good QOL improvement we can do - going to assign a C+ here

**Comment by thienlnam** [comment]
Ready to review proposals cc @parasharrajat

**Comment by thienlnam** [comment]
@gabrielessner Could you please check the copy for when a task was failed to be created?

Here are some of the existing error copy
```
        error: {
            invalidSplit: 'Split amounts do not equal total amount',
            other: 'Unexpected error, please try again later',
            genericCreateFailureMessage: 'Unexpected error requesting money, please try again later',
            genericDeleteFailureMessage: 'Unexpected error deleting the money request, please try again later',
            genericEditFailureMessage: 'Unexpected error editing the money request, please try again later',
            genericSmartscanFailureMessage: 'Transaction is missing fields',
        },

```

Maybe something like:
`Unexpected error creating a task, please try again later`?

**Comment by gabrielessner** [comment]
i am in the middle of and fully focused on re-writing roughly 30 help articles for the help dot migration, i wont be bale to get to this until tomorrow.

**Comment by thienlnam** [comment]
Thanks for the summary - I figured this might be the case.

> Currently, backend is deleting this report which is fine but not aligned with other pages in our app.

Technically the report doesn't exist in the first place, but the BE does clear the report from onyx on failure. This looks like what we have to do internally is set an error on the report itself and then the front-end PR will have to handle clearing that error / removing the report from onyx locally

**Comment by gabrielessner** [comment]
>         error: {
>             invalidSplit: 'Split amounts do not equal total amount',

This one is fine

>             other: 'Unexpected error, please try again later',

This one is so vague im afraid its not very helpful - can we maybe update it to say 'Unexpected error, please refresh the page and try again later',

> 
>             genericCreateFailureMessage: 'Unexpected error requesting money, please try again later',
>             genericDeleteFailureMessage: 'Unexpected error deleting the money request, please try again later',
>             genericEditFailureMessage: 'Unexpected error editing the money request, please try again later',

Im fine with these ones            

> genericSmartscanFailureMessage: 'Transaction is missing fields',

is it possible to include the missing fields in the error message? 

@thienlnam

**Comment by thienlnam** [comment]
@gabrielessner Ah I actually just need the single copy check - those are just examples I provided that already exist currently

This is the one we want to verify: `Unexpected error creating a task, please try again later `

**Comment by gabrielessner** [comment]
got it, sorry that wasn't clear to me earlier. 

> Unexpected error creating a task, please try again later

What is causing this error? Can we explain whats causing the error in the actual message or is that too much information? Would logging out / logging back in potentially fix it and if so, can we include that in the message? @thienlnam

**Comment by thienlnam** [comment]
> What is causing this error? Can we explain whats causing the error in the actual message or is that too much information?

This is kind of a general catch all error, so it could be a number of things. Logging out might fix it but might not depending on the issue but we don't have that context

**Comment by gabrielessner** [comment]
> Logging out might fix it but might not 

Ok, cool. If logging out _might_ fix it should we highlight that in the error? Like for example, we could say:

> Unexpected error creating a task, please try logging out and logging back in. If the error still persists, please try again later

If you don't like that idea, then I am not sure what else we could say and Im fine with just leaving as is @thienlnam

**Comment by thienlnam** [comment]
Took a look at this with some fresh eyes

> As a crash is happening, it means that fullReport is undefined which should not be the case.
>First, we should see why fullReport is getting undefined. It is getting deleted from Onyx somewhere.

I took a look at the BE again, and we're not intentionally deleting the report from onyx. I think this just happens when we clear it from onyx in the failure data https://github.com/Expensify/App/blob/c9dc4badcb742a08b3420a13b8b256a259f44660/src/libs/actions/Task.js#L134-L136

Let's be consistent with other flows like request money which seems to be the second option

Example with Request Money

1. On failure, instead of deleting the report let's add an error on the task
 errorFields: {
        createChat: ErrorUtils.getMicroSecondOnyxError('report.genericCreateReportFailureMessage'),
    },

2. Add the error on the report action as well
  [iouCreatedAction.reportActionID]: {
      errors: ErrorUtils.getMicroSecondOnyxError('iou.error.genericCreateFailureMessage'),
  },

**Comment by thienlnam** [comment]
> @thienlnam have we agreed to the translation [here](https://github.com/Expensify/App/pull/26848/files#diff-472528060691374654a2e2e866547d385eec3849efddca38cbfca1e5b3ba47d5R1537)?

Yes, let's continue with Unexpected error creating a task, please try again later

**Comment by thienlnam** [comment]
So then we don't actually clear the report, and it gets removed when we try to open the report?

**Comment by thienlnam** [comment]
Hmm, I don't know if we want to update OpenReport to work differently depending on the type of report. Though I do see it makes it difficult when OpenReport deletes the report from onyx if it doesn't exist. 

However, how do thread errors solve this? I imagine they have the same problem because when you create a thread you automatically are redirected to it calling openReport

**Comment by thienlnam** [comment]
>  IMO, we should keep all types of report creation failure behavior in the same way

I agree, the more we can keep consistent between these reports the better. 

I'll take a look in the BE later and see what is different between the new chat creation failure.

**Comment by thienlnam** [comment]
I did, and it does look like if we don't have access to a report from the back-end then we send a pusher update to clear the report.

But it's not task specific, and should be happening to failed chats as well. 

> I checked that when new Chat creation fails, openReport does not delete the report instead returns the error. This tells me that it behaving differently already.

I would be curious to see if this was still true if you switched to a different chat, and then back to the failed chat and if it ended up getting removed

**Comment by namhihi237** [comment]
@thienlnam after we switch to a different chat the wrong chat before has removed

**Comment by namhihi237** [comment]
Currently, the API returns differently when calling open report.
1. With new chat => return error
2. With task report =>  return key report with value null
So do we need to update the API, or we will use the trick below FE which is in the openReport function we can check to see if it is an error report task. If it is correct, we will reassign it with failure data. However, I do not recommend this method because it will cause confusion.

**Comment by isabelastisser** [comment]
Bump @thienlnam !

**Comment by thienlnam** [comment]
Yeah I don't like the idea of doing a front-end hack though I still am finding that the BE is doing the same thing on openReport.

I tested locally removing

        {
            onyxMethod: Onyx.METHOD.SET,
            key: `${ONYXKEYS.COLLECTION.REPORT}${optimisticTaskReport.reportID}`,
            value: null,
        },

in App, and the reportData is still there in my testing. Could this just be the case?


https://github.com/Expensify/App/assets/30609178/e5d4dbe2-0430-4fc6-bb76-946bcf62a3ec

**Comment by isabelastisser** [comment]
Hey @parasharrajat @namhihi237 @thienlnam , what are the next steps here?

**Comment by thienlnam** [comment]
> This looks good to me @namhihi237. But we should also show an error on the Task report. In the fix video above, I can see that there is RBR dot on the task report but there is no error shown while it is open. It should have an error similar to report action.

Agreed with this, it should have an error on the task report so you can clear it there as well

**Comment by thienlnam** [comment]
That's fine, it happens in other locations as well

**Comment by thienlnam** [comment]
PR almost complete, couple last comments but should be merged next week

**Comment by thienlnam** [comment]
Here's the linked PR https://github.com/Expensify/App/pull/26848

cc @isabelastisser This is ready for payment

**Comment by isabelastisser** [comment]
Thanks for the heads up, @namhihi237 ! I updated the payment amount in Upwork now.

**Comment by JmillsExpensify** [comment]
$1,000 approved for @parasharrajat based on [this comment](https://github.com/Expensify/App/issues/22608#issuecomment-1828507508).
