### ISSUE TITLE
[$1000] Request Money - Paid IOU preview showing $0 after re-login

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22946]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging.new.expensify.com or Expensify App on 2 devices - User A and User B
2. User A send several money requests to user B
3. User B paid this IOU elsewhere
4. Users A and B log out and log in again
5. Go to chat with IOU preview from step 2

## Expected Result:
IOU shows the previously paid amount

## Actual Result:
Paid IOU preview showing $0 after re-login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/27236c38-922b-462f-8978-0f24de7b3303

https://github.com/Expensify/App/assets/78819774/e480bbb8-f489-4ec7-a18a-aa63e5850324

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4bd5aaac9493670</li>
        <li>Upwork Job ID: 1680923763533008896</li>
        <li>Last Price Increase: 2023-08-07</li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
Yikes, this is weird. Triaging!

**Comment by zanyrenney** [comment]
@mollfpr what do you think about the proposals?

**Comment by mollfpr** [comment]
Fetching the IOU report seems like there are other options. We still have a delay before the `openReport` is finished.

**Comment by zanyrenney** [comment]
If this is intentional @mollfpr , should we be closing out this issue?

**Comment by mollfpr** [comment]
I'll confirm first with the team, but this should be fixed. The ideal solution might be to need to BE changes instead fetching the unnecessary report each time.

**Comment by mollfpr** [comment]
The amount is correctly shown in the current staging. I guess it's already fixed somewhere.

https://github.com/Expensify/App/assets/25520267/91a6e6da-38a0-48b0-8843-69902f4f8742

**Comment by mollfpr** [comment]
Actually, it's paid. There's another bug showing owes instead paid.

https://github.com/Expensify/App/assets/25520267/6292be4c-935e-431c-b278-a2e2eb265550

**Comment by zanyrenney** [comment]
That seems like a separate bug @mollfpr - if we want to report and fix that, let's do that in slack not as part of this issue.

**Comment by zanyrenney** [comment]
Heading ooo we're still looking for proposals, thanks in advance for the help moving this along BZ team!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by alexpensify** [comment]
Thank you for that update @mvtglobally

**Comment by alexpensify** [comment]
Thank you for the update here!

**Comment by mollfpr** [comment]
The issue with the IOU preview showing $0 is not reproduced, but we have another issue similar on the chat list in LHN.

After sign-in back, the IOU preview correctly showed the amount, but the alternate text on the chat list remains showing $0 before opening the IOU report.

https://github.com/Expensify/App/assets/25520267/45b42cee-9d9c-439d-a0ee-c4007f588c41

The requested amount is 100,000 JPY and is displayed as it is on the IOU report, but the conversion is missing two digits 00. So I think https://github.com/Expensify/App/issues/24051 is a different issue with this and shouldn't be closed.

**Comment by suneox** [comment]
I agree with @mollfpr an issue #24051 shouldn’t close because Japan, Korea currency doesn’t have decimal value and it’s a valid bug with countries has currency decimal is 0

**Comment by zanyrenney** [comment]
If the issue https://github.com/Expensify/App/issues/24051 shouldn't have been closed, let's tackle that in that issue rather that cross-posting here. Thanks @suneox @mollfpr

**Comment by alexpensify** [comment]
@zanyrenney since you are back online, I'm going to unassign myself. The latest status update is that we are still waiting for proposals here.

**Comment by ShogunFire** [comment]
So I am confused now what we are trying to resolve here, the original issue is already fixed right ?

**Comment by mollfpr** [comment]
@ShogunFire Let's wait for what the team says. Although, we still have a similar issue with the alternate text in the chat list.

**Comment by zanyrenney** [comment]
I also now cannot reproduce this and this this is solved as part of another fix. Closing. Please DM me if you disagree and think this should be reopened.
