### ISSUE TITLE
[Hold for Payment 2023-12-21][$1000] IOS - Permission popup indicates wrong message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23421]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
Go to phone settings Turn off Microphone permission.
- Go to New Expensify App
1. Go to setting
2. Go to any workspace
3. Setup Bank account
4. On last step click Save & continue

## Expected Result:
 It should show Alert for Microphone permission.

## Actual Result:
t shows Camera permission alert instead of microphone permission

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-26
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f1171187-f0ae-4db4-89f4-4cc647426f25

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689948082634299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01479aaf3e91037a82</li>
        <li>Upwork Job ID: 1683857056510726144</li>
        <li>Last Price Increase: 2023-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26071892</li>
<li>DinalJivani | Reporter | 26071895</li>
<li>ishpaul777 | Contributor | 27357555</li>
</ul></li>
    </ul>
</details>

**Comment by DinalJivani** [comment]
Here's the video for detailed steps for reproduction:

https://github.com/Expensify/App/assets/58871336/5062c49a-d64e-4a09-b8fe-300c31564b6c

**Comment by zanyrenney** [comment]
We should have this error message: 
![image](https://github.com/Expensify/App/assets/56830058/637df23f-dde4-453b-9f85-40c8c032f682)

**Comment by ishpaul777** [comment]
## Proposal

### Problem
IOS - Permission popup indicates wrong message when asking for permission for microphone, instead of requesting for microphone it asks for camera permission

### Root cause
[Here](https://github.com/Expensify/App/blob/8b236589fa5f748dc81722545478b9ef20426604/src/components/Onfido/index.native.js#L46-L49) we are checking for camera permission and based on that we are showing the popup message, microphone permission is not handled so even if errorMessage is for microphone permission it will show the popup message for camera permission because of this condition `CONST.ONFIDO.ERROR.USER_CAMERA_DENINED` is genric error message triggering alert with camera permission request.

```jsx
if (_.contains([CONST.ONFIDO.ERROR.USER_CAMERA_PERMISSION, CONST.ONFIDO.ERROR.USER_CAMERA_DENINED, CONST.ONFIDO.ERROR.USER_CAMERA_CONSENT_DENIED], errorMessage)) {
	Alert.alert(
		......
```
### Changes

1. we need to add/modify constants in CONST.ONFIDO.ERROR

ref - https://github.com/onfido/onfido-ios-sdk/blob/master/README.md#response-handler-errors
```
USER_CAMERA_DENINED: 'Onfido.OnfidoFlowError.cameraPermission', // before "Onfido.OnfidoFlowError"
USER_MICROPHONE_PERMISSION: 'Encountered an error: microphonePermission',
USER_MICROPHONE_DENINED: 'Onfido.OnfidoFlowError.microphonePermission',
```

2. check for camera and microphone permission, so we need check for microphone and camera permission seperately

```jsx
// Replace the previous condition that checks for camera permission with separate checks for camera and microphone permissions.
if (_.contains([CONST.USER_CAMERA_PERMISSION, CONST.USER_CAMERA_DENIED], errorMessage)) {
	// Alert for camera permission
} else if (_.contains([CONST.USER_MICROPHONE_PERMISSION, CONST.USER_MICROPHONE_DENIED], errorMessage)) {
	// Alert with desired translated message for microphone permission (Add the phrase keys to the translation file)
}
```

3. since the CONST.ONFIDO.ERROR.USER_CAMERA_CONSENT_DENIED is edge case and same error message for both camera and microphone permission, we should discuss a alternative behaviour for this case. (like exit the flow or show a generic error message "Something went wrong, please try again")

# Alternatively
If we can check whether we have microphone and camera permission programatically. We can show the popup message for microphone/camera permission based on that. With my research I found that we can check for permissions in [android](https://reactnative.dev/docs/permissionsandroid#check ). I am not sure whether we can check for permissions in IOS within React Native.

**Comment by zanyrenney** [comment]
bump @0xmiroslav ? please can you take a look!

**Comment by zanyrenney** [comment]
Hey @0xmiroslav - I agree with Spanish, but why can't we use the same copy as the screenshot provided here? Let me know your thoughts!

**Comment by zanyrenney** [comment]
Heading ooo we're still debating the copy here and if we need to add the waiting for copy label / get this translated in spanish! thanks in advance for the help moving this along BZ team!

**Comment by ishpaul777** [comment]
i wonder how we can we repro this on simulator? It is lauching the camera directly without asking for permisssions.

**Comment by johncschuster** [comment]
@0xmiroslav, do you have ideas for how we can reproduce this on simulator? That's a bit beyond my understanding.

**Comment by zanyrenney** [comment]
@0xmiroslav bumping for your thoughts on how to reproduce this please?

**Comment by ishpaul777** [comment]
Can't we collaborate with a C+ who has a physical iphone and can help with testing, cc- @johncschuster @0xmiroslav

**Comment by johncschuster** [comment]
I'll test this on my mobile device in the morning.

**Comment by ishpaul777** [comment]
Bump @0xmiroslav did you get the chance to review my proposal. Let me know if you have any concerns?

**Comment by situchan** [comment]
I'd like to take this as C+ based on [discussion](https://expensify.slack.com/archives/C02NK2DQWUX/p1691641008846119?thread_ts=1691488353.531539&cid=C02NK2DQWUX)

**Comment by ishpaul777** [comment]
@situchan what do you think of my proposal https://github.com/Expensify/App/issues/23421#issuecomment-1650414468

**Comment by zanyrenney** [comment]
thanks for stepping in @situchan - please review the proposal above!

**Comment by situchan** [comment]
@zanyrenney if https://github.com/Expensify/App/issues/23421#issuecomment-1650027024 can be used as English copy, can we get Spanish version for this?

**Comment by zanyrenney** [comment]
Have asked for spanish translation here - https://expensify.slack.com/archives/C21FRDWCV/p1692010538975479

**Comment by zanyrenney** [comment]
Spanish translation is: 

Acceso al micrófono denegado
Esta aplicación requiere acceso al micrófono de su dispositivo. Habilite el acceso al micrófono para esta aplicación en Configuración > Privacidad > Micrófono

**Comment by ishpaul777** [comment]
@situchan we have Spanish text copy now can I get an update here? Let me know if you have any concerns?

**Comment by situchan** [comment]
@ishpaul777 how are you going to test?

**Comment by ishpaul777** [comment]
https://github.com/Expensify/App/issues/23421#issuecomment-1669921569 
I asked the question here, i think this is a straightforward fix if anyone can help

**Comment by ishpaul777** [comment]
Or If there a way to mock the permissions you know on simulator that would be helpful.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by zanyrenney** [comment]
Hmm @mvtglobally i don't see any PR linked. Are you saying this has been solved as a bi-product of another issue?

**Comment by DinalJivani** [comment]
@zanyrenney @mvtglobally 
I see this issue is still reproducible not sure what @mvtglobally is missing here.

May be you have fresh installed app and for that you have to go to further steps in which app asks user to enable Microphone, Then you have to follow these steps:

Go to phone settings New Expensify -> Turn off Microphone permission.
Go to New Expensify App
Go to setting -> Go to any workspace
Setup Bank account -> On last step click Save & continue

Attaching full video here.

https://github.com/Expensify/App/assets/58871336/612d02af-5a58-4eed-801a-96604c91d45d

**Comment by zanyrenney** [comment]
Thanks for coming back here @DinalJivani - @mvtglobally please can you confirm and clarify the answer to my question above [here](https://github.com/Expensify/App/issues/23421#issuecomment-1686118601) thanks!

**Comment by zanyrenney** [comment]
bump @mvtglobally can you respond please?

**Comment by zanyrenney** [comment]
no response here from @mvtglobally so I have asked for clarity in Expensify Open source; here -  https://expensify.slack.com/archives/C01GTK53T8Q/p1693820129755339

**Comment by mvtglobally** [comment]
@zanyrenney our team is running weekly validation and issue may not always be repro as we have different devices. 
If contributors can still repro, mentioning in comments should help you to proceed. 
Are you personally able to repro?

**Comment by zanyrenney** [comment]
Thanks for the update, yes is reproducible for me on iOS.

**Comment by zanyrenney** [comment]
So we're still looking for proposals here @situchan

**Comment by zanyrenney** [comment]
bump @situchan ?

**Comment by situchan** [comment]
Still looking for contributor who is able to test their fix on iOS

**Comment by zanyrenney** [comment]
what can we do to help get a contributor working on this @situchan ?

**Comment by zanyrenney** [comment]
Asking for a volunteer here - https://expensify.slack.com/archives/C01GTK53T8Q/p1695260641687059

**Comment by pradeepmdk** [comment]
I will help you here I have physical Device

**Comment by DinalJivani** [comment]
> @zanyrenney @mvtglobally I see this issue is still reproducible not sure what @mvtglobally is missing here.
> 
> May be you have fresh installed app and for that you have to go to further steps in which app asks user to enable Microphone, Then you have to follow these steps:
> 
> Go to phone settings New Expensify -> Turn off Microphone permission. Go to New Expensify App Go to setting -> Go to any workspace Setup Bank account -> On last step click Save & continue
>
><details>
>
><summary>Attaching full video here.</summary>
>
>https://github.com/Expensify/App/assets/58871336/612d02af-5a58-4eed-801a-96604c91d45d
>
></details>
    

@allroundexperts Please check this full video, To reach the microphone service usage you have to go till further process of Recording user's video, then only you will see the Microphone permission usage in Settings. This is because that is the only place using Microphone service.

**Comment by zanyrenney** [comment]
Awesome, thanks for the update @allroundexperts

**Comment by zanyrenney** [comment]
any update here @allroundexperts ?

**Comment by zanyrenney** [comment]
Bump @situchan please can you provide feedback so we can move ahead to the PR. Thanks!

**Comment by zanyrenney** [comment]
bump @situchan please?

**Comment by situchan** [comment]
@allroundexperts thanks for the demo. Can you test android as well as the change also affects android?

**Comment by zanyrenney** [comment]
bump @allroundexperts for the testing on android please?

**Comment by zanyrenney** [comment]
bump @situchan @allroundexperts

**Comment by zanyrenney** [comment]
did you make progress @allroundexperts ?

**Comment by DinalJivani** [comment]
@allroundexperts 
I don't know if this would be helpful or not but want to mention that,

For Android I'm not sure but In iOS whenever System popup appears _(i.e.: For Permission Request)_ app is considered to be in Background state, 
Also if you change any permission for app running in Background it will restart the app.

**Comment by zanyrenney** [comment]
@situchan please add feedback. If you are unable to prioritise this, please say so we can reassign this? I have had to bump you numerous times on this issue and it's getting to the point where it feels like we should find another C+ otherwise.

**Comment by situchan** [comment]
I will give feedback today

**Comment by zanyrenney** [comment]
asked in slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1698054364350729

**Comment by situchan** [comment]
@allroundexperts I am not seeing your official proposal. Please submit so I can approve.

**Comment by situchan** [comment]
@ishpaul777's [alternative solution](https://github.com/Expensify/App/issues/23421#issuecomment-1650414468) looks good.
But he was not able to test on physcial device and cannot attach screenshots which is required step in PR checklist.
@allroundexperts volunteered on testing and shared demo video.

I understand that external contributors cannot easily test on iOS physical device.
So I suggest @ishpaul777 raise PR and @allroundexperts test and fill missing part of checklist.
And compensation suggestion: @ishpaul777: 75%, @allroundexperts: 25%
If everyone agrees.

🎀 👀 🎀 C+ reviewed

**Comment by situchan** [comment]
@allroundexperts thanks for the suggestion. It seems @ishpaul777 gave 👍 
ok, so share equal bounty, collaborate together on PR, both review and testing.

@chiragsalian all yours

**Comment by chiragsalian** [comment]
Cool sounds good to me, feel free to create the PR @ishpaul777.

**Comment by situchan** [comment]
Good point. We may need to confirm all copies once again.

English: 
> Camera permissions not granted
You have not granted us camera access. We need access to complete verification.

> Microphone Access Denied
This app requires access to your device's microphone. Please enable microphone access for this app in Settings > Privacy > Microphone.


Spanish:

> No has habilitado los permisos para acceder a la cámara
No has habilitado los permisos para acceder a la cámara. Necesitamos acceso para completar la verificaciôn.

> Acceso al micrófono denegado
Esta aplicación requiere acceso al micrófono de su dispositivo. Habilite el acceso al micrófono para esta aplicación en Configuración > Privacidad > Micrófono

@chiragsalian can you please confirm internally or add `Waiting for copy` label?

**Comment by chiragsalian** [comment]
cool i just asked internally in our slack channel. I'll post back here once i get a reply.

**Comment by chiragsalian** [comment]
Hi @mallenexpensify, could you help us out with the English copy [here](https://github.com/Expensify/App/issues/23421#issuecomment-1779520038) for the camera and microphone errors.
Additionally we were wondering if we could have a similar copy for both to make it more consistent.

**Comment by mallenexpensify** [comment]
👋 Lotta comments here....
1. Here's what we currently show in the Expensify App for 'enable camera'
![IMG_0473](https://github.com/Expensify/App/assets/22508304/da686c9a-9697-45f0-a86f-adbe80187b54)
I propose we use similar text (I removed `of receipts` since people will share non-receipt photos)
> Enable Access to Camera
To use Expensify to take pictures you'll need to all Expensify to access your camera:
Setting > New Expensify (where this is a button that links directly to Expensify Settings)

2. For microphone, is there a use case for when someone would use their mic, and need to enable?  I'm guessing we're pre-planning for the day someone would be able to record a video from the app, which seems like that's far off.   
Assume we _need_ copy, let's go with this
> Allow New Expensify to access your microphone to record video
Setting > New Expensify (where this is a button that links directly to Expensify Settings)

**Comment by mallenexpensify** [comment]
Thanks @ishpaul777 , it prolly would have been beneficial if I had read more of the issue :ohnothing:

So... the mic access is specific to Onfido then... right?  If so, should we address that?   
 
Personally, I have a pet peeve for apps that want access to my mic when it's not necessary (ie. Instagram where I don't post vids).   

How about these?

> Enable Camera Access
> We need access to your camera to complete bank account verification. Please enable via Setting > New Expensify (where this is a button that links directly to Expensify Settings)

> Enable Microphone Access
> We need access to your microphone to complete bank account verification. Please enable via Setting > New Expensify (where this is a button that links directly to Expensify Settings)

**Comment by mallenexpensify** [comment]
Thanks @ishpaul777 , I focused on iOS cuz I saw it was the one that was ✅ in the OP
<img width="505" alt="image" src="https://github.com/Expensify/App/assets/22508304/e2fa3415-f19c-4b4a-b8a9-224f21535977">

If the pop up for both iOS and Android provide for a direct link to settings, where camera access can be allowed, then we can provide a more generic message for enabling mic and/or camera.

**Comment by chiragsalian** [comment]
> in my opinion it will be better off if dont include the path

I'd like path to be included. I feel like most users are not really tech savvy and would loose interest in the product fast if they can't find what needs to be enabled quickly. But this is my opinion, if others disagree with me that's cool too.

i wasn't sure which other point you wanted to discuss, was it this,
> to showing a generic error message for camera and mic

Like one error regardless if its camera or mic error? Hmm i prefer 1 error each just because i think better user feedback results in faster resolution of issues because its clearer communication. 
If you meant the above just very specific to showing a generic error if its not one of the onfido errors I'm fine with that.

**Comment by chiragsalian** [comment]
> but similar in both ios and android

**Comment by chiragsalian** [comment]
> but similar in both ios and android

Yup. that sounds good to me.

> If agreed We can make this change specific to ios only like this

That code block looks good to me.

**Comment by mallenexpensify** [comment]
Yes, that's looks good to me @ishpaul777

**Comment by chiragsalian** [comment]
Hmm copy mostly LGTM. This part reads weird to me,
>  Please enable via Settings..

Shouldn't it instead be
> Please enable it via Settings..

or
> Please enable this in Settings..

or something similar.
Thoughts @mallenexpensify? Or is the copy fine as is?

**Comment by mallenexpensify** [comment]
Let's leave the copy as-is, I think it reads well-enough.  @ishpaul777 please add a period to the end of each of the sentences, thx.

**Comment by chiragsalian** [comment]
Cool works for me, i think spanish copy is still needed. I'll ask on slack to translate these,
> Enable Camera Access
> We need access to your camera to complete bank account verification. Please enable via Settings > New Expensify.

> Enable Microphone Access
> We need access to your microphone to complete bank account verification. Please enable via Settings > New Expensify.

**Comment by chiragsalian** [comment]
Spanish translations:
> Permiso para acceder a la cámara
Necesitamos acceso a tu cámara para completar la verificación de tu cuenta de banco. Por favor habilita los permisos en Configuración > Nuevo Expensify.

> Permiso para acceder al micrófono
Necesitamos acceso a tu micrófono para completar la verificación de tu cuenta de banco. Por favor habilita los permisos en Configuración > Nuevo Expensify.

**Comment by mallenexpensify** [comment]
From the PR, @ishpaul777 will be out a couple days
> I apologize for the unexpected turn of events, but I have to travel urgently for the next two days due to an emergency. I will make sure to complete this over the weekend. I sincerely apologize for any inconvenience this delay may cause.

**Comment by mallenexpensify** [comment]
Good catch @ishpaul777 , I believe we recently made a change for capitalization . Please have the titles be
- Enable camera access
- Enable microphone access

**Comment by mallenexpensify** [comment]
PR deployed to production 4 days ago, updated title to reflect payment is due the 21st. Updated to Weekly too.

**Comment by situchan** [comment]
BZ Checklist:
No regression but incorrectly implemented from the beginning.
I don't think this is worth adding to regression test suite

**Comment by mallenexpensify** [comment]
Reporter: @DinalJivani paid $250 via Upwork
Contributor: @ishpaul777 paid $1000 via Upwork
Contributor+: @situchan owed $1000 Upwork. 

@situchan , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01adeea47f2373964b

**Comment by situchan** [comment]
Accepted thanks

**Comment by situchan** [comment]
@mallenexpensify please check the compensation discussion from [here](https://github.com/Expensify/App/issues/23421#issuecomment-1777512421) to [here](https://github.com/Expensify/App/issues/23421#issuecomment-1777527189)

**Comment by mallenexpensify** [comment]
updated [payment post above ](https://github.com/Expensify/App/issues/23421#issuecomment-1866910494)
Once I confirm @ishpaul777 's refund I'll close (and after double checking if we need/want a regression test for this).

**Comment by mallenexpensify** [comment]
Thanks @ishpaul777 , confirming. 
<img width="334" alt="image" src="https://github.com/Expensify/App/assets/22508304/b221f0ab-ce97-4435-9cf2-6db479ded808">

I'm going to agree with you that we don't need a regression test @situchan cuz someone would have to manually go in and change the code from Mic > Camera which I can't see that ever happening.

**Comment by JmillsExpensify** [comment]
$500 payment to @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/23421#issuecomment-1866910494).
