### ISSUE TITLE
Error when create new chat in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23439]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go offline
2. Click FAB -> New chat
3. Search email -> Select user -> Send some message
4. Click FAB -> New chat
5. Select same previous user (Chat doesn’t show previous message)
6. Send some message again
7. Go online
## Expected Result: 
There should be no error and It should open same chat if selected for second time
## Actual Result: 
It opens new chat every-time, and show error when go online

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e69601f3-3585-4fcf-b489-f36ffefebee9

https://github.com/Expensify/App/assets/43996225/a9aef145-08a7-417a-b7bb-46b2b3cec306

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690057959260379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we create a chat multiple times with the same user offline, it creates multiple times the chat instead of opening the existing one

### What is the root cause of that problem?

In Report, when we check if an existing chat exist we call getChatByParticipantsByLoginList here:
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/libs/actions/Report.js#L532

In this method we check if the report has a participantAccountID that is not empty, we also check if the report has the same particpants than the participant of the chat we want to create here:
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/libs/ReportUtils.js#L2216-L2221

Those two conditions are not met because when we create a chat offline the method here:
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/libs/actions/Report.js#L534-L535

We retrieve the list of account ids of the participants by searching the logins in personalDetails. For a new chat this will return an empty list. So the participantsList that we pass to buildOptimisticChatReport will be empty here: 
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/libs/ReportUtils.js#L1728

### What changes do you think we should make in order to solve the problem?

In the buildOptimisticChatReport we need to set the field "participants" that is not set so far, we can pass the logins of the users to the method.

Then in getChatByParticipantsByLoginList here: https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/libs/ReportUtils.js#L2216 
instead of checking if the particpantsAccountIDs are empty we can check if the participants field is empty


### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment]
I believe this will get fixed by this PR: https://github.com/Expensify/App/pull/22147

**Comment by ShogunFire** [comment]
@puneetlath If I understand correctly the api will return the first chat created for that user and we delete the next ones right ? What happens to the messages sent offline in the "not first chats"?

**Comment by ShogunFire** [comment]
I still reproduce on staging 1.3.45.3

https://github.com/Expensify/App/assets/19537677/7c2d78a0-5afe-407d-8b2a-a72ca64eeda1

Are you offline ?

Are you creating two chats with a user you have never chat before ?

**Comment by puneetlath** [comment]
@ShogunFire do you still experience the error on this branch? https://github.com/Expensify/App/pull/22147

**Comment by ShogunFire** [comment]
Offline you will still see the two chats with that PR
![Screenshot_2023-07-25-11-44-15-01_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Expensify/App/assets/19537677/39014b95-fa81-45e6-8454-21b7a3cb9de3)

Is that a problem ? And that's why I asked that https://github.com/Expensify/App/issues/23439#issuecomment-1648309944

**Comment by puneetlath** [comment]
Ah got it. We are soon going to be getting rid of participants in favor of participantAccountIDs. Will the problem still exist then?

**Comment by ShogunFire** [comment]
Yes, we are already not using participants in that case, my proposal was actually to use it lol...
