### ISSUE TITLE
[$1000] Web - Request Money: Hmm... it's not here when requesting money after updating a user's profile

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26114]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website in two windows
2. create two new users
3. Login both users
4. click the + icon from LHN for user A
5. create a new chat from user A to user B
6. send a message from user A to user B
7. reply to a message from user B to user A
8. update a profile for both users
9. click the + icon from LHN
10. click money request
11. enter a value
12. select or enter user B's email
13. confirm the requested money
13. Observe the result

## Expected Result:
 A money request should be sent to user B

## Actual Result:
Hmm... it's not here page appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-6
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/481cce82-a621-457b-abc1-4b24ebf5b3e3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692440705016829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0199bcac5d2d2e5bbb</li>
        <li>Upwork Job ID: 1696546344484073472</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by lschurr** [comment]
Hi @burczu - could you try reproducing this bug?

**Comment by binary3oul** [comment]
This issue is seen by only user A

**Comment by dantastisk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The problem is that you can not request money from a user by using the FAB, if you have first created a chat with the user. It has nothing to do with changing settings and can be reproduced by just these simple steps:

1. Click the FAB, click "New chat" and type the email of a user that you have no chat history with.
2. Click the FAB again, click "Request money" and type the same email as in step 1
3. You will see a "Hmm... it's not here - You don't have access to this chat"-page

### What is the root cause of that problem?

The problem is caused by a combination of multiple factors. What happens is that the FE is not able to find the existing chat when creating the IOU, assumes that no chat exists between the 2 users and tries to create a new one. The BE is aware of the existing chat and returns the following error:

```js
{
...,
jsonCode: 666,
message: "There is a previously existing chat between these users.",
...
```

The way the FE checks if there is an existing chat/report when "Request money" is used from the FAB, is by comparing the account ID of the participant selected with the participants of all of the users existing chats/reports.

This happens here:

https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/libs/ReportUtils.js#L2820-L2839

So why is the FE not able the existing chat/report?

To explain this, let me first summarize what happens when a new chat is created from the FAB:

1. If the recipient participant is unknown, an optimistic personal detail with a temporary, locally generated accountID is created and stored in Onyx. This happens here:

https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/libs/actions/Report.js#L491-L521

Notice how this also pushes an object like the following to `onyxData.successData`:

```js
{onyxMethod: 'merge',
key: 'personalDetailsList',
value: {
  [ACCOUNT_ID]: null
}}
```

The purpose of this is to make sure that the optimistic personal detail is cleared from Onyx once the server responds with the actual personal detail with the correct accountID. However, the above code **does not work**. It is not possible to clear an object from Onyx by merging it with `null`. You can easily test this for yourself by opening the console of your browser and calling `Onyx.merge` with an object like the above wrapped in an array and `[ACCOUNT_ID]` substituted for one of the accountID's found under the `personalDetailList` of your Onyx store.

So, the first step to fixing the issue is to fix this code to properly clear the optimistic personal detail.

This doesn't fully solve the problem, however, as there is more to it.

The personal detail returned from the BE and stored in Onyx when a new chat is created with a previously unknown participant looks like this:

```json
"15542922": {
  "accountID": 15542922,
  "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_15.png",
  "displayName": "daniel.s.brinkmann+change4@gmail.com",
  "firstName": "",
  "lastName": "",
  "status": null
}
```

If you compare this to the optimistic personal detail from Report.js, you will notice that it has a few extra properties, but more importantly that the `login`-property is missing.

This is important because the code responsible for displaying the possible recipients when requesting money from the FAB includes these lines:

https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/libs/OptionsListUtils.js#L715-L719


### What changes do you think we should make in order to solve the problem?


To solve the problem, we will have to:
  1. Fix the faulty `onyxData.successData`-code by either merging with an object that sets all the required keys to `null`, or (probably the better solution) uses Onyx.METHOD.SET to properly clean up.
  2. Either
    **A.** make a change in the BE so that the `login` property gets sets on the returned personal detail
  OR
    **B.** remove the filter in the FE that requires the `login` property to be set. Hopefully someone from the internal team can access the issue mentioned in the comment ([https://github.com/Expensify/Expensify/issues/293465](https://github.com/Expensify/Expensify/issues/293465)) or by other means provide more insight as to wether this is still necessary (the comment mentions this as being a temporary fix and I did not notice anything breaking when I removed it).

I have tested a combination of 1. and 2.B and this solves the problem.

**Comment by burczu** [comment]
Hey @Ischurr! Sorry for the delay - I've missed this one. I'll take a look today!

**Comment by binary3oul** [comment]
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
When we attempt to request money using the "New chat" feature, we encounter the message **"Hmm... it's not here when requesting money."** 
In other words, we are unable to request money through the **"New chat"** .

To begin with:

1. Click Plus(+) Fab button and select "New Chat".
2. Type new user's Email into the composer located on New Chat popup.
3.  Select email and send request money.
### What is the root cause of that problem?

Final cause for this problem is **debtorEmail** property is missing (assigned **null** exactly) in the payload towards API when we request through the **New Chat** 


![Screenshot 2023-08-30 052233](https://github.com/Expensify/App/assets/134395032/1bd0cfd3-0cde-4e2c-acb3-018deda41953)

It brings the following response.

![Screenshot 2023-08-31 055037](https://github.com/Expensify/App/assets/134395032/665913df-5fb0-48b5-9f80-476ea56a560c)

Therefore, when user confirms requested money, 403 error encountered and shows **Hmm... It's not here** error.

![Screenshot 2023-08-31 071434](https://github.com/Expensify/App/assets/134395032/df209ce1-7e23-4ff6-ab4b-45c6ee6fe6cb)


Let me explain why.

To begin with:
1. Press F12 and click **Application** tab, then select IndexedDB\OnyxDB\keyvaluepairs.
2. Please take a look at the row with the key personalDetailsList.
(especially, please pay attention to the objects with the keys "15544627" and "189181028" )

![Screenshot 2023-08-31 073134](https://github.com/Expensify/App/assets/134395032/d4322144-f719-48e7-ad40-05109450dc3b)


To perform this operation successfully, we need login property that is associated with this operation.
Therefore,  we have to update the merge operation of Onyx with correct data so that enables to insert login propery into personalDetailsList property.

This login porperty is none other than debtorEmail I mentioned above.


### What changes do you think we should make in order to solve the problem?


We have to update [these lines](https://github.com/Expensify/App/blob/main/src/libs/actions/IOU.js#L1851-L1856) as following:


```
const participants = ReportUtils.isPolicyExpenseChat(report)
                ? [{reportID: report.reportID, isPolicyExpenseChat: true, selected: true}]
                : _.chain(report.participantAccountIDs)
                        .filter((accountID) => currentUserAccountID !== accountID)
                        .map((accountID, index) => ({accountID, selected: true, login: report.participants[index]}))
                        .value(); 
```

**Comment by binary3oul** [comment]
Hello @burczu
Please check my proposal.
I fixed this issue very simply to update just one code line.

**Comment by dantastisk** [comment]
https://github.com/Expensify/App/issues/26114#issuecomment-1701303334 This does not fix the issue. The code you linked is not even executed when requesting money by clicking the FAB, only when doing it from within a report.

Like mentioned in my proposal, the cause of the issue is Onyx having multiple personal details stored for the same participant  because the optimistic data is not cleared properly upon retrieving the correct data from the BE
AND
the BE not setting the login property

I wrote in my original proposal that a possible solution could be to remove the filter that requires the login property to be set. However, after further testing, I can now conclude that this is not the way to go, as it will leave "ghost" contacts in the suggestions like this:

<img width="375" alt="image" src="https://github.com/Expensify/App/assets/48072523/ec7e4564-97db-40c0-b0e1-d5328af233d1">

I will update my proposal to reflect this.

I also forgot to mention in my explanation that a new optimistic personal detail is created [here](https://github.com/Expensify/App/blob/54e69047a3157599dae233117a5d849ff1d0c58b/src/libs/OptionsListUtils.js#L810-L837) when no existing is found (due to the missing login property). This will have the same, temporary and wrong accountID as the one created when opening the chat report which is why it cannot find the existing chat report to create the IOU within.

So to summarize, the solution is to:
1. Properly clear the optimistic personal detail
2. Have the BE set the login property of the personal detail created when opening a report with a new/unknown participant

If you want to confirm my solution you can:

1. Change this line https://github.com/Expensify/App/blob/54e69047a3157599dae233117a5d849ff1d0c58b/src/libs/actions/Report.js#L504
to
```js
settledPersonalDetails[accountID] = allPersonalDetails[accountID] || {
  login: null,
  accountID: null,
  avatar: null,
  displayName: null,
   isOptimisticPersonalDetail: null
};
```
(for the actual PR this can be done cleaner, this is just for the POC)

2. Create a chat report from the FAB
3. Simulate the BE setting the login property by executing this in your browser console: 
```js
Onyx.update([{
  onyxMethod: 'merge',
  key: 'personalDetailsList',
  value: {
    12345678: {
      login: "example@mail.com"
     }
  }
}])
```
(replace "example@mail.com" with the correct email and 12345678 with the account ID returned by the BE in step 2. This can be extracted from the response of the OpenReport request in the network tab or by finding the correct object in Onyx, under the "personalDetailsList"-key).
4. Click "Request money" from the FAB, select the user and it should work.

@burczu This can be a confusing issue to wrap your head around, so lmk if you have any questions or need further explanation :-)

**Comment by binary3oul** [comment]
Thank you @dantastisk 
# [ Updated proposal](https://github.com/Expensify/App/issues/26114#issuecomment-1701303334)

In that case, we can see the following message from API.
![Screenshot 2023-08-31 113130](https://github.com/Expensify/App/assets/134395032/0affe3e3-eb04-49fc-a912-9d692013e911)

I believe that the backend is functioning properly, so now we need to proceed with the redirect operation to the chat channel. 
I have outlined the details of this operation in my proposal.

**Comment by burczu** [comment]
Thanks for all the proposal - I'll be reviewing them soon.

**Comment by dantastisk** [comment]
@misgana96 I did some further testing and you are correct. The solution is still the same, however, as the problem is still, that the BE does not set the `login` property of the personal detail when responding to the `OpenReport`-request.

Because of this the correct personal detail gets filtered out here:

https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/libs/OptionsListUtils.js#L715-L719

**Comment by lschurr** [comment]
Hey @amyevans - could you review this comment and let us know what you think? https://github.com/Expensify/App/issues/26114#issuecomment-1705105031

**Comment by amyevans** [comment]
I've been prioritizing Wave 6 but will try to look into this later today!

**Comment by lschurr** [comment]
Bump @amyevans :)

**Comment by amyevans** [comment]
Prioritizing Wave 6, not able to work on this at the moment

**Comment by lschurr** [comment]
I believe this is still on hold.

**Comment by amyevans** [comment]
The other PR is merged, though I haven't had time to get back to this yet.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by lschurr** [comment]
Is this off hold? Are we waiting for proposals @burczu @amyevans?

**Comment by burczu** [comment]
@dantastisk It seems like the BE part may be now fixed - could you please confirm it and check if we can now move forward with the FE changes you've proposed?

**Comment by burczu** [comment]
Just to inform, I'll be ooo for the next few days and we'll be back on Monday, November 6th.

**Comment by lschurr** [comment]
What's the latest on this one @burczu?

**Comment by burczu** [comment]
@lschurr As I wrote in this comment: https://github.com/Expensify/App/issues/26114#issuecomment-1780933659 - I think we should wait for @dantastisk to fix the FE part of the issue, as they provided the solution that we originally followed (please see this comment: https://github.com/Expensify/App/issues/26114#issuecomment-1705105031).

**Comment by dantastisk** [comment]
Sorry, I have been mia, have been ooo for a couple weeks.

I will take a look this week.

**Comment by burczu** [comment]
@dantastisk Any update here?

**Comment by dantastisk** [comment]
Sorry for the delay. I just checked on staging and it seems like BE is still not sending a login property.

**Comment by burczu** [comment]
Yeah, @amyevans, could you confirm? After your comment: https://github.com/Expensify/App/issues/26114#issuecomment-1759631334 you have removed the `HOLD` mark from the title so I think @lschurr and I assumed that the BE side is done, but it seems it's not yet?

**Comment by amyevans** [comment]
Sorry this wasn't clearer! I haven't done any backend work for this yet, it doesn't feel like it should be prioritized over wave6 work.

**Comment by lschurr** [comment]
Should this one still be on hold @amyevans?

**Comment by amyevans** [comment]
> Should this one still be on hold @amyevans?

Probably not HOLD since we don't have any other tracking issue for it.

**Comment by lschurr** [comment]
Based on Matt's update, should we be closing this one @amyevans? https://expensify.slack.com/archives/C01SKUP7QR0/p1702341728013009

**Comment by amyevans** [comment]
Yeah that makes sense to me, thanks @lschurr!

**Comment by dantastisk** [comment]
I am really curious as to what was in that update. Can you share?

**Comment by lschurr** [comment]
The update was crossposted here as well - https://expensify.slack.com/archives/C01GTK53T8Q/p1702496349813859

**Comment by dantastisk** [comment]
Thanks! Does that mean that I get no compensation? Because that would be quite disappointing I must say.

> https://github.com/Expensify/App/issues/26114#issuecomment-1718257026

**Comment by lschurr** [comment]
Yes, unfortunately since we won't be fixing this bug right now, we won't be issuing compensation. It's possible that this will get reopened in the future, at which point you could be hired for the job and compensated once a fix is put in place. Thanks @dantastisk!

**Comment by misgana96** [comment]
@lschurr What about the reporter bonus? Am I eligiable for a compensation?
