### ISSUE TITLE
[HOLD for payment 2023-10-13] Chat - Chat history not loading after returning from offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26143]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start staging.new.expensify.com or Expensify App
2. Log into any account that has chats with a long history
3. Open this chat
4. Go Offline
5. Scroll through cached chat history
6. Go online without leaving the chat

## Expected Result:
Chat history should load after going online

## Actual Result:
Chat history not loading after returning from offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/12db4769-c9f7-4b13-840c-8ad58e9391b2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I can reproduce this issue. However, it seems to have the same root cause as https://github.com/Expensify/App/issues/26181 where the ReconnectApp format is incorrect for ReportActions.

**Comment by luacmartins** [comment]
FWIW that's an issue in the API and is not a blocker for App deploy.

**Comment by luacmartins** [comment]
I'm gonna close this issue in favor of https://github.com/Expensify/App/issues/26181

**Comment by chiragsalian** [comment]
Resolved on staging with a web-E CP. Closing issue. If it persists feel free to reopen.

**Comment by luacmartins** [comment]
@lanitochka17 can you still reproduce this issue? It doesn't seem to be that widespread

**Comment by lanitochka17** [comment]
@luacmartins Issue still reproduce on latest build 1.3.67-1

https://github.com/Expensify/App/assets/78819774/509b9214-bd8e-4488-b65b-4200a02c7776

**Comment by marcaaron** [comment]
@luacmartins gonna jump off this one since it seems like you've got more context on the issue than me at this point, but lmk if you need anything here.

**Comment by luacmartins** [comment]
Ok, I took a look at this and the problem isL

1. `ReadOldestAction` fails
2. We call `SaveResponseInOnyx` but `response` is `undefined`
3. We return early [here](https://github.com/Expensify/App/blob/9fdd47f5f87bad95b9fd11904aeda057c0456d06/src/libs/Middleware/SaveResponseInOnyx.js#L19-L21) and never process `failureData`.
4. Which means `isLoadingMoreReportActions` is never set to false [here](https://github.com/Expensify/App/blob/9fdd47f5f87bad95b9fd11904aeda057c0456d06/src/libs/actions/Report.js#L716)
5. And we never call ReadOldestAction, because we return early [here](https://github.com/Expensify/App/blob/9fdd47f5f87bad95b9fd11904aeda057c0456d06/src/pages/home/report/ReportActionsView.js#L141)

**Comment by luacmartins** [comment]
I'm looking at this again but having issues reproducing the network error. Gonna switch spots and see if I can get a reliable internet connection

**Comment by luacmartins** [comment]
I have a draft PR up, but tests are failing. Gonna have to revisit my solution

**Comment by luacmartins** [comment]
Still discussing it in the PR

**Comment by luacmartins** [comment]
Discussing solutions in the PR

**Comment by luacmartins** [comment]
Adding `Bug` label to process payment for PR review - https://github.com/Expensify/App/pull/27650

**Comment by adelekennedy** [comment]
@luacmartins confirm the below is correct?

### Payouts due:

PR review Contributor+: $500 @situchan (Upwork)

Eligible for 50% #urgency bonus? N

No Upwork link as it's broken right now (as per usual)

**Comment by luacmartins** [comment]
@adelekennedy yes, that's correct!

**Comment by adelekennedy** [comment]
[Sent offer](https://www.upwork.com/jobs/~011f894936d995b367)

**Comment by adelekennedy** [comment]
payment made!
