### ISSUE TITLE
[$500] Re-entering same wrong magic code and verify keeps last digit in green

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#26813]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings ->profile-> contact method->add any contact method
3. Open that newly added contact method and enter wrong code
4. Dismiss the error and again add same wrong code over it
5. Click verify and observe that last digit still has green dash

## Expected Result:
App should have red dash below all the digits when error is triggered in add contact method
## Actual Result:
App displays last digit with green dash when error is dismissed and again same code is entered and error is triggered in add contact method
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.63-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/3f54de1e-a435-46d5-8ac2-f7ad0fe2fceb

https://github.com/Expensify/App/assets/38435837/68bbf26b-c187-440c-b5be-a0ea2901ef33

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693501161646589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d5900e7078ce653</li>
        <li>Upwork Job ID: 1699715481614094336</li>
        <li>Last Price Increase: 2023-09-28</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
Proposal by: @dhanashree-sawant
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1693501161646589
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
We are solving the problem of app displaying green border to magic code first and last field when submitted without any value or when resubmitted same value
### What is the root cause of that problem?
Currently in `MagicCodeInput` component, there is not way to find out whether `verify` button was triggered or not due to which `focusedIndex` value is not changed whenever we trigger `verify`. This lack of data is causing green background for first or last digit even on error in multiple different scenario's like:
1. `verify` button click when there is no input
2. `verify` button click when we re-enter same invalid code
### What changes do you think we should make in order to solve the problem?
We have to introduce variable which will let us know that `verify` button was triggered and introduce new condition to display `borderColorFocus`. This will help us to not only solve the issue for current scenarios but also fullproof the solution for any other such scenarios.
In BaseValidateCodeForm page of settings->profile->Contacts:
We can add `verifyCode` state at following [location](https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L76C2-L76C2)
```
const [verifyClick,setVerifyClick]= useState(false);
```
Set the state to true on `verify` button click at following [location](https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L137)
```
setVerifyClick(true);
```
Pass on both the variable and method (so we can again it to false on focus of any input) at following [location](https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L163)
```
verifyClick={verifyClick}
verifyClickChange={setVerifyClick}
```
In MagicCodeInput component:
Set default prop values to avoid issues with component used at different location (tested at all other locations to see if its working fine or not) by adding the code [here] (https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/components/MagicCodeInput.js#L62):
```
verifyClick: false,
verifyClickChange: ()=>{},
```
Modify style condition for the digit view to allow `borderColorFocus` only if value is false by changing code [here](https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/components/MagicCodeInput.js#L253)
```
focusedIndex === index && !props.verifyClick ? styles.borderColorFocus : {},
```
Set `verifyClick` value to false in `onFocus` to ensure it only affects once after `verify` button click and does not hinder normal border color change by adding code [here](https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/components/MagicCodeInput.js#L148)
```
props.verifyClickChange(false)
```
This will also modify state value in `BaseValidateCodeForm` of settings->profile->Contacts.
### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment]
Dupe - https://github.com/Expensify/App/issues/20416

**Comment by conorpendergrast** [comment]
@alitoshmatov Can you add some context? Same root cause, but different effect?

**Comment by alitoshmatov** [comment]
@bernhardoj You right, I think I made mistake. It does not look same
cc: @conorpendergrast

**Comment by conorpendergrast** [comment]
Nice, thanks for the confirmation there! I'll review triage this accordingly

**Comment by conorpendergrast** [comment]
Reproduced!

**Comment by conorpendergrast** [comment]
I'm on parental leave; re-assigning! This has been triaged and is waiting for proposals.

**Comment by laurenreidexpensify** [comment]
@ArekChr bump on proposal review ^^ thanks

**Comment by ArekChr** [comment]
I couldn't reproduce this error. I encountered different behavior, when trying to pass new code over it, it submits after pressing just one number. I'm not sure if this is correct behaviour.

https://github.com/Expensify/App/assets/24796318/251acb46-ca68-49cb-af90-f0edc65c0475

**Comment by ArekChr** [comment]
Thanks @neonbhai, for the details, reproduced now! 

@dhanashree-sawant in your proposal, there is a case when entering the same number again after the magic code is validated, last input is still highlighted on green

**Comment by ArekChr** [comment]
@neonbhai the code in the main branch is different since the proposal has been updated, there is a similar logic that you propose but in a new condition when "requiredTwoFactorAuth" is true, but still doesn't work, could you please update your proposal?

**Comment by dhanashree-sawant** [comment]
Thanks for checking my proposal, will check the issue and update the proposal for it.

**Comment by dhanashree-sawant** [comment]
Hi @ArekChr, this is what I see at my end with my current changes (attached video), let me know if I missed anything while testing. Also it is my first proposal so am not sure if I have written all the code part correctly for proper understanding, sorry if there was any confusion due to it. I will summarize everything below:

Add below code in BaseValidateCodeForm.js in `BaseValidateCodeForm` function after line 76

```
const [verifyClick,setVerifyClick]= useState(false);
``` 

Add below code in BaseValidateCodeForm.js in `useCallback` of `validateAndSubmitForm` as first line inside `useCallback`

```
setVerifyClick(true); 
```

Add below code as 2 extra parameter for `MagicCodeInput` component in BaseValidateCodeForm.js

``` 
verifyClick={verifyClick}
verifyClickChange={setVerifyClick}
```
   
Add below code as 2 more default props in `MagicCodeInput.js`

```
verifyClick: false,
verifyClickChange: ()=>{}, 
```
Modify condition for displaying `borderColorFocus` of input around line 256 of `ModifyCodeInput.js`

```
focusedIndex === index && !props.verifyClick ? styles.borderColorFocus : {},
```

Set verifyClickChange to false in `onFocus` function of `ModifyCodeInput.js`

```
props.verifyClickChange(false);
```

https://github.com/Expensify/App/assets/87513216/73c6b231-5d3f-4328-af92-e8666cad7b45

**Comment by ArekChr** [comment]
@neonbhai You are right. I opened the wrong file. Your [proposal](https://github.com/Expensify/App/issues/26813#issuecomment-1710079588) fixes the root cause, LGTM

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by cead22** [comment]
Waiting for @ArekChr 's thoughts on ^ before assigning a contributor. I agree clicking outside the input field should clear the green highlight

**Comment by ArekChr** [comment]
@dukenv0307 I have concerns about using onBlur for each text input component. It's confusing because MagicCode is designed with 6 inputs, so the blur event is triggered with every text change which might be misleading.

**Comment by dhanashree-sawant** [comment]
Hi @ArekChr, can you also provide your feedback for my proposal? would be helpful for me for future proposals. Basically I have brought in Verify click trigger into the main `BaseValidateCodeForm.js` component and added condition to not display green underline when verify click is triggered.

**Comment by ArekChr** [comment]
@dhanashree-sawant Your proposal indeed addresses the issues, but the additional state seems unnecessary, and it can be fixed without introducing new states that rerender the component.

**Comment by dhanashree-sawant** [comment]
Got it, thanks for the feedback.

**Comment by ArekChr** [comment]
@dukenv0307 I understand the intention behind not triggering a blur event for text input components. However, I have some concerns:

Reusing the blur functionality inside six pseudo inputs this way could create ambiguities in our codebase.

I'm concerned about a potential race condition. The `onKeyPress` function sets `editIndex`, and you are also reusing a blur function that depends on this index. There's a possibility that setting the state for `editIndex` and triggering the blur event could happen simultaneously. Using a ref for `editIndex` could make this safer.

> The issue when clicking outside the magic code input, the magic code input still looks focused but is unresponsive when typing numbers.

Also, I'm not sure if MagicInput is designed to behave this way, it only blurs after we either submit the form or enter all the required numbers.

The proposal from [neonbhai](https://github.com/neonbhai) uses an existing implementation from a different place that is more straightforward because we simply triggering blur when submitting the form.

**Comment by cead22** [comment]
Can somebody summarize what the different proposals do at a high level, and what the behavior is
- When you're entering numbers and click/tap outside the inputs
- When you're entering less than 6 numbers, and click verify (do the inputs stay highlighted, can you still enter numbers?)

Maybe it's worth discussing in #expensify-open-source what the ideal behavior should be, cause I think clicking/tapping outside the inputs should remove the focus (and highlight) from them, but I also think it'd be good, at least for the login page, to re-focus on the last input when an invalid magic code is entered and we put an error message on the screen

**Comment by cead22** [comment]
@ArekChr sounds like we're leaning towards using @neonbhai 's proposal, can you confirm before I assign? Thanks

**Comment by laurenreidexpensify** [comment]
@ArekChr bump thanks - https://github.com/Expensify/App/issues/26813#issuecomment-1736888874

**Comment by ArekChr** [comment]
> @ArekChr sounds like we're leaning towards using @neonbhai 's proposal, can you confirm before I assign? Thanks

Yes, agree

**Comment by laurenreidexpensify** [comment]
@ArekChr do you agree that is no longer reproducible - https://github.com/Expensify/App/issues/26813#issuecomment-1736906367?

**Comment by ArekChr** [comment]
@laurenreidexpensify The issue is still reproducible, the last input is still focused when entering the same number and pressing verify.

https://github.com/Expensify/App/assets/24796318/00a0a8ac-08bb-41ea-b741-219234ed01b5

**Comment by Santhosh-Sellavel** [comment]
This was found earlier while our testing, will be handled [here](https://github.com/Expensify/App/pull/28711).

**Comment by Santhosh-Sellavel** [comment]
May be I miss understood the problem, but after second look I see the actual issue described no longer reproducible on staging, Its already addressed. Only problem is last item still green on error case and that is addressed on our refactor [PR](https://github.com/Expensify/App/pull/28711).

cc: @cead22 @ArekChr

**Comment by cead22** [comment]
Sounds like we can close, but reopen if I misunderstood

**Comment by dhanashree-sawant** [comment]
Hi @cead22, @Santhosh-Sellavel the actual issue is itself the green last digit which is still reproducible. If it is being handled by that PR, would this be eligible for reporting bonus as PR is raised for issues raised after this issue.

**Comment by cead22** [comment]
I don't think so, since that PR links to 3 other issues, so this is just another symptom of the same root cause
