### ISSUE TITLE
[HOLD for payment 2023-09-29] [HOLD for payment 2023-09-27] [$500] IOU- In announce room, checkbox circle to unselect split bill participants is not responsive

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27774]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-condition: Workspace created with members
1. Go to https://staging.new.expensify.com/
2. Open an announce room
3. Tap plus icon near compose
4. Tap split bill
5. Enter an amount
6. Tap next
7. Tap on check box circle to unselect split bill participants

## Expected Result:
In announce room, tapping on check box circle to unselect split bill participants, must be able to unselect members

## Actual Result:
In announce room, tapping on check box circle to unselect split bill participants, is not responsive and user unable to unselect members

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cd7581b5-9260-400b-a029-e2e2df934a38

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011191e66c032d1767</li>
        <li>Upwork Job ID: 1704222117183524864</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by situchan** [comment]
@MitchExpensify [PR](https://github.com/Expensify/App/pull/27810) is already in review

**Comment by MitchExpensify** [comment]
Oh, cool. How did that happen? 😆 

Are deploy blockers simply up for C+ grabs upon creation?

**Comment by situchan** [comment]
This was caused by PR I reviewed

**Comment by MitchExpensify** [comment]
Ah got ya, thanks

**Comment by cristipaval** [comment]
Thanks @situchan for jumping into this. I see that the PR that introduced this regression is quite big so it's way easier to add the fix instead of reverting it.

**Comment by s-alves10** [comment]
We can add the missing props. May I help here?

**Comment by MitchExpensify** [comment]
*Payment summary*:

**Reporter:** NA Applause
**Contributor:**  @situchan $500 Upwork
**Contributor+:** @parasharrajat $500 NewDot Request 

I'm not sure I've seen a deploy blocker fixed by the person that caused the regression - Curious is these amounts look correct to everyone. CC @mallenexpensify for a BZ buddy check

**Comment by situchan** [comment]
Not eligible for compensation if regression.
Btw, this is edge case. Due to urgency and to avoid more conflicts, we merged big PR as is though it isn't perfect and several issues remaining to be resolved. So it was expected to have some regressions and fix as follow-up.
Context: https://expensify.slack.com/archives/C01GTK53T8Q/p1694772395119489?thread_ts=1694746421.663479&cid=C01GTK53T8Q

**Comment by situchan** [comment]
> This seems to be a regression from some PR. @situchan Could you please add the link to the PR?

https://github.com/Expensify/App/pull/25564

**Comment by cristipaval** [comment]
Thank you @parasharrajat and @situchan!
