### ISSUE TITLE
[$500] Edit message, save/cancel and visiting different report removes focus from composer

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29919]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697650111645879

## Action Performed:
1. Open the app
2. Open any report
3. Send any message
4. Edit the message
5. Save or cancel the edit message
6. Visit another report and observe that app does not focus on composer
## Expected Result: 
App should focus on composer whenever we visit any report
## Actual Result: 
App does not focus on composer when we edit any message, save/cancel the mesage and visit any other report

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/c3f36b1b-88c8-40ac-8d90-3a56dc825c84

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/64011705-26e2-4491-ae26-1c5fe5a23d8a

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/9b4e85c6-0ea2-446e-9efe-7051bebff9ec

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/b4674a0a-6d3c-4052-8897-b7c72814d42e

https://github.com/Expensify/App/assets/38435837/ef7bcf0a-7590-4fd9-b87e-3af9c7fb959b
</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/506d54e2-9240-4322-a645-be26708dad1a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2dccea0afb54c13</li>
        <li>Upwork Job ID: 1714761073301872640</li>
        <li>Last Price Increase: 2023-11-08</li>
    </ul>
</details>

**Comment by zukilover** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Composer is not focused when user has edited a chat from different report

### What is the root cause of that problem?
Within `deleteDraft` which is called in the `triggerSaveOrCancel` method, composer focused is set to false thus loses its focus state:

https://github.com/Expensify/App/blob/1ed55e0517e8855da3d6c5d54eb33ec4c45a4f22/src/pages/home/report/ReportActionItemMessageEdit.js#L275-L276

`isFocused` triggers `composerFocusKeepFocusOn` on an effect that then read from the state value to remove the focus `ref`.

https://github.com/Expensify/App/blob/1ed55e0517e8855da3d6c5d54eb33ec4c45a4f22/src/pages/home/report/ReportActionItemMessageEdit.js#L136-L138

### What changes do you think we should make in order to solve the problem?
Remove the offending line that triggers the focus state change:

```javascript
const deleteDraft = useCallback(() => {
        // InputFocus.callback(() => setIsFocused(false)); << remove this line
        InputFocus.inputFocusChange(false);
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by abzokhattab** [comment]
is it a regression from https://github.com/Expensify/App/pull/29073 ?

**Comment by ayazalavi** [comment]
@narefyev91 please take a look

**Comment by ayazalavi** [comment]
I am not sure, let me take a look.

**Comment by peterdbarkerUK** [comment]
Is this intended behaviour? From [here](https://github.com/Expensify/App/issues/30122#issuecomment-1773935669):

On small devices the auto focus will bring up the keyboard which may be annoying. Reports are optimized for reading. Ref: https://expensify.slack.com/archives/C01GTK53T8Q/p1617201995245400

**Comment by peterdbarkerUK** [comment]
Yes, please. If @zukilover's proposal still works to your liking? Looks like an extremely easy one.

**Comment by ayazalavi** [comment]
Let me please write down the proposal as well. Since apparently my PR is connected with this bug.

**Comment by zukilover** [comment]
That specific line was added from https://github.com/Expensify/App/issues/26527 to fix a glitch of the focus states (race condition).

It should be fixed with the new inputFocusChange, and thus the focus callback is a redundant line here that should be removed.

**Comment by ayazalavi** [comment]
it will cause regression if we remove this line and the bug mentioned in
the https://github.com/Expensify/App/issues/26527 will reappear.

**Comment by ayazalavi** [comment]
basically thats why I requested to put proposal but I am still not able to
find fix for it so far.

**Comment by zukilover** [comment]
If we take a look at how `composerFocusKeepFocusOn` is implemented, especially these lines:
https://github.com/Expensify/App/blob/17ce0c218189017f645ef0e1a53d52d87d6e7a21/src/libs/actions/InputFocus/index.website.ts#L16-L26

It tries to focus on `refSave` but `refSave` will be defined if `isFocused` is truthy, but the focusing is executed only when `isFocused` is falsy. This seems to be counterintuitive.

**Comment by ayazalavi** [comment]
## Proposal

### Restating the Problem
The problem we are addressing is that when a user edits a message in a chat and then switches to another chat, the main composer does not receive focus.

### Identifying the Root Cause
The root cause of this issue is that the focus on the compose field is triggered programmatically in [ComposerWithSuggestions](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js) at this location: 

https://github.com/Expensify/App/blob/bc9cb8f8ca149c1f90dd09de9f19ae97bcaf07f0/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L550.

The issue arises when the edit compose box loses focus after closing the edit input field. As a result, the main compose box in the same chat where the message was edited regains focus. When we switch to another chat, this line 

https://github.com/Expensify/App/blob/bc9cb8f8ca149c1f90dd09de9f19ae97bcaf07f0/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L542 

evaluates `prevIsFocused===true`, causing it to skip the focus() method call at 

https://github.com/Expensify/App/blob/bc9cb8f8ca149c1f90dd09de9f19ae97bcaf07f0/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L550. 

Consequently, the main compose box loses focus in the new chat.

### Proposed Solution
To solve this problem, we suggest calling the focus method at 

https://github.com/Expensify/App/blob/bc9cb8f8ca149c1f90dd09de9f19ae97bcaf07f0/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L614-L620. 

This will ensure that the main compose box receives focus as soon as it's layout'd, preventing the issue from occurring.

Result:

https://github.com/Expensify/App/assets/767439/ab557817-7268-4d40-b89c-cff9deeac54a

### Alternative Solutions
No alternative solutions were explored or mentioned in the proposal.

**Comment by peterdbarkerUK** [comment]
Not overdue, just waiting on proposal review

**Comment by ayazalavi** [comment]
@vinh hoang   
  

  
Simply calling focus on main composer layout callback fixes the issue. The issue is due to bug in main composer component as I said in my proposal. Focus doesn’t gets called in a condition when it was already focused without popover getting rendered. If popover gets rendered then to us gets called correctly and this bug doesn’t happen.
  
  
  
  
  
  
  

  
  
>

**Comment by peterdbarkerUK** [comment]
+1 I can no longer reproduce. I'm checking how compensation works in this scenario ([personal paper trial](https://expensify.slack.com/archives/C01SKUP7QR0/p1699885147013969))

**Comment by ayazalavi** [comment]
My ticket was marked with regression. Should I be paid for compensating that?
  
  
  
  
  
  
  

  
  
>

**Comment by peterdbarkerUK** [comment]
@ayazalavi I'm not sure I understand your question, could you clarify? Thanks!

**Comment by peterdbarkerUK** [comment]
Hey folks - first up, I really appreciate all your work making and reviewing proposals for this. 

As this has been resolved by the rn-web update, I'm going to close it out without paying bounties. The reason being that this issue was solved "in the course of things" unrelated to this issue, without work needing to be done. I understand this can be frustrating, though with the issues that are quick and easy to resolve I hope it is, on balance, not too painful. 

Please let me know if you have any questions or disagree!
