### ISSUE TITLE
[HOLD for payment 2023-11-27] [$500] PDF preview - Eye icon to show password on password protected PDF file is not working

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31101]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Pre-requisite: user should be logged in and must have sent a password protected PDF to any chat.

1. Tap on the password protected PDF preview on the chat.
2. Tap on "enter the password".
3. Type some characters.
4. Tap on the eye icon to reveal the password.

## Expected Result:
The password should be revealed and visible to the user.

## Actual Result:
The eye icon is not responsive, does nothing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/ebdcff4f-d209-4c73-9acd-9056646a8af9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017fc5a55459d7aad0</li>
        <li>Upwork Job ID: 1722545035115692032</li>
        <li>Last Price Increase: 2023-11-09</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27592501</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @peterdbarkerUK</details>

**Comment by izarutskaya** [comment]
Issue is not reproducible in production

https://github.com/Expensify/App/assets/115492554/75078f52-2c54-4cb4-8bdc-264968f04d5d

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 PDF preview - Eye icon to show password on password protected PDF file is not working

### What is the root cause of that problem?
This issue is introduced by https://github.com/Expensify/App/pull/24482 where `pointerEvents="box-none"` attribute in `View` compenent [here](https://github.com/Expensify/App/blob/f1586ce8cecb93fb25e2244f316ca057f041d122/src/components/TextInput/BaseTextInput/index.native.js#L272) is replaced with below style object
https://github.com/Expensify/App/blob/8c3e3bc73db5ff206b7c0bcfead587a78fc977d2/src/styles/pointerEventsBoxNone/index.ts#L3-L5

But they are not exactly the same thing and we don't have `box-none` value for `pointerEvents` style attribute as documented here https://reactnative.dev/docs/view#pointerevents `pointerEvents="box-none"` is more like this:
```css
.box-none {
     pointer-events: none;
}
.box-none * {
     pointer-events: auto;
}
```

### What changes do you think we should make in order to solve the problem?
We should revert this change and just apply `pointerEvents="box-none"` for all the instances

### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment]
@alitoshmatov's proposal is correct. Not sure if this would be treated as a Deploy Blocker. 

@danieldoglas let me know we're okay to proceed with the proposal or solve as a regression.

**Comment by alitoshmatov** [comment]
From https://github.com/necolas/react-native-web/releases/tag/0.19.0

> [add] Add support for pointerEvents style.

...

> [change] Deprecate pointerEvents prop. Use pointerEvents style.

But as we can see https://reactnative.dev/docs/view-style-props#pointerevents is not deprecated, also `pointerEvents` style already exists, thus conflicting with each other. I think deprecating `pointerEvents` of `View` component in `react-native-web` was not a good idea. They should keep supporting any attribute that exists in react native.

**Comment by getusha** [comment]
There is a box-none value e.g. https://github.com/necolas/react-native-web/blob/a3ea2a0a4fd346a1b32e6cef527878c8e433eef8/packages/react-native-web/src/exports/AppRegistry/AppContainer.js#L53

I doubt they will add it if it doesn't exist.

**Comment by getusha** [comment]
I think we can fix this by simply adding `styles.pointerEventsAuto` to the Checkbox component in `BaseTextInput`

**Comment by getusha** [comment]
> I think we can fix this by simply adding styles.pointerEventsAuto to the Checkbox component in BaseTextInput

why is that @tienifr any side effects by doing this?

**Comment by danieldoglas** [comment]
I agree this should be fixed as part of the upstream instead of our repo only. Assigning @tienifr

**Comment by alitoshmatov** [comment]
I think we are too focused on `react-native-web` if we apply upstream fix as @tienifr suggested this will only work on web, native apps would still have the same problem. I think we should prioritize react native approach first, which is using `pointerEvents` attribute in `View` component. 

@danieldoglas @mananjadhav @tienifr @situchan

**Comment by alitoshmatov** [comment]
😕  I am really confused, help me understand why `react-native-web` wants to deprecate something which is actively used in `react-native`?

**Comment by danieldoglas** [comment]
This error is only caused on web - Android and iOS native were not described as having this issue, only the browser version of those. @alitoshmatov.

Or are you saying it's also happening on native apps?

**Comment by situchan** [comment]
To clarify:
https://reactnative.dev/docs/view#pointerevents is soon to be deprecated
https://reactnative.dev/docs/view-style-props#pointerevents is newly introduced style value

**Comment by situchan** [comment]
> 😕 I am really confused, help me understand why `react-native-web` wants to deprecate something which is actively used in `react-native`?

Nope, react-native-web is trying to deprecate same as react-native.
react-native-web doesn't want to deprecate what is actively used and never going to be deprecated in react-native.

**Comment by peterdbarkerUK** [comment]
@mananjadhav could you review the [regression checklist](https://github.com/Expensify/App/issues/31101#issuecomment-1819065331)? This feels like something we should add to TestRail

**Comment by mananjadhav** [comment]
I think we have the [PR](https://github.com/Expensify/App/pull/24482) here as the offending PR.

Though I think this would've been difficult to detect considering it was an external package upgrade. I agree we should add a regression test for this one. The Test steps from the PR look good to me. wdyt @danieldoglas @peterdbarkerUK ?

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mananjadhav based on [this comment](https://github.com/Expensify/App/issues/31101#issuecomment-1832187798).

**Comment by peterdbarkerUK** [comment]
I need to hard-prioritise something else today, so this will now be a Wednesday job.

**Comment by peterdbarkerUK** [comment]
Blackholing a star notification

**Comment by peterdbarkerUK** [comment]
Ooop, I had [this](https://github.com/Expensify/Expensify/issues/346747) all written out and never hit submit, I clearly got distracted end of last week. All done!
