### ISSUE TITLE
[$500] IOU - User is redirected to not here page after deleting IOU request with message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33295]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.1.14.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM.
2. Click + > Request money.
3. Create a manual request.
4. On request details page, edit the amount.
5. Click 3-dot menu > Delete request.
6. Delete the request.
7. Click on browser back button.

## Expected Result:
In Step 6, after deleting the request, user is redirected to the main chat or Concierge since the report is now not unavailable.

## Actual Result:
In Step 6, after deleting the request, user is redirected to not here page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/90eedb90-a2e4-47bd-b5df-e9e3435050b4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7ea0b939fdc648e</li>
        <li>Upwork Job ID: 1737130492537094144</li>
        <li>Last Price Increase: 2024-01-02</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 28081714</li>
<li>dukenv0307 | Contributor | 28081715</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is redirected to not here page after deleting IOU request with message

### What is the root cause of that problem?
As we navigate back after deleting the request it is navigating to unavailable/deleted report so not here page is displayed 
### What changes do you think we should make in order to solve the problem?

We need to delete the route for the report/request when we delete the request.
### What alternative solutions did you explore? (Optional)

**Comment by namhihi237** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user is redirected to not here page after deleting IOU request with a message edit amou

### What is the root cause of that problem?
When we edit the amount we have a reportAction change amount, so `shouldShowDeletedRequestMessage` here returns the value `false`
https://github.com/Expensify/App/blob/b3ecf327c585ca323a628405f4ffc70877c601a0/src/libs/actions/IOU.js#L2278

Leading to not entering this condition
https://github.com/Expensify/App/blob/b3ecf327c585ca323a628405f4ffc70877c601a0/src/libs/actions/IOU.js#L2503-L2509
### What changes do you think we should make in order to solve the problem?
We should change the condition here to return true if all reportActions in the report are visibleAction and other than MODIFIEDEXPENSE
https://github.com/Expensify/App/blob/b3ecf327c585ca323a628405f4ffc70877c601a0/src/libs/actions/IOU.js#L2278

### What alternative solutions did you explore? (Optional)
N/A

**Comment by akinwale** [comment]
After reviewing both proposals, the proposed solution in @dukenv0307's [proposal](https://github.com/Expensify/App/issues/33295#issuecomment-1863240534) is more elegant and I suggest that we move forward with this.

🎀👀🎀 C+ reviewed.

**Comment by namhihi237** [comment]
@akinwale I think that solution is not enough, as I mentioned in the alternative solution, if we forward that way we need to update `childVisibleActionCount ` when the task is created and removed, otherwise it will cause regression

**Comment by iwiznia** [comment]
>  it's checking the last visible message, which will include MODIFIEDEXPENSE report actions, which are not considered visible comments in the thread that we should keep after deleting the money request

So MODIFIEDEXPENSE action is considered invisible in a non thread chat but considered visible in a thread?

**Comment by iwiznia** [comment]
Oh sorry, missed that comment... maybe this is fixed then? @kbecciv can you confirm if the bug is gone?

**Comment by akinwale** [comment]
> Oh sorry, missed that comment... maybe this is fixed then? @kbecciv can you confirm if the bug is gone?

It is still reproducible. The final step is to click on the browser back button.

**Comment by iwiznia** [comment]
Ah got it. OK proposal looks good then, just nitpick I think it's clearer to make it a regular condition instead of a ternary:
```
const shouldDeleteTransactionThread = transactionThreadID && !reportAction.childVisibleActionCount;
```

**Comment by akinwale** [comment]
@iwiznia I just ran another test on the latest main and it appears this has been fixed. It looks like I did not have my local branch updated when I initially checked.

We can close the issue.

**Comment by iwiznia** [comment]
Oh lol great
