### ISSUE TITLE
 Send Money - The participant selection page for Send money flow is noticeably slower

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33322]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32962
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to FAB> Send Money> Add amount

## Expected Result:
The participant selection page should be immediately open

## Actual Result:
The participant selection page for Send money flow is noticeably slower
Also, Search page hangs for seconds when closing it while the list is still loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ca981a22-2aa7-4d2d-af6f-a9bddad89c8c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment]
@lanitochka17 we had a regression tied to this flow that was fixed just now, could you re-test this please 🙇

**Comment by NikkiWines** [comment]
This loads immediately for me on staging, I don't think this is a blocker 

https://github.com/Expensify/App/assets/16747822/bf77e9e2-6e03-4f6a-bb58-c039fa2ecf2b

**Comment by TMisiukiewicz** [comment]
Still happens to me on `main` when using heavy account. I think it should be reopened as it seems it's not a regression from #32962 


https://github.com/Expensify/App/assets/13985840/919cb94d-641e-4f50-9161-98ae919171de

**Comment by mountiny** [comment]
@TMisiukiewicz The heavy account is really putting strain in the app, can you confirm that production is noticeably faster than staging for that account?

**Comment by TMisiukiewicz** [comment]
@mountiny staging and production are both suffering on that account, seems like the result is very similar

**Comment by mountiny** [comment]
In that case I think we can keep this closed as not a blocker and maybe bring this as a problem to performance channel and something to audit/ deiagnose for heavy accounts
