### ISSUE TITLE
[HOLD for payment 2024-01-31] `predeploy.yml` Github Action is broken in main

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#34108]
# Problem 

The `e2ePerformanceTests / Build apk from latest release as a baseline` step of the `predeploy.yml` has been failing consistently for about 25 runs (as of writing this issue). This appears to be happening since https://github.com/Expensify/App/pull/33645 was merged into main. Looking at one of the failed runs it appears to be Android related ([link](https://github.com/Expensify/App/actions/runs/7440265109/job/20241111986)).

# Solution

Investigate why the GH Action is failing consistently and provide a solution for it.

**Comment by hannojg** [comment]
I don't think the issue is related to that specific PR, but it's a problem people are having at the moment in general when building react native from source.
The issue is with boost and is reported here:

- https://github.com/boostorg/boost/issues/849

**Comment by hannojg** [comment]
I am investigating if we can patch react native for fix - but it might be that the boost archives are just broken on their servers - lets see.

**Comment by greg-schroeder** [comment]
Where did you land on this @hannojg?

**Comment by hannojg** [comment]
Sorry, forgot to update here!
This was a bug in react-native and should be fixed with this PR:

- https://github.com/Expensify/App/pull/31558

(As per [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1704789699107199?thread_ts=1704170670.083909&cid=C01GTK53T8Q) and this [thread](https://expensify.slack.com/archives/C05LX9D6E07/p1704790738355149?thread_ts=1704755329.727759&cid=C05LX9D6E07))

**Comment by blimpich** [comment]
Huh, I'm still seeing the [`process new code merged to main` workflow](https://github.com/Expensify/App/actions/workflows/preDeploy.yml?query=branch%3Amain) failing with what I think is the same [error](https://github.com/Expensify/App/actions/runs/7506827805/job/20439220546).

**Comment by blimpich** [comment]
Conversation for this going on in slack here: https://expensify.slack.com/archives/C05LX9D6E07/p1705092756559629?thread_ts=1704755329.727759&cid=C05LX9D6E07

**Comment by hannojg** [comment]
So it seems like there is a new issue now with the build step:

```
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
      Your current JDK is located in /usr/lib/jvm/temurin-11-jdk-amd64
      You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
```

**Comment by blimpich** [comment]
Huh, weird. @Julesssss @AndrewGable are you aware of any changes that might have caused the gradle issue that @hannojg mentioned?

**Comment by hannojg** [comment]
https://github.com/Expensify/App/commit/d541723453b40b5ab5e79e79cb084b33159f7c3b#diff-9526ccfd1d1813ed49c39f8c54dbeb512607376a007d824b905bc8b4e4d202d9 I think this commit may caused the issue.

I can look into it more detail tomorrow if no one is working on that already?
(Can't open the slack link unfortunately for some reason)

**Comment by blimpich** [comment]
@hannojg that sounds good. I don't think anyone else is looking into this right now. And sorry I don't know what happened with that slack link but I think this one should work: https://expensify.slack.com/archives/C05LX9D6E07/p1704755329727759

**Comment by blimpich** [comment]
Assigning to you @hannojg so that Melvin will count your updates and stop saying that this issue is overdue.

**Comment by Julesssss** [comment]
I don't see what change could have caused this, but if we're to take [logs](https://github.com/Expensify/App/actions/runs/7564275220/job/20598206703#step:14:47) at face value we might need to set the JDK version that github Actions run against. Though again I'm confused as to why this would occur out of nowhere 😕

**Comment by hannojg** [comment]
Yeah same @Julesssss the fix is probably quite simple but weird that it randomly happened. Didn't find the time today to push a PR - will do tmrw!

**Comment by hannojg** [comment]
PR is up:

- https://github.com/Expensify/App/pull/34786

**Comment by hannojg** [comment]
We just merged the PR. Seems like the issue is fixed:

![CleanShot 2024-01-22 at 15 33 54@2x](https://github.com/Expensify/App/assets/16821682/07f1acfb-00d9-41d0-8940-951b88010825)

However, right now, we check out the latest release version for the baseline app. This release currently doesn't include the new build action. So we have to wait for a new release for the pipeline to work again:

![CleanShot 2024-01-22 at 15 34 04@2x](https://github.com/Expensify/App/assets/16821682/8cc7f934-f3b7-4528-a1c8-4406fe614407)

**Comment by blimpich** [comment]
Sounds good, we can wait ⏳

**Comment by greg-schroeder** [comment]
No payments required - Margelo + internal reviews
