### ISSUE TITLE
Room - Inviting new user shown as hidden

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34175]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a room chat
3. Type @
and paste 2 new expensifail user who doesn't have account
4. Send the message

## Expected Result:
Inviting new user to room must not be shown as hidden in room chat page.

## Actual Result:
Inviting new user to room shown as hidden in room chat page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4c5b7332-893d-493f-b395-e76f26e49156

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kameshwarnayak** [comment]
Unable to reproduce in the main

**Comment by garrettmknight** [comment]
Couldn't replicate on prod, but I could on staging.

**Staging:**
<img width="570" alt="Screenshot 2024-01-12 at 6 45 28 PM" src="https://github.com/Expensify/App/assets/1529980/11b7f4bc-87ce-432e-a253-41e778b1932f">
**Prod:**<img width="736" alt="Screenshot 2024-01-12 at 6 46 31 PM" src="https://github.com/Expensify/App/assets/1529980/3e2b22fe-d9cd-4439-9e0f-70d18d61e0da">

**Comment by s77rt** [comment]
Not overdue. Awaiting for proposals (assuming the bug is still reproducible)

**Comment by kameshwarnayak** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Room - Inviting new user shown as hidden

### What is the root cause of that problem?

Root cause of the problem is `message.html` in the `onyxData` for `ACTIONABLEMENTIONWHISPER` action when `AddComment` API is made doesn't include the email id. 

This is the response
`Heads up, <mention-user accountID=16255402></mention-user> isn't a member of this room.`

Same can be observed in the below screenshot. 

<img width="1438" alt="Screenshot 2024-01-16 at 1 51 49 PM" src="https://github.com/Expensify/App/assets/2232432/9410743e-abf1-4427-bc79-30b0dc667182">


The user details is not in the local onyx and cannot be extracted from the local storage. Because of this, the below line returns `hidden`

https://github.com/Expensify/App/blob/8e2fb675389bb84deee4b8e001a536252883e72f/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L44

### What changes do you think we should make in order to solve the problem?
Best solution is for the backend to include the email id in the `message.html` response as shown below

`Heads up, <mention-user accountID=16255402>test+21312@expensifail.com</mention-user> isn't a member of this room.`

Alternatively we can make an additional request to get user details for the `accountID` from the front end. But this is not the best solution and changing the API response is the best way.

**Comment by garrettmknight** [comment]
Chill, Melv. Just got a proposal.

@s77rt can you give this proposal a look when you get a chance?

**Comment by s77rt** [comment]
@kameshwarnayak Thanks for the proposal. Your RCA makes sense. I think we should fix this in two steps:
1. Have BE return the email inside the mention tag as you suggested
2. Modify MentionUserRenderer to fallback to the tag content first before giving up to "Hidden"


🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/34175#issuecomment-1893295563)

Let's mark this Internal first till the BE changes are addressed. The `AddComment` response for the heads up message should include the invited user's email e.g.
```html
Heads up, <mention-user accountID=16271050></mention-user> isn't a member of this room.
```
should be

```html
Heads up, <mention-user accountID=16271050>@admin+lalala4@abdelhafidh.com</mention-user> isn't a member of this room.
```

**Comment by kameshwarnayak** [comment]
@s77rt I think there is a merit in modifying MentionUserRenderer first. 

That way we can test the scenario where the fallback works as expected without forcefully creating the scenario

**Comment by s77rt** [comment]
@kameshwarnayak We can go in parallel

**Comment by kameshwarnayak** [comment]
> @kameshwarnayak We can go in parallel

Yes, Makes sense. Can this be assigned to me too so that I can fix the MentionUserRenderer component.

**Comment by s77rt** [comment]
Makes sense! Is there any case where we want to keep invited users shows up as "Hidden"?

**Comment by jasperhuangg** [comment]
@s77rt at least for the message sender, anyone they mention should never show up as `Hidden`.

**Comment by kameshwarnayak** [comment]
@jasperhuangg That makes sense in this scenario. However it is good to have a fallback because I get this result in the #admin report. The frontend change fixes this. 

Unless it is intended. 

<img width="1440" alt="Screenshot 2024-01-19 at 12 00 54 AM" src="https://github.com/Expensify/App/assets/2232432/b2da6d58-4d4d-44f4-8ffc-83ae68d63186">

**Comment by s77rt** [comment]
@jasperhuangg What about the other members? Would we send them the personal details via the pusher or we are not supposed to send them any?

**Comment by jasperhuangg** [comment]
> That makes sense in this scenario. However it is good to have a fallback because I get this result in the #admin report. The frontend change fixes this.

We should also be fixing this in the back-end by sending out the personal details and updating a few checks. I can create an internal issue that outlines what needs to be done, and I think that should solve all the problems mentioned here.

**Comment by kameshwarnayak** [comment]
@jasperhuangg Sure Jasper. Let me know incase you need any changes done on the frontend.

**Comment by s77rt** [comment]
@jasperhuangg Can you please add `Internal` label here?

**Comment by jasperhuangg** [comment]
Not overdue, have some changes that I'm working on that fix the issue

**Comment by garrettmknight** [comment]
Actively working in the PR. Chill out, melv.

**Comment by jasperhuangg** [comment]
This should be resolved!

**Comment by kameshwarnayak** [comment]
@jasperhuangg - This doesn't fix the issue completely. Please find the video attached. 

https://github.com/Expensify/App/assets/2232432/b0b6284c-3483-4fcd-9f1e-ddaec28786df

The current fix solves the issue for the user is tagged at that moment. However not all older tags are resolved as seen in the video. 

Secondly if you logout and login again the `#admin` report has `@hidden` instead of email ids

<img width="1440" alt="Screenshot 2024-01-30 at 10 44 56 AM" src="https://github.com/Expensify/App/assets/2232432/58fd9247-7930-4414-8542-f55b0c985c3a">

The front end solution mentioned [here](https://github.com/Expensify/App/issues/34175#issuecomment-1893295563). Solves the issue. We can solve this from the backend too. However it might be too much of processing in the backend. The solution mentioned in the proposal requests for personal details if it doesn't exist in onyx. 

Look forward to hearing from you.

**Comment by jasperhuangg** [comment]
@kameshwarnayak We have back-end fixes planned for this, and would rather not move forward with your front-end solution. It breaks the 1:1:1 pattern we use in our code place, namely calling `openPublicProfilePage` to fetch the user's personal details (which is associated with an entirely different action).

cc @puneetlath just double-checking, are we going to make people that are in rooms tied to a policy known users to policy admins?

**Comment by puneetlath** [comment]
Yes, we are!
