### ISSUE TITLE
Message didn’t show up in #social as unread in LHN, but I got the email notification. ie. LHN is not updating from posts in #social til it's clicked on

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34273]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704231385914329

## Action Performed: (Updated by @mallenexpensify on Jan 17)
Precondition: must have access to #social channel in NewDot on the `Expensify Chat` workspace (hence why this needs to be internal, Matt A hasn't been able to reproduce in other rooms)
1. Have focus on a report that isn't #social
2. Have others post to #social or just wait 15 mins for chats to come in, which is usually pretty frequently

## Expected Result: 
New chats to show in LHN for the #social room

## Actual Result: 
New chat don't show in LHN until the chat is clicked on, then chats load in the main #social report and LHN updates. 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01059dcd731dd4aa05</li>
        <li>Upwork Job ID: 1747761033220931584</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
@MitchExpensify if this never happens to you, will you unassign and put me on as BZ?  Thx

**Comment by MitchExpensify** [comment]
Still unable to reproduce reliably https://expensify.slack.com/archives/C049HHMV9SM/p1705174729264039?thread_ts=1704231385.914329&cid=C049HHMV9SM

**Comment by MitchExpensify** [comment]
Switching to Weekly while we figure out how to reproduce

**Comment by mallenexpensify** [comment]
If I had to guess, the repro step involves putting your computer to sleep or closing the lid. 
I can most-reliably reproduce it with the #social room.

**Comment by MitchExpensify** [comment]
Tried closing the lid and sleeping in a variety of ways to no success..

I think I can only close this issue at this point and we can reopen if we are able to reliable reproduce

**Comment by mallenexpensify** [comment]
Gonna take over

**Comment by mallenexpensify** [comment]
It's not just #social, just happened with chat with Scott too, got a desktop notification 20 mins ago, noticed it didn't show in LHN, loaded once I clicked it

**Comment by mallenexpensify** [comment]
Also being discussed [here](https://expensify.slack.com/archives/C049HHMV9SM/p1705463885293559)

**Comment by mallenexpensify** [comment]
Tested in/on a test room and wasn't able to repro.  Wonder if it's because #social has a lot of chats? files?
<img width="394" alt="image" src="https://github.com/Expensify/App/assets/22508304/74b0094d-b0b5-4d9a-9f84-4425d0199acb">

**Comment by kadiealexander** [comment]
Just adding in here that I experience it too - persistently always with #social, but inconsistently with other chats as well. It was worst when we were having issues during harvesting (#fireroom-2024-01-10-site-slowness). And it's definitely worse for chats that have a lot of content. 

https://github.com/Expensify/App/assets/59587260/d0826320-a5bb-4208-a98c-f88084669ad7

**Comment by mallenexpensify** [comment]
Shit, made this External then realized that External folks don't have access to our social channel, changing.

**Comment by mallenexpensify** [comment]
Updated the OP with repro steps, added to the #vip-vsb project and posted in that room.  It's internal cuz contributors don't have access to #social (and I'm unable to reproduce in other rooms, some which I have many dozens of chats in)
https://expensify.slack.com/archives/C066HJM2CAZ/p1705534245864589

**Comment by mallenexpensify** [comment]
Also checking with QA to see if they have any high traffic rooms that contributors can be added to

**Comment by mallenexpensify** [comment]
^^ ooooh, Marc might have [a fix above](https://github.com/Expensify/Web-Expensify/pull/40585)
gonna put this on hold now, pending that PR 🤞

**Comment by mallenexpensify** [comment]
Maybe not directly related but, when I just clicked into #social, it took almost 30 seconds for the chats to load (and the most recent chat to show in LHN)

**Comment by mallenexpensify** [comment]
From Marc [here](https://expensify.slack.com/archives/C049HHMV9SM/p1705692178419189?thread_ts=1705428473.219199&cid=C049HHMV9SM)
In general, I would say for any situations like this i.e. where there are chats missing from the LHN the process to help someone debug it would be:
1. Identify the reportID of the chat that you expect to see (ask the other person if you need to)
2. Confirm that the reportID is not in your Onyx data report_[reportID] key
3. If it is, check to see what the report.notificationPreference value is
4. If it’s not, look at the Network tab and try to see if it came back in the usual places where we might expect to see it i.e. GetMissingOnyxUpdates  or ReconnectApp
5. Previous step requires you have the Network tab open and capturing the responses before you open the app

**Comment by mallenexpensify** [comment]
- https://github.com/Expensify/Web-Expensify/pull/40585#issuecomment-1905064112
Above is on staging, going to try to do some testing later. Also wanting to suss out more examples of where this occurring because, for me, it's almost exclusively in #social.

**Comment by mallenexpensify** [comment]
PR above hit staging two days ago and I'm still experiencing the bug on Version 1.4.31-4
Repro steps are still the same.   

@marcaaron any idea what next best steps might be?  I can post in #engineering to try to get more 👀 on it

**Comment by marcaaron** [comment]
There are a lot of potential things to look into. Generally speaking, it is very hard (maybe impossible?) to _confirm_ the delivery of an update from the server to the client in realtime (or after the fact). If you didn't see the LHN update but got an email then the basic problem would logically be one of these:

- A. Got the update, but something prevented the LHN from updating (possible but unlikely)
- B. Never got the update

B has another layer of complexity because we have "reliable updates" now which means that if you miss an update we should be sending you those updates at some point. I think we don't really do that until you reconnect from being offline or take some other kind of action in the app.

**Comment by marcaaron** [comment]
This could also explain it https://expensify.slack.com/archives/C0671JDRKQW/p1706062397300099?thread_ts=1706048639.315449&cid=C0671JDRKQW

**Comment by mallenexpensify** [comment]
Thanks for the deets and especially the link. I commented there, asking for an update once I can test via staging.  

Also also ran into another issue of #social  not updating
- Send message in iOS
- Stay on the screen with the keyboard and compose box showing
- Ask someone else to confirm once a new post is added after yours
- Observe your message is the last shown on iPhone.  

![IMG_1047](https://github.com/Expensify/App/assets/22508304/e944a957-9159-45f5-87f7-ff5b673a6be9)

**Comment by mallenexpensify** [comment]
Random note... I noticed when I started up this morn and went to #social, the chat in LHN, the one that initially showed when I went to #social then the one that loaded were all different.

**Comment by mallenexpensify** [comment]
Def doesn't seem to be getting better, I've updated NewDot 4 times today and am continually testing, both Flo and Scott have run into issues today too. https://expensify.slack.com/archives/C049HHMV9SM/p1706569754923139?thread_ts=1706551202.735269&cid=C049HHMV9SM

Checking in #ngineering https://expensify.slack.com/archives/C03SSAQ7P/p1706569735098989

**Comment by aldo-expensify** [comment]
Maybe this is related to what is being fixed here: https://github.com/Expensify/Web-Expensify/pull/40434

`AddComment` can crash if the chants has many participants. Maybe sometimes it crashes before sending out the onyx updates?

**Comment by mallenexpensify** [comment]
Another (potentially) interesting bit.  I closed/quit NewDot last night.  When I opened it this morn, it showed an old chat in LHN or #social.  So, even with a clean/fresh instance, it's still not loading and showing correctly. 

Thanks for the comment @aldo-expensify , I'm going to follow that PR.

**Comment by aldo-expensify** [comment]
> Thanks for the comment @aldo-expensify , I'm going to follow that PR.

From my testing yesterday, even if `AddComment` doesn't crash anymore, the push events still don't arrive for big chats, so that PR may not be the final solution

**Comment by mallenexpensify** [comment]
>the push events still don't arrive for big chats, 

Is this specific to Pusher?  
Also, possibly off topic a bit, if the push event doesn't happen for a big chat, does that affect it showing in LHN **and** also in the main chat?  (there's a bug where a bunch of chats from a couple weeks ago don't show in #social, they disappeared)

**Comment by aldo-expensify** [comment]
> does that affect it showing in LHN and also in the main chat?

I think the bug makes you miss the message itself and the latest visible message in the LHN (both updates come from the pusher when someone sends a message).

> bunch of chats

Are you referring to "messages"? are you saying that they sent a message in social that failed to be posted?

**Comment by mallenexpensify** [comment]
This is  the other bug (that I don't think is directly related but ¯\_(ツ)_/¯  ) 
- https://github.com/Expensify/App/issues/34687

**Comment by aldo-expensify** [comment]
I can confirm that messages in `#social` are throwing errors:

<img width="1088" alt="image" src="https://github.com/Expensify/App/assets/87341702/18d296d8-6eee-4f6c-a36c-b621f44baadb">

Log of the command running out of memory: https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2284dc4505deef2dab-YVR%22)+AND+timestamp:[2024-01-30T18:54:56.360Z+TO+2024-01-30T20:54:56.360Z]&index=logs_expensify-026534

This does allow the message to be posted (saved in the database), but the pusher events are not sent so no one gets notified/updated with the new message

**Comment by aldo-expensify** [comment]
> This is the other bug (that I don't think is directly related but ¯_(ツ)_/¯ )
> 
> * [[$500] #Room - When scrolling up in #social Room a weird mix of old chats show up from different dates #34687](https://github.com/Expensify/App/issues/34687)

that looks different, but can't be certain until investigated :P

**Comment by mallenexpensify** [comment]
> I can confirm that messages in #social are throwing errors:

ooooh, and the PR is fixing the `AddComment` bug, right ? so there's a good chance that PR will help or fix things, right?!?!

**Comment by aldo-expensify** [comment]
> ooooh, and the PR is fixing the AddComment bug, right ? so there's a good chance that PR will help or fix things, right?!?!

Apparently it is not fixing it completely. In my local testing of the PR, the command doesn't crash anymore, but I still don't get the pusher events. I haven't investigated why the pusher events are still getting lost.

**Comment by mallenexpensify** [comment]
ooooh, i got a notification *and* #social updated in LHN. I unsure if it's consistent though so will keep checking/testing
<img width="383" alt="image" src="https://github.com/Expensify/App/assets/22508304/67a61817-622b-4c56-9bcb-340176bea96b">

<img width="421" alt="image" src="https://github.com/Expensify/App/assets/22508304/e991ca54-87bc-49c1-9358-a79adf004b67">

**Comment by mallenexpensify** [comment]
Shared in #expensify-bugs
https://expensify.slack.com/archives/C049HHMV9SM/p1706818982723529?thread_ts=1704231385.914329&cid=C049HHMV9SM

**Comment by mallenexpensify** [comment]
Tracked another ~dozen updates in #social and it appears that I'm receiving the desktop notification for all chats and that LHN *is* updating for each comment.

**Comment by mallenexpensify** [comment]
Closing, issue has been fixed,
