### ISSUE TITLE
IOU – The amount is not displayed when the scan of the PDF receipt is complete

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34295]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as the WS employee
3. Select the option to Request money &gt; Scan receipt
4. Select the option to upload a receipt
5. Upload a PDF receipt file
6. Click on Request
7. Wait until the scan of the receipt is complete
8. Once complete navigate to the request conversation

## Expected Result:
The amount is updated and displayed

## Actual Result:
The amount is not displayed when the scan of the PDF receipt is complete, red dot appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b2803811-3a93-4adb-a9f8-e782f1fc831b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Do you have the PDF that was used? The video makes it seem like the smartscan was unable to find an amount in the receipt

**Comment by situchan** [comment]
> Do you have the PDF that was used? The video makes it seem like the smartscan was unable to find an amount in the receipt

@lanitochka17 please

**Comment by joelbettner** [comment]
Just a heads up, this seems like it might be related to https://github.com/Expensify/App/issues/34064.

**Comment by joelbettner** [comment]
@lanitochka17 gentle bump.

**Comment by lanitochka17** [comment]
![ReceiptExample](https://github.com/Expensify/App/assets/78819774/7dcda9c9-52b1-45e7-a91b-1a64ab25757d)

Steps:
1. Go to https://staging.new.expensify.com/
2. Log in as the WS employee
3. Create scan request
4. Open IOU while the receipt is scanning
5. Edit the missing fields Merchant and Amount
6. Go back and reopen the IOU

**Comment by joelbettner** [comment]
I was not able to re-create this. @lanitochka17 the title of the issue says a PDF receipt was scanned, but you've provided a .png image.

**Comment by joelbettner** [comment]
@lanitochka17 could you try to re-create it again? It is possible that this has already been fixed by some other PRs.

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 1.4.28-0


https://github.com/Expensify/App/assets/78819774/3e98d9f1-3089-4489-9ac7-aa2e9ce78ba0

[PDF_receipt.pdf](https://github.com/Expensify/App/files/13990456/PDF_receipt.pdf)

**Comment by joelbettner** [comment]
Thank you @lanitochka17!

@situchan the pdf has been provided in the comment above.

**Comment by joelbettner** [comment]
@lanitochka17 I tried the steps on staging and I was not able to reproduce the issue.

 - I logged in as an employee on a workspace.
 - I uploaded the pdf as a scan for a money request.
 - I opened the money request while the pdf was scanning and changed the merchant and amount
 - I went back to the IOU report and things looked correct
<img width="1014" alt="image" src="https://github.com/Expensify/App/assets/13264774/2ac217d9-7fc3-4f81-975c-f0792fd8e20b">

**Comment by situchan** [comment]
reproduced but differently.
Instead of error, got minus amount

<img width="777" alt="Screenshot 2024-01-20 at 2 03 48 AM" src="https://github.com/Expensify/App/assets/108292595/00c0d451-8fa1-48ec-b3ee-cb1f183ecfeb">
<img width="776" alt="Screenshot 2024-01-20 at 2 03 56 AM" src="https://github.com/Expensify/App/assets/108292595/98f2c974-ab64-4b44-a40e-9833d90262cd">

**Comment by joelbettner** [comment]
@lanitochka17 I'm still quite confused. I'm not able to reproduce this and neither is @situchan.

From the recent video you posted, it looks like the amount never got set during when it was scanning...is that correct? Then, in the video, I do not see you attempting to update the amount as per the reproduction instructions.

I think you may have just run into a smartscan that was incorrect, in which case the user would be able to update the amount?

**Comment by joelbettner** [comment]
If I follow the instructions at the top in the original issue I get the following, which all looks good to me:

I smartscanned the pdf and let it complete:
![image](https://github.com/Expensify/App/assets/13264774/55d37704-8d76-4ae9-b7e8-88f35e607e40)

After it completed smart scanning I opened the transation:
![image](https://github.com/Expensify/App/assets/13264774/6ea43cb1-f479-42fd-af69-7983f94f21b3)

I edited the amount as per the instructions because the smartscanner could not determine which value should be used as the amount:
![image](https://github.com/Expensify/App/assets/13264774/bec0041b-8031-445d-9e86-972896331fcf)

Everything saved correctly:
![image](https://github.com/Expensify/App/assets/13264774/28cdbc3b-404e-412b-bea6-41e6dd3a0d56)


I don't think this is a bug. I think this is just a weird receipt where the amount that should be entered for the transaction is very unclear. When I look at it I cannot tell if the amount should be 9.99, -0.38, 0.38, or 0.00.

<img width="606" alt="image" src="https://github.com/Expensify/App/assets/13264774/cef8c948-f9b6-4de4-971f-4875184d3177">

So, I think the smartscanner did the correct thing in this case and left the amount value to be determined by the user.

**Comment by joelbettner** [comment]
I'm going to close this issue. Feel free to re-open if it is happening with many smartscans where the amount is obvious.
