### ISSUE TITLE
[HOLD #41128] [$500] mWeb - Chat -  The keyboard appears for a moment when leaving the thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.34-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35202

## Action Performed:
1. Go to URL https://staging.new.expensify.com/ on Android
2. Login with any account
3. Navigate to any conversation
4. Start a thread and send some messages
5. Tap and hold on a message and choose Reply in Thread
6. Click on the three-dot menu and hit "Leave thread"

## Expected Result:
The keyboard doesn't appear for a moment when leaving the thread

## Actual Result:
The keyboard appears for a moment when leaving the thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a5af76fc-b522-4efe-93de-d2573919715b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01278478c2e7ed2136</li>
        <li>Upwork Job ID: 1752743923246346240</li>
        <li>Last Price Increase: 2024-03-15</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
I can reproduce this based on the steps in the OP. I think this can be External so waiting for proposals.

**Comment by samilabud** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We are keeping the focus on the composes after we click on ThreeDotsMenu/Leave
https://github.com/Expensify/App/blob/ed95bc03c14e81d6ea78508b2d318ac5231d9b97/src/components/ThreeDotsMenu/index.tsx#L105
However after navigate back to the main chat we loose the focus on the composer, this cause at first the keyboard shows (focused in the composer inside the thread) and later hide (composer is not focused).

### What changes do you think we should make in order to solve the problem?
We should remove the composer focus when user click in the ThreeDotsMenu removing this code (e.preventDefault()):
https://github.com/Expensify/App/blob/ed95bc03c14e81d6ea78508b2d318ac5231d9b97/src/components/ThreeDotsMenu/index.tsx#L107
```

onMouseDown={(e) => {
                            /* Keep the focus state on mWeb like we did on the native apps. */
                            if (!Browser.isMobile()) {
                                return;
                            }
}}

```
**Result:**

https://github.com/Expensify/App/assets/5216036/4069a067-4495-4ac1-80e0-1f30b077e150

### What alternative solutions did you explore?
We can set composer focused when user navigate back to the main chat.

**Comment by Christinadobrzyn** [comment]
collecting proposals!

**Comment by sobitneupane** [comment]
@samilabud 

https://github.com/Expensify/App/blob/ed95bc03c14e81d6ea78508b2d318ac5231d9b97/src/components/ThreeDotsMenu/index.tsx#L102-L108

Above code block was introduced by [this PR](https://github.com/Expensify/App/pull/28899). As per the discussion in the PR, the change was made to refocus the text input after closing the modal.

> I was testing it and in any other case, if the composer was focused and we open any modal or menu, it get's refocused on going back, so we should do the same with the 3 dots!

We refocus the text input after closing the modal in Native and mWeb. If we remove the code, the text input will not get refocused even if we close the modal without taking any action.

**Comment by Christinadobrzyn** [comment]
Still accepting proposals!

**Comment by samilabud** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/35494#issuecomment-1920018779)

@sobitneupane I have added the details of alternative proposal, please check it out.

**Comment by sobitneupane** [comment]
I will review the proposal asap.

**Comment by sobitneupane** [comment]
@samilabud Thanks for the update.

But I am quite confused about the solution. It looks like a work around to me.

What we want is to prevent the keyboard to appear close and reopen after leaving the thread. Can you please re-sate the problem, the root cause and how your solution is going to deal with the root cause. Please do explain your solution as well.

**Comment by Christinadobrzyn** [comment]
hi @sobitneupane can you take a peek at the updated proposal or let me know if you'd like me to raise the price to get more proposals?

**Comment by sobitneupane** [comment]
@samilabud Thanks for your proposal. I am not sure if we want to autofocus the Composer of the report after user leaves the thread.

@Christinadobrzyn Do we want to autofocus the Composer of the report after user leaves the thread?

**Comment by Christinadobrzyn** [comment]
Hi @sobitneupane oh that is a good question, it looks like we autofocus the composer on the other platforms so I think that would be the expectation on Android too. Example on NewDot app


https://github.com/Expensify/App/assets/51066321/baccce2f-e272-4e79-b459-de379f545761

**Comment by sobitneupane** [comment]
@Christinadobrzyn I think we should compare it with Native apps rather than Web. I will test it on Android and update here.

**Comment by sobitneupane** [comment]
In Android/Native, we don't open keyboard on leaving the thread.

https://github.com/Expensify/App/assets/25876548/d4adfe6b-d542-43ba-8f8b-8eaa902757a7

**Comment by Christinadobrzyn** [comment]
Oh perfect - good thinking @sobitneupane! Thank you for testing!

**Comment by sobitneupane** [comment]
@Christinadobrzyn We would want[ this behavior](https://github.com/Expensify/App/issues/35494#issuecomment-1953808192) in mWeb as well, right?

**Comment by Christinadobrzyn** [comment]
yeah I think we want the same behaviour across all platforms. But I think this 'keyboard issue' would only affect the mobile apps right?

**Comment by Christinadobrzyn** [comment]
Just checking in, do you need anything @sobitneupane?

**Comment by Christinadobrzyn** [comment]
hi @sobitneupane can you lend an update? Should I reach out to SWM or Callstack to see if they might be able to help?

**Comment by sobitneupane** [comment]
Sorry for the delay @Christinadobrzyn. I will review it today.

**Comment by sobitneupane** [comment]
@Christinadobrzyn It behaves differently in Android:Native and iOS:Native.

In Android:Native, when we leave the thread, the keyboard doesn't appear.

In iOS:native, if the parent report has the keyboard opened while entering the thread, the keyboard will reappear on leaving the thread. If the parent report has the keyboard closed while entering the thread, the keyboard will remain closed on leaving the thread.

I think the behavior we want is the later(iOS:Native) . [This issue](https://github.com/Expensify/App/issues/35494#issue-2110602099) is existent on iOS:Native as well.

https://github.com/Expensify/App/assets/25876548/504e7a2d-4892-452d-8689-594eb47c8ccd

**Comment by Christinadobrzyn** [comment]
Oh wow, that's great testing @sobitneupane. Hum... I might need to tap the shoulders of some engineers here to see what we want to have happen here. Let me reach out to the team for some feedback on what we should expect here.

**Comment by Christinadobrzyn** [comment]
Reached out to the team for some guidance on what we want here - https://expensify.slack.com/archives/C066HJM2CAZ/p1709232994656039

**Comment by Christinadobrzyn** [comment]
Follow up from the team @sobitneupane 

Here's what is expected: 

> They keyboard should only appear when clicking on compose, so I think the keyboard should not automatically appear when clicking Leave. It should only appear when the input field is tapped

So I think that means we want to follow Android:Native based on ^ (the keyboard only opens when you tap on Compose) does that sounds correct?

**Comment by sobitneupane** [comment]
Yup. That sounds right. We can do that.

> They keyboard should only appear when clicking on compose, so I think the keyboard should not automatically appear when clicking Leave. It should only appear when the input field is tapped

**Comment by Christinadobrzyn** [comment]
Awesome! thank you @sobitneupane! It sounds like we're back to reviewing proposals, right?

**Comment by sobitneupane** [comment]
Yes, @Christinadobrzyn. Waiting for proposals.

@samilabud Would you like to update your proposal?

**Comment by Christinadobrzyn** [comment]
Hi @ra-md - yes I think this can be external if you want to submit a proposal! 

(@sobitneupane let me know if that's incorrect and it is internal)

**Comment by sobitneupane** [comment]
Nope. This can be external. We are looking for proposals to solve the issue.

**Comment by Christinadobrzyn** [comment]
Collecting proposals!

**Comment by Christinadobrzyn** [comment]
@sobitneupane do you think the bounty should be raised on this job? Not sure how complex it is.

**Comment by sobitneupane** [comment]
I believe it's not complicated. I suggest sharing it in the expensify-open-source channel to increase visibility.

**Comment by Christinadobrzyn** [comment]
Asking SWM if they can take this - https://expensify.slack.com/archives/C04878MDF34/p1710295513394389

**Comment by jeremy-croff** [comment]
> Asking SWM if they can take this - https://expensify.slack.com/archives/C04878MDF34/p1710295513394389

Would you like proposals for the two mentioned differences?
1. Don't appear the keyboard briefly on Android
2. Don't re-appear the keyboard on IOS Native ( even if it was previously opened ) as per the last findings.

**Comment by Christinadobrzyn** [comment]
Hi @jeremy-croff! Thanks for checking on this - hum... that is a good question - I think the workflow we want is for the keyboard not to open on any devices so I'm not sure if that needs multiple proposals - @sobitneupane can you lend some insights?

**Comment by jeremy-croff** [comment]
> Hi @jeremy-croff! Thanks for checking on this - hum... that is a good question - I think the workflow we want is for the keyboard not to open on any devices so I'm not sure if that needs multiple proposals - @sobitneupane can you lend some insights?

I had deleted me question but the original questeion was this:

Do we propose both for:
1. mWeb flashing of keyboard
2. IOS Native to not remember the previous state

But after thinking through it, if we lost focus it would handle both, so I deleted it. Thanks!

**Comment by Kicu** [comment]
hey, I'm Mateusz and I work for SWM, I will also take a look at this one

**Comment by Kicu** [comment]
@Christinadobrzyn @sobitneupane I did some investigating and my understanding is that the keyboard flashes because of the `preventDefault` introduced in this PR: https://github.com/Expensify/App/pull/28899 which makes the composer on the thread page to newer de-focus (blur) when clicking three dots menu. So after we click "leave" for a split second the focus is back on the composer in the thread report (so keyboard appears) and then we navigate to previous view (keyboard disappears).

I believe that is more-less consistent with the description of root cause by @ra-md above - what he wrote in the cause section makes sense to me. Im not sure about the solution.

---

**However** I talked to a few folks at SWM and was informed that they hope to soon introduce the live markdown editor on web. Because of that I checked if the bug still exists on this branch: https://github.com/Expensify/App/pull/38152 and it seems it does not.

On this branch the behavior is that after leaving the thread the focus correctly returns back to composer which means the  keyboard appears but does not flash (check my video).

So 2 questions:
Q1: if we want to introduce this markdown editor should we perhaps wait with this bug?
Q2: Im still not 100% sure what is your intention about the focus when leaving the thread - should it try to go back to previous state (focused/unfocused) or should it just always de-focus? 

### new behavior on Android: mWeb

https://github.com/Expensify/App/assets/3929868/ed35ed1f-281e-4816-9dc7-a516212e5cbb

**Comment by sobitneupane** [comment]
Thanks @Kicu 

> Q1: if we want to introduce this markdown editor should we perhaps wait with this bug?

We can wait on https://github.com/Expensify/App/pull/38152 if it fixes the issue of keyboard reappearing.

> Q2: Im still not 100% sure what is your intention about the focus when leaving the thread - should it try to go back to previous state (focused/unfocused) or should it just always de-focus?

According to @Christinadobrzyn [here](https://github.com/Expensify/App/issues/35494#issuecomment-1977504027), we would always like to de-focus when leaving the thread.

cc: @Julesssss

**Comment by Christinadobrzyn** [comment]
hold for https://github.com/Expensify/App/pull/38152

**Comment by Christinadobrzyn** [comment]
monitoring https://github.com/Expensify/App/pull/38152

**Comment by Christinadobrzyn** [comment]
https://github.com/Expensify/App/pull/38152 is in prod - testing again 

testing again, I think this is resolved - asking QA for a buddy check. https://expensify.slack.com/archives/C9YU7BX5M/p1712807680219989

**Comment by kavimuru** [comment]
Issue is fixed now. But the behavior now is little different. Keyboard does not disappear when leaving the chat.

https://github.com/Expensify/App/assets/43996225/b76e6599-84f2-4bbb-ab05-5bb81e931c78

**Comment by Julesssss** [comment]
Thanks for sharing. Yeah we'll need to take a look at that

**Comment by Christinadobrzyn** [comment]
hi sorry @sobitneupane or @Julesssss can you provide an update, I'm not sure if we looking for proposals for the issue reported https://github.com/Expensify/App/issues/35494#issuecomment-2049863174 or if that should be a different issue. I'm wondering if that is an issue at all...

**Comment by Christinadobrzyn** [comment]
Dmd Jules to see if I can get some guidance on what to do next for this

**Comment by Julesssss** [comment]
Hey @Christinadobrzyn I was ooo. 

> But the behavior now is little different. Keyboard does not disappear when leaving the chat.

As the user is going back to a parent thread I'm not sure this is a big issue. The pre-fix keyboard issue was far worse in my opinion, but lets see if we can further improve. Some questions first though: 

- Is this only occurring on Android?
- Does this only occur when navigating from a child thread back to a parent thread?
- What about being linked from one chat to another?
- When going from a top level chat to the LHN does this occur?

**Comment by Christinadobrzyn** [comment]
Sorry for the delay here - I'll test these on Monday unless someone @sobitneupane you have time. 

1. Is this only occurring on Android?
2. Does this only occur when navigating from a child thread back to a parent thread?
3. What about being linked from one chat to another?
4. When going from a top level chat to the LHN does this occur?

**Comment by sobitneupane** [comment]
> 1. Is this only occurring on Android?

 I tested it on IOS. But it looks like there is some Issue in IOS with navigation. Each time I leave the thread instead of going back to the parent thread, it opens a new report(parent report). When I go back, I will end up in the same report(parent report). This issue can only be tested once the issue gets resolved.
 

https://github.com/Expensify/App/assets/25876548/3ea04dcc-e6bc-46aa-aa0e-07181676e18a

I could not test it on android though. I am having some issue while trying to build android.

**Comment by Julesssss** [comment]
Hey @sobitneupane, the issue you mention sounds like [this issue](https://github.com/Expensify/App/issues/41128).  Maybe we can wait for this one to be resolved

**Comment by sobitneupane** [comment]
> Hey @sobitneupane, the issue you mention sounds like [this issue](https://github.com/Expensify/App/issues/41128). Maybe we can wait for this one to be resolved

Agreed. It seems like there might be a connection there.

**Comment by Christinadobrzyn** [comment]
added Hold for https://github.com/Expensify/App/issues/41128 to the subject. Let me know if that doesn't seem like the best next move.

**Comment by Christinadobrzyn** [comment]
watching - https://github.com/Expensify/App/issues/41128

**Comment by Julesssss** [comment]
Hey @Christinadobrzyn, I'm going to try and move that linked issue forward.

**Comment by Christinadobrzyn** [comment]
thanks @Julesssss! I'll keep an eye on https://github.com/Expensify/App/issues/41128

**Comment by Christinadobrzyn** [comment]
monitoring - https://github.com/Expensify/App/issues/41128

**Comment by Christinadobrzyn** [comment]
monitoring - https://github.com/Expensify/App/issues/41128

**Comment by Christinadobrzyn** [comment]
PR  - https://github.com/Expensify/App/issues/41128 is done and I think this is resolved. 

Testing again and the keyboard shows after leaving a thread. 

https://github.com/Expensify/App/assets/51066321/c6d690b8-2e26-4f6a-bd37-02b8244b301c

Gonna ask QA to test again.

**Comment by isagoico** [comment]
Issue is still reproducible on Android mWeb 

https://github.com/Expensify/App/assets/44479856/af6b9f9d-a2a9-4066-9184-39aa716c6651

**Comment by Christinadobrzyn** [comment]
hum @sobitneupane can you restest? I'm not able to reproduce as is above https://github.com/Expensify/App/issues/35494#issuecomment-2134661043

**Comment by sobitneupane** [comment]
@Christinadobrzyn I could not reproduce the [issue](https://github.com/Expensify/App/issues/35494#issuecomment-2134661043) in Android/Chrome.

**Comment by Christinadobrzyn** [comment]
Awesome - let's close! thanks for checking @sobitneupane!
