### ISSUE TITLE
The color of Status Bar (top part of the background) is not consistent

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35632]
## Action Performed:
1. Open the app on iOS (confirming with @s77rt if this issue is only present on iOS)
1. Go to Chat page (Chat icon on the bottom tab)
2. Go to Settings page (🔧 icon on the bottom tab)
3. Go to Settings page > Workspaces

## Expected Result:
The color should be consistent

## Actual Result:
The colors are different across different pages

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

screenshots -> https://github.com/Expensify/App/pull/33280#issuecomment-1922009959

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hayata-suenaga** [comment]
Please hold a little bit before posting proposals until I confirm that this issue is handled independently (there is a possibility that this issue is combined with [this issue](https://github.com/Expensify/App/issues/35571))

**Comment by bernhardoj** [comment]
Posting a proposal before going offline in case we want to handle it separately.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The status bar color doesn't match the page on the chat and workspace list page.

### What is the root cause of that problem?
The status bar color is defined by the PAGE_THEMES here.
https://github.com/Expensify/App/blob/8fa0994d09038dd32f2079bf6bd121c999a14d29/src/styles/theme/themes/dark.ts#L94-L98

The chat/HOME page uses `productDark200` (for dark mode) as the color, but the page color uses `appBG`, which is `productDark100`. It goes the same for the workspace list which uses pink color.
https://github.com/Expensify/App/blob/8fa0994d09038dd32f2079bf6bd121c999a14d29/src/styles/theme/themes/dark.ts#L111-L114

### What changes do you think we should make in order to solve the problem?

We can update the color to `productDark100` to match the page color or just remove it from the list because the default value is `productDark100` (appBG).
https://github.com/Expensify/App/blob/8fa0994d09038dd32f2079bf6bd121c999a14d29/src/components/CustomStatusBarAndBackground/index.tsx#L74-L75

_we need to update the light mode color too_

**Comment by rushatgabhane** [comment]
defering to @hayata-suenaga's comment to hold https://github.com/Expensify/App/issues/35632#issuecomment-1924192114

**Comment by hayata-suenaga** [comment]
still waiting for an answer to [this](https://github.com/Expensify/App/issues/35571#issuecomment-1924156952)

**Comment by kosmydel** [comment]
This one was fixed in [this PR](https://github.com/Expensify/App/pull/35564).

However, there are other problems with StatusBar: 
- android insets are broken sometimes: https://github.com/Expensify/App/pull/35564#issuecomment-1926772435,
- the status bar is not updating after theme change: https://github.com/Expensify/App/pull/35672#issuecomment-1933807425

**Comment by hayata-suenaga** [comment]
Because the issue is fixed in @kosmydel's [PR](https://github.com/Expensify/App/pull/35672), I'll close this issue.

> the status bar is not updating after theme change

@kosmydel, could you handle this issue in your PR?

**Comment by bernhardoj** [comment]
@hayata-suenaga It's not fixed yet for the home page https://github.com/Expensify/App/issues/35632#issuecomment-1934279437

**Comment by hayata-suenaga** [comment]
The offending issue for the deploy blocker liked above was identified and it's not this issue

**Comment by hayata-suenaga** [comment]
> @hayata-suenaga It's not fixed yet for the home page https://github.com/Expensify/App/issues/35632#issuecomment-1934279437

[checking here](https://github.com/Expensify/App/pull/35672#issuecomment-1936290751)

**Comment by hayata-suenaga** [comment]
@kosmydel could you check [this comment](https://github.com/Expensify/App/issues/35632#issuecomment-1934279437) when you have time please? 🙇

**Comment by kosmydel** [comment]
> @kosmydel could you check [this comment](https://github.com/Expensify/App/issues/35632#issuecomment-1934279437) when you have time please? 🙇

Changing this in config broke the android insets. That's why I haven't changed it. Here is more details:
https://github.com/Expensify/App/pull/35564#issuecomment-1926772435

**Comment by hayata-suenaga** [comment]
>> @kosmydel could you check https://github.com/Expensify/App/issues/35632#issuecomment-1934279437 when you have time please? 🙇
> 
> Changing this in config broke the android insets. That's why I haven't changed it. Here is more details:
> https://github.com/Expensify/App/pull/35564#issuecomment-1926772435

@kosmydel Thank you for reminding me of that. Are you working on this in a separate issue or should I create a new issue for you?

**Comment by kosmydel** [comment]
> @kosmydel Thank you for reminding me of that. Are you working on this in a separate issue or should I create a new issue for you?

I can have a look at this, but I found a PR (https://github.com/Expensify/App/pull/34409) that addresses a mWeb status bar issue. The author of the PR [suggests that he found a solution for that](https://github.com/Expensify/App/pull/35672#issuecomment-1937839694). In case this doesn't solve our problem, I can surely investigate it.

**Comment by hayata-suenaga** [comment]
okay let's see if the PR will solve the issue 👍
