### ISSUE TITLE
[HOLD for payment 2024-03-11] [HOLD for payment 2024-03-07] IOU details page appears after delay and it is empty when request is created offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37466]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Request money from any user.
3. In 1:1 DM, click on the IOU preview twice to go to transaction thread.
4. Return to IOU report.
5. Click on the IOU preview to go transaction thread again.
6. Note that the details show up after some delay.
7. Go offline.
8. Create another IOU with the same user.
9. Click on the IOU preview twice to go to transaction thread.

## Expected Result:
In Step 5, the IOU details page will appear without delay (production behavior).
In Step 9, the IOU details will show even when the request is created offline (production behavior).

## Actual Result:
In Step 5, the IOU details page appears after some delay.
In Step 9, the IOU details page is blank when the request is created offline.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/25c59098-4e26-4490-b72c-3a061ed77de6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@techievivek FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by techievivek** [comment]
Seems like a regression from some recent change and indeed a bad one.

**Comment by youssef-lr** [comment]
This seems to be coming from [here](https://github.com/Expensify/App/pull/37449), reverting it fixed it for me. cc @tgolen 

https://github.com/Expensify/App/assets/9680864/75b8ecc3-0669-4e84-9acb-d5b2cf2d9eae

**Comment by techievivek** [comment]
@youssef-lr Great catch, any idea why I am unable to find this PR changes in the diff between staging and production https://github.com/expensify/app/compare/production...staging
I was trying to look at the recent deployed changes to figure out what could have caused this.

**Comment by youssef-lr** [comment]
I'm not sure, what I did was go through the PRs from the [checklist](https://github.com/Expensify/App/issues/37459).

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The detail view appears with a delay while online, but not shown at all while offline.

### What is the root cause of that problem?
This happens after this [PR](https://github.com/Expensify/App/pull/37449) that replaces `ReportActionsUtils.getParentReportAction` usage with an onyx subscription.
https://github.com/Expensify/App/blob/48b24ec69b585d4fc660e9569a59d72aeb21c637/src/pages/home/ReportScreen.js#L648-L658

When we open the transaction thread for the first time, the onyx selector props is always undefined (onyx bug, [known issue](https://expensify.slack.com/archives/C01GTK53T8Q/p1706734523238609), explained at the bottom of root cause), so `parentReportAction` will return an empty object initially. After we get the report action data, the `ReportActionsView` won't re-render because the component is memoized and we [didn't include `parentReportAction`](https://github.com/Expensify/App/blob/48b24ec69b585d4fc660e9569a59d72aeb21c637/src/pages/home/report/ReportActionsView.js#L281).

If the parent action data is empty, `shouldDisplayParentAction` will be `true` even though it should be `false`
https://github.com/Expensify/App/blob/5cfcf69c243d2f74037587bac49f256c056abc3b/src/pages/home/report/ReportActionsListItemRenderer.js#L58-L59

The `shouldDisplayParentAction` component uses ancestor logic as shown below.
https://github.com/Expensify/App/blob/5cfcf69c243d2f74037587bac49f256c056abc3b/src/pages/home/report/ReportActionItemParentAction.tsx#L76
https://github.com/Expensify/App/blob/5cfcf69c243d2f74037587bac49f256c056abc3b/src/libs/ReportUtils.ts#L4991-L4995

Notice that we take the `parentReportAction` in `getAllAncestorReportActionIDs` imperatively and it's possible that the data is available in that function scope.

While online, it's most likely other props is triggering the re-render

<details>

<summary>Onyx issue</summary>

Both `parentReportAction` `key` and `selector` depend on the component props, in this case, `report` and both have issues. First, the `key`.

`key` expects the function params to pass the component existing props. However, the component `props` never contains the other previous onyx data.
https://github.com/Expensify/react-native-onyx/blob/d59649ef69a563ad2cffd55995875e711a5182a3/lib/withOnyx.js#L60

Second, the `selector`. When the component is first rendered, we try to get the cached value and use the `selector` if available.
https://github.com/Expensify/react-native-onyx/blob/d59649ef69a563ad2cffd55995875e711a5182a3/lib/Onyx.js#L278-L284

However, the `selector` will only work properly if we pass the current state of the component. From the code linked above, notice that we take the state from `mapping.withOnyxInstance.state`, but it's never available because the `mapping` object inside the `withOnyx` constructor doesn't contain a `withOnyxInstance` with a `state` property.
https://github.com/Expensify/react-native-onyx/blob/d59649ef69a563ad2cffd55995875e711a5182a3/lib/withOnyx.js#L61

</details>
### What changes do you think we should make in order to solve the problem?

For the re-render issue, we should include `parentReportAction` equality check to `ReportActionsView` memo.
```
if (!_.isEqual(oldProps.parentReportAction, newProps.parentReportAction)) {
    return false;
}
```

For the onyx issue, first, we should get the current state of the onyx data.
```
const cachedState = underscore_1.default.reduce(mapOnyxToState, (resultObj, mapping, propertyName) => {
    // resultObj is the latest reduced object
    const currentState = getOnyxDataFromState(resultObj, mapOnyxToState);
```

Then, extend both `key` props and `value` mapping with the current state.

```
const key = Str.result(mapping.key, {...props, ...currentState});
let value = Onyx.tryGetCachedValue(key, {
    ...mapping,
    withOnyxInstance: {
        state: getOnyxDataFromState(resultObj, mapOnyxToState),
    }
});
```

Just like we did in [here](https://github.com/Expensify/react-native-onyx/blob/d59649ef69a563ad2cffd55995875e711a5182a3/lib/withOnyx.js#L104)

**Comment by techievivek** [comment]
Ok, that is a nice way to figure things out as well. :hattip:
I just realized that changes are there but it was not being rendered unless we click on `load diff`.
<img width="1704" alt="Screenshot 2024-02-29 at 2 55 53 PM" src="https://github.com/Expensify/App/assets/35863227/22dc73f6-f778-4b13-b60b-800a14550ad6">


https://github.com/expensify/app/compare/production...staging#diff-dd4bfa50713397aca8cb40145317936ab0affe19abc2a9c24d6c8849ed75dc9bR564

**Comment by techievivek** [comment]
>  I tried to guess which PR could have caused this from the titles, but at the end gave up and started reverting PRs one by one lol.

Woww 😄 🙇

**Comment by tgolen** [comment]
Wow, great RCA @bernhardoj. I confirmed that updating the memoization fixes the problem. I missed that in the original PR. I should be able to create a PR for that in a few minutes.

For the Onyx issues, it would be great to open a new GH for that and finally get it fixed. I think the explanation is great and that could be a big source of the problems with using selectors.

**Comment by tgolen** [comment]
PR is created here: https://github.com/Expensify/App/pull/37504

**Comment by OfstadC** [comment]
Adding [this here](https://github.com/Expensify/Expensify/issues/372645) for tracking

Affected Primary Email Address
[oyaboardtreasurer@gmail.com](mailto:oyaboardtreasurer@gmail.com)

Concierge Chat
https://www.expensify.com/concierge/#/chat/17591280

**Comment by youssef-lr** [comment]
I think this should be fixed now.

**Comment by bernhardoj** [comment]
Just FYI, the appearance delay is still happening because of the Onyx issue.

**Comment by sakluger** [comment]
I'm kinda confused what's going on here. I think [this PR](https://github.com/Expensify/App/pull/37504) was intended to fix the issue, but according to @bernhardoj, there is still a delay.

@techievivek @youssef-lr do either of you know what's going on?

**Comment by tgolen** [comment]
That PR was really intended to fix the page not loading at all when offline (the worst part). I couldn't see any noticeable delay when loading, but I also don't think it's really _that_ related to any of the recent changes. It's more just that it takes a little time to read the data from Onyx, and that's OK. We could maybe think about implementing a loading state for this, but I don't know if it's really worth it. If you think it's a problem, I think we should open a new GH issue and get proposals for solving the delay.

**Comment by sakluger** [comment]
Thanks for explaining @tgolen. I agree that we've solved the main issue and we can close this out.

Is @parasharrajat due payment for the PR review, or no because it's a regression?

**Comment by tgolen** [comment]
@parasharrajat Still needs paid for a C+ review. The regression was caused by my PR so it's only a mark against me :D

**Comment by sakluger** [comment]
Thanks @tgolen for clarifying. 🙇 

**Summarizing payment on this issue:**

Contributor+: @parasharrajat $500, please request on Newdot

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
