### ISSUE TITLE
Split bill - Duplicated error message when making to split bill request with a user

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37492]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Make a split bill request with a new user
2. Make another split bill request the user again

## Expected Result:
'There is a previously existing chat between these users' error message shouldn't be duplicated

## Actual Result:
'There is a previously existing chat between these users' error message is duplicated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/cbd42f75-d6e1-4e91-8f85-03e53c2b1995

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@Gonals  I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Gonals** [comment]
Taking a look after lunch!

**Comment by Gonals** [comment]
@izarutskaya, why is the error expected in the first place? I don't think asking fro a second split should cause an error at all

**Comment by bernhardoj** [comment]
Yeah, looks like the app tries to generate a new chat, but I can't reproduce it.

https://github.com/Expensify/App/assets/50919443/e1f778b7-e83c-4c70-a82e-ba38733911ae

One weird thing though, is where the contacts list comes from
<img width="195" alt="image" src="https://github.com/Expensify/App/assets/50919443/29a50ae0-08c7-4aa1-8ecd-4a4cbbffb755">

**Comment by Gonals** [comment]
> Yeah, looks like the app tries to generate a new chat, but I can't reproduce it.
> 
>  Screen.Recording.2024-02-29.at.22.38.58.mov 
> One weird thing from the OP video though, is where the contacts list comes from <img alt="image" width="195" src="https://private-user-images.githubusercontent.com/50919443/308962817-29a50ae0-08c7-4aa1-8ecd-4a4cbbffb755.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTgxNjEsIm5iZiI6MTcwOTIxNzg2MSwicGF0aCI6Ii81MDkxOTQ0My8zMDg5NjI4MTctMjlhNTBhZTAtMDhjNy00YWExLThlY2QtNGE0Y2JiZmZiNzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE0NDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzOWUyMGEyOGE2ZGQxNmQ4NDdiNTNhY2FjMmVhYmY0MmIyYzRhYTM2MGEyZWY1N2I0YzVkMzQxMjgwYmJiNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I9X4UNvOR5N4SFh5I_fhlfbOu9ry-czsxNwbkrL1puo">

It only happens if the chosen contact doesn't have an expensify account when you request the first split

**Comment by bernhardoj** [comment]
I split with the identical user as the OP video and looks like it's an existing user as it has a display name of B. I also tried with random non-existing user but still can't reproduce.

**Comment by Gonals** [comment]
> I split with the identical user as the OP video and looks like it's an existing user as it has a display name of B. I also tried with random non-existing user but still can't reproduce.

On Staging? I can reproduce fine

**Comment by Gonals** [comment]
Ok.
Seems like the errors is caused by how we generate the AccountID for the user when the user doesn't have an expensify account:
- We generate an optimistic account in the front end and create the split.
- We call the backend. The account gets created with a different accountID
- We create a new split. The frontend fails to find the existing report because the participant's ID doesn't match.

Fix: Make sure we are passing correctly the optimistic accountID to the backend, and that the backend is actually using it to create the account.

**Comment by puneetlath** [comment]
FYI, this is likely fixed by [this revert](https://github.com/Expensify/App/pull/37529). Will have QA re-test once it is CP'd.

**Comment by puneetlath** [comment]
Looks like that revert ^ didn't fix the issue. So we still need to figure out what is going on here.

**Comment by youssef-lr** [comment]
Reverting that PR locally does not fix the issue for me. I also reproduce this in production:

<img width="1781" alt="Screenshot 2024-02-29 at 21 50 58" src="https://github.com/Expensify/App/assets/9680864/3add5545-4ede-43bd-a86d-1f4d4bd36b69">

I think this is known and related to this issue: https://github.com/Expensify/App/issues/30140

**Comment by youssef-lr** [comment]
Also, I think in production we still don't have a way to split with a single user, so this looks like a deploy blocker because we just made it possible in the linked PR. But this issue is known and can be reproduced if you split with multiple users.

**Comment by youssef-lr** [comment]
Closing in favor of https://github.com/Expensify/App/issues/30140
