### ISSUE TITLE
[HOLD for payment 2024-04-03] [$500] Scan- After uploading a corrupted file, user needs to dismiss error from 2 reports

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37502]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1.Log in in the app
2.Start the Request money ; "Scan" receipt flow
3.Upload a corrupted file
4. After the upload fails the user sees a red error message explaining that the file was not uploaded
5.Click on the X to dismiss the error
## Expected Result:
The expense is deleted and the red error message disappears

## Actual Result:
The user needs to dismiss the error separately from the report chat in LHN and the request chat in LHN

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/bac506ba-d637-4fff-9fea-859e38cd79cc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e40cdcd3593e0c5a</li>
        <li>Upwork Job ID: 1763390673983709184</li>
        <li>Last Price Increase: 2024-03-08</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reviewer | 0</li>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
We think that this bug might be related to #vip-billpay
cc @davidcardoza

**Comment by m-natarajan** [comment]
@kadiealexander FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Pujan92** [comment]
I will review tomorrow.

**Comment by Pujan92** [comment]
@kadiealexander @rayane-djouah  I think the specific iou error should not be displayed with the Report preview. Bcoz if the user creates multiple money requests with the corrupted file, how it can be distinguished for which specific iou it shows the error?
I was trying to find the PR which added that error to the report preview, but not succeeded yet.

**Comment by Pujan92** [comment]
I think we usually show the RBR indicator there which informs the user about some error within any iou.

**Comment by kadiealexander** [comment]
@Pujan92 is correct here, thanks!

**Comment by Pujan92** [comment]
@rayane-djouah's [proposal](https://github.com/Expensify/App/issues/37502#issuecomment-1985230444) looks good to me for showing the RBR indicator to the report preview in a case when there is an error available for any of its iou action.

🎀👀🎀 C+ reviewed

**Comment by MonilBhavsar** [comment]
In the POC video, there is no RBR indication in LHN for the workspace chat. We should display a red dot in LHN, no?

**Comment by MonilBhavsar** [comment]
> Remove the logic that add the error to the report preview action [here](https://github.com/Expensify/App/blob/807ce54e7b045f4e19c0a5b2876f401d23869d8f/src/libs/actions/IOU.ts#L701-L726).

Did we find out the reason why the error message was added to preview action? Let's make sure we don't create regression

**Comment by Pujan92** [comment]
> In the POC video, there is no RBR indication in LHN for the workspace chat. We should display a red dot in LHN, no?

I am not sure whether all ancestor reports to that transaction should show the RBR in the LHN or not. In POC workspace chat doesn't show RBR bcoz as per the current implementation we show it when any of that specific report's action contains an error.

> Did we find out the reason why the error message was added to preview action? Let's make sure we don't create regression

It seems to be added here https://github.com/Expensify/App/pull/30477 but for that change, my earlier [doubt](https://github.com/Expensify/App/issues/37502#issuecomment-1978700389) repeats(do we need to show the same error to the report preview which I believe to exist only for that iou?)

**Comment by MonilBhavsar** [comment]
> I am not sure whether all ancestor reports to that transaction should show the RBR in the LHN or not. In POC workspace chat doesn't show RBR bcoz as per the current implementation we show it when any of that specific report's action contains an error.

Okay, I confirmed. no need to display rbr error on workspace chat report. only on IOU report would do

> It seems to be added here https://github.com/Expensify/App/pull/30477 but for that change, my earlier https://github.com/Expensify/App/issues/37502#issuecomment-1978700389 repeats(do we need to show the same error to the report preview which I believe to exist only for that iou?)

I don't think so, since preview can contain many IOU's and displaying an error is not ideal as we don't know error comes from which IOU report. So we should inly display a red dot on preview and an error message on IOU report.

**Comment by MonilBhavsar** [comment]
Thanks! Proposal looks good to me 👍

**Comment by MonilBhavsar** [comment]
Can we please also test the PR with distance request as we're reverting a change https://github.com/Expensify/App/pull/30477 for distance request.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by MonilBhavsar** [comment]
How is this issue not reproducible by Applause. Did we miss something during test or we updated the code elsewhere? cc @mvtglobally @kadiealexander

**Comment by Pujan92** [comment]
> How is this issue not reproducible by Applause without making a PR. Did we miss something during test or we updated the code elsewhere? cc @mvtglobally @kadiealexander

It is still reproducible with the latest main

https://github.com/Expensify/App/assets/14358475/8f114d88-de28-4b0a-a10d-67669dc984a9

**Comment by MonilBhavsar** [comment]
Okay, thanks for confirming!

**Comment by MonilBhavsar** [comment]
^This might be false warning. Still discussing...

**Comment by kadiealexander** [comment]
@Pujan92 bump for the checklist!

**Comment by Pujan92** [comment]
@kadiealexander I think checklist is not needed here as new behaviour implemented based on [this](https://github.com/Expensify/App/issues/37502#issuecomment-1991091085),

**Comment by Pujan92** [comment]
### Regression Test Steps

1. Goto Request money and select Scan option
2. Upload the corrupted file and click on Request
3. Verify that after the request fails the user sees RBR in iou report preview
4. Verify that the error message explaining that the file was not uploaded is displayed only with the iou action and not for the iou report preview.

Do you agree 👍 or 👎 ?

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $500 @rayane-djouah
- [ ] Contributor+: $500 @Pujan92

Upwork job is [here](https://www.upwork.com/ab/applicants/1763390673983709184/hired).
