### ISSUE TITLE
[$250] Time - Incorrect time is displayed in the conversation when Timezone Asia/Almaty is selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37657]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4360419
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with your HT account
3. Navigate to your account settings
4. Select the Profile menu
5. Navigate to the Timezone menu
6. Disable automatic location detection
7. Select Timezone Asia/Almaty
8. Create a new conversation
9. Send a message to the conversation
10. Match the time to https://time.is/Almaty

## Expected Result:
If you select the time zone Asia/Almaty, the correct time UTC+5 should be displayed in the conversation

## Expected Result:
Incorrect time is displayed in the conversation when Timezone Asia/Almaty is selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/636cfaa1-848b-4d1c-9628-70a7a398e2f9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6b6a2a8c5d7e88b</li>
        <li>Upwork Job ID: 1764447579559890944</li>
        <li>Last Price Increase: 2024-03-04</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mallenexpensify** [comment]
Unsure if we want to fix.  @Ollyws if we do.. I'm assuming this would be a super-quick fix, do you agree? 
Checking on in #vip-vsp
https://expensify.slack.com/archives/C066HJM2CAZ/p1709512189362859

**Comment by mallenexpensify** [comment]
Marked external, put starting price at $250 cuz I have a hunch this should be a pretty quick fix. 
Added to #vip-vsb

**Comment by garatkarr** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The time displayed in the chat page for Asia/Almaty is incorrect. It's off by 1 hour.

### What is the root cause of that problem?
Kazakhstan has decided to unify the entire country under 1 timezone. This is a new change on March 1, 2024.

### What changes do you think we should make in order to solve the problem?
We need to update the date-fns-tz library that contains the latest IANA time zone definitions.

### What alternative solutions did you explore? (Optional)

**Comment by abzokhattab** [comment]
I think that should be fixed from the browser engine itself 

the `date-fns-tz` library uses `Intl.DateTimeFormat` to get the timezone offset as you can notice here it still returns `+6`

<img width="384" alt="image" src="https://github.com/Expensify/App/assets/59809993/1422eb64-87c7-4f82-8257-fbebdec9d7bf">


an alternative would be either to temporally delete the `Asia/Almaty` timezone [here](https://github.com/Expensify/App/blob/426cf80b450677bf46e21a7fe45daade2acf4008/src/TIMEZONES.ts#L212)  since Kazakhstan unified the timezone at the beginning of the month OR we add a special handling for the `Almaty` timezone where if selected the timezone `+5` should be passed to the `utcToZonedTime` [here](https://github.com/Expensify/App/blob/61ad4769e0215b48706a74615e843fb765eeab58/src/libs/DateUtils.ts#L119-L135)

**Comment by askavyblr** [comment]
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
The time displayed on the chat page for Asia/Almaty is incorrect.

What is the root cause of that problem?

The function **getLocalDateFromDatetime** does not return the time according to the specified time zone.

**What changes do you think we should make in order to solve the problem?**

need to change utcToZonedTime to zonedTimeToUtc , zonedTimeToUtc converts time from a specified time zone to UTC time.

What alternative solutions did you explore? (Optional)

**Comment by godofoutcasts94** [comment]
I think this [comment](https://github.com/Expensify/App/issues/37657#issuecomment-1977735612) is totally right and also this problem persists only with Kazakhstan. No other places like Asia/Dubai etc are facing this same kind off issue.
