### ISSUE TITLE
Public room -Flickering skeleton animation displayed when navigating to a specific high-traffic public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37661]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4356797 https://expensify.testrail.io/index.php?/tests/view/4356898
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out of ND
2. Navigate to the public room using the link https://staging.new.expensify.com/r/3504895439653267

## Expected Result:
The public room history is displayed

## Actual Result:
The flickering skeleton animation is displayed for both anonymous and logged-in users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/27276390-ec2b-4d93-96ac-9194163907c0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01588ebc2314d68b01</li>
        <li>Upwork Job ID: 1765421847111221248</li>
        <li>Last Price Increase: 2024-03-06</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sonialiap** [comment]
I can reproduce this in high-traffic public rooms

**Comment by sonialiap** [comment]
[Asking](https://expensify.slack.com/archives/C066HJM2CAZ/p1709646010674799) about adding to VSB

**Comment by aldo-expensify** [comment]
https://github.com/Expensify/App/assets/87341702/fb72657d-baef-4382-aea7-64df6483d923

Seeing the same. The `OpenReport` requests is sent repeatedly even if it is returning with data and status 200.

**Comment by mallenexpensify** [comment]
@ntdiary added a C+ to see if you can help move this along promptly since it appears to be a 🔥 
Posted about in the [main Slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1709744557685969?thread_ts=1709570318.571869&cid=C049HHMV9SM).  Also posting in multiple other threads where people have reported. 

https://github.com/Expensify/App/assets/22508304/063e5312-4729-4e94-8333-7acf3307799c

**Comment by mallenexpensify** [comment]
From @muttmuure [here](https://expensify.slack.com/archives/C049HHMV9SM/p1709736085611629?thread_ts=1709735010.687869&cid=C049HHMV9SM)
> I’m seeing this in my logs. Why does it think that the lastUpdateID is 0?

```
{
    "time": "2024-03-06T14:35:00.110Z",
    "level": "DEBUG",
    "message": "[info] [OnyxUpdateManager] Applying update type: https with lastUpdateID: 0 - {\"command\":\"Log\"}"
  },
  {
    "time": "2024-03-06T14:35:00.108Z",
    "level": "DEBUG",
    "message": "[info] Previous log requestID - {\"requestID\":\"860311d5f8d97318-LHR\"}"
  },
  {
    "time": "2024-03-06T14:34:58.763Z",
    "level": "DEBUG",
    "message": "[info] [Onyx] merge() called for key: reportMetadata_6776919265133947 properties: lastVisitTime,isLoadingInitialReportActions,isLoadingOlderReportActions,isLoadingNewerReportActions - \"\""
  },
  {
    "time": "2024-03-06T14:34:58.762Z",
    "level": "DEBUG",
    "message": "[info] [Onyx] merge() called for key: reportActions_6776919265133947 properties: 5220381777552645747,9189258398038276014,5514330367120214215,7312333272043513032,7607659533221106701,734863121346938828,431243154008379624,3379919554842971946,7782945018870765321,5906699133482318063,4145272259058405029,7548591480460524846,2732667892711270795,2766333939484535180,5673605844344849161,32616088397020746,1589393902428745259,5254923154543353134,958302817212925818,732720724330394525,2370615682229079678,9067181423516643026,3390545651931976426,5876404949611911179,4900922565788788944,2669332844165934551,3150000638359980640,4143609918589993651,3246334180503630519,4408122153597115141,2443906772672231945,8250490918630488402,2299827756839074786,5954359198991893664,5836891988329218083,1632169384377201626,7576413168622278314,9154308382949491137,1681486643478227840,3114836172311362106,1683068534259561850,4843197093796402981,4363824191762738130,942716927840425557,2484762178975675702,2651348311848450548,4861487096694968432,2880361839874324318,9206701431181640198,5200213749396829171,7829693152176357921,7941300228999757604,7019601756623020436,4106027846539712000,6542766482103760141,3045626228808135090,1702543127057527400,8832830748685771629,2563566568783559186,2389554498514424023,1478305200643758388,4498527134904401013,9083050271648449829,3779329354078325476,4884063327251168174,5402286745718405403,2678192071607413952,8215468274965509365,7951570801836465233,7822467412541138271,5497148552208508222,2796100570698202178,8102052770275999958,2722104789836837696,6808473310370190455,5700275578159651734,1804242843964654163,626584805158492612,8421113665842954328,3726161497179475587,2343259414409995456,209662895484152490,6620224440946668495,1927808032022049002,3429446116516351257,2090568216891954193,3972711566872978184,6979832152806910940,4049431811265253467,5247031310566040609,8338557849676917938,4274385541428589428,815187009935745253,4989716406453529109,5112437857299383892,4107369930108890270,7552951858803789921,3360870196679648085,6934700263157465183,8093719144687894557,3254435409235010302 - \"\""
  },
  {
    "time": "2024-03-06T14:34:58.761Z",
    "level": "DEBUG",
    "message": "[info] [OnyxUpdateManager] Applying update type: https with lastUpdateID: 0 - {\"command\":\"GetOlderActions\"}"
  },
  {
    "time": "2024-03-06T14:34:58.759Z",
    "level": "DEBUG",
    "message": "[info] Finished API request - {\"command\":\"GetOlderActions\",\"jsonCode\":200,\"requestID\":\"860311d219da7318-LHR\"}"
```

**Comment by roryabraham** [comment]
We treated this as a fire and handled it in #fireroom-2024-03-06-public-rooms-spamming-getolderactions. It's fixed now 🙂

**Comment by aldo-expensify** [comment]
@roryabraham for me it still flickers forever, but spamming OpenReport. I can still reproduce [this](https://github.com/Expensify/App/issues/37661#issuecomment-1979952531) after logging out and in.

**Comment by roryabraham** [comment]
@cead22 was also reporting that, we thought it was a separate issue

**Comment by aldo-expensify** [comment]
> we thought it was a separate issue

it may be a completely different issue/cause
