### ISSUE TITLE
Split - Split button is smaller than the split button on production

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38351]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to FAB > Request money > Manual.
3. Enter amount > Next.

## Expected Result:
The split button will not be smaller than the button on production.

## Actual Result:
The split button is smaller than the button on production. On Android and iOS app, when the font size is minimum, the button is even smaller.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c8a5904c-26c3-4ccb-b483-b38fda41b387

![image](https://github.com/Expensify/App/assets/93399543/3a6c3c88-9e17-4798-8d24-81fd789507f7)

![image](https://github.com/Expensify/App/assets/93399543/514f6cf1-3639-4df2-8b80-e74f2e7fd700)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to  #wave-collect - Release 1
CC @trjExpensify

**Comment by luacmartins** [comment]
This was already fixed by this CP https://github.com/Expensify/App/pull/38275. Confirmed that's solved in staging on the latest build. Closing.

**Comment by kbecciv** [comment]
@luacmartins The issue is still reproducible on version 1.4.52-3. I'm attempting to identify which build has resolved the issue in CP.

**Comment by luacmartins** [comment]
Oh I see that they are 4px smaller on staging. 

Staging 
![Screenshot 2024-03-14 at 1 54 26 PM](https://github.com/Expensify/App/assets/22219519/65277b8f-4261-4c8a-bb3a-357caa719e0b)

Production
![Screenshot 2024-03-14 at 1 54 39 PM](https://github.com/Expensify/App/assets/22219519/e4600649-bac5-4f1a-8045-d39f5d6874d6)

@Expensify/design can you confirm the correct size for these?

Either way, I don't think this is a blocker.

**Comment by dannymcclain** [comment]
The left/right padding should be `12px`, so the Staging one is the right size (first screenshot in your comment).

![CleanShot 2024-03-14 at 15 17 14@2x](https://github.com/Expensify/App/assets/7516624/8a2e50c5-1fda-4762-922e-cada71380542)

**Comment by luacmartins** [comment]
Awesome, thank you so much for confirming! Seems like we're good to close here.
