### ISSUE TITLE
[HOLD for payment 2024-06-06] [Awaiting NewDot Request] [$250] [Simplified Collect][Tags] - Error when deleting dependent tags and unable to dismiss the error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38683]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is admin of Collect workspace
- The Collect workspace has multilevel dependent tags
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces > Collect workspace
3. Go to Tags
4. Click on the first level tag (California)
5. Click 3-dot menu > Delete tag
6. Delete the tag

## Expected Result:
User will be able to delete the tag

## Actual Result:
Error shows up when deleting the first level tag. The error cannot be dimissed by clicking X

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/96dbe80c-40ba-4ff7-b154-948a1926605e

[Bug6420680_1710950420154!Dependent_-_Multi_Level_tags_NEW.csv](https://github.com/Expensify/App/files/14669853/Bug6420680_1710950420154.Dependent_-_Multi_Level_tags_NEW.csv)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017bf91552e94657a4</li>
        <li>Upwork Job ID: 1784921028579934208</li>
        <li>Last Price Increase: 2024-04-29</li>
<li>Automatic offers: </li>
<ul>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by lanitochka17** [comment]
@deetergp  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by deetergp** [comment]
I can't reproduce this locally 🤔 Collect policies are beta / not available to the public, so I don't think this is a blocker.

**Comment by deetergp** [comment]
Also not able to reproduce on staging (web)

**Comment by deetergp** [comment]
This PR is the culprit https://github.com/Expensify/App/pull/38453

**Comment by luacmartins** [comment]
cc @allroundexperts

**Comment by deetergp** [comment]
Not overdue. This PR should take care of it https://github.com/Expensify/App/pull/38759

**Comment by deetergp** [comment]
Still waiting on that PR.

**Comment by deetergp** [comment]
The PR was merged 2 hours ago. I'll ask for a retest once it's out on staging.

**Comment by luacmartins** [comment]
@lanitochka17 could you please retest this issue? We think this might have been fixed.

**Comment by lanitochka17** [comment]
@luacmartins Issue is still reproducible 

https://github.com/Expensify/App/assets/78819774/80b0e066-7fb0-49fe-9bc0-50806a628e95

**Comment by pecanoro** [comment]
@luacmartins @deetergp  This is the error that is being triggered: https://github.com/Expensify/Expensify/issues/391149

**Comment by luacmartins** [comment]
We don't support multi level tags in NewDot, so we shouldn't be calling `removeTags` on multiple tag lists

**Comment by deetergp** [comment]
Should we even be displaying multi-level tags in NewDot if they are not supported?

**Comment by deetergp** [comment]
Should we even be presenting users with the option to delete them then?

**Comment by luacmartins** [comment]
No, we shouldn't. We should just hide that option if we're viewing multi level tags

**Comment by deetergp** [comment]
So then this sounds like it can be external after all 🎉

**Comment by pecanoro** [comment]
@allroundexperts Friendly bump to review proposals since I am still seeing this on the back-end 😄

**Comment by allroundexperts** [comment]
Given we just want to hide the option for multi level tags, the [proposal](https://github.com/Expensify/App/issues/38683#issuecomment-2083477820) from @gijoe0295 looks good enough to me.

C+ reviewed 🎀 👀 🎀

**Comment by deetergp** [comment]
Missed @allroundexperts's seal of approval ❤️  Will review in the AM.

**Comment by deetergp** [comment]
@gijoe0295's proposal looks good to me as well 🚀

**Comment by deetergp** [comment]
Looks like we have a PR in review for this and it's ready for another look by @allroundexperts 🎉

**Comment by garrettmknight** [comment]
Payment Summary:

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @gijoe0295 $250 paid in Upwork
- Reviewer: @allroundexperts $250

**Comment by garrettmknight** [comment]
@allroundexperts can you complete the checklist when you get a chance and request payment?

**Comment by allroundexperts** [comment]
## Checklist

1. https://github.com/Expensify/App/pull/38453
2. This was a deploy blocker and is clearly mentioned in the PR that caused it.
3. N/A
4. The steps given in OP look simple enough to me.

**Comment by garrettmknight** [comment]
Already added payment summary - just need @allroundexperts to request payment in ND.

**Comment by garrettmknight** [comment]
Just waiting on ND payment.

**Comment by deetergp** [comment]
Still waiting on ND payments?

**Comment by garrettmknight** [comment]
Yep!

**Comment by luacmartins** [comment]
Bump @allroundexperts for payment request! 🤑

**Comment by allroundexperts** [comment]
Hi @luacmartins!

I have this noted down. Please feel free to close.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
