### ISSUE TITLE
[HOLD for payment 2024-04-15] [HOLD for payment 2024-04-09] Scan - Camera is seen as black screen and error occurs after tap capture icon

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39285]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/37817
## Action Performed:
Prerequisite: Reset permission of the app
1. Go to FAB > Request Money > Scan
2. Verify that the camera request permission prompt doesn't appear
3. Click on the Continue button or capture icon
4. Verify that the camera request permission prompt appears
5. Accept the permission
6. Tap "Manual" tab
7. Close the app
8. Open the app
9. Go to FAB > Request Money
10. Tap Scan tab and verify the screen is black
11. Tap Capture icon

## Expected Result:
Camera is seen correctly and user can capture photos

## Actual Result:
Camera is seen as black screen and error occurs after tap Capture icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d9b69057-374d-46ef-954e-2c07b6af7c53

https://github.com/Expensify/App/assets/78819774/9ad5aa23-bf9b-40d4-8a57-98ff36845027

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by deetergp** [comment]
I suspect this PR is what introduced the regression https://github.com/Expensify/App/pull/37483

**Comment by mountiny** [comment]
@deetergp can you create a revert PR? This seems like something we cannot CP fix for

**Comment by deetergp** [comment]
@mountiny Revert PR is [here](https://github.com/Expensify/App/pull/39367). I think we might need someone with a physical android device to test it to see if it resolves this and @johnmlee101's blocker.

**Comment by Monicahinga** [comment]
I have seen the black screen. I can help with the testing once the revert PR is done.
I have a physical Android device to check them.

**Comment by Monicahinga** [comment]
Contributor details
Your Expensify account email: onicahinga25@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011654b49fbd60bd8f

**Comment by marcaaron** [comment]
Asked for a re-test [here](https://expensify.slack.com/archives/C9YU7BX5M/p1712006866085039)

**Comment by kavimuru** [comment]
Issue is fixed. 

https://github.com/Expensify/App/assets/43996225/7f02bc48-3074-4c3c-86f1-361d2bb8349f

**Comment by deetergp** [comment]
Looks like we're good. Closing!

**Comment by Monicahinga** [comment]
I can still see the black screen error on my end. Have tried to uninstall and install back the app and the black screen error still exists.

**Comment by mountiny** [comment]
Reopening so we can verify this is really fixed

**Comment by mrousavy** [comment]
Hey! any chance you could grab the `adb logcat` logs for me? I need to investigate why the Camera is not starting.

I need the part before it tries to open a Camera, until the very end - somewhere in there there must be an error.

**Comment by mountiny** [comment]
@mrousavy based on QA this was repro in `Realme GT2 PRO` device

**Comment by mrousavy** [comment]
maybe the GPU preview view is faulty? I'll try to reproduce

**Comment by chrispader** [comment]
This issue got fixed in https://github.com/Expensify/App/pull/39854

**Comment by Julesssss** [comment]
Fix merged, handling C_ payment in the original issue: https://github.com/Expensify/App/issues/38796
