### ISSUE TITLE
[$250] Distance - Expense report turns blank when distance is requested offline and returning online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39461]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** exploratory around https://expensify.testrail.io/index.php?/tests/view/4470385
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat with no unsettled request.
3. Create a distance request.
4. Go to one transaction report view.
5. Go offline.
6. Create another request.
7. Go to expense report.
8. Go online.

## Expected Result:
The expense report will not turn blank after the request is generated online.

## Actual Result:
The expense report turns blank after the request is generated online.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f5b3e9cb-3594-41fe-a8d2-e8dc793dcc57

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01931d3dd62fc4be98</li>
        <li>Upwork Job ID: 1775660164545712128</li>
        <li>Last Price Increase: 2024-04-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by NikkiWines** [comment]
this behaviour looks fine to me? @kbecciv can you expand on what `expense report turns blank` means in this context?

**Comment by NikkiWines** [comment]
Weird, this seems to occur regardless of how many expenses are on the report so I don't think it's tied to the recent one-transaction view changes 🤔 

And I can reproduce this error simply by refreshing the page 

https://github.com/Expensify/App/assets/16747822/8fbbb8f1-8ca4-40d7-9bf4-8bf4f8c8d3f4

**Comment by NikkiWines** [comment]
I'm unable to reproduce this on dev - going to see if there's any sort of reconnect request that could be causing issues 🤔

**Comment by NikkiWines** [comment]
OK, yeah I can reproduce this on staging only with the following steps: 

1. Create an money request on a workspace chat
2. Create a second money request on a workspace chat
3. Navigate to to expense report 
4. Go offline
5. Go back online 
6. Wait a few seconds and see the report page lose all content 

Not sure why this is failing on staging specifically but will continue to investigate tomorrow

**Comment by jasperhuangg** [comment]
This isn't happening for me on staging. @NikkiWines can you verify if I'm following the reproduction steps correctly?


https://github.com/Expensify/App/assets/31285285/7850c672-46f7-4865-a550-5bcd27ab4a27

**Comment by NikkiWines** [comment]
Hmm, yeah definitely still reproducible for me 😞 

https://github.com/Expensify/App/assets/16747822/f1dfa1e3-5589-4e61-a893-a0faafef74b3

**Comment by jasperhuangg** [comment]
Looping in external contributors to help out

**Comment by jasperhuangg** [comment]
After some additional investigation with @NikkiWines and @roryabraham we were able to find that the report actions view is empty because the `previousReportActionIDs` returned from the back-end are malformed.

This points to the issue being a back-end bug and not something that we should block the NewDot deploy on.

**Comment by jliexpensify** [comment]
@jasperhuangg hello, should this be an `Internal` issue then?

**Comment by jasperhuangg** [comment]
@jliexpensify ah yup, thanks for checking in on that, updated the issue

**Comment by luacmartins** [comment]
Looking at this now

**Comment by luacmartins** [comment]
Ok, managed to reproduce in staging and dev. It seems to only happens when we do a full reconnect, so to reproduce in dev we can comment out [this code](https://github.com/Expensify/Web-Expensify/blob/2272cc89e8bc30ae364828579457f795b37f414a/lib/AppInit.php#L397-L437)

**Comment by luacmartins** [comment]
I see that we're setting the previousReportActionID to 0
![2](https://github.com/Expensify/App/assets/22219519/3fb33607-17e3-48b0-9534-d4a3cc29edea)

**Comment by luacmartins** [comment]
Hmm `$report['parentReportAction']` doesn't have the `previousReportActionID` set [here](https://github.com/Expensify/Web-Expensify/blob/2272cc89e8bc30ae364828579457f795b37f414a/lib/ReportAPI.php#L6775)

**Comment by luacmartins** [comment]
`jsonResponse["reportList"]` comes from getChats and we're getting the parentAction [here](https://github.com/Expensify/Auth/blob/87d16b1d3485986ab41f1e246d5728aaca94d549/auth/lib/Report.cpp#L6198)

**Comment by luacmartins** [comment]
Hmm I can't find any methods to retrieve the `previousParentReportActionID` for a single action. Do we have one @roryabraham? Or do we need to use `Report::getActionList` to get the whole list and then filter out by that single action?

**Comment by luacmartins** [comment]
Oh nvm it looks like we have an overload of `getActionList` that takes in the reportActionID

**Comment by roryabraham** [comment]
This should be fixed now. requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1713202683220999

**Comment by kavimuru** [comment]
Still reproduced in mweb

https://github.com/Expensify/App/assets/43996225/e20474f6-bf09-45ce-9a71-b7b977f37a47

**Comment by jliexpensify** [comment]
@NikkiWines since this is a `Polish` issue, should we change the priority?

**Comment by NikkiWines** [comment]
I'm unable to reproduce on staging or prod for mweb or web - let's close this out and if this resurfaces we can reopen or handle it in a fresh issue. 

<details closed>
<summary>Videos</summary>
<br>

Web - Prod

https://github.com/Expensify/App/assets/16747822/dba5f396-71c9-4d1f-91e4-61ad12423af6

Web - Staging 

https://github.com/Expensify/App/assets/16747822/a47dd383-b3af-4a31-8f90-83a91f78bb57

mWeb - Staging

https://github.com/Expensify/App/assets/16747822/504f6bb9-1715-42ab-afe7-c3896b05f38b

</details>
