### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] OD redirection - Concierge chat flickers non-stop after redirecting from Old Dot to New Dot

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39831]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log out of New Dot if logged in
2. Log in to Old Dot
3. Click on the Concierge icon on the bottom right

## Expected Result:
After redirecting to New Dot, Concierge chat will not flicker

## Actual Result:
After redirecting to New Dot, Concierge chat flickers non-stop

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8438bdc9-7e9a-4d11-a737-29c3a8bee7a1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd4a71bbd34dbd5f</li>
        <li>Upwork Job ID: 1777373249826816000</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to  #wave-collect - Release 1

**Comment by lanitochka17** [comment]
@youssef-lr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment]
I hate this bug, this keeps popping up. I am worried the rootcause might lay in the onyx bump #38114 but I wish I would be wrong

**Comment by c3024** [comment]
@lanitochka17 the video attached is not for this issue. Could you upload the correct video?

**Comment by lanitochka17** [comment]
@c3024 sorry for confusion

https://github.com/Expensify/App/assets/78819774/631599b7-17b6-4426-8b1f-fac92c9e1254

**Comment by c3024** [comment]
Can someone help me with how to redirect to New Dot Dev when pressing on the Chat icon in staging/prod old dot?

**Comment by c3024** [comment]
That makes sense and works but how did this work in the earlier version of Onyx? 🤔

**Comment by mountiny** [comment]
@c3024 @tienifr I believe we want to avoid the onyx bump being reverted as there has been lots of backlog.

Could you confirm if the solution proposed from @tienifr would not have consequences in some other parts of the app?

**Comment by c3024** [comment]
@mountiny 

I don't see any consequences in other parts of the app with that solution.

Moreover, we are just splitting into a new hook with moving the block with `isAccountLoading` into it so it does not appear to bring any undesired behaviour.

**Comment by mallenexpensify** [comment]
Added `Bug` to get a BZ assigned

**Comment by mountiny** [comment]
@tienifr can you please raise the PR and make sure to test thoroughly any potential areas of regressions? Thank you!

**Comment by kavimuru** [comment]
Issue fixed in web, 1.4.61-1 version.

https://github.com/Expensify/App/assets/43996225/0bb1439f-1142-409d-8454-9d7763cd0c63

**Comment by mountiny** [comment]
@kavimuru thank you for testing

Removing the blocker label 

This is still hapening for native platforms and desktop cc @c3024 @tienifr so looking for further solutions

Given that, this solution should not be rewarded the full price, but only $250 as it did not fix the bug fully

**Comment by mountiny** [comment]
Good to retest, the mobile platforms are still not working though, right?

**Comment by mountiny** [comment]
@tienifr I think my comment stemmed from your discussion with @c3024 in the PR. Can you test the deeplink to concierge chat in native is working as expected?

**Comment by c3024** [comment]
Yes, there wasn't a continuous reloading (flickering) on native apps on `main` which is the bug here. But it was showing a different `Your session has expired` screen when tried to visit the Concierge chat with deeplink on native apps.

**Comment by mountiny** [comment]
sounds good then, I can ask QA to verify these redirections

@kavimuru could you please retest the concierge chat deeplinks/ redirections you got in Testrail and related to this issue so we can close this out

**Comment by mountiny** [comment]
I think we are good to pay this one out

**Comment by CortneyOfstad** [comment]
Payment set for tomorrow! @c3024 can you complete the checklist by EOD, so there is no delay in issuing payment? Thanks!

**Comment by c3024** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
 
* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #36750 
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/36750/files#r1578185695
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion has been started because this could not have been identified earlier easily.
* [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Log out of New Dot if logged in
2. Log on to Old Dot
3. Click on the Concierge icon on the bottom right. It redirects to New Dot
4. After redirecting to New Dot, verify that Concierge chat does not flicker continuously

👍 or 👎

**Comment by CortneyOfstad** [comment]
## Payment Summary

@tienifr — paid $500 via Upwork
@c3024 — paid $500 via Upwork

**Comment by CortneyOfstad** [comment]
Regression test here — https://github.com/Expensify/Expensify/issues/390864

Closing — thanks all!
