### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] Tapping outside quickly after clear status leads the user going back to the report screen

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39848]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712306439703269

## Action Performed:
1. Go to Settings > Profile > Status
2. Change the status and save
3. Tapping status again
4. Click on clear status
5. Tapping outside quickly and notice

## Expected Result: 
The user should keep the side on the profile page
## Actual Result:
 The user goes back to report screen

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/092ed5d7-c2ea-471a-a78c-e2809cb3de42

https://github.com/Expensify/App/assets/38435837/68e393d4-e99c-47d1-97db-7d3c5df2da5f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d6d259b4d3f1b08</li>
        <li>Upwork Job ID: 1777489376165974016</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>GandalfGwaihir | Contributor | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tapping outside quickly after clear status leads the user going back to the report screen

### What is the root cause of that problem?
B/c we are navigating back here after interaction
https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L109-L110
### What changes do you think we should make in order to solve the problem?

We need to check if it is in the status page by checking the url
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tapping outside quickly after clear status leads the user going back to the report screen

### What is the root cause of that problem?
B/c we are navigating back here after interaction 
https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L109-L110
when we quickly dismiss modal then it will run goBack on that route opening the report screen instead of the intended dismissing of the status modal
### What changes do you think we should make in order to solve the problem?

 we should use `dismissModal` instead of `goBack`
```
            Navigation.dismissModal();

```


### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tapping outside quickly after clear status leads the user going back to the report screen

### What is the root cause of that problem?
B/c we are navigating back here after interaction 
https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L109-L110
when we quickly dismiss modal then it will run goBack on that route opening the report screen instead of the intended dismissing of the status modal
### What changes do you think we should make in order to solve the problem?

 we should use `dismissModal` instead of `goBack`
```
            Navigation.dismissModal();

```


### What alternative solutions did you explore? (Optional)
We can also remove the `runAfterInteraction` and make the navigation happen immediately

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tapping outside quickly after clear status leads the user going back to the report screen

### What is the root cause of that problem?
B/c we are navigating back here after interaction 
https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L109-L110
when we quickly dismiss modal then it will run goBack on that route opening the report screen instead of the intended dismissing of the status modal
### What changes do you think we should make in order to solve the problem?

 we should use `dismissModal` instead of `goBack`
```
            Navigation.dismissModal();

```

Also apply same change here
https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L94-L95
### What alternative solutions did you explore? (Optional)
We can also remove the `runAfterInteraction` and make the navigation happen immediately

**Comment by jliexpensify** [comment]
Interesting, I can repro but it doesn't take me to a Report - instead I get taken to my `Profile` screen. Also on v1.4.61-0

**Comment by jliexpensify** [comment]
I also think this shoudl go in #vip-vsb as it deals with `Chat Functionality`

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user goes back to report screen

### What is the root cause of that problem?
When we save or clear status, we call `goBack` function after interaction here. So if we tapping outside quickly before this function is called, we will go back to previous screen which is report screen in this case.


https://github.com/Expensify/App/blob/76c7fa923bb85969d709352e65d955b223a57ada/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L109-L111
### What changes do you think we should make in order to solve the problem?


We should cancel the interaction task if it's not called before the `StatusPage` is unmounted.

1. Create a `navigateBackToPreviousScreenTask` ref

```
const navigateBackToPreviousScreenTask = useRef<{
    then: (onfulfilled?: () => any, onrejected?: () => any) => Promise<any>;
    done: (...args: any[]) => any;
    cancel: () => void;
} | null>(null);
```

2. Assign this ref to the interaction task 

```
navigateBackToPreviousScreenTask.current = InteractionManager.runAfterInteractions(() => {
    navigateBackToPreviousScreen();
});
```
https://github.com/Expensify/App/blob/76c7fa923bb85969d709352e65d955b223a57ada/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L109

https://github.com/Expensify/App/blob/76c7fa923bb85969d709352e65d955b223a57ada/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L93

3. Cancel the task if the component is unmounted

```
useEffect(() => {
    return () => {
        if (!navigateBackToPreviousScreenTask.current) {
            return;
        }

        navigateBackToPreviousScreenTask.current.cancel();
    }
}, [])
```
### What alternative solutions did you explore? (Optional)
NA

**Comment by jliexpensify** [comment]
Hi @dukenv0307 - for fairness sake, I think it would be good to keep this with the auto-assigner. We currently don't have a documented process for what happens if a C+ reports a bug and wishes to be assigned - if you feel that the C+ who reports a bug should be the one assigned, you can present a Problem/Solution statement in #contributor-plus for review by our team and we can add it to our documentation, if we agree.

Also bumping @thesahindia for reviews!

**Comment by jliexpensify** [comment]
Bumped @thesahindia on Slack, please review. If you're not able to take this on, I'll re-assign the issue.

**Comment by nkdengineer** [comment]
@thesahindia The proposal from @GandalfGwaihir will not correct in this case we clear the status and open quickly any modal by shortcut keyboard like `Search page` or `Short cut modal` like this video (I applied the selected solution in this video). We should cancel the interaction task when the component is unmounted that will make sure we will do nothing if the component is unmounted before the interaction task is executed.

cc @youssef-lr 

https://github.com/Expensify/App/assets/161821005/a4792877-4ad5-4667-8a35-f5509a658e38

**Comment by youssef-lr** [comment]
Honestly, I'm not sure this is bug is worth fixing right now, how likely is this to be an issue for real world users? cc @jliexpensify

**Comment by youssef-lr** [comment]
@GandalfGwaihir let's hold off on working on this until we're sure we want to fix this.

**Comment by nkdengineer** [comment]
@youssef-lr  Since the solution to fix all possible cases is very simple, I think we can fix all of this to not face other bugs like this in the further.

**Comment by jliexpensify** [comment]
Hi @GandalfGwaihir - sorry for not sharing an update: I reached out to @youssef-lr via DM but haven't heard back yet. Basically, I'm fine to close this but before doing so, I was asking Youssef if we should fix this as per [this comment](https://github.com/Expensify/App/issues/39848#issuecomment-2052049169).

**Comment by youssef-lr** [comment]
Alright given it's simple, I agree let's just fix it!

**Comment by nkdengineer** [comment]
> Alright given it's simple, I agree let's just fix it!

@youssef-lr If we agree that we also this fix, should we re-assign here since my proposal also cover this case meanwhile the selected proposal doesn't fix this.

**Comment by youssef-lr** [comment]
@GandalfGwaihir what do you think? Do you mind letting this one to @nkdengineer as it fully fixes the issue? You'll still be eligible for 50% of the payment.

**Comment by youssef-lr** [comment]
>but still if you insist to go with their proposal I am okay with 50% compensation , final decision is yours :) thanks

Let's go with 50/50, thanks everyone for your understanding!

**Comment by jliexpensify** [comment]
Hello, so is this correct, then?

- C: @nkdengineer $125
- C: @GandalfGwaihir $125
- C+: @thesahindia $250 (New.Dot Payment)

[EDITED UPWORKS JOB](https://www.upwork.com/jobs/~014d6d259b4d3f1b08)

**Comment by nkdengineer** [comment]
@youssef-lr Since the PR is opened, I think we can apply my solution in this PR. WDYT? And can you assign me here for payment?

**Comment by youssef-lr** [comment]
Sounds good @nkdengineer. Let's apply the change in the existing PR.

**Comment by jliexpensify** [comment]
New summary, is this correct?

- C: @allgandalf $125
- C: @nkdengineer $125
- C+: @thesahindia $250 (ND request)
- C+: @dukenv0307 $250

[Upwork job](https://www.upwork.com/jobs/~014d6d259b4d3f1b08)

**Comment by jliexpensify** [comment]
Aha sorry - I was going off [this](https://github.com/Expensify/App/issues/39848#issuecomment-2147599200)

Hmm, I don't think we pay out bug reporting anymore but let me double-check.

**Comment by youssef-lr** [comment]
Not overdue

**Comment by jliexpensify** [comment]
Ah sorry, I missed this one yesterday. Paying today!

@thesahindia and @allgandalf - is there a checklist that needs to be done?

**Comment by jliexpensify** [comment]
Whoops sorry, ignore me - [no checklist needed](https://github.com/Expensify/App/issues/39848#issuecomment-2149451518).

**Comment by jliexpensify** [comment]
Damn, job is expired. @allgandalf and @nkdengineer - can you accept the offers [here](https://www.upwork.com/jobs/~014d20846f4697d5d9)?

**Comment by jliexpensify** [comment]
Cheers, just waiting on @nkdengineer

**Comment by nkdengineer** [comment]
Sorry @jliexpensify I don't have any Upwork Connects left so could not apply to [the job](https://www.upwork.com/jobs/~014d20846f4697d5d9). Would you mind sending the offer directly to my [Upwork profile](https://www.upwork.com/freelancers/~0134d0b74faef1a5ac)?

TIA!

**Comment by jliexpensify** [comment]
@nkdengineer I sent you an offer yesterday, can you see / accept this?

![image](https://github.com/Expensify/App/assets/30815269/3ed46778-d180-4c45-bd3d-742a90d23901)

**Comment by nkdengineer** [comment]
@jliexpensify Yes I accepted, thanks

**Comment by jliexpensify** [comment]
Everyone is paid, and the job is closed! @thesahindia and JMills, [please refer to this summary for ND payments](https://github.com/Expensify/App/issues/39848#issuecomment-2148614012).

**Comment by JmillsExpensify** [comment]
$250 approved for @thesahindia
