### ISSUE TITLE
Offline indicator appears for quick moment on home page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40133]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.62-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712757382154049

## Action Performed:
Go to new.expensify.com/ Go to staging.new.expensify.com

## Expected Result:
There should be no quick flash of the offline indicator
## Actual Result:
The offline indicator shows and disappears after a brief moment
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-04-10 at 15 55 14](https://github.com/Expensify/App/assets/38435837/8e95607b-0272-47e4-a283-069c6635b123)

https://github.com/Expensify/App/assets/38435837/a7ce2d7a-1818-4e3f-8ca3-30327ecbf83b

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
@tienifr can you confirm that your PR [here](https://github.com/Expensify/App/pull/39595) will fix this issue?

**Comment by shawnborton** [comment]
It can fix this, or it will fix it? If it already fixes the issue mentioned here, I can just go ahead and close this out.

**Comment by shawnborton** [comment]
Keeping this open until @tienifr's PR is merged, as this one is still happening.

**Comment by slafortune** [comment]
PR not yet merged

**Comment by slafortune** [comment]
PR merged and issue is fixed - no able to recreate 👍

**Comment by shawnborton** [comment]
I'm still seeing this on our latest staging. Can we look into this one again?

**Comment by shawnborton** [comment]
Actually ignore me, I can't reproduce
