### ISSUE TITLE
[ON HOLD for #40171] Share code is missing in settings page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40212]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713018323142529

## Action Performed:
1. Open app
2. Tap the avatar at the bottom
3. Tap settings at the top left 
4. Look for the share code
## Expected Result:
Share code should appear
## Actual Result:
Share QR code is missing
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/Expensify/App/assets/38435837/ab58e12d-a994-4385-a14e-043fb9c59ee5" width="40%" height="40%">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment]
Fixed in latest main by this PR https://github.com/Expensify/App/pull/40171

**Comment by shawnborton** [comment]
Nice, I think we can probably close this one then.

**Comment by m-natarajan** [comment]
@CortneyOfstad bug is still able to reproduce.

@johnmlee101 also able to reproduce https://expensify.slack.com/archives/C049HHMV9SM/p1713213237251439

<img src="https://github.com/Expensify/App/assets/38435837/46fe9368-b9fb-4b0f-b9f9-e60f1337c47a" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/38435837/cd762b47-a74f-4edf-b8c4-eacd1e95f669" width="40%" height="40%">

**Comment by CortneyOfstad** [comment]
Sounds good @m-natarajan — will put this on-hold for PR https://github.com/Expensify/App/pull/40171

**Comment by CortneyOfstad** [comment]
PR was deployed to staging 10 hours ago 🎉

**Comment by CortneyOfstad** [comment]
Still on staging

**Comment by CortneyOfstad** [comment]
Deployed to production 10 minutes ago! Will keep an eye on this for the next 7 days to see if there are any reverts and will close once confirmed this is fixed 👍

**Comment by CortneyOfstad** [comment]
Not overdue! Have to wait for the PR to reach 7 days before this can be closed

**Comment by CortneyOfstad** [comment]
PR has hit 7 days, so this can be closed!
