### ISSUE TITLE
[$250] [Guided Setup Stage 3] [CVP] Selecting Pay button from email as a new user, taking to the IOU report rather than the preview in the DM

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42321]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715814647719679

## Action Performed:
1. Log in as user A in public domain
2. Click FAB and select "Submit Expense"
3. Enter amount and enter any email address with which no expensify account exists (user has access to the email inbox)
4.  Look for the email from user A
5.  Click "Pay" from the new user email

## Expected Result:

That user is then taken to the chat report
![image](https://github.com/Expensify/App/assets/51066321/1b03f86a-4681-4d4b-91e4-ea9069672fb8)

## Actual Result:
User is taken to the DM deeplinked to the IOU preview

<img width="2884" alt="image" src="https://github.com/Expensify/App/assets/51066321/5ff76486-126f-461d-a4e2-4678b14bf92d">

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a9780ce3-bc73-4d4b-89c2-29d20bfad382

https://github.com/Expensify/App/assets/38435837/367088d7-3ae1-46a7-938b-f7a715e4e013

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012fae825a3d74577c</li>
        <li>Upwork Job ID: 1792806639199625216</li>
        <li>Last Price Increase: 2024-05-21</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
Hum... I'm not getting the IOU email for some reason - nor is the IOU loading in the User B account- I think there might be delays

**Comment by Christinadobrzyn** [comment]
Asking for some guidance on how to create the IOU - https://expensify.slack.com/archives/C049HHMV9SM/p1716187149930759?thread_ts=1715814647.719679&cid=C049HHMV9SM

I'm not getting these emails

**Comment by Christinadobrzyn** [comment]
OP is updated and this is reproducible - I think this can be external?

**Comment by b4s36t4** [comment]
I'm not sure weather this can be external as email templates are sent via backend. The link attached to `Pay` button is linked to IOU report we need to update the email template to link the DM report.

**Comment by Christinadobrzyn** [comment]
ah good catch @b4s36t4 - thank you for reviewing that. Going to make this internal

**Comment by Christinadobrzyn** [comment]
original discussion [here](https://expensify.slack.com/archives/C03TBKRSB/p1715816142095909?thread_ts=1715620897.464219&cid=C03TBKRSB)

**Comment by Christinadobrzyn** [comment]
asking tom if he can buddy check my thinking on the release timeframe - https://expensify.slack.com/archives/C036QM0SLJK/p1716884563004939

**Comment by Christinadobrzyn** [comment]
still looking for someone to pick this up.

**Comment by Christinadobrzyn** [comment]
Internal issue so I'm working on finding someone to pick this up

**Comment by Christinadobrzyn** [comment]
still trying to find someone to grab this

**Comment by Christinadobrzyn** [comment]
Actually, reading over the issue again, I don't think this relates to email templates as I originally thought. This flow pertains to where the user is taken within the app. I wonder if this can be external. 

@hoangzinh can you lend your thoughts?

**Comment by Christinadobrzyn** [comment]
Oh thank you for the feedback @hoangzinh - That is a good point. @danielrvidal would you be able to provide your thoughts on https://github.com/Expensify/App/issues/42321#issuecomment-2152080085. I think that is a good point to keep the process as is.

**Comment by danielrvidal** [comment]
I think I disagree... this is a brand new user. They are going to be very confused by going into the IOU, as that doesn't really look like anything. If you go to the DM or chat UI, you at least have some context of what you are looking at. 

I could see an argument for existing users, but even then I think taking them to the DM/chat UI is better so they have context and click pay, or choose to go into the IOU.

**Comment by Christinadobrzyn** [comment]
Ah thank you for the insight @danielrvidal  - I certainly agree with that from a new user perspective - that is a good point. We should be looking at these as a new user experience. We'll keep this open for a volunteer.

**Comment by Christinadobrzyn** [comment]
asking for a volunteer- https://expensify.slack.com/archives/C036QM0SLJK/p1718062588508659

**Comment by Christinadobrzyn** [comment]
Just a heads up - I'm going to be out until June 24th, so I'm going to assign a teammate to watch this while I'm away. 

@slafortune - this is internal and we're waiting for it to get picked up/trying to find a volunteer. TY!

**Comment by techievivek** [comment]
This needs to be fixed internally, I can take a look into it.

**Comment by trjExpensify** [comment]
How you getting on with this @techievivek? When can we expect a PR?

**Comment by slafortune** [comment]
@techievivek do you have an update to share?

**Comment by techievivek** [comment]
I reviewed the code the other day and found that we have a special `if` case for handling money requests, linking them to the parent report. However, I need to investigate further to understand why it is not behaving as expected. I will have an update to share tomorrow.

**Comment by techievivek** [comment]
Requesting a retest, as I believe this issue is fixed. The issue was created before we made changes to this flow for the Xerocon event.

**Comment by kavimuru** [comment]
Bug is still reproduced. 

https://github.com/Expensify/App/assets/43996225/c5974f0a-51cc-4bb3-b23a-de85bb0b1c6a

**Comment by Christinadobrzyn** [comment]
hi @techievivek just checking on this, do you think you'll have the bandwidth to work on this or do you want me to try and find another internal volunteer?

**Comment by trjExpensify** [comment]
@techievivek coming from [this convo](https://expensify.slack.com/archives/C036QM0SLJK/p1719950007681159?thread_ts=1719930802.520799&cid=C036QM0SLJK), I'm moving this into the Guided Setup: Stage 3 project to track to ensure we get to the bottom of it before the next release.

**Comment by Christinadobrzyn** [comment]
@techievivek can you provide an update for Melvin? TY!

**Comment by techievivek** [comment]
Sent a PR to fix the behaviour of pay button.

**Comment by Christinadobrzyn** [comment]
Awesome! Should we move this to weekly @techievivek while the PR is in review?

**Comment by trjExpensify** [comment]
PR has been deployed, right? I don't think there's payment here for a webPR.

**Comment by trjExpensify** [comment]
Great, we're done here then. @danielrvidal is there a CVP test you want to update for this or is it accounted for?

**Comment by Christinadobrzyn** [comment]
@danielrvidal just checking in on this [question](https://github.com/Expensify/App/issues/42321#issuecomment-2231059973) when you have a moment!

**Comment by Christinadobrzyn** [comment]
I'll DM @danielrvidal to check on any other reason to keep this open.

**Comment by danielrvidal** [comment]
I just tested on mobile/web and it works as expected. I'll update the CVP so it reflects this (I think it already did).

**Comment by Christinadobrzyn** [comment]
Awesome! thank you Daniel! Closing this out.
