### ISSUE TITLE
[HOLD for payment 2024-11-01] [$250] Attachment - Press enter fullscreen mode in video player by Tab, app go to fullscreen

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44379]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** crowdtest.expensify+test002@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app
2. Go to any conversation
3. Click "+" and choose Add Attachment
4. Choose any available video
5. Press the Tab on the video player to fullscreen
6. Press enter

## Expected Result:
Only the video player is fullscreen; the app keeps its original size. Same as what happens when using a cursor: 

- Upload a video to a chat as an attachment
- Click fullscreen
- Notice the video expands to fullscreen
- Press Enter and the video uploads into the chat as expected

## Actual Result:
You will see after clicking the fullscreen button in the video player by pressing enter at the index position. Then the application will be fullscreen instead of video player.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e53f1f7b-7c9f-4ee4-af69-4b7a7b1c76d4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d24e62428813c96d</li>
        <li>Upwork Job ID: 1806399701650517149</li>
        <li>Last Price Increase: 2024-07-04</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103091438</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by Christinadobrzyn** [comment]
Ah that is a good catch, this seems to be affecting all of the platforms. I'm not actually sure if we want to change anything though - asking the team for some guidance. https://expensify.slack.com/archives/C066HJM2CAZ/p1719340979142479

**Comment by Christinadobrzyn** [comment]
no response from the team. I think it's safe to assume we want the behaviour to be the same as when using a cursor: 

- Upload a video to a chat as an attachment
- Click fullscreen
- Notice the video expands to fullscreen
- Press Enter and the video uploads as expected

 I think this can be external

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
You will see after clicking the fullscreen button in the video player by pressing enter at the index position. Then the application will be fullscreen instead of video player.

### What is the root cause of that problem?
We use [pressOnEnter](https://github.com/Expensify/App/blob/e78c38e85aab34c815b95d8763f3d01f3a58b42d/src/components/AttachmentModal.tsx#L550) for confirmation button in AttachmentModel.

If the user is [focused on another button](https://github.com/Expensify/App/blob/e78c38e85aab34c815b95d8763f3d01f3a58b42d/src/components/Button/index.tsx#L131) (`accessibilityRoles.includes(activeElementRole ?? '')` conditition), `Enter` will not trigger click on the button with  `pressOnEnter=true`. This is because the intention of the user is to press on that focused button, not the `Confirm` button.

But the video player controls buttons (like fullscreen button) do not have `role` `BUTTON` defined. They use [IconButton](https://github.com/Expensify/App/blob/e78c38e85aab34c815b95d8763f3d01f3a58b42d/src/components/VideoPlayer/VideoPlayerControls/index.tsx#L119) which does not have it.

When the user press Enter, the video will both become full screen (because fullscreen button on player is focused) and being sent (because `pressOnEnter` is `true`) at the same time, so the video will disappear from the screen.

### What changes do you think we should make in order to solve the problem?

We need to add proper `BUTTON` roles for video player controls buttons (like fullscreen button), they uses [IconButton](https://github.com/Expensify/App/blob/e78c38e85aab34c815b95d8763f3d01f3a58b42d/src/components/VideoPlayer/VideoPlayerControls/index.tsx#L119). `IconButton` is a button so we should add the role [here](https://github.com/Expensify/App/blob/e78c38e85aab34c815b95d8763f3d01f3a58b42d/src/components/VideoPlayer/IconButton.tsx#L31)
```
role={CONST.ROLE.BUTTON}
```
This will fix all cases of `IconButton`, or we don't put in `IconButton` component but pass in individually when using `IconButton` instead, like in [here](https://github.com/Expensify/App/blob/e78c38e85aab34c815b95d8763f3d01f3a58b42d/src/components/VideoPlayer/VideoPlayerControls/index.tsx#L119) and in `IconButton` it will use the role passed in.

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
[Proposal updated](https://github.com/Expensify/App/issues/44379#issuecomment-2196669019) to clarify

**Comment by Christinadobrzyn** [comment]
hi @getusha can you check on the proposal - thank you!

**Comment by getusha** [comment]
Thanks for the proposal @nkdengineer
The RCA makes sense and the solution works for this issue, However i see the `More` menu button isn't working as expected on pressing enter after focusing. could you look into that? it'd be great to have that fixed as well since this is a pretty straight-forward issue.

https://github.com/Expensify/App/assets/75031127/28dd4b33-78a5-4887-a377-487edffd236a

**Comment by nkdengineer** [comment]
> this is a pretty straight-forward issue.

@getusha The change might look straight-forward but finding the root cause for it was quite tough. As you can see the issue was External for almost a day without any proposal 😃 

> However i see the More menu button isn't working as expected on pressing enter after focusing.

This has completely different RCA and solution therefore I'd suggest to create a new GH. I've taken a quick look at that and it happens because in [here](https://github.com/Expensify/App/blob/2fa1734d661546522359043759a00402dc47acc2/src/components/VideoPlayer/BaseVideoPlayer.tsx#L111), when the click is triggered by `Enter`, the `pageX` and `pageY` will be 0 and the popover will display at the wrong location. The solution will be to store a ref for the [ThreeDots](https://github.com/Expensify/App/blob/2fa1734d661546522359043759a00402dc47acc2/src/components/VideoPlayer/VideoPlayerControls/index.tsx#L127), and pass that ref along when calling [showPopoverMenu](https://github.com/Expensify/App/blob/2fa1734d661546522359043759a00402dc47acc2/src/components/VideoPlayer/VideoPlayerControls/index.tsx#L129). In there if the `pageX` and `pageY` are both 0, we'll fall back to the location of the threedots (eg. by using [measureInWindow](https://github.com/Expensify/App/blob/2fa1734d661546522359043759a00402dc47acc2/src/components/ButtonWithDropdownMenu/index.tsx#L57) on the ref). Or we can just use the location of the threedots at all times and not rely on the `event` cursor location. 

I'd be happy to post a complete proposal (based on above solution) for that issue once the new GH is created 👍 

Meanwhile we can move forward with this issue.

**Comment by Christinadobrzyn** [comment]
Update for Melvin - we're discussing proposals

**Comment by getusha** [comment]
@Christinadobrzyn Should we handle [this issue](https://github.com/Expensify/App/issues/44379#issuecomment-2204141595) here, or should we handle it separately?

**Comment by Christinadobrzyn** [comment]
So let's report [that bug](https://github.com/Expensify/App/issues/44379#issuecomment-2204141595) in Expensify-Bugs and focus on just working on this one issue. TY!

**Comment by getusha** [comment]
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/44379#issuecomment-2196669019) looks good to me
🎀 👀 🎀  C+ Reviewed

**Comment by nkdengineer** [comment]
> So let's report https://github.com/Expensify/App/issues/44379#issuecomment-2204141595 in Expensify-Bugs and focus on just working on this one issue. TY!

@getusha Are you going to report this bug? If not I can help

I will also post the [proposal](https://github.com/Expensify/App/issues/44379#issuecomment-2206839124) there once the bug is posted

**Comment by getusha** [comment]
>@getusha Are you going to report this bug? If not I can help

@nkdengineer you can't see that issue without having this issue fixed, since the modal closes immediately. that's why i decided to report it after we fix this

**Comment by Christinadobrzyn** [comment]
hi @MonilBhavsar can you take a peek at the [proposal review](https://github.com/Expensify/App/issues/44379#issuecomment-2216861840) and discussions to 👍

**Comment by nkdengineer** [comment]
There's no discussion outstanding, everything is clear. We're good to start the PR once @MonilBhavsar [assigns](https://github.com/Expensify/App/issues/44379#issuecomment-2216861840)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by MonilBhavsar** [comment]
@nkdengineer @getusha any idea how this is fixed?

**Comment by nkdengineer** [comment]
@MonilBhavsar It's still reproducible in both `main` and staging, I tried just now. In the below video, when tabbing to the Full screen button and press Enter, the video player flickers and disappears, it doesn't stay in full screen as expected.

https://github.com/Expensify/App/assets/161821005/76f7577c-2fca-4ddb-ad4f-f16cdb435d0b

**Comment by MonilBhavsar** [comment]
Thanks for checking!

**Comment by Christinadobrzyn** [comment]
Update for Melvin - working on the PR

**Comment by Christinadobrzyn** [comment]
Update for Melvin - working on the PR

**Comment by Christinadobrzyn** [comment]
How's the PR review going @getusha - can you provide an update?

**Comment by Christinadobrzyn** [comment]
Oh awesome! Thank you for the update. We'll monitor - https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

**Comment by Christinadobrzyn** [comment]
Update for Melvin - monitoring - https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

**Comment by Christinadobrzyn** [comment]
monitoring - https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

**Comment by Christinadobrzyn** [comment]
monitoring - https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

**Comment by Christinadobrzyn** [comment]
monitoring - https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

**Comment by Christinadobrzyn** [comment]
monitoring - https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

**Comment by Christinadobrzyn** [comment]
monitoring - https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

**Comment by Christinadobrzyn** [comment]
monitoring - https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

Heads up that I'm going to be ooo until 9/30. Since we're reviewing the PR I'm not going to add another BZ teammate. If you need anyone before Monday please ping in Slack for a volunteer.

**Comment by Christinadobrzyn** [comment]
monitoring - https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

**Comment by Christinadobrzyn** [comment]
monitoring - https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

**Comment by Christinadobrzyn** [comment]
monitoring - https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

**Comment by Christinadobrzyn** [comment]
monitoring - https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

**Comment by Christinadobrzyn** [comment]
monitoring - https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

**Comment by Christinadobrzyn** [comment]
Just checking on this PR - @MonilBhavsar and @getusha how are things going? https://github.com/Expensify/App/pull/45379#issuecomment-2258786734

**Comment by MonilBhavsar** [comment]
We're awaiting a review from @getusha

**Comment by Christinadobrzyn** [comment]
@getusha do we need a regression test for this?

Payouts due:

- [ ] Contributor: $250 @nkdengineer (Upwork offer - https://www.upwork.com/nx/wm/offer/103091438)
- [ ] Reviewer: $250 @getusha (please request payment through NewDot)

**Comment by Christinadobrzyn** [comment]
Thanks @getusha - paid out based on this [payment summary](https://github.com/Expensify/App/issues/44379#issuecomment-2451160038). @getusha please make sure to request payment through NewDot.

**Comment by Christinadobrzyn** [comment]
Closing this since it's just waiting payment to @getusha through NewDot.

**Comment by garrettmknight** [comment]
$250 approved for @getusha
