### ISSUE TITLE
[$250] Distance - Android - Distance not updated after removing waypoint offline and returning online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45005]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause -Internal Team

## Action Performed:
1. Open the app and log in as a member of a workspace
2. Open to the workspace chat
3. Submit a distance expense with 3 waypoints
4. Navigate to the distance expense details conversation
5. Disable internet connection
6. Tap Distance > remove one of the waypoints and save changes
7. Return online

## Expected Result:
After user returns online the map loads and the distance field is updated

## Actual Result:
The map is not loaded and the distance field still displays "Pending"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/53c58c4d-53c2-4307-b448-f431988110dc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b70acd65a32d4043</li>
        <li>Upwork Job ID: 1810557798188010467</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 103246150</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by kadiealexander** [comment]
Android <> iOS bug swap

**Comment by jliexpensify** [comment]
Can repro this.

**Comment by jliexpensify** [comment]
Waiting for proposals

**Comment by jliexpensify** [comment]
Still awaiting proposals

**Comment by jliexpensify** [comment]
Hmm I just tried again and can't repro this anymore on 9.0.10-6. What about you @mkhutornyi?

**Comment by jliexpensify** [comment]
Hmm ok, weird! Anyway have bumped #open-source [here.](https://expensify.slack.com/archives/C01GTK53T8Q/p1721799269660319)

**Comment by hannojg** [comment]
Hi, I Hanno from Margelo, an expert agency and I can work on this issue! 😊

**Comment by jliexpensify** [comment]
All yours @hannojg!

**Comment by hannojg** [comment]
Thanks! Have been carried away but other tasks. But have availability starting next week to actively look into that! Thanks for the patience.

**Comment by hannojg** [comment]
https://github.com/user-attachments/assets/2f7d03be-548a-4343-a4f3-543f200c8b15

Hey, I can't seem to reproduce that issue on latest `main` branch anymore!

**Comment by hannojg** [comment]
Unable to reproduce on 9.0.13-4 (latest prod)


https://github.com/user-attachments/assets/167ba85e-500d-4cbc-91b4-f1cd0450230a

**Comment by hannojg** [comment]
There was a recent Onyx bump in which we fixed the order in which Onyx updates got applied - I suspect that has already fixed this bug!

**Comment by jliexpensify** [comment]
Oh, nice - thanks for the update! Ok, will close this one then.

**Comment by lanitochka17** [comment]
Issue is still reproducible on mWeb/Chrome, mWeb/Safari

https://github.com/user-attachments/assets/ad12625c-ddcd-4713-b825-c4ce308bab64

**Comment by jliexpensify** [comment]
cc @hannojg as it's still reproducible

**Comment by jliexpensify** [comment]
Any thoughts here @hannojg? Thanks!

**Comment by hannojg** [comment]
Taking a look now!

@lanitochka17 It seems that the bug you're reporting now is different from the one described initially, right? 
In your video it seems that the Map for the distance is never loaded. However it seems to me that the "distance" field in the report gets calculated correctly once you go online (which the issue was originally about).

Let me fix the bug with the map not showing up!

**Comment by hannojg** [comment]
Hm, right now I can't reproduce on android/iOS mWeb, neither on staging nor dev

https://github.com/user-attachments/assets/06a4485c-76f4-49e4-abac-46beca0601d1

Will check the code though, maybe I find something suspicious 🤞

**Comment by hannojg** [comment]
The one difference I see between your and my reproduction is that your expenses have a "review required" - how can I reproduce that part? cc @jliexpensify

**Comment by jliexpensify** [comment]
@hannojg - Puneet said it's likely a Violation, which is what I also thought. Maybe @lanitochka17 can open a distance expense and share a screenshot to verify?

**Comment by hannojg** [comment]
Hm, even with the report violation I can't reproduce the issue on neither android nor iOS:

https://github.com/user-attachments/assets/7818094f-efdb-42e7-925d-989a0a00dcca

**Comment by hannojg** [comment]
I also looked into how this is implemented - its using our default image component (which in general works well when reconnecting to the network).
The other thing is that the preview image is generated on the backend, thus it's just an image we are seeing.
Maybe for some reason the backend failed to generate a preview image for the reports @lanitochka17 reported?

**Comment by jliexpensify** [comment]
@hannojg, what do we think about this one? Is it important enough to investigate further/work on or should we close it?

**Comment by hannojg** [comment]
hm, its not reproducible for me on any of my devices, plus its using our default image component that works usually perfect when switching network.
If @lanitochka17 can reproduce 100%, we might want to keep ti open, but otherwise i'd close it. Personally i also feel like this is a very low impact bug (but i might be wrong here)

**Comment by jliexpensify** [comment]
Yep, lets close this one then - thanks @hannojg!
