### ISSUE TITLE
[HOLD for payment][$250] Mention-Numbers are displayed when editing an email mention of a user that is not a contact

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45259]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a message containing "@" mentioning an existing user but is not in your contact list
4. Right-click on the message > Edit comment.
5. Observe the edit field

## Expected Result:
The mentioned user's full email address is displayed in the edit box

## Actual Result:
User ID number is displayed in the edit box instead of the email address

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c952c847-711a-4c34-a39f-56d8d0604344

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831462503801260039</li>
        <li>Upwork Job ID: 1831462503801260039</li>
        <li>Last Price Increase: 2024-09-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Mention-Numbers are displayed when editing an email mention of a user that is not a contact

### What is the root cause of that problem?

The root cause of the problem is the [`Parser.htmlTomakdown`](https://github.com/Expensify/App/blob/28e5e4553454503180a64103bb35fae743424b6b/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L244) function needs an `accountIDToName` map to convert the mentioned accountIDs to the respective name.

This issue occurs in the [`Report.saveReportActionDraft`](https://github.com/Expensify/App/blob/28e5e4553454503180a64103bb35fae743424b6b/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L244) function in the [`ContextMenuActions.tsx`](https://github.com/Expensify/App/blob/28e5e4553454503180a64103bb35fae743424b6b/src/pages/home/report/ContextMenu/ContextMenuActions.tsx) file

https://github.com/Expensify/App/blob/28e5e4553454503180a64103bb35fae743424b6b/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L243-L245

Therefore, the [`Parser.htmlTomakdown`](https://github.com/Expensify/App/blob/28e5e4553454503180a64103bb35fae743424b6b/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L244) function returns the raw accountID because the HTML looks like the below example.

`"<mention-user accountID="17038670"/>"`

It returns `@17038670` instead of `@Alice` and saves the draft as `@17038670` in the onyx.

### What changes do you think we should make in order to solve the problem?


We should pass an `accountIDToName` object for the extras argument for the [`Parser.htmlTomakdown`](https://github.com/Expensify/App/blob/28e5e4553454503180a64103bb35fae743424b6b/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L244).

1) The First Solution which displays `"@Alice"`

We should create the `accountIDToName` record just before calling the [`Report.saveReportActionDraft`](https://github.com/Expensify/App/blob/28e5e4553454503180a64103bb35fae743424b6b/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L244) function.

So, the code that will create the `accountIDToName` object should look similar to the one below.

```
const accountIDToName: Record<string, string> = {} as Record<string, string>;

if (reportAction.originalMessage?.mentionedAccountIDs) {
    reportAction.originalMessage.mentionedAccountIDs.forEach((accountID: number) => {
        accountIDToName[accountID] = ReportUtils.getDisplayNameForParticipant(accountID);
    });
}

Report.saveReportActionDraft(reportID, reportAction, Parser.htmlToMarkdown(getActionHtml(reportAction),  { accountIDToName }));
```

https://github.com/Expensify/App/assets/22982173/198118d1-9a79-4dd5-aac7-61278a1d6b56


2) The Second Solution which displays `"@Hidden"`

Introduce `accountIDToName` by the following example code shown below.

```
accountIDToName: ReportUtils.getDisplayNameForParticipant as unknown as Record<string, string>
```

https://github.com/Expensify/App/assets/22982173/19f914ee-b43c-47b0-8631-e475957e7513


### What alternative solutions did you explore? (Optional)

We could use or create a function to display "@Alice" instead of "@Hidden" like the second solution illustrated above for cleaner code in one line.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User ID number is displayed in the edit box instead of the email address

### What is the root cause of that problem?
After we mention a user that we haven't chatted with before, BE returns the personal details of this user without `login`. And then `accountIDToNameMap` of this user is fallback to `accountID`


https://github.com/Expensify/App/blob/7e6375c0d3288f70b99b254eeec9857e1b69e16c/src/libs/Parser.ts#L18
### What changes do you think we should make in order to solve the problem?
Instead of falling back to accountID,  we can fall back to `displayName` or `Hidden`.

```
accountIDToNameMap[personalDetails.accountID] = personalDetails.login ?? getDisplayNameForParticipant(personalDetails.accountID);
```
https://github.com/Expensify/App/blob/7e6375c0d3288f70b99b254eeec9857e1b69e16c/src/libs/Parser.ts#L18

### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment]
Hmm, weird scenario. Interesting. I think either is fine. I guess display name is better.

**Comment by nkdengineer** [comment]
@aimane-chnaif It comes from this PR https://github.com/Expensify/App/pull/44732. It's simply something we display when we don't have a user `login` field so changing the fallback will not cause any regression.

**Comment by Tony-MK** [comment]
@aimane-chnaif, Could you give feedback on my proposal?

I believe the best-excepted behavior is display `@displayName`.

**Comment by Tony-MK** [comment]
Yeah.

According to my testing, the other proposal does not display `@displayName` but `@hidden`.

Therefore, editing a message, for example, `@Alice` would be `@hidden` after the edit.

Basically, like my second solution in my [propsal](https://github.com/Expensify/App/issues/45259#issuecomment-2223294141)

We should attempt the first solution.

**Comment by nkdengineer** [comment]
@aimane-chnaif Is there any problem with my proposal?

**Comment by Tony-MK** [comment]
> And [#45259 (comment)](https://github.com/Expensify/App/issues/45259#issuecomment-2237669800) was not confirmed yet.

@aimane-chnaif, Do you want the PR that introduced this line?

**Comment by nkdengineer** [comment]
@aimane-chnaif The change came from this PR https://github.com/Expensify/App/pull/40565. And I see that in this PR we only test the case select the mention in suggestion list that already had the `login` field.

**Comment by nkdengineer** [comment]
> your solution always shows @Hidden though @DisplayName exists.

What does that mean? It always shows when open edit composer or after editing?

**Comment by Tony-MK** [comment]
@aimane-chnaif, This issue was fixed at https://github.com/Expensify/App/pull/45352

**Comment by nkdengineer** [comment]
@aimane-chnaif We can still reproduce this bug with the mentioned user who doesn't set the display name. I updated my [proposal](https://github.com/Expensify/App/issues/45259#issuecomment-2225176426) with the fix and result 

https://github.com/user-attachments/assets/2aecbf23-2e59-4ce0-bab9-fe7d8fc5bb7e

> Both as @Tony-MK commented https://github.com/Expensify/App/issues/45259#issuecomment-2242096703

The checked and my previous proposal also works as expected

**Comment by nkdengineer** [comment]
@kadiealexander The PR was deployed to production 2 weeks ago.

**Comment by kadiealexander** [comment]
Ah sorry, the payment automation broke. Let me finish things now.

**Comment by kadiealexander** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@aimane-chnaif] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@aimane-chnaif] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@aimane-chnaif] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@aimane-chnaif] Determine if we should create a regression test for this bug.
- [ ] [@aimane-chnaif] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $250 @nkdengineer ([offer](https://www.upwork.com/nx/wm/offer/103821605))
- [ ] Reviewer: $250 @aimane-chnaif (via manual request)

Upwork job is [here](https://www.upwork.com/ab/applicants/1831462503801260039/job-details).

**Comment by kadiealexander** [comment]
@nkdengineer please let me know when you accept the offer.
@aimane-chnaif bump on completing the checklist!

**Comment by nkdengineer** [comment]
@kadiealexander I accepted the offer

**Comment by kadiealexander** [comment]
@aimane-chnaif sent you an offer!

**Comment by kadiealexander** [comment]
@aimane-chnaif bump!

**Comment by kadiealexander** [comment]
@aimane-chnaif please reopen the issue once you've accepted the Upwork offer.

**Comment by kadiealexander** [comment]
Paid, thanks @aimane-chnaif!
