### ISSUE TITLE
[HOLD for payment 2024-09-07][$250] Chat - Messages stuck highlighted when opening context menus consecutively

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45524]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat with existing messages
3. Right click on a message
4. Right click on another message
5. Click anywhere to close context menu

## Expected Result:
The second clicked message should not be highlighted

## Actual Result:
The second clicked message remains highlighted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1f1843ca-b401-407b-9121-fd858833a78e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010fad7b2cd94a8560</li>
        <li>Upwork Job ID: 1818656780802952530</li>
        <li>Last Price Increase: 2024-08-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Message background is stuck when open context menu while other context menu is showing.

### What is the root cause of that problem?
When we open a context menu, we pass a show and hide callback to the popover.
https://github.com/Expensify/App/blob/1084706b35c2157656ca747374b766083c910061/src/pages/home/report/ReportActionItem.tsx#L357-L358

Show callback will set the context menu active to true, while the hide callback will toggle the context menu and set it based on the context menu visibility.

When we open the first context menu and then open the second one, the hide callback of the first and second context menus is called. [The hide callback is cleared when called](https://github.com/Expensify/App/blob/1084706b35c2157656ca747374b766083c910061/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx#L241-L248).

Why the hide callback is called twice?

When we open a context menu, if an existing context menu is found, it will hide it first.
https://github.com/Expensify/App/blob/1084706b35c2157656ca747374b766083c910061/src/pages/home/report/ContextMenu/ReportActionContextMenu.ts#L126-L133

hideContextMenu() will set the context menu visibility to false while runAndResetOnPopoverHide() triggers the hide callback (1st hide callback).

Because we set the visibility to false, the context menu popover onModalHide is triggered, calling another runAndResetOnPopoverHide().

1. Open the first context menu, hide callback is set to the first context menu hide callback (callback = 1st)
2. Open the 2nd context menu.
- The first context menu hide callback is called (callback = empty) (hideContextMenu and runAndResetOnPopoverHide are called)
- The second context menu hide callback is set (callback = 2nd)
- The second context menu hide callback is called (callback = empty) (runAndResetOnPopoverHide is called by onModalHide)
3. Close the 2nd context menu, no hide callback is called, the highlight stays

### What changes do you think we should make in order to solve the problem?

If we look at the popover without overlay initial implementation, they face this problem before and that's why they added the code to close the current context menu before opening a new one in this [commit](https://github.com/Expensify/App/commit/3546860679cce9c67eb8a2ebe5db6b979b94a396).
https://github.com/Expensify/App/blob/1084706b35c2157656ca747374b766083c910061/src/pages/home/report/ContextMenu/ReportActionContextMenu.ts#L126-L133

But if you notice in the commit, we only call `runAndResetOnPopoverHide` to trigger the hide callback, which means we never set the context menu visibility to false (which also means the context menu never closes, just repositioned to a new position of the 2nd context menu).

But in this [resolve conflict commit](https://github.com/Expensify/App/pull/19011/commits/75f5ab4b29e773d7dcfc164a0ae2a73ab27979ce#diff-806bed8159a7b3bb0426a91aedf577b89e3cb8d8640182560d602338fa86d297), they added `hideContextMenu`. I believe it's because to allow opening the 2nd context menu on the same message without any problem.

Why does the double hide callback happen now? I'm pretty sure it's because the component has gone through several changes. For example, if you move the setting visibility to true here
https://github.com/Expensify/App/blob/1084706b35c2157656ca747374b766083c910061/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx#L216

to outside the promise, then the double hide callback won't happen since `setIsPopoverVisible(false)` and `setIsPopoverVisible(true)` are called almost right after the other, so the visibility state stays true. But in the current situation, the component has enough time to re-render the component with visibility of false, which triggers the extra `runAndResetOnPopoverHide`.

There solution is to wait until the current context menu is completely hidden before opening a new one. `hideContextMenu` second param supports a hide callback which we can use to show the second context menu after the 1st one is hidden.
```
if (contextMenuRef.current.instanceID) {
    hideContextMenu(undefined, // show context menu);
    // no need runAndResetOnPopoverHide
    return;
}
// show context menu immediately
```

**Comment by hungvu193** [comment]
Will be on my review list this tomorrow

**Comment by hungvu193** [comment]
@nyomanjyotisa I don't think we allow using `async/await` at the moment. Please checkout the contributing guide [here](https://github.com/Expensify/App/blob/b783854f2fdf09d09638aa0c471c9a0f1f8a7e78/contributingGuides/STYLE.md#esnext-are-we-allowed-to-use-insert-new-language-feature-why-or-why-not)

**Comment by hungvu193** [comment]
@bernhardoj Can you provide a little bit more about the code snippet that you mentioned here?  TIA

> There solution is to wait until the current context menu is completely hidden before opening a new one. `hideContextMenu` second param supports a hide callback which we can use to show the second context menu after the 1st one is hidden.
> 
> ```
> if (contextMenuRef.current.instanceID) {
>     hideContextMenu(undefined, // show context menu);
>     // no need runAndResetOnPopoverHide
>     return;
> }
> // show context menu immediately
> ```

**Comment by bernhardoj** [comment]
"// show context menu" is the showContextMenu code.
https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/pages/home/report/ContextMenu/ReportActionContextMenu.ts#L133-L152

So, it will look like this
```
if (contextMenuRef.current.instanceID) {
    hideContextMenu(undefined, () => contextMenuRef.current.showContextMenu(...));
    return;
}
contextMenuRef.current.showContextMenu(...);
```

**Comment by hungvu193** [comment]
I see. I don't think it works, I still can reproduce this issue.

https://github.com/user-attachments/assets/2a45b175-2364-4c4d-9ef2-c17e767564fc

**Comment by bernhardoj** [comment]
@hungvu193 I found that the `instanceID` is never cleared when hiding the popover, so `contextMenuRef.current.instanceID` is always true even though there is no active popover. So, when we try to open the popover again, it tries to hide it, but nothing to hide, so the hide callback is never called.
https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/pages/home/report/ContextMenu/ReportActionContextMenu.ts#L128-L129

I have updated my [proposal](https://github.com/Expensify/App/issues/45524#issuecomment-2247255696) to fix that too.

**Comment by hungvu193** [comment]
@bernhardoj I still don't think it works

https://github.com/user-attachments/assets/0c63acd1-1c9e-44f8-bf92-afa6f3086fd0

**Comment by hungvu193** [comment]
> ## Proposal
> [updated](https://github.com/Expensify/App/issues/45524#issuecomment-2264426501)
> 
> Actually we can store the instanceID in PopoverProvider. I have updated my proposal to use it.

Thanks for your update, reviewing shortly

**Comment by bernhardoj** [comment]
@hungvu193 you missed the early return

<img width="872" alt="image" src="https://github.com/user-attachments/assets/05d07fa8-2204-4643-8735-5fec482aa0cd">

**Comment by hungvu193** [comment]
I think it's still the same, here's the diff I tested:
<details><summary>Diff</summary>

```diff

diff --git a/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx b/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx
index 5cfce625201..9c65ba3e0f8 100644
--- a/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx
+++ b/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx
@@ -245,6 +245,7 @@ function PopoverReportActionContextMenu(_props: unknown, ref: ForwardedRef<Repor
 
         onPopoverHide.current = runAndResetCallback(onPopoverHide.current);
         onPopoverHideActionCallback.current = runAndResetCallback(onPopoverHideActionCallback.current);
+        setInstanceID('');
     };
 
     /**
diff --git a/src/pages/home/report/ContextMenu/ReportActionContextMenu.ts b/src/pages/home/report/ContextMenu/ReportActionContextMenu.ts
index c8d952be097..c04055922c8 100644
--- a/src/pages/home/report/ContextMenu/ReportActionContextMenu.ts
+++ b/src/pages/home/report/ContextMenu/ReportActionContextMenu.ts
@@ -126,8 +126,30 @@ function showContextMenu(
     // If there is an already open context menu, close it first before opening
     // a new one.
     if (contextMenuRef.current.instanceID) {
-        hideContextMenu();
-        contextMenuRef.current.runAndResetOnPopoverHide();
+        hideContextMenu(undefined, () =>
+            contextMenuRef?.current?.showContextMenu(
+                type,
+                event,
+                selection,
+                contextMenuAnchor,
+                reportID,
+                reportActionID,
+                originalReportID,
+                draftMessage,
+                onShow,
+                onHide,
+                isArchivedRoom,
+                isChronosReport,
+                isPinnedChat,
+                isUnreadChat,
+                disabledActions,
+                shouldCloseOnTarget,
+                setIsEmojiPickerActive,
+                isOverflowMenu,
+            ),
+        );
+        // contextMenuRef.current.runAndResetOnPopoverHide();
+        return;
     }
 
     contextMenuRef.current.showContextMenu(

```

</details>


https://github.com/user-attachments/assets/f901a3ea-6e8c-476b-8a18-d67588ca353c

**Comment by bernhardoj** [comment]
Can you try clearing the instance ID before calling the `onPopoverHide`?

**Comment by hungvu193** [comment]
> Can you try clearing the instance ID before calling the `onPopoverHide`?

Cool I think it worked.

**Comment by hungvu193** [comment]
@tsa321 I'm sorry but this piece of code right here made me really confused, the `id` params is the value from `getContextInstaceID()` which also the instanceID. 

<img width="1160" alt="Screenshot 2024-08-06 at 22 16 35" src="https://github.com/user-attachments/assets/84a13eb7-ca8a-4b82-993d-f520a1724f4f">

**Comment by hungvu193** [comment]
I don't think introducing another reference to store the last opened InstanceID and using recursion is a good way to handle such cases. Even if it resolves the issue, it makes the code difficult for other contributors to read and understand.

**Comment by hungvu193** [comment]
Still evaluating proposals

**Comment by hungvu193** [comment]
After taking another close review, @bernhardoj 's proposal here looks good to me!

🎀 👀 🎀  C+ reviewed!

**Comment by hungvu193** [comment]
little bump @roryabraham

**Comment by bernhardoj** [comment]
PR is ready

cc: @hungvu193

**Comment by bernhardoj** [comment]
The PR is reverted because of https://github.com/Expensify/App/issues/47659, but I can't repro it both in emulator or physical device. @hungvu193 are you able to reproduce the issue?

**Comment by hungvu193** [comment]
I can't reproduce the issue either :/ long pressing is a part of test case I don't think we missed it during our PR process

**Comment by bernhardoj** [comment]
I've tried checking out the commit where our PR is merged, but I still can't repro it. How should we move forward with this?

**Comment by hungvu193** [comment]
Hmm I think we still need to fix this issue. Can you please take a look when you have time @bernhardoj

**Comment by bernhardoj** [comment]
@hungvu193 do you mean to redo the PR?

Maybe we can open the PR and have a build and let QA (or @luacmartins since he can repro it) test https://github.com/Expensify/App/issues/47659 once again from the build. What do you think?

**Comment by hungvu193** [comment]
> @hungvu193 do you mean to redo the PR?
> 
> Maybe we can open the PR and have a build and let QA (or @luacmartins since he can repro it) test #47659 once again from the build. What do you think?

I think that's ok, then if it still introduces https://github.com/Expensify/App/issues/47659, we should fix it in that PR.

**Comment by bernhardoj** [comment]
> Maybe it would help to test it in strict mode.

Still not repro. I believe strict mode is not enabled when QA test it too.

> I think that's ok, then if it still introduces https://github.com/Expensify/App/issues/47659, we should fix it in that PR.

Cool, opened up a new PR.

cc: @hungvu193

**Comment by hungvu193** [comment]
> Maybe it would help to test it in `strict` mode. I tested it in strict mode with my proposed code changes, and almost everything works properly. There is only one issue: on mobile Chrome/MWeb, the `Copy to Clipboard` function doesn’t work properly. Aside from that, everything else is functioning correctly.

Thanks, We will definitely use StrictMode during our PR process.

**Comment by hungvu193** [comment]
@anmurali  The second attempt was deployed to prod 8 days ago. This issue is now ready for payment

**Comment by anmurali** [comment]
I think this issue behooves a regression test?

**Comment by hungvu193** [comment]
**Regression Test:**
1. Open any chat that has multiple messages (or send multiple messages on the chat)
2. Right-click on one message.
3. Right-click on another message While the first context menu is open.
4. Repeat it multiple times
5. Verify the highlight of the message disappears once the context menu of the message is hidden
6. Close the context menu
7. Right-click on a message
8. Verify the context menu is shown and the message is highlighted

Do we 👍  or 👎  ?

**Comment by hungvu193** [comment]
@anmurali Can you please handle the payment summary here? Ty 😄

**Comment by roryabraham** [comment]
This was deployed to prod on 2024-08-30 so is definitely ready for payment. Marking it as such

**Comment by anmurali** [comment]
@hungvu193 is paid
Sent @bernhardoj an offer [here](https://www.upwork.com/nx/wm/offer/104438554)

**Comment by bernhardoj** [comment]
@anmurali I've requested in ND.

**Comment by anmurali** [comment]
Payment summary

- [ ] @hungvu193 paid $250 on Upwork
- [ ] @bernhardoj approved $250 via New Dot

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
