### ISSUE TITLE
[Workspace Feeds] Expensify Card - Expensify Card page reopens when clicking Back from workspace editor

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46045]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to Workspace settings > Expensify Card
3. Click Issue card
4. Click back button to return to Expensify Card main page
5. Click back button to return to workspace editor
6. Click back button again

## Expected Result:
 App will return to workspace list
 

## Actual Result:
App returns to Expensify Card main page again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9c344a94-058d-429d-8474-0c3843fa8e70

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by mountiny** [comment]
This is not a blocker as this feature is behind beta

**Comment by koko57** [comment]
I can take this one

**Comment by koko57** [comment]
I cannot recreate this in version 9.0.11-2
https://github.com/user-attachments/assets/9a42846c-6877-41e7-addf-b38b285cf56b

this was fixed in https://github.com/Expensify/App/pull/45690/files#diff-dd029be30c66f2c0c9f9087ee89e752d8771153991c2f2cf9c4ceec89d64e9af

**Comment by mountiny** [comment]
Thanks

**Comment by lanitochka17** [comment]
Issue is still reproducible on the 9.0.11-2

https://github.com/user-attachments/assets/fe84960d-768c-45c0-8c73-96c133c9b951

**Comment by mountiny** [comment]
cc @koko57

**Comment by koko57** [comment]
@lanitochka17 can you please retest on production version 9.0.11-5 or 9.012-0? The line I mentioned earlier fixes the issue for sure, it was deployed to staging in version  9.0.11-2, to production 9.0.11-5 or 9.0.12-0. So if you were retesting production version of 9.0.11-2 the change wasn't there.

I cannot reproduce it locally in v 9.0.13-0 Develop
https://github.com/user-attachments/assets/aa649f6c-dc01-46e4-9e2a-6c78cc65671d

**Comment by lanitochka17** [comment]
Issue is not reproducible

https://github.com/user-attachments/assets/5b6a8740-8b8b-4c8a-9be9-9d46dcbabb11

**Comment by mountiny** [comment]
nice, thanks
