### ISSUE TITLE
iOS - Attachment - App crashes when pasting an image from Google app (not Chrome browser)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47065]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Google app is installed on the iOS device
- Google search widget is added to the home screen
1. Open Google search widget from the home screen
2. Search for an image
3. Long press on the image and copy it
4. Launch New Expensify app
5. Go to chat
6. Paste the image

## Expected Result:
App will not crash

## Actual Result:
App crashes
This issue only happens when the image is copied from Google app, and not Chrome or Safari browser

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e68b8e1f-0eb5-47c3-9e02-08b7e397c31c

https://github.com/user-attachments/assets/93e1d8d1-c845-42c4-9650-1d1324ce2791

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by marcaaron** [comment]
Seems unrelated to the API so removing the DeployBlocker label

**Comment by marcaaron** [comment]
>This issue only happens when the image is copied from Google app, and not Chrome or Safari browser

Seems pretty edge case to me... this currently works on production? Or is it not possible to test because we can't paste at all?

Seems like the latter: https://github.com/Expensify/App/pull/45722

**Comment by roryabraham** [comment]
cc @s77rt

**Comment by s77rt** [comment]
Hmm I'm not totally sure how I can test this on the Simulator. Can we get the error report?

**Comment by roryabraham** [comment]
Created https://github.com/Expensify/App/pull/47110 so this doesn't have to block deploy, but yes I'll also try to track down the crash report for you. Jury's out whether it will be of any use

**Comment by s77rt** [comment]
Can be demote this to not a blocker since it's a feature that didn't exist? And it seems to be an edge case

**Comment by roryabraham** [comment]
I agree it's an edge case, but imo a non-critical new feature causing a crash should be treated as a blocker. especially since we don't really know the root cause, there might be other instances that we haven't discovered. We'd rather users not be able to paste images than to have their app crash when they try.

**Comment by roryabraham** [comment]
waiting for an approval on https://github.com/Expensify/App/pull/47114 to complete the CP

**Comment by roryabraham** [comment]
Should be fixed in 9.0.18-7: https://github.com/Expensify/App/actions/runs/10311017716

**Comment by marcaaron** [comment]
I think given that this flow is very specific to the Google app and that reverting didn't solve the issue we should demote it for now. Gonna do that.

**Comment by m-natarajan** [comment]
Still reproducible 

https://github.com/user-attachments/assets/02abdd06-fec3-4bd0-a04a-d3e4ac5dcdbd

**Comment by s77rt** [comment]
https://github.com/Expensify/App/pull/47114 didn't include the removal of the RN patch

**Comment by puneetlath** [comment]
@s77rt I don't totally follow. What does that mean needs to be done?

**Comment by s77rt** [comment]
@puneetlath If this is still reproducible then I think we should just wait for https://github.com/Expensify/App/pull/47203 to hit staging

**Comment by mvtglobally** [comment]
issue is fixed

https://github.com/user-attachments/assets/f9c89fef-3b17-469d-a0b9-9f30ed72d2ec

**Comment by mvtglobally** [comment]
Looks resolved 
https://github.com/user-attachments/assets/b06e637e-8331-4037-9512-ed9bc07015c4
