### ISSUE TITLE
[$250] [Search v1.2] - Total amount of the grouped expenses does not update after deleting the expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47385]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit at least 3 expenses to any user.
3. Go to Search.
4. Go to Shared.
5. Select one of the expenses via checkbox.
5. Click on the dropdown.
6. Click Delete.
7. Delete the selected expense.

## Expected Result:
The total amount of the grouped expenses will update accordingly after deleting the expense.

## Actual Result:
The total amount of the grouped expenses does not update after deleting the expense.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/05daa814-df4a-42a0-a091-0ef1f1f4a5ef

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012231bbe2d257a312</li>
        <li>Upwork Job ID: 1823653421702250918</li>
        <li>Last Price Increase: 2024-08-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search Page - Total amount of the grouped expenses does not update after deleting the expense
### What is the root cause of that problem?
When we delete the expense, the `deleteMoneyRequestOnSearch` function got invoked, but the BE doesn't return or tell the FE to update the Onyx total amount, but when we refresh the page we see the correct amount from the BE
### What changes do you think we should make in order to solve the problem?
After deleting the expense we can invoke the `Search` API to update the total amount
### What alternative solutions did you explore? (Optional)
We can sum the total by summing of all transactions instead of using the total property, because when the `deleteMoneyRequestOnSearch` function got invoked, the BE return an Onyx response and setting the deleted transaction to null

**Comment by codewaseem** [comment]
https://github.com/Expensify/App/issues/47385#issuecomment-2289155103
Proposal Updated to include demo.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Grouped expenses total does not update after deleting an expense.

### What is the root cause of that problem?

handleDeleteExpenses is not included in SearchActions.search useEffect

### What changes do you think we should make in order to solve the problem?

Add `handleDeleteExpenses` to the useEffect

src/components/Search/index.tsx
```tsx
    useEffect(() => {
        if (isOffline) {
            return;
        }

        SearchActions.search({queryJSON, offset, policyIDs});
        // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps
    }, [isOffline, offset, queryJSON, handleDeleteExpenses]);

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by sonialiap** [comment]
@zanyrenney I'm OOO Aug 19-30, adding leave buddy. 
Status: waiting for @aimane-chnaif to review and select a proposal

**Comment by wildan-m** [comment]
@aimane-chnaif 

[Proposal Updated](https://github.com/Expensify/App/issues/47385#issuecomment-2290960307)

- Add alternative solution by updating optimistic data

**Comment by flodnv** [comment]
I feel like we shouldn't be calling the API just after calling it, the API should return what the frontend needs.

Since this is related to a new search feature, I'm reassigning this to you @luacmartins for assessment.

**Comment by luacmartins** [comment]
I agree with Flo, we shouldn't trigger an AP call to update data. I think this is a BE issue and we should just update `DeleteMoneyRequestOnSearch` to be sending the updated report totals to clients.

**Comment by sonialiap** [comment]
@zanyrenney I'm back from OOO, unassigning you. Thanks for keeping an eye on this!

**Comment by sonialiap** [comment]
@aimane-chnaif after internal engineering review, do you think we can move forward with either proposals (maybe with a little reworking) or do you think we need a new one?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment]
This is fixed. Closing.

**Comment by IuliiaHerets** [comment]
This issue is still repro, build - v9.0.57-4

https://github.com/user-attachments/assets/a6eedba0-211b-4c2e-a8ee-d5b6871c7043

**Comment by luacmartins** [comment]
@IuliiaHerets I'm a bit confused by the video posted. Could you include one that follows the steps in the OP?

**Comment by IuliiaHerets** [comment]
@luacmartins Right now tester can't repro this issue

https://github.com/user-attachments/assets/326d12bb-5fb8-488d-b2fc-9d673585e50c
