### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] QAB - Workspace avatar remains custom when change do default

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49448]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):** gocemate+a2177@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sign-up for an gmail account as a brand new user
2. Create a workspace and give it a custom avatar
3. Go to FAB
4. Click Submit expense and send a manual request to the workspace
5. Change the workspace avatar to default
6. Open FAB
7. Take a look at the workspace avatar in the QAB

## Expected Result:
Default workspace avatar should be displayed in the quick action button

## Actual Result:
Custom workspace avatar is displayed in the quick action button when user change the workspace avatar to default. Avatar doesn't get removed not only on the QAB but also for the workspace chat also.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7ba18b69-148b-4f61-9332-c5cb3f610240

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838248313041984995</li>
        <li>Upwork Job ID: 1838248313041984995</li>
        <li>Last Price Increase: 2024-11-18</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 105022549</li>
<li>mkzie2 | Contributor | 105022550</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Custom workspace avatar is displayed in the quick action button when user change the workspace avatar to default. Avatar doesn't get removed not only on the QAB but also for the workspace chat also.

### What is the root cause of that problem?
When we remove the avatar of the policy, `report. policyAvatar` hasn't changed. It leads after we remove the avatar, `isSameAvatarURL` still `true` then we return the policy avatar from `workSpaceIconsCache` which is still old policy avatar

https://github.com/Expensify/App/blob/37bf6b2fef128786dfcd83257a56f56c0cd1eb3d/src/libs/ReportUtils.ts#L1958-L1965
### What changes do you think we should make in order to solve the problem?
When we get the `policyAvatarURL` here, we should check if the policy still exists we should prioritize the `avatarURL` of policy first

```
const reportPolicy = policy ?? allPolicies?.[`${ONYXKEYS.COLLECTION.POLICY}${report?.policyID}`];

// disabling to protect against empty strings
// eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
const policyAvatarURL = reportPolicy ? reportPolicy?.avatarURL : report?.policyAvatar;
```

https://github.com/Expensify/App/blob/37bf6b2fef128786dfcd83257a56f56c0cd1eb3d/src/libs/ReportUtils.ts#L1958-L1965

### What alternative solutions did you explore? (Optional)

We have some other solutions like updating `policyAvatar` to empty for all related reports of the workspace when we remove the custom avatar or we can update `workSpaceIconsCache` of the policy to the default icon when we delete the custom avatar.

**Comment by hayes102** [comment]
I think this is more a backend issue, where the 
the `report?.policyAvatar` doesnt update on policy avatar removal.

FYI: the `report?.policyAvatar`  was introduced to solve this issue https://github.com/Expensify/App/issues/33470, so i think the safest solution would be to fix it from the backend

**Comment by situchan** [comment]
Thanks for the proposals. Please explain in root cause why this bug only happens in QAB.

**Comment by mkzie2** [comment]
@situchan This bug also happens for policy-related reports like the video below. The old policy avatar displays briefly until the `OpenReport` API is complete that update `policyAvatar` to empty.

https://github.com/user-attachments/assets/29cdc6b6-1359-4241-a2f9-3235c2932406

**Comment by situchan** [comment]
I am inclined to https://github.com/Expensify/App/issues/49448#issuecomment-2369231324.
Can we fix this in backend? 🎀👀🎀

**Comment by mkzie2** [comment]
@situchan  When we update the avatar of the workspace back-end update the `policyAvatar` of the report but this will not be returned in the response because maybe we can have many related reports for a workspace. Then when we open a related report this field will be updated. So I think we should update the way we get the avatar in frontend.

cc @luacmartins

**Comment by luacmartins** [comment]
This is yet another example of duplicated data causing issues.  Can we use the data in the `policy_` key instead?

**Comment by mkzie2** [comment]
@luacmartins Yes that is what I proposed.

**Comment by luacmartins** [comment]
Yea, I think we should be using that. FWIW we have a way to retrieve[ non-member policy data](https://github.com/Expensify/App/blob/f4a225d9d8f03e46c8b9d8cc22932571df1a1eda/src/types/onyx/Policy.ts#L1352-L1369), so I'm not even sure why we added policyAvatar to the report key as this also goes against our principles of keeping DB and Onyx data the same cc @techievivek

**Comment by mkzie2** [comment]
@luacmartins I think we used `policyAvatar` for the case the policy is deleted

**Comment by situchan** [comment]
@techievivek kind bump https://github.com/Expensify/App/issues/49448#issuecomment-2372636151

**Comment by techievivek** [comment]
> Yea, I think we should be using that. FWIW we have a way to retrieve[ non-member policy data](https://github.com/Expensify/App/blob/f4a225d9d8f03e46c8b9d8cc22932571df1a1eda/src/types/onyx/Policy.ts#L1352-L1369), so I'm not even sure why we added policyAvatar to the report key as this also goes against our principles of keeping DB and Onyx data the same

I see, I wasn’t aware we already had a method to retrieve policy data for non-members. Since that's the case, I agree we should use that instead of introducing a new field. It also seems that adding the avatar to reports follows a similar approach to when we added the policyName field https://github.com/Expensify/App/pull/37003/files#diff-5f549daaaaca967d763b3671e371465143185bab398c16825ff9cb2d41a7de7fL120, which also goes against the principle of keeping the DB and Onyx data consistent. Should we look into that as well?

**Comment by luacmartins** [comment]
Yes, I think we should

**Comment by slafortune** [comment]
@situchan @luacmartins is there a proposal that will work - or an update?

**Comment by situchan** [comment]
Not overdue

**Comment by luacmartins** [comment]
I think there's a bit of internal work that needs to be done before we can change anything in App itself. @techievivek are you able to work on [these changes](https://github.com/Expensify/App/issues/49448#issuecomment-2382316577)?

**Comment by techievivek** [comment]
@luacmartins This only requires a frontend change, right? As you mentioned, we already sent all those details via the backend, so can we not pass this to an external contributor via this GH? Or do we need some other backend changes as well?

**Comment by luacmartins** [comment]
Do non-members already have access to that data? If they do, then I agree we only need FE changes.

**Comment by situchan** [comment]
@mkzie2 can you please confirm that your solution works for non-members and share video?

**Comment by mkzie2** [comment]
@situchan Here is the video. In the video, I invited a user who isn't a member of the WS to the WS chat via mention, and the avatar is displayed correctly. In this case, the invited user will not have the data of the policy and it's used `policyAvatar` from report data to display

https://github.com/user-attachments/assets/6d9e26c8-b6d0-4bf7-b569-b8b4c140d0aa

**Comment by situchan** [comment]
> it's used `policyAvatar` from report data to display

So it's outdated avatar, which is wrong

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

QAB - Workspace avatar remains custom when change do default

### What is the root cause of that problem?

We are using outdated avatar from `report?.policyAvatar` 

https://github.com/Expensify/App/blame/f4a225d9d8f03e46c8b9d8cc22932571df1a1eda/src/libs/ReportUtils.ts#L1942

### What changes do you think we should make in order to solve the problem?

`report?.policyAvatar` originally created to get policy avatar url because at the time PR created, non-member user doesn't have information about the URL https://github.com/Expensify/App/issues/33470#issuecomment-1867249606, but then this solution will cause synchronization issue.

Since we can now access the policy avatarUrl even when someone is not the member of a workspace, we can revert this PR https://github.com/Expensify/App/pull/35792 and replace all `report.policyAvatar` usage to `policy.avatarUrl`

### What alternative solutions did you explore? (Optional)
N/A

**Comment by situchan** [comment]
> Since we can now access the policy avatarUrl even when someone is not the member of a workspace

@wildan-m can you please double check? Please also share test steps where non-member can see workspace.
Also make sure that reverting doesn't cause [original bug](https://github.com/Expensify/App/issues/33470)

**Comment by wildan-m** [comment]
@situchan thanks for your comment, I've tried with fresh account and it's not working as expected, (maybe previously working because of cache) seems BE is not returning any info for non member.

![image](https://github.com/user-attachments/assets/9c8d4a8d-3eae-4232-941d-09376dca63c3)

> FWIW we have a way to retrieve[ non-member policy data](https://github.com/Expensify/App/blob/f4a225d9d8f03e46c8b9d8cc22932571df1a1eda/src/types/onyx/Policy.ts#L1352-L1369)

@luacmartins @techievivek do we need to call some functions to fill that data? I think it will be automatically populated with nonmember info at the time someone invited?

**Comment by mkzie2** [comment]
> So it's outdated avatar, which is wrong

@situchan 

- For nonmembers, `policyAvatar` is updated if we refresh the page. To keep it up to date, we need to send the pusher data when we update the WS avatar. Nonmembers are required to use `policyAvatar` because they don't have `policy` data.

**Comment by situchan** [comment]
> Do non-members already have access to that data? If they do, then I agree we only need FE changes.

can we get correct answer? I don't think they have access.
cc: @luacmartins @techievivek

**Comment by luacmartins** [comment]
@situchan we can probably test this in the frontend by logging in and seeing what kind of data a non-member gets once they try to join a policy.

**Comment by wildan-m** [comment]
@luacmartins I've tried that, no data on the  initial invite https://github.com/Expensify/App/issues/49448#issuecomment-2413068913

**Comment by mkzie2** [comment]
@luacmartins We have two types of none-member:

1. The user is requesting to join the WS, this user will have the `policyDetailsForNonMembers` 

<img width="661" alt="Screenshot 2024-10-18 at 14 12 26" src="https://github.com/user-attachments/assets/d7052ad4-db2e-4b53-b9fd-a222ecb7b202">

2. The user is invited to a WS chat of a member via mention, this user doesn't have `policy` data and we use `report.policyAvatar` to display the avatar of the report.

**Comment by wildan-m** [comment]
How can non member request join if they can't access the WS page? is it only for public room?

**Comment by luacmartins** [comment]
One way that I know of is via an invite link

**Comment by luacmartins** [comment]
>The user is invited to a WS chat of a member via mention, this user doesn't have policy data and we use report.policyAvatar to display the avatar of the report.

Hmm it seems like we'd need some backend changes to accommodate for this.

**Comment by luacmartins** [comment]
Haven't been able to look into this. @techievivek do you have bandwidth to take the internal part of this issue?

**Comment by techievivek** [comment]
Yeah, I can handle the backend changes for this.

**Comment by mkzie2** [comment]
@techievivek Will we remove `policyName` and `policyAvatar` in `report` data?

**Comment by techievivek** [comment]
Yep.

**Comment by techievivek** [comment]
Not overdue, will take a look into it today.

**Comment by techievivek** [comment]
Not overdue.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment]
Did this get fixed somewhere?

**Comment by techievivek** [comment]
Not sure, I can ask for a re-test to confirm if this is still happening in some way.

**Comment by techievivek** [comment]
Requested here https://expensify.slack.com/archives/C9YU7BX5M/p1730701188532819

**Comment by izarutskaya** [comment]
Issue is still reproducible
Build v9.0.56-9

https://github.com/user-attachments/assets/372103fd-a3df-4a9f-a0d3-888c9afdf5c2

**Comment by situchan** [comment]
I am going to be on parental leave. Please reassign C+

**Comment by techievivek** [comment]
We added the change here https://github.com/Expensify/Auth/pull/9612 that returns the policy avatar in the report.

**Comment by techievivek** [comment]
From the discussions above, this doesn’t seem like a good solution because the data can become outdated—for example, when the policy avatar is updated, as we don’t push these updates to the policy’s related reports, right?

**Comment by techievivek** [comment]
Don't we have the updated policy avatar data in the onyx? Can we not use that instead? Why are we preferring to look at the report's key for the policy avatar?

**Comment by mkzie2** [comment]
> From the discussions above, this doesn’t seem like a good solution because the data can become outdated—for example, when the policy avatar is updated, as we don’t push these updates to the policy’s related reports, right?

Yeah, when we update the policy avatar, the report's `policyAvatar` is not updated. It will be updated after we reload or open the report.

> Can we not use that instead?

I think this data is necessary for this [case](https://github.com/Expensify/App/issues/49448#issuecomment-2399296682).

> Why are we preferring to look at the report's key for the policy avatar?

That is how the bug happens and we need to prefer the policy's avatar if the policy data exists

**Comment by techievivek** [comment]
I agree that we could prevent sending policy avatar data to the reports, but I am curious why are we relying on that value from the report instead of directly getting it from the workspace. I understand it can be challenging when non-workspace members are invited to an associated workspace room, as they don’t have access to workspace data and would need to get it from the report. Is that what’s happening here? Is it only broken for non-members? Is it working correctly for workspace members?

If the issue only affects non-workspace members, then perhaps we should add some logic to the `UpdateWorkspaceAvatar` command to also push updates to non-workspace members who are linked to the policy through certain rooms. Does that approach make sense? @luacmartins @c3024

**Comment by techievivek** [comment]
> That is how the bug happens and we need to prefer the policy's avatar if the policy data exists

So the current code looks at the report data first and then only the policy data?

**Comment by mkzie2** [comment]
Yes.

**Comment by techievivek** [comment]
Not overdue

**Comment by mkzie2** [comment]
> Is that what’s happening here?

This original bug happens for policy members. But we have a concern about the `policyAvatar` of the report for non-policy members on the side of this user. The report's avatar was not updated in real-time when we updated the policy avatar. So we need some updates like this:

- For policy members, we need to look at policy data first (This is the frontend change)

- For non-policy members, we need to push an update via pusher then the `policyAvatar` of the report can be updated in real-time without refreshing. (This is the backend change)

@techievivek What do you think?

**Comment by wildan-m** [comment]
@techievivek 

> We added the change here https://github.com/Expensify/Auth/pull/9612 that returns the policy avatar in the report.

Can't access. does it means non member can now access the `policy.avatarUrl` ?

> If the issue only affects non-workspace members, then perhaps we should add some logic to the UpdateWorkspaceAvatar command to also push updates to non-workspace members who are linked to the policy through certain rooms. Does that approach make sense?

I think, it makes sense to ensure we have a single source of truth.

**Comment by techievivek** [comment]
@mkzie2 

> @techievivek What do you think?

Yeah, I agree with that solution and was thinking the same. For workspace members, we can fetch the data from the workspace since that must have the updated data. And for non-members we can push the updates when we update the avatar.

**Comment by techievivek** [comment]
> Can't access. does it means non member can now access the policy.avatarUrl ?
No, that was done only as part of invite room command and not when we update the policy avatar.

**Comment by techievivek** [comment]
@luacmartins how does this plan look like? https://github.com/Expensify/App/issues/49448#issuecomment-2469860109

**Comment by luacmartins** [comment]
Plan sounds good to me

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by c3024** [comment]
This is fixed. Does this still need anything from frontend?

**Comment by mkzie2** [comment]
@c3024  I still can reproduce this bug, we still need the front-end fix since `policyAvatarURL` is still wrong in the case the policy avatar is removed.

https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/libs/ReportUtils.ts#L2062

**Comment by c3024** [comment]
@mkzie2 

I cannot repro this with steps in the OP.

https://github.com/user-attachments/assets/efe2e4ad-a638-4d06-86bf-108a1fd3cfd2

Could you share the steps with which you can reproduce the bug?

It looks like, at the time you posted [your proposal](https://github.com/Expensify/App/issues/49448#issuecomment-2360547115), `report.policyAvatarURL` used to be prioritized and you suggested to prioritize the policy `avatarURL`. But, now, as on existing `main` (as linked in your [comment above](https://github.com/Expensify/App/issues/49448#issuecomment-2481398858) also), the policy `avatarURL` is prioritized. It looks like some other PR already made this change. Correct me if I am wrong.

**Comment by mkzie2** [comment]
@c3024 As the video shows, the avatar briefly becomes the old avatar after you open the chat report again. If you click on the plus icon without going back to the inbox, you can see the old avatar is present in QAB. The reason is this condition is still wrong when we remove the workspace avatar. In this case `policy?.avatar` is an empty string and `report.policyAvatar` is the old policy avatar. It will be updated if `OpenReport` API is called.

https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/libs/ReportUtils.ts#L2062

**Comment by c3024** [comment]
@mkzie2 

>If you click on the plus icon without going back to the inbox, you can see the old avatar is present in QAB. 

Thanks! I missed that. 

>In this case policy?.avatar is an empty string and report.policyAvatar is the old policy avatar.

When `avatarURL` is an empty string, your solution allows it to be assigned to `policyAvatarURL`.

> const reportPolicy = policy ?? allPolicies?.[`${ONYXKEYS.COLLECTION.POLICY}${report?.policyID}`];
> 
> // disabling to protect against empty strings
> // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
> const policyAvatarURL = reportPolicy ? reportPolicy?.avatarURL : report?.policyAvatar;

The comment
> // disabling to protect against empty strings
 
suggests disallowing empty strings for `policyAvatarURL`. 

Does allowing `''` to `policyAvatarURL` not cause any regressions?

**Comment by mkzie2** [comment]
@c3024 This will not cause any regressions because we update this to the correct data. I guess we added this comment in the past for the case we update the avatar of policy from default to a custom avatar, in this case ` report?.policyAvatar` isn't updated immediately and it's an empty string and `policy?.avatarURL` is the custom avatar link.

**Comment by techievivek** [comment]
I am not aware of any backend changes made for this. Is the problem fixed? Do we need any frontend code update for this? @mkzie2 Do we have a proposal that can be reviewed?

**Comment by mkzie2** [comment]
@techievivek The bug is still reproducible. I've had a proposal [here](https://github.com/Expensify/App/issues/49448#issuecomment-2360547115) and it's still valid now.

**Comment by c3024** [comment]
@mkzie2 's [proposal](https://github.com/Expensify/App/issues/49448#issuecomment-2360547115) LGTM!

🎀 👀 🎀 C+ reviewed.

**Comment by c3024** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: This is an edge case and the offending lines changed over many PRs so no specific PR can be held responsible.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: No discussion was started because this could not have been identified earlier.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1. Create a workspace
2. Go to workspace settings > Profile > Edit workspace avatar (change to custom avatar)
3. Go to FAB > Submit expense to submit a manual request to the workspace
4. Go to workspace settings > Profile > Remove photo (change to default avatar)
5. Press FAB (do not go to Inbox)
6. Verify the workspace avatar in QAB is correct

Do we agree 👍 or 👎


</details>

**Comment by techievivek** [comment]
Regression test sounds good to me.

**Comment by techievivek** [comment]
@slafortune Can we please get that added to the testRail? Thanks.

**Comment by slafortune** [comment]
@c3024 Paid $250 [automatic offer](https://www.upwork.com/nx/wm/offer/105022549) (Reviewer)
@mkzie2 Paid $250 [automatic offer](https://www.upwork.com/nx/wm/offer/105022550) (Contributor)
