### ISSUE TITLE
[HOLD for payment 2024-11-28] [$250] Contact Methods - Navigated back to "New contact method" when going back to online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51189]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to account settings > Profile
2. Click on "Contact Method"
3. Click on "New Contact method"
4. Add a email > Add
5. In the verification page go Offline and return back online

## Expected Result:
User is not Navigated back to "New contact method" when going back to online

## Actual Result:
Navigated back to "New contact method" when going back to online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/4d75470f-4cf1-4715-aecd-8dbb65cdb882

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853397434469388025</li>
        <li>Upwork Job ID: 1853397434469388025</li>
        <li>Last Price Increase: 2024-11-11</li>
<li>Automatic offers: </li>
<ul>
<li>wildan-m | Contributor | 104874938</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment]
No more reproducible, it was solved here
https://github.com/Expensify/App/pull/49445

**Comment by zanyrenney** [comment]
Closing as solved above!

**Comment by lanitochka17** [comment]
Issue is still reproducible on the mWeb/Chrome on the latest build 9.0.55-2

https://github.com/user-attachments/assets/cc2f859e-272b-4db9-b981-0d616d1444f9

**Comment by zanyrenney** [comment]
Hmm i can't reproduce this.

**Comment by zanyrenney** [comment]
@lanitochka17 still about to reproduce?

**Comment by lanitochka17** [comment]
User is still Navigated back to "New contact method". But now tester is seeing that user is navigated to "New contact method" page when pressing on cmd + D.

https://github.com/user-attachments/assets/90ec0fd0-edb9-4580-b1f5-77acd90415df

**Comment by zanyrenney** [comment]
Okay, this not the expected behaviour, so let's get this added to external for priorities.

**Comment by zanyrenney** [comment]
Being navigated to the wrong place and requiring use of cmd +D = quality issue.

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Part of the screen is covered with black rectangle on MC page. Scrolling gets stuck after swiping up and down a few times

### What is the root cause of that problem?
After we offline and online, `ReconnectApp` API is called which update `isLoadingReportData` to `true`

https://github.com/Expensify/App/blob/10454f06334ae3d07d4a28a81c5c79f3d2112c53/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L143

It leads loading page shown, and the input is unmounted and mounted again which causes the empty input appears

https://github.com/Expensify/App/blob/10454f06334ae3d07d4a28a81c5c79f3d2112c53/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L168-L170

### What changes do you think we should make in order to solve the problem?
Here we check whether the `policy` is `undefined` or not to display the loading page but if `policyID` is `undefined` this condition is always `true`. So I think we should add the condition to check `policyID` is `undefined` or not to show the loading page

```
const shouldShowFullScreenLoadingIndicator = !isMoneyRequest && isLoadingReportData !== false && (!Object.entries(policy ?? {}).length || !policy?.id) && policyID;
```
https://github.com/Expensify/App/blob/10454f06334ae3d07d4a28a81c5c79f3d2112c53/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L143

### What alternative solutions did you explore? (Optional)

We can add `shouldSaveDraft` to the input here to save the draft value.

https://github.com/Expensify/App/blob/10454f06334ae3d07d4a28a81c5c79f3d2112c53/src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx#L133

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Return to "New contact method" when going back online.

### What is the root cause of that problem?

We are using Modal to show validation section. Using modal have these limitations:
- Will hide each time we re-mount / refresh the page
- Will hide each time another modal open

### What changes do you think we should make in order to solve the problem?
Contact validation page is not directly related to a report, but we conditionaly show loading indicator each time report data loaded here:

https://github.com/Expensify/App/blob/c286316d1b6efacc0e36694c21125513aa078970/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L144

I think we don't need to show loading indicator in validation page because it  is not directly related to a report, we can add new `shouldDisableLoadingIndicator` prop in `AccessOrNotFoundWrapper`

and modify logic to show the loading

```tsx

    const shouldShowFullScreenLoadingIndicator = !isMoneyRequest && isLoadingReportData !== false && (!Object.entries(policy ?? {}).length || !policy?.id) && !shouldDisableLoadingIndicator;

```

Apply it in `src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx` or other similar pages

```tsx

        <AccessOrNotFoundWrapper shouldBeBlocked={isActingAsDelegate} shouldDisableLoadingIndicator={true}>
 
```

This way the validation modal will not need to re-mount.

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/51189-disable-loading-indicator-for-validate-modal?expand=1)
### What alternative solutions did you explore? (Optional)
If the bounty is doubled, I am willing to convert `ValidateCodeActionModal` to a page. Despite its widespread use, the conversion process is not straightforward.

This will also resolve this issue https://github.com/Expensify/App/issues/51189#issuecomment-2454455809

**Comment by wildan-m** [comment]
[Proposal Updated](https://github.com/Expensify/App/issues/51189#issuecomment-2463712776)

- add alternative 2 based on https://github.com/Expensify/App/issues/51189#issuecomment-2469069685 suggestion

@fedirjh If no one has proposed it yet, I have added it as alternative 2. I agree that we only need a "not found" page for this case and the `isActingAsDelegate` condition seems sufficient.

**Comment by wildan-m** [comment]
@fedirjh The PR is ready https://github.com/Expensify/App/pull/52523. Thanks!

**Comment by zanyrenney** [comment]
https://github.com/Expensify/Expensify/issues/448571

**Comment by zanyrenney** [comment]
### payment summary
@wildan-m requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104874938) (Contributor) - paid $250 via upwork 
@fedirjh requires payment through NewDot Manual Requests - please request $250 via ND.

**Comment by garrettmknight** [comment]
$250 approved for @fedirjh
