### ISSUE TITLE
[$250] QBD - Tags show as disabled despite selecting `Import as Tags` in workspace config

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52133]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5184319
**Email or phone of affected tester (no customers):** applausetester+dqbd7@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: User is connected to QBD
1. In a workspace connected to QBD, navigate to Accounting > Import 
2. Verify `Import as tags` appears for one or more coding configurations 
3. Navigate to `More features` > `Tags` and notice the toggle shows disabled
4. Navigate to the LHN and notice that `Tags` menu item is absent 

## Expected Result:
If `Import as Tags` is selected under Accounting > Import, then More Features > Tags should show as `Enabled` (with lock icon) and `Tags` should show in the LHN. 

<img width="763" alt="image" src="https://github.com/user-attachments/assets/aa97f2ce-dd6a-466b-9b1f-5491442de82e">

## Actual Result:
When `Import as Tags` is selected under Accounting > Import,  More Features > Tags shows as `Disabled` (with lock icon) and `Tags` does not show in the LHN. 

<img width="590" alt="image" src="https://github.com/user-attachments/assets/ec144042-47f1-476a-8218-de65c08f6a51">

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/9fa67f00-febf-42a4-894b-75e791534fa5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856453961383871063</li>
        <li>Upwork Job ID: 1856453961383871063</li>
        <li>Last Price Increase: 2024-11-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Tags feature is disabled and not active  on the WorkspaceMoreFeaturesPage when a user has QuickBooks Online (QBO) connected. 
### What is the root cause of that problem?
I think this line is causing the issue:
https://github.com/Expensify/App/blob/580bf69714fcb90fbf96026b3e2fc12f4b556eeb/src/pages/workspace/WorkspaceMoreFeaturesPage.tsx#L213
### What changes do you think we should make in order to solve the problem?
I think we can change it to :
` isActive: (policy?.areTagsEnabled || hasAccountingConnection) ?? false,
`

**Comment by stephanieelliott** [comment]
Confirmed this seems buggy

**Comment by mananjadhav** [comment]
@stephanieelliott any reason this is a QBD specific bug? The reason I am asking is if Tags toggle should be enabled for the other connections?

**Comment by me-ZaidAli** [comment]
@mananjadhav are you guys still considering proposals for the issue?

**Comment by mananjadhav** [comment]
Yes open for proposals while I still have my outstanding question.

**Comment by stephanieelliott** [comment]
> @stephanieelliott any reason this is a QBD specific bug? The reason I am asking is if Tags toggle should be enabled for the other connections?

No, I bet this got labeled QBD because it was one of the QBD regression tests. But in general - if Tags toggle is enabled, it should show in Workspace settings. If disabled, it should not. That goes for all integrations.

**Comment by mananjadhav** [comment]
Still waiting for better proposals. I don't think adding accounting integration check is the correct solution.

**Comment by Shahidullah-Muffakir** [comment]
@mananjadhav, what are your thoughts on my updated [proposal](https://github.com/Expensify/App/issues/52133#issuecomment-2461090404)?

**Comment by mananjadhav** [comment]
Assigning an engineer here. I think this needs to be fixed on the backend.

🎀 👀 🎀 C+ reviewed.

**Comment by MariaHCD** [comment]
@stephanieelliott to clarify my understanding - for a workspace that is connected to any accounting integration (whether that's QBD or QBO or any other), the tags feature will be disabled and locked in `More features`. And so, in the `Accounting` settings, the tags feature should also be disabled and locked. Is my understanding correct?

@mananjadhav could you outline why you think this requires backend changes?

**Comment by MariaHCD** [comment]
Waiting on clarification on the above and then we can decide how to proceed here

**Comment by mananjadhav** [comment]
> for a workspace that is connected to any accounting integration (whether that's QBD or QBO or any other), the tags feature will be disabled and locked in More features. 

AFAIK it would depend on the accounting integration. For instance if Xero the tags are enabled then the More Features will show them enabled and locked.  

> could you outline why you think this requires backend changes?

The `areTagsEnabled` flag is supposed to be synced from Policy connection is populated from the backend. It could be backend or IS sync issue. May be I jumped too early but I feel this is something to be fixed from backend.

**Comment by mananjadhav** [comment]
@MariaHCD did you get a chance to look at my comment?

**Comment by MariaHCD** [comment]
I’m still unclear on the expected behavior in this scenario and would appreciate some clarification.

For the basic case, my understanding is:

> If the Tags toggle is enabled, it should appear in the Workspace settings. If disabled, it should not. This behavior applies to all integrations.

However, I’m uncertain about how this works when a policy is connected to an accounting integration. Specifically, does this mean that tags are automatically enabled? If so, should they be displayed as locked and enabled in the Workspace Settings page? Is there any integration-specific logic here? (I'm assuming not but wanted to check anyway)

cc: @stephanieelliott and @aldo-expensify (I understand you’ve worked on some of the backend logic related to enabling tags)

**Comment by aldo-expensify** [comment]
> cc: @stephanieelliott and @aldo-expensify (I understand you’ve worked on some of the backend logic related to enabling tags)

From testing manually with QBO (which I think should be the same), I see that `Tags` is enabled by default after connecting:

<img width="580" alt="image" src="https://github.com/user-attachments/assets/95ac7350-dfc2-4f85-b682-112ffd3b4ecf">

In QBO the defaults settings are set in the IS server here:

https://github.com/Expensify/Integration-Server/blob/9fbb26613c260101be30ef4c045c399dbb73cb25/src/expensify/quickbooksonline/QuickbooksOnlineImporter.java#L212-L213

I'm guessing that for QBD there should be something similar (should verify).

Then, in PHP, when we are storing the connection data for the first time we enable tags here:

https://github.com/Expensify/Web-Expensify/blob/b096b163a1313f07454405c8f508512befcea951/lib/PolicyAPI.php#L3890-L3891


This piece in PHP is only doing it for XERO and QBO, should it do it for all connections? or should we just add QBD there?

**Comment by stephanieelliott** [comment]
Sorry for the delay guys, I was out for Thanksgiving. I think we are snowballing on this issue though -- whether Tags are auto-enabled when you first connect is not really an issue, I think we can just assume that behavior is working as intended. 

The `Locked` behavior is also not a factor here -- Tags will always show the lock icon whether enabled or disabled. This is just because you can't modify the toggle from the `More Features` tab, Tags must be enabled/disabled from the `Accounting` tab. 

The actual bug is that **even when Tags are enabled, `Tags` doesn’t appear in the LHN and the More Features > Tags setting shows as Disabled**. This is a problem because it prevents users from viewing or modifying the Tags that were imported through the integration.

These images may help explain it a little better, but let me know if I can clarify this any further! 
 
### Current behavior: 

`Import as Tags` is selected under Accounting > Import, but More Features > Tags shows as `Disabled` and `Tags` does not show in the LHN. 

<img width="590" alt="image" src="https://github.com/user-attachments/assets/ec144042-47f1-476a-8218-de65c08f6a51">


### Expected behavior: 

 **if** `Import as Tags` is selected under Accounting > Import, **then** More Features > Tags should show as `Enabled` and `Tags` should show in the LHN. 

<img width="763" alt="image" src="https://github.com/user-attachments/assets/aa97f2ce-dd6a-466b-9b1f-5491442de82e">

**Comment by mananjadhav** [comment]
Thanks @stephanieelliott. This [comment](https://github.com/Expensify/App/issues/52133#issuecomment-2515834925) makes sense. Will you be able to update the GH issue body? I think the important step is that the Workspace > Import > Any of the options have `imported as tags`, yet the More Features > Tag shows `disabled` with lock. This should've been shown as `enabled` with lock.

I'll investigate this but also open for proposals now.

**Comment by stephanieelliott** [comment]
> I think the important step is that the Workspace > Import > Any of the options have imported as tags, yet the More Features > Tag shows disabled with lock. This should've been shown as enabled with lock.

Yep, exactly @mananjadhav! I will update the issue body to make this more clear

**Comment by stephanieelliott** [comment]
Just spot checked and it looks like this is still occurring. It is isolated to QBD though, not seeing it with other integrations.

**Comment by mananjadhav** [comment]
Yes because I checked Netsuite and Xero. It worked fine. I don't have QBD setup and I am setting it up. 

@stephanieelliott Would it be possible for you to share the policy JSON from your local browser? To verify the data + conditions we have.

**Comment by mananjadhav** [comment]
Still waiting for proposals.

**Comment by mananjadhav** [comment]
Still waiting for proposals.

**Comment by MariaHCD** [comment]
Not overdue - still awaiting proposals

**Comment by stephanieelliott** [comment]
Oooh I think this is fixed! Spot checked a handful customer accounts who just connected today, and all are showing`Tags` in the menu as intended: 

<img width="776" alt="image" src="https://github.com/user-attachments/assets/b14439fe-989f-4399-be8b-1005df8c6fdb" />

<img width="685" alt="image" src="https://github.com/user-attachments/assets/c1a423c7-0e20-4ec4-9ba3-42253b676459" />

**Comment by IuliiaHerets** [comment]
QA team can repro this issue in the latest build v9.0.80-2

https://github.com/user-attachments/assets/48fbb4fe-f1ea-40b8-bd77-bdadea461fc5

**Comment by MariaHCD** [comment]
Looks like the issue is still occurring. @stephanieelliott could you double check? 👀  Thanks!

**Comment by mananjadhav** [comment]
Yes. I think I had [mentioned](https://github.com/Expensify/App/issues/52133#issuecomment-2494753678) this earlier too. I think this needs to be fixed on the backend.

**Comment by stephanieelliott** [comment]
Hm, this is strange because it looks like it is not happening in actual customer accounts? This is a customer account where they just created the initial QBD less than 15 minutes ago:

<img width="753" alt="image" src="https://github.com/user-attachments/assets/dec8e721-7f9c-4ef1-89cc-9dcf91a51e56" />

<img width="810" alt="image" src="https://github.com/user-attachments/assets/4bbf438f-646d-4a8a-9884-72bcd467ad72" />

--

I wonder if this maybe has something to do with our QBD test environment? Like perhaps we don't have the relevant coding elements enabled or they are not importable for some reason. Let me see if I can get into our QBD test environment and I will have a look.

**Comment by mananjadhav** [comment]
Quick bump @stephanieelliott

**Comment by stephanieelliott** [comment]
I didn't get a chance to check this today -- will test tomorrow!

**Comment by stephanieelliott** [comment]
Ok I tested this in our QBD test environment and was able to reproduce the issue. This is so weird though, because it seems to only occur in the test environment and not in customers' production accounts.

@kadiealexander @francoisl – any ideas here? Could this be related to how our QBD test environment is configured?

**Here is a quick summary of what's happening:** 

After connecting to QBD and configuring coding, it it will not import the list of tags despite selecting `Import as Tags` in the config.

Weirdly, this behavior seems isolated to our QBD test environment -- customers' production accounts seem to be importing Tags just fine. For example, [here](https://app.codat.io/companies/a7818139-46dd-4d80-ad7a-2081300ebe58/summary) is a customer account who connection within the last 24h, Tags are importing and show in the LHN as expected.

**Comment by francoisl** [comment]
> Could this be related to how our QBD test environment is configured?

I doubt it. Our test environment behaves like any other QBD environment, there's nothing really specific to it.

> This is a customer account where they just created the initial QBD less than 15 minutes ago:

Any chance they connected to QBD from Classic? My guess without reading every comment above is that this is a NewDot-only bug.

**Comment by stephanieelliott** [comment]
Thanks @francoisl. That crossed my mind as well and I tried reproing both ways -- connecting via Classic then viewing in ND, and connecting via ND and viewing via ND. Both had the same issue, with the list (Items, in my test) not populating as Tags. Report fields worked fine though. 

Either way, if it's not our QBD environment causing the an issue then I suppose we consider this a legit bug that maybe is just not consistently reproducible.

**Comment by mananjadhav** [comment]
I still feel in this scenario that this needs to be internal. What do you think @francoisl ?

**Comment by francoisl** [comment]
Should be fixed on staging now, @lanitochka17 can you retest please?

**Comment by lanitochka17** [comment]
Issue is not reproducible on the build 9.0.91-2. Fixed

**Comment by lanitochka17** [comment]
Issue is not reproducible on the build 9.0.91-2. Fixed

**Comment by francoisl** [comment]
Great! I'm going to just close this then as it was handled internally.
