### ISSUE TITLE
Login - Onboarding modal does not appear when logging in with a new account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53284]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** htad26+dfgssdsddhgf@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Log in with a new gmail account

## Expected Result:
Onboarding modal appears when logging in with a new Gmail account

## Actual Result:
Onboarding modal doesn't appear when logging in with a new Gmail account. User is logged in to the account directly without the onboarding proccess

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d102ebc8-68f3-4af3-aa1d-2bdb5c444e59

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Cc @trjExpensify

**Comment by trjExpensify** [comment]
Ah, is this the bug you saw on dev only? 🤔

**Comment by trjExpensify** [comment]
Discussing in [this thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1732885655811369).

**Comment by trjExpensify** [comment]
Taking this over. Vit has a PR up.

**Comment by mountiny** [comment]
PR is merged, but we could not reproduce locally as this seems to be some production specific issue when user runs into a commit, this explains flakiness. hopefully this change will fix it

**Comment by mountiny** [comment]
This is fixed by auth PR

**Comment by Shahidullah-Muffakir** [comment]
@trjExpensify , @mountiny  I’m still experiencing this issue.
When signing up through expensify.com, the onboarding flow modal on new.expensify.com doesn’t always show up.

https://github.com/user-attachments/assets/7ec75729-7cab-4f79-ae7b-4f663bc8f3d1

**Comment by trjExpensify** [comment]
Interesting.... seems to be working for me. 


https://github.com/user-attachments/assets/79f3e615-482c-4352-bc81-64b7848a2ba1

**Comment by Shahidullah-Muffakir** [comment]
Hmm, I see. Thanks for confirming. It seems to work fine in staging but not in production.

When I sign up through staging.expensify.com and get redirected to staging.new.expensify.com, the onboarding flow modal appears as expected.

**Comment by trjExpensify** [comment]
Yeah, you're not the only one. It seems like we're getting mixed results.
