### ISSUE TITLE
Account - After log in with 'tester@applausecard.expensifail.com' the content does not load

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54159]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.76-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5346561
**Email or phone of affected tester (no customers):** tester@applausecard.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** All platforms and enviroments.
**App Component:** Other

## Action Performed:
1. Open the app or go to: staging.new.expensify.com
2. Log in with the acc:  tester@applausecard.expensifail.com

## Expected Result:
After logging in, the contents of the account are loaded.

## Actual Result:
After logging in the content of the account continues to load endlessly

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1728" alt="Bug6694346_1734189388657!Screenshot_2024-12-14_at_12 09 35_PM" src="https://github.com/user-attachments/assets/ea18579a-48a8-4b5d-a7ff-9f9447294ee1" />

https://github.com/user-attachments/assets/5cf8fe93-79e4-4f84-b912-bdd370201908

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by RachCHopkins** [comment]
This looks a LOT like https://github.com/Expensify/App/issues/53277

**Comment by RachCHopkins** [comment]
Ok https://github.com/Expensify/App/issues/53277 is fixed. @IuliiaHerets can we get a retest on this please?

**Comment by IuliiaHerets** [comment]
@RachCHopkins Issue is still reproducible in the latest build 

https://github.com/user-attachments/assets/6bd7fc38-2f8a-4897-98ab-44c729425fe2

**Comment by hannojg** [comment]
Hm, I wasn't able to reproduce on latest staging release with that same account 🤔 

![CleanShot 2024-12-31 at 16 52 03](https://github.com/user-attachments/assets/e205a714-4adf-4400-8bbe-5809c7b1ebd7)

When you start the app, can you please:

1. Open the dev tools
2. Click on the network tab (this starts recording network requests)
3. Log in, wait in the stuck screen for ~2min
4. In the network tab you can now press export (the little arrow down in the top bar), and share the HAR file with us here please?

**Comment by mallenexpensify** [comment]
Thanks @hannojg and @IuliiaHerets.  I [posted in #qa ](https://expensify.slack.com/archives/C9YU7BX5M/p1735865330063479?thread_ts=1735534020.225369&cid=C9YU7BX5M)
> [@Irina Zarutskaya](https://expensify.slack.com/team/U03V7GLL1QE)
.  Can you test one more time, following the details outlined [here](https://github.com/Expensify/App/issues/54159#issuecomment-2566553086)?
Thx

**Comment by izarutskaya** [comment]
Let me know if I can help something else

https://github.com/user-attachments/assets/6227a768-f9eb-49fa-bde6-186259221a75

[HAR file](https://applause-ts.slack.com/archives/C9YU7BX5M/p1735890157877099?thread_ts=1735534020.225369&cid=C9YU7BX5M)

**Comment by RachCHopkins** [comment]
@mallenexpensify there's discussion continuing [here](https://expensify.slack.com/archives/C05LX9D6E07/p1732753794274069) on this topic today.

**Comment by mallenexpensify** [comment]
@hannojg , 👀 above from the retest. 

Thanks @izarutskaya

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by RachCHopkins** [comment]
Thanks @mvtglobally, keep me posted on whether it says that way!

**Comment by muttmuure** [comment]
Single user account, testing, making LOW

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by RachCHopkins** [comment]
Ok I'm calling it. Please reopen if it continues.
