### ISSUE TITLE
chat-Code block message is not shown as bold text in preview

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#54857]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.81-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N
**Email or phone of affected tester (no customers):** N
**Issue reported by:** Applause Internal Team
**Device used:** Redmi note 10s Android 13
**App Component:** Chat Report View

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a chat 
3. Enter # `fahaha` jsjsjsj
4. Send the message

## Expected Result:
Code block message must be shown as bold text in preview.

## Actual Result:
Code block message is not shown as bold text in preview. But in conversation, code block text shown in bold.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c31a234d-8a79-4e26-8ccb-5dced2ae46f3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
Here's what it looks like on desktop
<img width="383" alt="image" src="https://github.com/user-attachments/assets/7ca1c3bc-0ad2-4054-a02d-0de1672f2b4c" />

and on iOS
<img width="436" alt="SnagitHelper2024 2025-01-07 17 59 02" src="https://github.com/user-attachments/assets/d78a8c3f-201f-4167-a7bf-aa9e8a74c32a" />

I'm unsure why iOS wouldn't show similar formatting as desktop for code blocks. @dubielzyk-expensify do you happen to know?

**Comment by dubielzyk-expensify** [comment]
I think the problem is that the iOS keyboard is adding a single quote character ' instead of the ` character. If you copy the ` character manually on iOS it still works. So I think the issue is that we're inserting the wrong character, but I'm confused as to why this changed? 

Tested it on Android and it works there with the right quote character, so I think that's the issue.

**Comment by mallenexpensify** [comment]
Thanks @dubielzyk-expensify , that makes sense (I've ran into related issues with quotes... forever).  
Do you think we want to 'fix' it? I'm unsure if we want to make changes that are platform specific.  But.. if it's the platform that's _making the changes_ then... maybe?

**Comment by dubielzyk-expensify** [comment]
I guess I'm just curious to find out if this changed? Cause I seemed to remember being able to make code blocks on iOS and now you can't? Maybe I remember wrong though. cc @Expensify/design to see what they think

**Comment by shawnborton** [comment]
Hmm good question, I can't remember either if this was ever a thing or if something changed. I agree with Jon's assessment though, this just might be a limitation of the iOS keyboard preventing the user from being able to do this via markdown.

**Comment by dannymcclain** [comment]
Ok that works for me. So basically we just need to make the composer match the final message state.

**Comment by mallenexpensify** [comment]
@dannymcclain good catch about `#` being added at the front, sorry I didn't clearly mention that before. 

 I updated the OP to 
## Expected Result:
Text in code block message should be the same font size as the rest of the text 

## Actual Result:
Font of text in code block message is smaller 

And added this screenshot
<img width="187" alt="image" src="https://github.com/user-attachments/assets/6e730d5a-44d7-4268-a3f1-1bbb496f3bb2" />

Is that what y'all are thinking for the Expected Behaviour?

**Comment by dubielzyk-expensify** [comment]
That sounds right to me

**Comment by mallenexpensify** [comment]
@Ollyws can you review @daledah 's proposal above? Thx

**Comment by shawnborton** [comment]
> Are we saying we want to remove/change the styling for the code block to match the rest of the text in all cases?

No, I think we just the inline code block portion to feel like it's closer in font size to the surrounding text. In the example you just showed, I think we're probably fine. 

But in this example, there's quite a big difference between the font styles:

![Image](https://github.com/user-attachments/assets/bf5cd75a-6762-4d62-a3f9-e0ced2648ebb)

In that second screenshot, I would expect:
- that the inline code appears bold, since the rest of the line is bold
- that the inline code has a slightly bigger font size, to match the heading style that it is wrapped in

Let me know if that makes sense, cc @Expensify/design for the gut check too!

**Comment by dannymcclain** [comment]
Yup, exactly what Shawn said!

**Comment by thienlnam** [comment]
cc @tomekzaw What do you think about the proposal?

**Comment by tomekzaw** [comment]
@thienlnam As for the proposal https://github.com/Expensify/App/issues/54857#issuecomment-2579140992, here's what I think:
* We can definitely add another item in `markdownStyle` to declare the desired formatting for inline code inside heading. 
* Since we already have `h1` key in `markdownStyle`, perhaps we should rename the new style to `codeInH1` or `codeInsideH1` for the sake of consistency? On the other hand, I don't really like having both `h1` and `H1` to be honest.
* I'm not sure if we need to specify `fontFamily`, `color` and `backgroundColor` separately. In Expensify these will be the same as for `code`. At this point I also don't see any use cases outside of Expensify. Perhaps customizing only `fontSize` should suffice?
* Speaking of `fontSize`, we also have `emoji.fontSize` style. If I follow correctly, this style also overrides the font size for emojis inside heading. Perhaps we should also consider adding `h1emoji.fontSize` style?
* By default, `h1` uses bold font weight but it looks like inline code inside heading is not bold. Can we also make sure that inline code nested in heading is also formatted in bold by default (like @shawnborton noticed in https://github.com/Expensify/App/issues/54857#issuecomment-2592260693)? There's also an edge case where inline code is nested in italic nested in heading – in that case, the inline code should be bold+italic.

**Comment by thienlnam** [comment]
Thanks for that, @daledah can you update your proposal to address those comments?

**Comment by thienlnam** [comment]
Yeah, please cover it as well

**Comment by mallenexpensify** [comment]
Bumping to $500 to help _inspire_ @daledah to prioritize. And/or to get additional proposals 😉

**Comment by mallenexpensify** [comment]
@daledah , think you'll be able to help here?

**Comment by HorusMabia** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Within a header, inline-code message is not shown as bold text in preview
Within a multiline blockquote, text between asterisks spanning multiple lines is not rendered as bold

### What is the root cause of that problem?
The text preview uses [react-native-live-markdown](https://github.com/Expensify/react-native-live-markdown) which styles the input field. 
To apply the style the input string is parsed in stages:
 markdown-> html -> tokens -> tree -> (processed)markdown + TextAndRanges 
TextAndRanges is a list of MarkdownRange  `{type: MarkdownType,  start: number,  length: number}`. [(markdownType)](https://github.com/Expensify/react-native-live-markdown/blob/149b3ee43d4e7f7d91085d29a776e8e7a59309ac/src/commonTypes.ts)

1. The inline code within a header isn’t bold because its styling overwrites the header styling

2. The multiline quote isn’t rendered in bold because the parser does not recognize the asterisk symbols as valid markdown syntax. This happens because the regex does not allow unpaired HTML tags within the asterisks. [regex](https://github.com/Expensify/expensify-common/blob/838857fb5f57ea226263418fdd869c2eda5ea0e4/lib/ExpensiMark.ts#L492)

### What changes do you think we should make in order to solve the problem?
A function that checks over MarkdownRanges for 2 things 
1 - if any code type is within a Header type MarkdownRange, and swaps it with codeInsideH1 as mentioned above. 
2- if any paired asterisks or other markdown symbols like _ for italics is found inside consecutive blockquotes and the correct MarkdownRange to the list 

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
Include tests with example markdown texts that contain common nested markdown elements (bold, italics, code, quotes etc...)

### What alternative solutions did you explore? (Optional)
1.Changing the regex
2.Changing the html
3.Changing the tree

I tried correcting the output of parseMarkdownToHTML by changing the value of [shouldKeepRawInput](https://github.com/Expensify/react-native-live-markdown/blob/149b3ee43d4e7f7d91085d29a776e8e7a59309ac/src/parseExpensiMark.ts#L34)  to get the desired HTML since interlaced tags work as intended with HTML like so: 
![Image](https://github.com/user-attachments/assets/37138645-435e-4eb5-bc93-912b15b9de73)
However this did not work as you cannot represent interlaced tags in a tree format. On the web interlaced HTML tags are resolved by closing and reopening the tag this result in the follow HTML:
![Image](https://github.com/user-attachments/assets/29b3ec7d-aa86-4dd2-a832-13b0e708e316)
Correcting the tree structure to match the above HTML caused inconsistencies between the processed markdown and the original input. If the two are different a parser error is thrown. In this case bypassing the error results in the folowing: 
![Image](https://github.com/user-attachments/assets/d672179e-04b1-48d7-96d8-999e5d9a98e3)
- Bold styling affects the chevron (which is meant to denote the start of a blockquote).
- The asterisk styling is applied to the wrong character due to the unaccounted blockquote syntax ("> ").
- Unexpected behavior when editing text, since the displayed styled text does not match the actual text.”

Note: It is possible to change the parsers and resolve these mismatched markdowns and styling errors however the fix would require a lot more changes.

**Comment by HorusMabia** [comment]
Contributor details
Your Expensify account email: horus.mabia@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0122dcdb84dcd21c77

**Comment by mallenexpensify** [comment]
Welcome @HorusMabia !  @Ollyws , 👀 above on their proposal plz. 

Unrelated, one of my heroes is named Horace, bit about him [here](https://www.nytimes.com/2013/06/19/realestate/commercial/as-coney-island-stirs-one-mans-vision-is-unbuilt.html?unlocked_article_code=1.w04.Se9K.PFF49kxhbEJ5&smid=url-share)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by ikevin127** [comment]
✅ Looks like **issue was fixed**, **not reproducible** anymore (Staging v9.0.98-7):

(my input for each comment)

```text
# `code` block

`code` *block*

`code` block
```

(result)

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/0a0210c2-0c65-4780-8468-9f12c9a57a70" />

##

✅ Regarding the mWeb / Native not typing the ( ` ) [backtick] character but ( ' ) [apostrophe] instead, that's not an Expensify issue, but rather a user issue because in order to type ( ` ) [backtick] you need to `hold the apostrophe until you get the pop up with four options and the backtick is on the left` (see how to video below).

<details>
<summary>How to</summary>

https://github.com/user-attachments/assets/097af037-4de7-4bfd-a9e9-c2e73a6357bb

</details>

##

⚠ The only issue here seems to be the code block font size when # (header / bold) markdown style is applied, which in the preview makes the code block font size look smaller than the non-code block text.

**Comment by mallenexpensify** [comment]
Thanks @ikevin127 going to close for now.  Let's either consider it fixed (or, I don't think this is high value or priority to keep working on  

<img width="298" alt="Image" src="https://github.com/user-attachments/assets/a19a93c0-e0d9-48ed-9b21-25a154d4f1fb" />

**Comment by HorusMabia** [comment]
The bug with the quote block is still reproducible. The original [issue](https://github.com/Expensify/App/issues/55293) was closed and meant to be fixed here. 

![Image](https://github.com/user-attachments/assets/0a05bc67-9952-4aad-bcca-4613ced5771e)
(also happens with italics)

**Comment by HorusMabia** [comment]
@mallenexpensify yes, that's what I understood this issue to be. Otherwise the preview doesn't reflect what happens once you send the message.

**Comment by mallenexpensify** [comment]
Thx @HorusMabia , I'm going to leave this closed. If anyone from the design team thinks we should fix it, please reopen.
