### ISSUE TITLE
[HOLD for payment 2025-01-21] [HOLD for payment 2025-01-18] [$500]  Hybrid Android - App overlaps with status bar when app is killed and relaunched

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54988]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.82-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** No, reproducible on hybrid only
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+010108kh@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Samsung Galaxy Z Fold 4 / Android 14
**App Component:** Other

## Action Performed:
1. Launch hybrid app.
2. Log in to a new Expensifail account.
3. After logging in, kill the app.
4. Relaunch the app.
5. Kill app and relaunch app several times because sometimes app launches without issue.

## Expected Result:
App will not overlap with status bar after killing app and relaunching app.

## Actual Result:
App overlaps with status bar after killing app and relaunching app.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/39b917ba-9142-4f9f-874f-a3733820b15b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021877375704795838083</li>
        <li>Upwork Job ID: 1877375704795838083</li>
        <li>Last Price Increase: 2025-01-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by mountiny** [comment]
@pecanoro does it happen reliably? You can still click the buttons right?

Definitely not a good UX if its shifted

Gonna ask swm to look into this

**Comment by pecanoro** [comment]
@mountiny I can't open the menus on the top, I am stuck, so pretty unusable

**Comment by pecanoro** [comment]
I think it might be due to https://github.com/Expensify/App/pull/51475 but I am not fully sure since I am having trouble testing it

**Comment by WoLewicki** [comment]
I saw this issue some time ago while working on `0.76` so it is most probably connected. At some point I stopped seeing this so I thought that it is fixed but seems like it is just much less frequent now. But yeah, most probably #48911 is the cause.

**Comment by jayeshmangwani** [comment]
@shubham1206agra Yes We have a similar issue when opening the app from a notification here https://github.com/Expensify/App/issues/48190, and I can reliably reproduce that issue. 

However, the current issue that occurs when opening the app normally is not reproducible on my end.

**Comment by pecanoro** [comment]
The problem is that forcing stopping the app doesn't fix it either. Logging out doesn't work either. So I am going to try uninstalling and installing again

**Comment by s77rt** [comment]
We also merged https://github.com/Expensify/App/pull/54961 which could be related

**Comment by pecanoro** [comment]
This is coming from a comment in Slack. After trying different things, it seems the old app in the hybrid app is broken for me forever, no matter what I try. However, if I am really precise, I can open the top right menu and open the new app. What is interesting is that the new app is not always broken and it's much harder to reproduce there as you all mentioned.

**Comment by mountiny** [comment]
No 9 dollars more for you :D

**Comment by thienlnam** [comment]
Demoting this based on the internal conversation [here](https://expensify.slack.com/archives/C07NMDKEFMH/p1736468107010579?thread_ts=1736463110.960229&cid=C07NMDKEFMH)

**Comment by pecanoro** [comment]
@thienlnam Why though? This makes hybrid completely unusable for Android users and there is no work around

**Comment by mountiny** [comment]
Asked for a retest

**Comment by kavimuru** [comment]
Bug is not reproducible

https://github.com/user-attachments/assets/6c11b724-eae2-465b-9d4b-45dc3fe8372f

**Comment by pecanoro** [comment]
The oldApp of the hybrid app is still broken for me, but I can report it as a different bug

**Comment by WoLewicki** [comment]
I think the OD is being worked on in different PR but for sure would be best to have a repro @pecanoro so it can be tested to see if it is indeed fixed.

**Comment by pecanoro** [comment]
@WoLewicki It's always broken for me, when I open the app, it looks like this:

![Image](https://github.com/user-attachments/assets/a4f83f8d-633d-4b08-8590-b6442421cf87)

(I checked the version, it's updated to the lastest one)

**Comment by pecanoro** [comment]
@ZhenjaHorbach Good to know! I restarted the android hybrid GH action, maybe it will work this time, we will see

**Comment by pecanoro** [comment]
Nah, it failed again, it will have to be uploaded manually

**Comment by cristianobrocheir** [comment]
Hi there! Got another user reporting the issue:

mschuler@scoposhg.com
https://www.expensify.com/concierge/#/chat/6747603

![Image](https://github.com/user-attachments/assets/f76f7905-f3f4-4be6-a2aa-4cf1e102bf8e)

**Comment by pecanoro** [comment]
My phone is on 9.0.84-4, so I think it's not fixed even if the production build failed

**Comment by mountiny** [comment]
cc @chrispader and @kirillzyusko for visibility

**Comment by AndrewGable** [comment]
I agree, this seems to be limited to Android 15.

**Comment by Julesssss** [comment]
@ZhenjaHorbach I don't think either are the correct fix yet. Thanks for trying mine though! I'm going to close it.

**Comment by mountiny** [comment]
Confirmed fix in staging

**Comment by pecanoro** [comment]
I don't think this needs payment so closing

**Comment by pecanoro** [comment]
@ZhenjaHorbach Can you link it? I couldn't find it, that's why I closed it, but it was a long issue so I probably missed it.

**Comment by pecanoro** [comment]
Oh I see it [here](https://github.com/Expensify/App/pull/55082)! It wasn't showing as approved, so I thought you didn't review it, but now I see the checklist.

**Comment by pecanoro** [comment]
@isabelastisser $250 for @ZhenjaHorbach [here](https://github.com/Expensify/App/issues/54988#issuecomment-2604074844)!

**Comment by isabelastisser** [comment]
Offer sent in Upwork to @ZhenjaHorbach. All set!
