### ISSUE TITLE
[HOLD for payment 2025-01-18] [HOLD for payment 2025-01-17] Hybrid - Android - Onboarding - "Travel and expense, at the speed of chat" modal appears after every login

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#55021]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.82-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/54972
**Issue reported by:** Applause Internal Team
**Device used:** Samsung S23FE/ Android 14
**App Component:** Other

## Action Performed:
Setup:
It can be run on the Web (https://staging.expensify.com)
1. Sign in to a new account on OldDot
2. Create a workspace
3. Create a report with expenses and submit it
4. Run this script in the browser console:
`NVP.set('tryNewDot', {classicRedirect: {dismissed: true, completedHybridAppOnboarding: false}, nudgeMigration: {timestamp: '2024-01-07'}});`

Steps:
1. Open the Expensify app
2. Sign in to the same account registered in the setup
3. Switch to NewDot
4. Confirm that the "Travel and expense, at the speed of chat" modal is displayed
5. Tap on "Let's go!"
6. Log out and log in again

## Expected Result:
The "Travel and expense, at the speed of chat" modal only appears after the first login for migrated accounts.

## Actual Result:
The "Travel and expense, at the speed of chat" modal appears after every login in migrated accounts.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0cfab34d-e0bc-482a-a2a2-58e0690f70a1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by aldo-expensify** [comment]
Seems like this is getting fixed by https://github.com/Expensify/App/pull/55005, so this doesn't look like a `DeployBlocker`

**Comment by blimpich** [comment]
Just merged the PR, will wait to see that CP-ed and then retest this

**Comment by blimpich** [comment]
Asked for retest here: https://expensify.slack.com/archives/C9YU7BX5M/p1736454070227579

**Comment by kavimuru** [comment]
Reproducible in 9.0.82-5 

https://github.com/user-attachments/assets/4be98f92-9589-4aee-8052-be97c6b92325

**Comment by thienlnam** [comment]
Should be resolved in 9.0.82-6

**Comment by blimpich** [comment]
@thienlnam tester has it still not working: https://expensify.slack.com/archives/C9YU7BX5M/p1736463627682619?thread_ts=1736454070.227579&cid=C9YU7BX5M

Should we keep the deploy blocker label?

**Comment by thienlnam** [comment]
Oh hmm @rayane-djouah @allroundexperts @puneetlath, looks like https://github.com/Expensify/App/pull/55005 didn't fix this

**Comment by blimpich** [comment]
Conversation is ongoing in slack here: https://expensify.slack.com/archives/C01GTK53T8Q/p1736464127120649?thread_ts=1736444631.474489&cid=C01GTK53T8Q

**Comment by Christinadobrzyn** [comment]
I believe this is a regression of https://github.com/Expensify/App/issues/54915#issuecomment-2599673495, correct? 

So payment would only be made - https://github.com/Expensify/App/issues/54915#issuecomment-2599673495
