### ISSUE TITLE
[$250] Expense - Next step still shows "Waiting for admin to pay" when pay button is hidden

### ISSUE THREAD

**Issue by jponikarchuk** [Expensify/App#58298]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.12-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+ps309@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Delayed submissions and Add approvals features are enabled.
- User has a negative amount expense created on Old Dot.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click on the expense preview.
4. Click Submit.
5. Click Approve.

## Expected Result:
Next step will show "No further action required".

## Actual Result:
Next step shows "Waiting for an admin to pay expense(s)."

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a456fc14-e406-4ba2-99ef-5c600c8bf750

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021903039185107417763</li>
        <li>Upwork Job ID: 1903039185107417763</li>
        <li>Last Price Increase: 2025-03-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by sonialiap** [comment]
Asking for a retest, this might have been solved by https://github.com/Expensify/App/pull/57983

**Comment by izarutskaya** [comment]
Still reproducible in offline mode
 

https://github.com/user-attachments/assets/d52d5922-f9ab-4eec-a1f3-a9cacd274528

**Comment by sonialiap** [comment]
Thanks Irina!

**Comment by sonialiap** [comment]
@youssef-lr do you think this is related to the issue you were working on here https://github.com/Expensify/App/issues/56121#issuecomment-2733197495?

**Comment by youssef-lr** [comment]
Just a note, we will bring back the pay button but only "elsewhere", no ACH, when the report has a negative total. PR here https://github.com/Expensify/Web-Expensify/pull/46030

**Comment by m-natarajan** [comment]
Able to reproduce only in offline mode 

https://github.com/user-attachments/assets/52d9fcc2-9436-41a6-bc32-a01ab96a1307

**Comment by sonialiap** [comment]
@youssef-lr based on m-natarajan's test looks like we're still queuing the negative report for payment in offline mode. Is this something that we'll be changing in your update?

**Comment by youssef-lr** [comment]
I'll fix this issue in the same PR

**Comment by sonialiap** [comment]
@youssef-lr do you mean this PR https://github.com/Expensify/Web-Expensify/pull/46030? Or since that one was merged two weeks ago, do you have a new one?

**Comment by youssef-lr** [comment]
Sorry was OOO. I'll get back to this issue tomorrow @sonialiap

**Comment by sonialiap** [comment]
@youssef-lr any updates?

**Comment by youssef-lr** [comment]
Working on the fix now @sonialiap

**Comment by youssef-lr** [comment]
PR in progress, will be in review today.

**Comment by sonialiap** [comment]
@youssef-lr how's the PR review going?

**Comment by youssef-lr** [comment]
Sorry got caught up with an other high priority PR, I'm on it again today.

**Comment by sonialiap** [comment]
@youssef-lr any progress on this issue?

**Comment by youssef-lr** [comment]
Still working on higher priority stuff, I'll try to get to it today or Monday.

**Comment by sonialiap** [comment]
@youssef-lr I don't think the offline mode fix PR was ever linked to this issue. Could you share the link to it please?

**Comment by youssef-lr** [comment]
@sonialiap just linked it. Will finish it up this week!

**Comment by sonialiap** [comment]
@youssef-lr thanks for the link. How's the PR going?

**Comment by sonialiap** [comment]
Thanks!

**Comment by youssef-lr** [comment]
Sorry haven't managed to get to this yet, I'm super busy with the F1 tracking pixels that need to be live early next week.

**Comment by youssef-lr** [comment]
No update yet

**Comment by sonialiap** [comment]
Back from OOO @jliexpensify feel free to unassign yourself if you'd like

**Comment by youssef-lr** [comment]
I'm going to have time for this starting Thursday.

**Comment by sonialiap** [comment]
@youssef-lr were you able to spend some of your free time on this issue?

**Comment by jliexpensify** [comment]
Unassigning myself as Sonia is back

**Comment by youssef-lr** [comment]
Still focusing on higher priority issues as we don't support negative expense in NewDot yet.

**Comment by youssef-lr** [comment]
I'll get to this this week probably the by the end of it.

**Comment by youssef-lr** [comment]
Same

**Comment by youssef-lr** [comment]
Raising a PR this week since I have spare cycles
