### ISSUE TITLE
Expense Reports - Hold violation appears and disappears when p2p expense is held

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#58856]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.16-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kok1@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3 / Chrome
**App Component:** Search

## Action Performed:
Precondition:
- Log in with Expensifail account.

1. Go to staging.new.expensify.com
2. Go to FAB > Create expense > Manual.
3. Submit an expense to any user (not workspace chat).
4. Go to expense report.
5. Click on the report header > Hold.
6. Enter reason and save it.
7. Go to Reports > Expense Reports.
8. Click on the expense report from Step 3.

## Expected Result:
Hold violation will persist on the expense row.

## Actual Result:
Hold violation appears and disappears on the expense row.

This issue only happens with p2p expense. For workspace expense, the hold violation persists.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1e5be445-86b7-486b-948e-b96849dfd6f6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by vincdargento** [comment]
@jliexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by luacmartins** [comment]
This view is behind a beta. NAB. @Kicu

**Comment by jliexpensify** [comment]
Not overdue, @Kicu is working on this

**Comment by DylanDylann** [comment]
Not overdue. @Kicu is working on it

**Comment by trjExpensify** [comment]
>@Kicu is working on it

was it actually addressed in https://github.com/Expensify/App/pull/58903, or coming as a follow-up?

**Comment by trjExpensify** [comment]
@DylanDylann can you confirm on the Q above.

**Comment by Kicu** [comment]
I _think_ this is not yet fixed and will require another fix. 
However I would like to put this on HOLD for https://github.com/Expensify/App/pull/59433 - because in this PR @jnowakow is modifying the transaction table and changing some logic related to selecting them.
I think a better time to fix this violation would be after we merge the other PR.

**Comment by jliexpensify** [comment]
Other PR is deployed to staging now!

**Comment by Kicu** [comment]
Me or someone else from the team will soon verify whether this is indeed fixed

**Comment by Kicu** [comment]
@borys3kk is looking into this.

**Comment by borys3kk** [comment]
Hi, today I investigated this issue and this is what I found:

- it doesn't matter from where I created hold, it disappeared always after adding another transaction to iou report, the problem is that the backend returns null for all transaction violations (as in attached screenshot 1 below)

<img width="792" alt="Image" src="https://github.com/user-attachments/assets/adad3746-4cb5-48a3-b112-60a22df1946b" /> 

<p align="center">Screenshot 1.</p>

- The difference between hold for IOU and workspace requests is negligible (left IOU, right workspace, screenshot 2)

<img width="2038" alt="Image" src="https://github.com/user-attachments/assets/08aa5abb-4158-4247-b8f9-f43dcfa1b026" />

<p align="center">Screenshot 2.</p>

- The issue was only reproducible on dev backend, I wasn't able to reproduce it on staging one (i tried reproducing it both on staging and on local development)


https://github.com/user-attachments/assets/de529856-12c0-4733-9561-f879898b8abe

<p align="center">Video 1.</p>

https://github.com/user-attachments/assets/8e0d653a-94c3-40dd-932b-7508a8e120d3

<p align="center">Video 2.</p>

Testing steps if someone want to reproduce it:
- create expense in iou chat
- create another expense in the same chat
- go to reports > expense reports > click on the report with these two expenses
- in table view hold one of them
- it can persist for a bit or disappear almost immediately
- if you add another expense from this view all holds disappear (the moneyRequest gets nulled reportViolations data it can be seen on ss 1.)

Summary:
- There probably is an issue on dev backend that causes all report violations in IOU report to be nulled
- We could handle these state changes (hold violation not visible here) in our components by checking not the reportViolations_xxx data but the comments for each violation - this technique is used in other components for example in moneyRequestPreview
- This is NOT reproducible on expense reports in workspaces (video 2)

**Comment by luacmartins** [comment]
I imagine this might be related to the violations beta and why this doesn't happen in staging/prod. I couldn't tell why the violations are null from a quick glance at the code though.

**Comment by jliexpensify** [comment]
Just a heads up that I am OOO until the 30th but will fix up any payments when I'm back.

**Comment by borys3kk** [comment]
Hi this is not overdue, still waiting for BE investigation :)

**Comment by mountiny** [comment]
Investigation pending!

**Comment by jliexpensify** [comment]
Not overdue!

**Comment by luacmartins** [comment]
Not yet. I'll investigate this today.

**Comment by luacmartins** [comment]
I'm not able to reproduce this anymore

https://github.com/user-attachments/assets/fef519ba-fe61-4f63-b129-ddb6f79910e6

**Comment by trjExpensify** [comment]
Reckon it was a bug because of the broken one expense report view then probably: 

<img width="1112" alt="Image" src="https://github.com/user-attachments/assets/6d57d3c9-9703-4f37-9332-d5dbf0186ac1" />

**Comment by trjExpensify** [comment]
Yeah, same. Closing! 

https://github.com/user-attachments/assets/7a2fa3a8-e887-4768-b7ec-fc4ae25b806b

**Comment by luacmartins** [comment]
Nice!
