### ISSUE TITLE
[Due for payment 2025-04-23] [Due for payment 2025-04-16] [Report Creation UI] Follow up tasks

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#59295]
There is could of follow up tasks to handle after this PR is merged that we are aware off https://github.com/Expensify/App/pull/58795
- [x] There is option to `Create Report` in FAB when no workspaces are present https://github.com/Expensify/App/pull/59386
- [x] No create report option in workspace chat https://github.com/Expensify/App/pull/59386
- [x] New expenses added from the report view page doesn't get updated in the table of the report view.
- [x] No option to add expense if report is created offline https://github.com/Expensify/App/pull/59386
- [x] ~Expense tab is highlighted when report is opened in the search page~ - taken care of in another PR. 
- [x] Add test for NextStepsUtils to cover the empty report case https://github.com/Expensify/App/pull/59386
- [x] Assert in the test for QAB that correct chatReportID was added by optimistic action @SzymczakJ 

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by SzymczakJ** [comment]
WIP I'll give it out for review soon.

**Comment by trjExpensify** [comment]
Melv, go away. Jakub has a draft PR up: https://github.com/Expensify/App/pull/59386

**Comment by mountiny** [comment]
@SzymczakJ I believe all of the points were addressed in https://github.com/Expensify/App/pull/59386 but just wanted to check in that is the case with you too and then we can close this one

**Comment by SzymczakJ** [comment]
I believe @allgandalf found a way to repro **"No option to add expense if report is created offline"**, which I wasn't able to reproduce, so that's the only issue not resolved.
But as we stated in https://github.com/Expensify/App/pull/59386#pullrequestreview-2743664591 we will fix these things in another follow up, so if there's one we can move **"No option to add expense if report is created offline"** to it.

**Comment by mountiny** [comment]
@SzymczakJ Lets just use this issue for that, once you have a PR for it or if we can export this with reproduction steps, just let me know

**Comment by mountiny** [comment]
All points should be fixed so we can close now, thanks 🎉
