### ISSUE TITLE
[Due for payment 2025-05-20] [$250]Report - Not Found page is displayed when opening user's chat after paying invoice

### ISSUE THREAD

**Issue by jponikarchuk** [Expensify/App#60253]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.28-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+0808aofuo@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** MacOS Chrome, Desktop
**App Component:** Chat Report View

## Action Performed:
Precondition:
* User A has a workspace with invoicing enabled. (User A: c.dobrzyn+45@expensifail.com)
* User B does not have any workspace. (User B: c.dobrzyn+1241241@expensifail.com)
* User A and B do not have chat history with each other.

1. [User A] Send an invoice to User B.
2. [User B] Go to Reports > Chats.
3. [User B] Click Pay.
4. [User B] Click Pay as business > Pay elsewhere.
5. [User B] Click on the workspace avatar > Members > Click on User A’s profile > Click on Message button

## Expected Result:
User B should be navigated to a chat with user A

## Actual Result:
Not found page is displayed, and an undefined value is displayed in the URL

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bed8d1b2-18ae-4505-98b8-f65c298adf1c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021914790682113304013</li>
        <li>Upwork Job ID: 1914790682113304013</li>
        <li>Last Price Increase: 2025-04-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not found report when we press the message button after receiving invoice.

### What is the root cause of that problem?
When we receive the invoice and then press the Message button on the new user profile page, we call `navigateToAndOpenReportWithAccountIDs`.
https://github.com/Expensify/App/blob/bd8186e7a8c31ce8854d524559f2e98685d2fd2d/src/libs/actions/Report.ts#L1300-L1312

It first finds the existing chat between the users, and if not found, it will create a new report. In our case, we don't have it yet, but `getChatByParticipants` returns a result, but the report object doesn't have the `reportID`, basically the data is incomplete. The data is received from the Pusher when receiving the invoice.

Since the reportID is undefined, we are navigated to the `r/undefined` page.

### What changes do you think we should make in order to solve the problem?

We need to also check whether the report has reportID or not to decide whether we want to create a new report or not.
```
const chat = getChatByParticipants([...participantAccountIDs, currentUserAccountID]);
if (!chat?.reportID) {
    newChat = buildOptimisticChatReport({
        participantList: [...participantAccountIDs, currentUserAccountID],
    });
}
const report = newChat ?? chat;
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

We can test by calling `navigateToAndOpenReportWithAccountIDs` and make sure `navigateToReportWithPolicyCheck` is called with a report object that has the `reportID`, even though `getChatByParticipants` returns an incomplete report data.

**Comment by RachCHopkins** [comment]
Sorry, I'm OOO until the 28th and I haven't had time to triage this yet. Reassigning.

**Comment by Christinadobrzyn** [comment]
I can't get this to work, I think everything is broken today in NewDot. I'll try on Monday

**Comment by Christinadobrzyn** [comment]
Okay, I got this to work. I think it is resolved, I was routed to the chat with User A when clicking the message. I'll ask QA to test.

**Comment by Christinadobrzyn** [comment]
@bernhardoj are you still getting this error?

**Comment by IuliiaHerets** [comment]
Issue is still reproducible

https://github.com/user-attachments/assets/266007c2-1cc2-4c7f-b6a0-7ba156589b98

**Comment by Christinadobrzyn** [comment]
@mananjadhav, can you check this proposal when you have a moment? https://github.com/Expensify/App/issues/60253#issuecomment-2804447219

**Comment by mananjadhav** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/60253#issuecomment-2804447219) looks good to me.


🎀 👀 🎀 C+ reviewed.

**Comment by mallenexpensify** [comment]
@lakchote 👀 plz. 
making LOW on `#quality` project , hoping we'll have a PR soon.

**Comment by lakchote** [comment]
@bernhardoj's proposal LGTM.

**Comment by bernhardoj** [comment]
@mananjadhav @lakchote may I know which solution to use? The main or the alternative?

I kinda like the alternative because the incomplete report object that is received from the Pusher is the invoice transaction thread, and currently, `getChatByParticipants` returns it. Even though the main solution still ignores it because it doesn't have `reportID`, using the alternative solution prevents `getChatByParticipants` from returning that report in the first place.

_The only concern I have is whether there is a case where the policyID field is missing from DM_

**Comment by mananjadhav** [comment]
> The only concern I have is whether there is a case where the policyID field is missing from DM

I think the main solution is cleaner. But I think @lakchote can best answer this question and their recommendation too.

**Comment by bernhardoj** [comment]
> I prefer the alternative solution but you'll have to modify your check see:
> If the report's policyID is _FAKE_  or has no value, then we can consider it a DM.

Thanks! I'll prepare the PR now.

**Comment by bernhardoj** [comment]
PR is ready

cc: @mananjadhav

**Comment by Christinadobrzyn** [comment]
monitoring PR https://github.com/Expensify/App/pull/61089

**Comment by Christinadobrzyn** [comment]
@mananjadhav Do we need a regression test?

**Comment by Christinadobrzyn** [comment]
@mananjadhav do we need a regression test?

**Comment by Christinadobrzyn** [comment]
Just a heads up that I'm going to be ooo May 21st - May 27th. Back on the 28th.

I'll assign someone to pay this. Payment summary - https://github.com/Expensify/App/issues/60253#issuecomment-2893410792

We're just waiting on the regression test step.

**Comment by twisterdotcom** [comment]
Starring @mananjadhav for the checklist.

**Comment by mananjadhav** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:
- We need a new user and an existing user.

### Test:

1. [User B] Sign up as a new user
2. [User B] Create a new workspace and enable invoices
3. [User B] Send an invoice to User A
4. [User A] Open the invoice room
5. [User A] Press the report header > Members
6. [User A] Press the User B
7. [User A] Press Message on the profile page
8. [User A] Verify the User B chat is open


Do we agree 👍 or 👎

**Comment by mananjadhav** [comment]
@Christinadobrzyn @twisterdotcom I think it makes sense to add a regression test for this one. Suggested one from the PR. I haven't been able to spend time on finding the offending PR. 

Will do try to do that. Meanwhile @bernhardoj do you have any idea on the offending PR?

**Comment by bernhardoj** [comment]
Based on my root cause, I don't think there is an offending PR. The `isOneOnOneChat` logic is quite old. I think it's more of an issue that has recently been noticed by QA when performing the test steps where the user receives the incomplete report data.

<img width="626" alt="Image" src="https://github.com/user-attachments/assets/5bc2c218-bfed-4517-99a1-ef262f766e6a" />

**Comment by twisterdotcom** [comment]
Payment Summary:

- Reviewer: @mananjadhav owed $250 via NewDot
- Reviewer: @bernhardoj owed $250 via NewDot

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav
