### ISSUE TITLE
[DUE FOR PAYMENT 5/20] [$250] Login - Not able to log in with a new account while navigating to public room as anon user

### ISSUE THREAD

**Issue by jponikarchuk** [Expensify/App#60566]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.1.30-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5967397&group_by=cases:section_id&group_order=asc&group_id=229066
**Email or phone of affected tester (no customers):** n/a
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.3.2/Safari, iPhone 13 18.3.2/Safari
**App Component:** Other

## Action Performed:
1.Log out of New Expensify
2.Navigate to this link - https://staging.new.expensify.com/r/2091104345528462
3.Verify you can see the room as an anonymous user
4.Click on Sign In or any other action that should not be allowed to an unauthenticated user
5.Verify you're redirected to the Sign In page
6.Log in with a new account

## Expected Result:
The onboarding flow appears after sign in

## Actual Result:
Not able to log in with a new account while navigating to public room as anonymous user. After entering a new email, the MC input is displayed, but the MC doesn't arrive to the inbox. After requesting a new MC, there is an error message "There was an error. Please try again. If the issue persists, please reach out to concierge@expensify.com".

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/44b87101-6672-43a3-b2b2-795162945845

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021915132779694893213</li>
        <li>Upwork Job ID: 1915132779694893213</li>
        <li>Last Price Increase: 2025-04-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JS00001</details>

**Comment by kpadmanabhan** [comment]
@jponikarchuk : unable to reproduce the issue. Email with MC comes fine for me on staging. Are you still able to reproduce this issue? Could it be that staging was fixed in the meantime?

![Image](https://github.com/user-attachments/assets/cab21796-df51-45bd-a185-999f5d7efd62)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Login with new account as anonymous user shows MC view instead of sign up view.

### What is the root cause of that problem?
Sign up view is shown based on this condition.
https://github.com/Expensify/App/blob/7a42c6afc78bff6a67d7e1b2193e9c738a3311cd/src/pages/signin/SignInPage.tsx#L114

Everything is true except `!isAccountValidated`. `isAccountValidated` in this case is true, so it becomes false. The account validated state comes from this temp hook.
https://github.com/Expensify/App/blob/7a42c6afc78bff6a67d7e1b2193e9c738a3311cd/src/hooks/useAccountValidation.tsx#L4-L12

It checks both user and account `validated`. In anonymous user case, `user.validated` is true, so the hook also returns true.

### What changes do you think we should make in order to solve the problem?

Instead of using `||`, we should use `??`, so we will check `account.validated` first and only fallback if it's undefined.

OR

Don't use the hook and use `account.validated` directly.

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

N/A

**Comment by jponikarchuk** [comment]
@kpadmanabhan Tester can still reproduce this issue. We can receive a MC when try to log in with an existing user. But when we enter a new email, the MC input appears instead of an onboarding flow.

https://github.com/user-attachments/assets/b92df406-e3e8-4c02-b219-b5e93170a768

**Comment by CortneyOfstad** [comment]
Getting eyes on this!

**Comment by JS00001** [comment]
Looks good, I've assigned to you @bernhardoj

**Comment by CortneyOfstad** [comment]
PR is actively moving!

**Comment by JS00001** [comment]
This is deployed to prod

**Comment by CortneyOfstad** [comment]
Not sure what happened here, but let's get this paid!

@thesahindia can you complete the checklist to see if a regression test is needed? Thanks!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@bernhardoj — to be paid $250 via NewDot
@thesahindia — to be paid $250 via NewDot

## Regression Test 
https://github.com/Expensify/Expensify/issues/503881

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
