### ISSUE TITLE
[$500] [Due for payment 2025-05-22] [Simplified Actions] FOLLOWUP: Add Primary and Secondary actions to report previews and header

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#60852]
Let's use this issue to track any follow ups from https://github.com/Expensify/App/pull/59999

### Needs work
- [x] Remove beta flag and delete `*HeaderOld.tsx` files

### In review
- [x] https://github.com/Expensify/App/issues/61092
- [x] https://github.com/Expensify/App/issues/59876
- [x] https://github.com/Expensify/App/issues/60914
- [x] https://github.com/Expensify/App/issues/61019
- [x] https://github.com/Expensify/App/issues/60911
- [x] https://github.com/Expensify/App/issues/60912
- [x] https://github.com/Expensify/App/issues/60913
- [x] https://github.com/Expensify/App/issues/61005
- [x] https://github.com/Expensify/App/issues/59905
- [x] https://github.com/Expensify/App/issues/59893

### Fixed
- [x] https://github.com/Expensify/App/issues/59890
- [x] https://github.com/Expensify/App/issues/59927
- [x] https://github.com/Expensify/App/pull/61049#discussion_r2066672411

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021927410316859179861</li>
        <li>Upwork Job ID: 1927410316859179861</li>
        <li>Last Price Increase: 2025-05-27</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@jnowakow @borys3kk I retested all issues reported by QA and added the ones that are still reproducible to the OP. @borys3kk has a draft PR to address a few of them already. It seems like one of them is coming from the BE so I'll take a look at that one. @jnowakow could you pick one of the other issues that are not addressed yet and work on a PR for it please?

**Comment by jnowakow** [comment]
@luacmartins  https://github.com/Expensify/App/issues/60913 is also fixed by @borys3kk in his PR

**Comment by jnowakow** [comment]
@luacmartins I've opened PR for https://github.com/Expensify/App/issues/59927 - it's here https://github.com/Expensify/App/pull/60957

**Comment by jnowakow** [comment]
@luacmartins I think https://github.com/Expensify/App/issues/59905 was fixed by some search related changes
![Image](https://github.com/user-attachments/assets/6c1877ab-59e9-4673-8243-e01bf5d1af08)

**Comment by jnowakow** [comment]
@luacmartins for https://github.com/Expensify/App/issues/59876 I'm getting this error when trying to move IOU report to workspace:
![Image](https://github.com/user-attachments/assets/1ba9edca-4384-4eb2-aaf0-27822cdd60a4)

I think it's backend issue 🤔

**Comment by trjExpensify** [comment]
>@luacmartins for https://github.com/Expensify/App/issues/59876 I'm getting this error when trying to move IOU report to workspace:

Doesn't Carlos have a draftPR up for this one here: https://github.com/Expensify/App/pull/60872

**Comment by luacmartins** [comment]
Yea, I'll address that one in my PR

**Comment by trjExpensify** [comment]
Sounds good!

**Comment by jnowakow** [comment]
@luacmartins is this https://github.com/Expensify/App/pull/61049#discussion_r2066672411 connected to this project? 😅

**Comment by borys3kk** [comment]
Hi
Regarding the remaining issues:
$ https://github.com/Expensify/App/issues/59876 is taken caren by you Carlos
$ https://github.com/Expensify/App/issues/59905 was fixed as stated in this comment: $ https://github.com/Expensify/App/issues/60852#issuecomment-2835084439
$ https://github.com/Expensify/App/issues/59893 was fixed in my [pr](https://github.com/Expensify/App/pull/60891)
$ https://github.com/Expensify/App/issues/61092 is I think expected behaviour but waiting for response from tester if it's a bug I will take care of this
$ https://github.com/Expensify/App/pull/61049 fixed by you Carlos
$ https://github.com/Expensify/App/issues/61019 you're taking care of this on as well
so all in all I think all issues from this follow up are lookef after :)

**Comment by luacmartins** [comment]
>@luacmartins is this https://github.com/Expensify/App/pull/61049#discussion_r2066672411 connected to this project? 😅

Not really, but I think it's a cleanup item that we should address sooner rather than later. It's at the bottom of the list priority wise though

**Comment by luacmartins** [comment]
> https://github.com/Expensify/App/issues/59905 was fixed as stated in this comment: $ https://github.com/Expensify/App/issues/60852#issuecomment-2835084439

I can still reproduce this issue following the steps in the OP (except for the gmail part)

https://github.com/user-attachments/assets/337d9dc7-c001-4fb9-ac49-8ed31d91d001

**Comment by luacmartins** [comment]
>https://github.com/Expensify/App/issues/61092 is I think expected behaviour but waiting for response from tester if it's a bug I will take care of this

Being discussed in the issue

**Comment by luacmartins** [comment]
I created a separate issue for https://github.com/Expensify/App/pull/61049#discussion_r2066672411, so we can move it outside this project https://github.com/Expensify/App/issues/61258

**Comment by luacmartins** [comment]
I think all the PRs fixing the bugs in the OP are merged. @jnowakow let's update https://github.com/Expensify/App/pull/61378 to get it merged tomorrow!

**Comment by mananjadhav** [comment]
@luacmartins I understand we had regressions here, but the PRs were too big to review covering a lot of areas. I was wondering if we could bump the price on this one to $500-750 ?

**Comment by suneox** [comment]
> [@luacmartins](https://github.com/luacmartins) I understand we had regressions here, but the PRs were too big to review covering a lot of areas. I was wondering if we could bump the price on this one to $500-750 ?

I've also worked hard to review PRs #58621, #58084, and #59999, which have large scopes and many edge cases. It would be great if we could consider increasing the payment for this one as well.

**Comment by luacmartins** [comment]
Yea, I agree this one was complex. I think $500 would be fair in this case considering the regressions.

**Comment by slafortune** [comment]
Reviewer: @mananjadhav owed $500 via NewDot
ROLE Contributor: @suneox paid $500 via Upwork offer sent [here](https://www.upwork.com/nx/wm/offer/107508282)
Contributor: @borys3kk is from an agency-contributor and not due payment
Contributor: @jnowakow is from an agency-contributor and not due payment

**Comment by slafortune** [comment]
ROLE Contributor: @suneox paid $500 via Upwork ✅

**Comment by garrettmknight** [comment]
$500 approved for @mananjadhav
