### ISSUE TITLE
Reports - "Manager McTest" is the sender, "You" is the receipient instead of the other way

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#61493]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.40-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sjdoidjsoijiosidj@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Gmail account
3. Complete the onboarding
4. Open FAB > Create expense
5. Click Try it out on the scan tooltip
6. Click Create expense
7. Go to Reports > Expenses

## Expected Result:
"From" field should be You, "To" field should be Manager McTest

## Actual Result:
"From" field is Manager McTest, "To" field is You

## Workaround:
Unknown

## Platforms:
Select the officially supported platforms where the issue was reproduced:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

<details>
  <summary>Platforms Tested:</summary>
On which of our officially supported platforms was this issue tested:

- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

</details> 

https://github.com/user-attachments/assets/6c05b0b5-7095-40e0-b4e1-7308bdc0f2d1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @grgia</details>

**Comment by DylanDylann** [comment]
This is a BE bug. The BE returns the wrong data. accountID and managerID should be interchanged

cc @grgia 

<img width="605" alt="Image" src="https://github.com/user-attachments/assets/2630955e-d2cb-4432-9247-3e3f67e174f7" />

**Comment by adelekennedy** [comment]
making internal

**Comment by adelekennedy** [comment]
@grgia bump on the above!

**Comment by grgia** [comment]
We merged the BE fix. Let's retest @adelekennedy  @lanitochka17

**Comment by adelekennedy** [comment]
I'm still seeing the same issue (From Manager McTest) after creating the test expense - @grgia am I just holding this totally wrong?

<img width="1510" alt="Image" src="https://github.com/user-attachments/assets/083f41d7-7768-4785-b1c6-31ed0d71fa57" />

**Comment by DylanDylann** [comment]
@grgia It seems the BE fix hasn't been deployed to staging. I still see that accountID and managerID are wrong

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/7508d130-2811-43db-8487-7211bd11d314" />

**Comment by grgia** [comment]
Hmm. that's weird

**Comment by grgia** [comment]
It seems to be specific to search then

**Comment by grgia** [comment]
https://github.com/Expensify/Auth/blob/main/auth/lib/SearchUtils.cpp#L952-L955

@lakchote @luacmartins would you please help me understand this decision so we can fix the manager logic

**Comment by luacmartins** [comment]
That was added to handle two scenarios:

1. The pay flow where the user submitting the expense is the "manager", since they are sending money, thus paying someone
2. When submitting a tracked expense to another user (not workspace)

I think the 1st scenario is correct, but when I look at the 2nd scenario, I think there's actually a bug with that flow. I see that we call `ConvertTrackedExpenseToRequest` but in that case we're submitting it to another user, not a workspace. That flow is flipping the sign of the transaction when it shouldn't (since IOUs have positive values in the DB)

**Comment by grgia** [comment]
@adelekennedy yes but will not get to this until next week

**Comment by grgia** [comment]
## Daily Update

I spent some time debugging this. 

- The request money responses seem correct. `Search` is returning the wrong account ID for only manager mctest in the snapshot. 
<img width="308" alt="Image" src="https://github.com/user-attachments/assets/de3e9379-ca6d-40fc-b459-492ec9887076" />

> Fix the issue with `ConvertTrackedExpenseToRequest`
- This seems to be removed? Not seeing where that plays into this. 


# Next Steps

- It's strange to me that it's only the manager mctest transactions. Theories
     - It's from the FE
     - It's from the payment logic
     - It's a case we're not handling in search (but why wouldn't this be like any other IOU otherwise?)

# ETA

Next week

**Comment by grgia** [comment]
Making daily to prioritize

**Comment by grgia** [comment]
Thread here: https://expensify.slack.com/archives/C07HPDRELLD/p1750428166332269

**Comment by grgia** [comment]
Pushed a PR for future reports

If we want to fix the existing ones, we would need to do a CQ

**Comment by grgia** [comment]
PR deployed to prod

**Comment by grgia** [comment]
<img width="1471" alt="Image" src="https://github.com/user-attachments/assets/20763cc4-ccf2-4e02-ba2e-0cfc2616df0e" />
