### ISSUE TITLE
Workspace - New member row is invisible when inviting member while member search is performed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#61692]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/60488
**Email or phone of affected tester (no customers):** applausetester+893n29@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Invite at least 16 members to the workspace
1. Go to staging.new.expensify.com
2. Go to workspace settings > Members
3. Enter anything on the search field that will return a few results
4. Click Invite member
5. Select a member and invite them
6. Clear the search field
7. Scroll down to where the new member is supposed to be seen

## Expected Result:
The new member row will be visible in the list

## Actual Result:
The new member appears as a blank row in the list. The row is visible after clicking on the member

## Workaround:
Unknown

## Platforms:
Select the officially supported platforms where the issue was reproduced:
- [ ] Android: App
- [x] Android: mWeb Chrome
- [ ] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

<details>
  <summary>Platforms Tested:</summary>
On which of our officially supported platforms was this issue tested:

- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

</details> 

https://github.com/user-attachments/assets/7b06486a-ddb8-4ae1-8a66-0ff64749437f

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rlinoz** [comment]
We might get it fixed here: https://github.com/Expensify/App/pull/61686

**Comment by IuliiaHerets** [comment]
Issue is still happens

https://github.com/user-attachments/assets/def09c6d-aaef-417f-8dae-3d695eebbde7

**Comment by rlinoz** [comment]
Hey @IuliiaHerets do you mind trying again? I can't repro, or maybe I did something different?

Version: v9.1.43-5

https://github.com/user-attachments/assets/4c2b5dfd-5da8-4de4-b737-ca61134c144a

**Comment by rlinoz** [comment]
Asked for retest here https://expensify.slack.com/archives/C9YU7BX5M/p1746814926083649

**Comment by IuliiaHerets** [comment]
@rlinoz Two testers can't reproduce the issue

https://github.com/user-attachments/assets/8d7bfd16-7061-4571-afa4-a4a470ab4dae
