### ISSUE TITLE
[Due for payment 2025-06-11] [$250] tags-User able to delete all tags.

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#62537]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9 1.48-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/58052
**Email or phone of affected tester (no customers):** slottwo1@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Redminote 10s android 13 phone
**App Component:** Workspace Settings

## Action Performed:
1. Launch app
2. Create a new workspace and enable tags
3. Tap Tags 
4. Add a tag 
5. Tap settings - enable members must tag all expenses 
6. Delete the tag

## Expected Result:
User must not be able to delete all tags. Cannot delete all tags modal must be shown.

## Actual Result:
User able to delete all tags and Cannot delete all tags modal is not shown.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f5e53327-2f73-4d44-8804-caa0412f7fa7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021927373792094838117</li>
        <li>Upwork Job ID: 1927373792094838117</li>
        <li>Last Price Increase: 2025-05-27</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 107474659</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by ijmalik** [comment]
Hi @sakluger 

The issue has been resolved in v9.1.49-4.

https://github.com/user-attachments/assets/4a60ebdf-5d44-49bb-a31a-45b63fa865e7

**Comment by mitarachim** [comment]
QA team still reproduce this issue using build v9.1.49-4

https://github.com/user-attachments/assets/da2638dd-645e-4b12-b43c-60d318332799

**Comment by mananjadhav** [comment]
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/62537#issuecomment-2899821276) looks good.

🎀 👀 🎀 C+ reviewed.

**Comment by mananjadhav** [comment]
PR was reviewed and merged.

**Comment by sakluger** [comment]
@mananjadhav please complete the BZ checklist 🙏

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @nkdengineer $250, paid via Upwork
Contributor+: @mananjadhav $250, please request on Newdot

**Comment by mananjadhav** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/commit/b5b6e9c9e05703ba43322341ed74408efb203f12#r159909682

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: NA

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal

### Test:
1. Create a new WS
2. Enable tag features
3. Create some tags
4. Tap settings - enable members must tag all expenses
5. Select all tags > Delete tags
6. Verify that Cannot delete all tags modal is shown.

Do we agree 👍 or 👎

**Comment by mananjadhav** [comment]
@sakluger Apologies for the delay. Here's the checklist ^
