### ISSUE TITLE
[Due for payment 2025-07-01] [$250] After moving expenses to the same report, selection mode persists but checkboxes are missing

### ISSUE THREAD

**Issue by nlemma** [Expensify/App#62578]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.49-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+x34@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.4 / Chrome
**App Component:** Money Requests

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat. 
3. Submit two expenses to workspace chat.
4. Go to Reports.
5. Tap bookmark button.
6. Tap Expense Reports.
7. Tap on the expense report with two expenses.
8. Long press on any expense > Select.
9. Tap dropdown button.
10. Tap Move expenses.
11. Tap on the selected report.
12. Tap app back button.

## Expected Result:
In Step 11, selection mode will exit.
In Step 12, app will return to Reports.

## Actual Result:
In Step 11, selection mode persists, but checkboxes are missing on the expense rows.
In Step 12, app back button reopens the same expense report.

On web, in Step 11, after moving expenses to the same report, app returns to Inbox.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/441e9677-b9e8-4e57-ac85-b3819321062a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021925786519842829002</li>
        <li>Upwork Job ID: 1925786519842829002</li>
        <li>Last Price Increase: 2025-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 107623220</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After moving expenses to the same report, selection mode persists but checkboxes are missing

### What is the root cause of that problem?
We don't reset the selectedTransaction list when moved to the same report 
https://github.com/Expensify/App/blob/413eb1052189ea3d7e57971e03e3d67510c395e1/src/pages/iou/request/step/IOURequestEditReport.tsx#L27-L35
### What changes do you think we should make in order to solve the problem?

We should reset selectedTransaction no matter the report it is moved is the current one or not
```
  const selectReport = (item: ReportListItem) => {
        if (selectedTransactionsID.length === 0) {
            return;
        }
        if (item.value !== transactionReport?.reportID) {
            changeTransactionsReport(selectedTransactionsID, item.value);
        }
        setSelectedTransactionsID([]);
        Navigation.dismissModalWithReport({reportID: item.value});
    };
```
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

N / A
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After moving expense to the same report, the selected transaction is not cleared.

### What is the root cause of that problem?
When we select the same report, it won't clear the selected transaction.
https://github.com/Expensify/App/blob/409e68ecced8a794176954e49d9adc2fdb7838ec/src/pages/iou/request/step/IOURequestEditReport.tsx#L31-L35

It should simply close the edit report modal.
https://github.com/Expensify/App/blob/409e68ecced8a794176954e49d9adc2fdb7838ec/src/libs/Navigation/Navigation.ts#L628-L635

However, `dismissModalWithReport` will only works well if we are on a report page. In our case, the `topmostReportID` is undefined and `isReportsSplitTopmostFullScreen` is also false.

### What changes do you think we should make in order to solve the problem?

To make it work with report screen on search too, we can create a new function, `getTopmostSearchReportId`.
```
const getTopmostSearchReportId = (state = navigationRef.getState()) => getTopmostSearchReportParams(state)?.reportID;
```

<details>
<summary>getTopmostSearchReportParams</summary>

```
function getTopmostSearchReportParams(state: State): SearchFullscreenNavigatorParamList[typeof SCREENS.SEARCH.MONEY_REQUEST_REPORT] | undefined {
    if (!state) {
        return;
    }

    const topmostSearchFullscreenNavigator = state.routes?.filter((route) => route.name === NAVIGATORS.SEARCH_FULLSCREEN_NAVIGATOR).at(-1);

    if (!topmostSearchFullscreenNavigator) {
        return;
    }

    const topmostReport = topmostSearchFullscreenNavigator.state?.routes.filter((route) => route.name === SCREENS.SEARCH.MONEY_REQUEST_REPORT).at(-1);

    if (!topmostReport) {
        return;
    }

    return topmostReport?.params as SearchFullscreenNavigatorParamList[typeof SCREENS.SEARCH.MONEY_REQUEST_REPORT];
}
```

</details>

Then, we will use `getTopmostSearchReportId` if we are on search page.
```
const topmostFullScreen = ref.getRootState().routes?.findLast((route) => isFullScreenName(route.name));
const isReportsSplitTopmostFullScreen = topmostFullScreen?.name === NAVIGATORS.REPORTS_SPLIT_NAVIGATOR;
const isSearchTopmostFullScreenRoute = topmostFullScreen?.name === NAVIGATORS.SEARCH_FULLSCREEN_NAVIGATOR;
const topmostReportID = isSearchTopmostFullScreenRoute ? getTopmostSearchReportId() : getTopmostReportId();
```

Next, we check if the search navigator topmost screen is the money request report.
```
const isSearchReportsTopmostFullScreen = isSearchTopmostFullScreenRoute && topmostFullScreen?.state?.routes.at(-1)?.name === SCREENS.SEARCH.MONEY_REQUEST_REPORT;
```

We dismiss the modal if either `isReportsSplitTopmostFullScreen` or `isSearchReportsTopmostFullScreen` is true.
```
(isReportsSplitTopmostFullScreen || isSearchReportsTopmostFullScreen)
```

(we can consider adding this logic to the page component instead to not alter the dismissModalWithReport behavior at all)

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

N/A

**Comment by VictoriaExpensify** [comment]
Yeah we should fix this

**Comment by alitoshmatov** [comment]
Is this feature still on, I see can use "Move" feature in older codebase but now it is not appearing

**Comment by alitoshmatov** [comment]
Sorry for late response. Weird I did enable all betas, tried with different accounts but still cannot use `move` feature. I will ask for someone else to take over, since I have less availability than usual and feature not working I don't want to prevent this issue from moving forward.

**Comment by allroundexperts** [comment]
I can take over @alitoshmatov

**Comment by alitoshmatov** [comment]
Asked for help on [slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1749405403388119). @VictoriaExpensify Can you reassign to @allroundexperts

**Comment by allroundexperts** [comment]
Thanks for the proposals @bernhardoj and @FitseTLT.

Both of you pointed out the correct RCA and the proposed solutions work as well.

I think @FitseTLT's [proposal](https://github.com/Expensify/App/issues/62578#issuecomment-2901093054) is more straight forward and would have a lot less side effects.

@bernhardoj While I acknowledge that we can move the logic suggested by you to the component itself, but if we are doing that, then in my opinion adding the following is much more simpler:

```
if (item.value === transactionReport?.reportID) {
            Navigation.dismissModal(); // We can optionally also use goBack(backTo);
            return;
}
```

Due to these reasons, I think we should proceed with @FitseTLT's [proposal](https://github.com/Expensify/App/issues/62578#issuecomment-2901093054).

🎀 👀 🎀 C+ reviewed

**Comment by NikkiWines** [comment]
Yep, makes sense. Moving forward with @FitseTLT's proposal

**Comment by allroundexperts** [comment]
Can I be please assigned here @NikkiWines?

**Comment by VictoriaExpensify** [comment]
Payment summary:
C: @FitseTLT paid $250 via Upwork
C+: @allroundexperts owed $250 via NewDot

Thanks so much for stepping in here @allroundexperts! 🙏

**Comment by trjExpensify** [comment]
approved $250 for @allroundexperts.
