### ISSUE TITLE
Reports - App loads infinitely when creating report in offline mode

### ISSUE THREAD

**Issue by nlemma** [Expensify/App#62677]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.51-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check - New feature testing
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** sdnoisduds11oiosdi@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.4 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Account has at least one workspace.
- Account does not have any unsubmitted report.

1. Go to staging.new.expensify.com
2. Go to Reports.
3. Go to Submit.
4. Go offline.
5. Click Create report.

## Expected Result:
App will create a new report.

## Actual Result:
App loads infinitely when creating report in offline mode.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/03acd144-3c8a-4bc4-b28f-b976716f9b09

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nlemma** [comment]
@sakluger FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by luacmartins** [comment]
@JS00001 seems to come from the suggested searches PR

**Comment by sakluger** [comment]
This is likely a regression, so the contributor who worked on the offending PR can ideally help fix it.

**Comment by JS00001** [comment]
@luacmartins This is an issue even with suggested search reverted. Using the FAB to create a report when offline doesn't work

**Comment by JS00001** [comment]
This is also on production

**Comment by luacmartins** [comment]
I have a PR with a fix

**Comment by Beamanator** [comment]
removing blocker label - we can close if this doesn't exist anymore, but @JS00001 mentioned this exists on prod? Either way this shouldn't be a blocker anymore

**Comment by SzymczakJ** [comment]
SWM Traditional Reports team could look into that later today ✋ @SzymczakJ @sumo-slonik @JakubKorytko

**Comment by sumo-slonik** [comment]
Hi, I'm Kuba from SWM and I'd be happy to take care of it.

**Comment by getusha** [comment]
Didn't we fix this [here](https://github.com/Expensify/App/pull/62683)?

**Comment by luacmartins** [comment]
Ah yes, we already fixed this. @sumo-slonik was that comment meant for https://github.com/Expensify/App/issues/62954?

**Comment by sumo-slonik** [comment]
@luacmartins It seems to me that it's still not fully fixed. We made it display properly, but it's still not possible to add expenses to such a report. However, I’ve managed to fix it now and I'm currently preparing a PR for it.

https://github.com/user-attachments/assets/3db40d5f-4a26-4767-8c60-1fbaece27390

**Comment by luacmartins** [comment]
Ah nice! Yea, we didn't handle those cases in my PR. Thanks for the improvements!

**Comment by sakluger** [comment]
@getusha could you please complete the BZ checklist before the payment due date? Thanks!

**Comment by sakluger** [comment]
@getusha bump on the BZ checklist.

**Comment by getusha** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/62683/files#r2149704052

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/a

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.
- No, it's an offline issue and i think a testrail is an overkill

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @sumo-slonik - no payment required
Contributor+: @getusha $250, please request on Newdot
