### ISSUE TITLE
[HOLD][$250] Column Headers Misaligned with Table Content in Reports > Submit

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#62819]
Held on https://github.com/Expensify/App/pull/62926

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs Reproduction
**Reproducible in production?:** Needs Reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation** (hyperlinked to channel name): [#Expensify Bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1748247849987609)

## Action Performed:

1. Go to Reports > Submit
2. Observe the alignment of the column headers with the data rows.

## Expected Result:
Column headers should always align perfectly with the corresponding table columns, regardless of the date format.

## Actual Result:
The Date column header has a fixed or outdated width that does not adjust to the content below it, resulting in misaligned columns.

## Workaround:
Unknown
## Platforms:
Select the officially supported platforms where the issue was reproduced:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

<details>
  <summary>Platforms Tested:</summary>
On which of our officially supported platforms was this issue tested:

- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

</details>

![Image](https://github.com/user-attachments/assets/42992632-c157-4710-89b4-9d8fe0294716)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021927452545309562456</li>
        <li>Upwork Job ID: 1927452545309562456</li>
        <li>Last Price Increase: 2025-06-02</li>
<li>Automatic offers: </li>
<ul>
<li>samranahm | Contributor | 107541577</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cristipaval</details>

**Comment by samranahm** [comment]
Gentle bump @allroundexperts

**Comment by muttmuure** [comment]
Bumped the price

**Comment by parasharrajat** [comment]
@muttmuure Actually, there is already a proposal which has not be reviewed yet so I don't think it warrants a price increase yet.

**Comment by allroundexperts** [comment]
I'll review it today.

**Comment by allroundexperts** [comment]
@samranahm's [proposal](https://github.com/Expensify/App/issues/62819#issuecomment-2910447030) looks good to me. The RCA is correct and the solution works. I was able to reproduce the issue as well.

🎀 👀 🎀 C+ reviewed

**Comment by shawnborton** [comment]
Before we go assigning this - @SzymczakJ are you going to fix this in this PR here? https://github.com/Expensify/App/pull/62926 

Just wondering if we are already taking care of this or not...

**Comment by cristipaval** [comment]
Thanks for the heads up @shawnborton!

@samranahm, please wait until @SzymczakJ responds 🙏

**Comment by samranahm** [comment]
Tested PR #62926, but it doesn't fix this issue. Should I submit a PR?

**Comment by shawnborton** [comment]
@SzymczakJ can you take a look here please?

**Comment by SzymczakJ** [comment]
Sorry for responding so late, I accidentally missed this message. I don't see this issue on my branch. I fixed many issues lately, so this one was probably also fixed. I think we can close this issue once my PR is merged

<img width="680" alt="Image" src="https://github.com/user-attachments/assets/483b146b-55ac-48b9-b965-517c859e79c2" />

<img width="680" alt="Image" src="https://github.com/user-attachments/assets/6c35dacc-44a4-42d2-8c94-677517d4eba4" />

**Comment by SzymczakJ** [comment]
Well, I also cannot repro this on staging, so maybe we should just retest?

**Comment by shawnborton** [comment]
I'm still seeing it on staging: 

![Image](https://github.com/user-attachments/assets/9082c9ed-413f-4308-b622-f544604d16d5)

It happens when you have expenses that include a year which makes the date column wider. Looks like the date column in the header is not getting wider to match the content/rows below.

So it sounds like we still need to move forward with a fix, cc @cristipaval

**Comment by cristipaval** [comment]
Thanks @SzymczakJ and @shawnborton!

@samranahm , you're all set to fix it.

**Comment by samranahm** [comment]
@allroundexperts PR https://github.com/Expensify/App/pull/63442 ready

**Comment by shawnborton** [comment]
Wow, how did @samranahm 's proposal get accepted here? It is not correct at all.

**Comment by shawnborton** [comment]
Perhaps we should just have SWM take care of this? cc @trjExpensify @mountiny

**Comment by mountiny** [comment]
Someone from SWM was already working on aligning the columns, right @SzymczakJ @Kicu

**Comment by Kicu** [comment]
I can verify with the guys tomorrow if someone is doing something similar - then they can cover this one as well.
Otherwise one of us will pick it up (I should have time tomorrow since I'm only working on 1 more cleanup right now).

**Comment by shawnborton** [comment]
Sounds good, keep us posted!

**Comment by samranahm** [comment]
**With out year**

<img width="1051" alt="Image" src="https://github.com/user-attachments/assets/f6df7e43-45be-4374-8a51-dbffe21896f0" />

</br >




</br >

<img width="1051" alt="Image" src="https://github.com/user-attachments/assets/7d6cf8a4-d042-4d8a-a8bd-2c466b132da4" />

**Comment by samranahm** [comment]
With year

<img width="1051" alt="Image" src="https://github.com/user-attachments/assets/40b8819c-802c-4442-9812-acdd639a7a50" />


</br>


</br>

<img width="1051" alt="Image" src="https://github.com/user-attachments/assets/24348d93-ac5f-4a23-9de3-fd04f82295c4" />

**Comment by samranahm** [comment]
Working on another solution, @shawnborton can you confirm the design above please

**Comment by shawnborton** [comment]
I think we should just go with our expert contributors on this, sounds like they can take it. 

The designs above are incorrect. The date column header should not be centered.

**Comment by Kicu** [comment]
I'm starting to work on this today

**Comment by Kicu** [comment]
Ok small update, I have synced with @SzymczakJ and it would seem that all these alignment problems do not happen on his PR where he aligns the TransactionRow components for Report view and Search. Here is the PR: https://github.com/Expensify/App/pull/62926

### bug visible on staging, my account:

<img width="700" alt="Image" src="https://github.com/user-attachments/assets/e870aec4-7bb5-413b-b01b-6b649cb8adb7" />

### same data, on Jakub's PR:

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/d8cbcb27-fa39-40fa-bbc1-5d526b3692f1" />
<img width="800" alt="Image" src="https://github.com/user-attachments/assets/92887040-e2db-4856-9c25-bf2c47fcd7df" />

#### also correct with long+short dates
<img width="804" alt="Image" src="https://github.com/user-attachments/assets/c8c280f7-73b9-451a-91ee-c87a3d7217fb" />

After testing I believe the best course of action it so wait for merge of https://github.com/Expensify/App/pull/62926 and then retest if the bug happens - but it shouldn't. We can put this one on HOLD I believe.

**Comment by cristipaval** [comment]
Thank you all!

**Comment by shawnborton** [comment]
Oh that's great news, then let's definitely get Jakub's PR merged soon and we'll be good <3

**Comment by mountiny** [comment]
Pr was merged

**Comment by samranahm** [comment]
PR #62926 from @Kicu deployed to production

**Comment by Kicu** [comment]
@SzymczakJ was the author of the PR, I just verified that it seemed to fix the bug :)

Now we should retest.

**Comment by shawnborton** [comment]
Yeah, it does seem to fix things on my end too. I'm just gonna close for now, but we can reopen if we find any more bugs.

**Comment by samranahm** [comment]
@cristipaval Could you please process the payments as per 

 > If  we decide to close the job before it is successfully completed 
 >
 > * 50% payment to contributor and C+ if the contributor was hired/assigned.
 > * 50% payment if the contributor wasn't assigned and
 >   The bug was fixed by a different PR
 > * The proposal was 🎀👀🎀 by the C+, and
 >   
 >   * Most of the code used in the fix came from the accepted proposal
 >   * 100% due to the contributor if they  drafted a PR and requested a review.
 >   * 100% due to C+ if they reviewed the PR.
 >     One caveat here might be if the hired contributor wasn't working on their PR with urgency.

**Comment by cristipaval** [comment]
@muttmuure could you please handle the payments here? 🙏 

50% due to the contributor (they made the PR ready) - @samranahm 
50% due to the C+ ( they didn't review the PR) - @allroundexperts

**Comment by SzymczakJ** [comment]
Hey, the PR that @samranahm raised was not solving the issue correctly as @shawnborton noticed here: https://github.com/Expensify/App/issues/62819#issuecomment-2940203507. Along the way we decided to stick with expert contributors from SWM and it even turned out that [my PR](https://github.com/Expensify/App/pull/62926) that was raised before this issue was created fixed this issue. 
That said, the PR that @samranahm created didn't really help us with anything and _most of the code used in the fix **didn't come** from the accepted proposal(no code from this PR was used because it was simply not correct)_
I don't wanna cause anyone problems, but I think paying for this issue a full bounty is unjust

**Comment by shawnborton** [comment]
I totally agree with that.

**Comment by cristipaval** [comment]
@SzymczakJ I know the proposed solution was wrong, but it is my fault that I accepted it. I also gave them the green light to work on it [here](https://github.com/Expensify/App/issues/62819#issuecomment-2939428208).

So, the payment is not for the work they did; it is actually for respecting the "contract" I "signed" by hiring them and asking them to implement their solution. cc @muttmuure @shawnborton, what do you think we should do here?

**Comment by cristipaval** [comment]
> but I think paying for this issue a full bounty is unjust

Thinking a bit more, you're right, @SzymczakJ. Even when a contributor is hired, and their work is deployed, if regressions occur in production, we add a penalty to the bounty. I think a wrong solution is even worse than one that adds regressions. So, I agree that we shouldn't pay the full bounty. Thanks for raising that!

I edited the payment summary [here](https://github.com/Expensify/App/issues/62819#issuecomment-2961855652), @muttmuure

**Comment by mountiny** [comment]
I agree with Cristi, because we asked the contributor to work on this we should pay them $50 for their effort and we later accepted this was a mistake and we wanted a slightly different solution. But I dont think we should pay more than that

**Comment by shawnborton** [comment]
That works for me!

**Comment by samranahm** [comment]
@mountiny I respect your decision but we've instructions [here](https://github.com/Expensify/App/issues/62819#issuecomment-2961807138) for similar cases $50 wouldn't be fair I believe, the PR was crafted andi requested review, I ever worked on another solution and provide mocks [here](https://github.com/Expensify/App/issues/62819#issuecomment-2940743854) I think we should go with half bounty as per current summary, wyt

**Comment by mountiny** [comment]
@samranahm Sorry where does that text come from, I dont see it in the https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#payment-for-contributions

**Comment by samranahm** [comment]
@mountiny there is another doc mentioned in https://github.com/Expensify/App/issues/62166#issuecomment-2886501306

**Comment by mountiny** [comment]
Seems like that is new but ok yeah then you should get half so $125

**Comment by shawnborton** [comment]
Understand why we landed there given we have the existing policy for it, but I will say it feels like a bit of a bummer. Let's be cautious and make sure we are reviewing @samranahm 's proposals extra closely next time - I personally felt like it was way off from being a viable solution and I was surprised it was picked.

**Comment by allroundexperts** [comment]
@shawnborton I think you tested it with an account that had a lot of rows. I tested the proposal with a new account and the proposal worked for that.

**Comment by shawnborton** [comment]
I mentioned multiple times that we need to adjust the date column width in the column headers. The proposal clearly did not solve the issue, as all it did was use a text-align: center style. Again, I think this is a learning opportunity for us - we did not thoroughly evaluate the proposals, and we did not check with the @Expensify/design team when in doubt. 

It's all good though, as we do have a fix. I am merely just cautioning us to be careful with these kinds of "simple" proposals for next time.

**Comment by mountiny** [comment]
Agree with that, sometimes things like this slip through, lets be more lenient in future

**Comment by cristipaval** [comment]
Thank you all for sharing your thoughts here! 🙏

**Comment by shawnborton** [comment]
Not overdue, awaiting payments.

**Comment by muttmuure** [comment]
$125 - @samranahm 
$125 - @allroundexperts

**Comment by trjExpensify** [comment]
approved $125 for @allroundexperts.
