### ISSUE TITLE
[Awaiting checklist] [$250] Expense - Expense date changes to a day before the selected date after splitting expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#63712]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.60-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/6218975&group_by=cases:section_id&group_order=asc&group_id=400779
**Email or phone of affected tester (no customers):** applausetester+ck652510@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
Use an expensifail account
Create a workspace with Delay submission disabled and Add approvals enabled
Submit a manual expense in workspace chat
1. Navigate to staging.new.expensify.com
2. Navigate to the expense preview created in workspace chat
3. Click on More > Split
4. Click "Add split" button to add one or more splits
5. For one of the splits, edit the category and date
6. Click "Save" to process the Split
7. Observe the split expense date changes to a day before the selected date

## Expected Result:
Each split expense should display correct selected date

## Actual Result:
Expense date changes to a day before the selected date after splitting expense

## Workaround:
Unknown

## Platforms:
Select the officially supported platforms where the issue was reproduced:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

<details>
  <summary>Platforms Tested:</summary>
On which of our officially supported platforms was this issue tested:

- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

</details> 

https://github.com/user-attachments/assets/78800cba-2b0f-4474-a16e-c9d8a6e2529c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021937248461999382996</li>
        <li>Upwork Job ID: 1937248461999382996</li>
        <li>Last Price Increase: 2025-06-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by garrettmknight** [comment]
@ZhenjaHorbach I can't seem to repro this one. Can you give it a try?

**Comment by garrettmknight** [comment]
https://github.com/user-attachments/assets/420b87c8-b5dd-4715-9e48-be538f5b1e74

**Comment by ZhenjaHorbach** [comment]
The same 
I can't reproduce 
And following the video this problem was related to BE
But it seems it was fixed there

**Comment by lakchote** [comment]
@garrettmknight @ZhenjaHorbach I can't reproduce either.

Asked for a QA retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1749629461825969).

**Comment by IuliiaHerets** [comment]
@lakchote Issue still reproduces on v9.1.64-1

https://github.com/user-attachments/assets/620acc11-8183-4b01-9813-ab9bd26375a9

**Comment by garrettmknight** [comment]
I'm not sure what I'm doing differently, but I still can't seem to repro:

https://github.com/user-attachments/assets/c7fd642a-7771-426d-a36f-7f4ee03479aa

**Comment by IuliiaHerets** [comment]
Issue not repro on OD 

https://github.com/user-attachments/assets/6abdad9c-a13d-4e27-8629-9fcfa548746b

**Comment by lakchote** [comment]
I'll try to reproduce it again tomorrow. cc @ZhenjaHorbach: Did you try with the same prerequisite steps too?

To me, it looks like a frontend bug since the issue isn't present in OldDot, and the backend code is the same.

**Comment by ZhenjaHorbach** [comment]
No luck from my side 
And I still think that this is a BE issue
Since the date changes occur with a delay (at the same time with total amount that is updated from BE)

https://github.com/user-attachments/assets/3d126603-1cef-4487-b8e6-5a4f31de808c

**Comment by lakchote** [comment]
I couldn't reproduce either.

I have doubts regarding the fact that it's backend related, since date logic for splits hasn't been touched at all, and also the problem is not there in OldDot.

What do you want to do here @garrettmknight, given the fact that we can't reproduce?

**Comment by ZhenjaHorbach** [comment]
Maybe we should add Needs Reproduction label so that more eyes could see it and try to reproduce it
Because I have no idea why this isn't reproducible for me

**Comment by lakchote** [comment]
@IuliiaHerets was there any prerequisite steps that wasn't written that could explain why we can't reproduce, but you can?

**Comment by garrettmknight** [comment]
I think we keep this open until @IuliiaHerets can no longer repro.

**Comment by garrettmknight** [comment]
@IuliiaHerets I still can't seem to reproduce this one.

**Comment by garrettmknight** [comment]
cc @lakchote @ZhenjaHorbach

**Comment by ZhenjaHorbach** [comment]
> [@ZhenjaHorbach](https://github.com/ZhenjaHorbach) this is fixed, right?

Since this PR has been in production for a week already
I think so !

**Comment by garrettmknight** [comment]
Sweet, just making sure we didn't miss any dangling PRs.

**Comment by garrettmknight** [comment]
@allroundexperts checklist please!

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @ZhenjaHorbach $250 via NewDot
- Reviewer: @allroundexperts $50 via NewDot

**Comment by JmillsExpensify** [comment]
Payment Summary:

 - @ZhenjaHorbach $250 via NewDot
 - @allroundexperts $50 via NewDot

**Comment by allroundexperts** [comment]
I reviewed https://github.com/Expensify/App/pull/64824. Usually, the amount is same as the contributor unless something has changed recently that I missed 😄
