### ISSUE TITLE
iOS - App is not responsive when launched via shortcut when onboarding is not completed

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#63972]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.64-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** bbbdjdikdkdkdcvdhdhddh@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** iPhone 15 Pro Max / iOS 18.5
**App Component:** Other

## Action Performed:
1. Launch Expensify app.
2. Log in a new Gmail account.
3. On onboarding step "What's your work email?", kill the app.
4. Long press on the app icon.
5. Tap Manually create.
6. Tap any button in the app.

## Expected Result:
When onboarding is not completed and launching app via shortcut, onboarding should resume.

## Actual Result:
When onboarding is not completed and launching app via shortcut, onboarding does not resume. App lands on Inbox.
Tapping any button in the app does not do anything.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [x] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/77800969-2721-4c88-ada0-2a35eed2d958

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by techievivek** [comment]
Removing the DeployBlocker label since this doesn't seem related to recent web deploy and seems like a frontend-only bug.

**Comment by dangrous** [comment]
hopefully fixed by https://github.com/Expensify/App/pull/63987

**Comment by Julesssss** [comment]
> hopefully fixed by [#63987](https://github.com/Expensify/App/pull/63987)

@dangrous could you run an early test on [those](https://github.com/Expensify/App/pull/63987#issuecomment-2963329608) adhoc builds please while we await full review? thanks

**Comment by BlameGPT** [comment]
### Possible culprit PRs for this issue
- #63588: This PR explicitly tests app launch flows via shortcuts when the app is closed or in the background, matching the issue's scenario of launching via shortcut during onboarding.
- #63800: This PR modifies onboarding email logic and adds logging related to onboarding email validation, which is relevant to the onboarding step where the issue occurs.
- #63757: This PR changes the sign-in page UI and flow after signing out, which is related to login and onboarding flows, potentially affecting app responsiveness after login.

**Comment by dangrous** [comment]
Fix PR / ad hoc builds look good to me! Should we go ahead and merge to fix, or wait for C+ review?

**Comment by Julesssss** [comment]
I merged as the diff is small

**Comment by Julesssss** [comment]
Requested a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1749673979747359)

**Comment by IuliiaHerets** [comment]
@Julesssss Issue still reproducible on the build 9.1.64-0, Iphone 14 Pro Max/ios18

https://github.com/user-attachments/assets/d7f4d974-f925-4a0c-9192-2dfca1278bfc

**Comment by Julesssss** [comment]
Oh sorry, we should test `9.1.64-5`... This seems to work for me on iOS `18.1.1`, iPhone 13 mini

https://github.com/user-attachments/assets/49e6a56a-2222-444d-b024-5c5222d1e72d

**Comment by Julesssss** [comment]
Working on Android too. I'm going to remove the blocker label while we await confirmation from @IuliiaHerets [here](https://expensify.slack.com/archives/C9YU7BX5M/p1749676216082379?thread_ts=1749673979.747359&cid=C9YU7BX5M).  But I think that has been resolved and can be closed

**Comment by IuliiaHerets** [comment]
@Julesssss Issue is not reproducible on the latest build 64-5

https://github.com/user-attachments/assets/51a45b7d-10cb-44bd-a64c-16466b8f839d
