### ISSUE TITLE
Reports - App crashes when returning to reports after deleting splits and creating new ones.

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#64123]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.66-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ibellicotest+1042@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Motorola MotoG60 - Android 12 - Chrome (mWeb - Hybrid App) / Windows 10 - Chrome
**App Component:** Search

## Action Performed:
Prerequisite: Account has at least one workspace created.
1. Open the staging.new.expensify.com website.
2. Open any workspace.
3. Create a manual expense.
4. Open the just created expense.
5. Tap on "More" and select "Spli"
6. Tap on "Save"
7. Navigate to "Reports"
8. Select both splits and delete them.
9. Return to workspace chat.
10. Create a new manual expense.
11. Open the expense and tap on "More"
12. Tap on "Split" and save the amounts.
13. If app didn´t crash yet, return to "Reports"
14. Note that the app crashes after this action.
15. Refresh the app and try to open "Reports" section again.
16. Note that app keeps crashing.

## Expected Result:
User should be able to continue using the app properly after deleting created splits and creating new ones.

## Actual Result:
After deleting created splits on "Reports", creating a new manual expense on workspace, splitting it and trying to return to "Reports" the app crashes. After this, app keeps crashing everytime "Reports" section is opened.

this issue reproducible in Production using expensifail account

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[Bug6858582_1749770292615!log.txt](https://github.com/user-attachments/files/20718139/Bug6858582_1749770292615.log.txt)

https://github.com/user-attachments/assets/06da89ed-1345-4c36-91f4-ff431bc4d697

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After deleting created splits on "Reports", creating a new manual expense on workspace, splitting it and trying to return to "Reports" the app crashes. After this, app keeps crashing everytime "Reports" section is opened.

### What is the root cause of that problem?

The accountID can be undefined in

https://github.com/Expensify/App/blob/36fde9a465fc5ae7f95c6c572901ba1e2720522b/src/libs/SearchUIUtils.ts#L395

### What changes do you think we should make in order to solve the problem?


We should update the type of accountID to number | undefined and update this line 

https://github.com/Expensify/App/blob/36fde9a465fc5ae7f95c6c572901ba1e2720522b/src/libs/SearchUIUtils.ts#L395

to 

```
        const from = personalDetailsMap.get(transactionItem.accountID?.toString()) ?? emptyPersonalDetails;
```
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

None

### What alternative solutions did you explore? (Optional)



**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by dmkt9** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After deleting created splits on "Reports", creating a new manual expense on workspace, splitting it and trying to return to "Reports" the app crashes. After this, app keeps crashing everytime "Reports" section is opened.

### What is the root cause of that problem?
- Regression from [PR](https://github.com/Expensify/App/pull/63092), transaction data was injected directly into the snapshot without an `accountID`.  
https://github.com/Expensify/App/blob/04a715bfc26d183ffd934dde4f9cf4fb51cc2e50/src/libs/actions/IOU.ts#L11731-L11742
- This causes `accountID` here to be `undefined` and crashes the App:
https://github.com/Expensify/App/blob/04a715bfc26d183ffd934dde4f9cf4fb51cc2e50/src/libs/SearchUIUtils.ts#L395

### What changes do you think we should make in order to solve the problem?
1. Remove the code [here](https://github.com/Expensify/App/blob/04a715bfc26d183ffd934dde4f9cf4fb51cc2e50/src/libs/actions/IOU.ts#L11731-L11752). Since once the Search API succeeds the previously added transaction is discarded—and because we already update the transaction [here](https://github.com/Expensify/App/blob/04a715bfc26d183ffd934dde4f9cf4fb51cc2e50/src/libs/actions/IOU.ts#L11695-L11702)—if we’re on the SearchPage the data will automatically sync into the snapshot via Onyx, making this insertion redundant.  
2. To prevent this from happening again, validate `accountID` the same way we do `managerID`.
https://github.com/Expensify/App/blob/04a715bfc26d183ffd934dde4f9cf4fb51cc2e50/src/libs/SearchUIUtils.ts#L395-L396
```js
const from = transactionItem.accountID ? personalDetailsMap.get(transactionItem.accountID.toString()) ?? emptyPersonalDetails : emptyPersonalDetails;
```
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
NA
### What alternative solutions did you explore? (Optional)
NA

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by bernhardoj** [comment]
Should be fixed in https://github.com/Expensify/App/issues/64121

**Comment by flaviadefaria** [comment]
Asked for a re-test here - https://expensify.slack.com/archives/C9YU7BX5M/p1750239359768849

**Comment by IuliiaHerets** [comment]
@flaviadefaria Issue is still reproduced on mWeb/Chrome.
 Windows10/Chrome - no crash, but app freezes after refreshing the page, build 9.1.68-3.

https://github.com/user-attachments/assets/c6bf84ec-2829-4378-8a85-80d066065ba6
https://github.com/user-attachments/assets/9b82125d-a6c4-4970-b2e2-b3786a45be99

**Comment by flaviadefaria** [comment]
@bernhardoj, is this something you want to look at, or should I just apply the regular labels?

**Comment by bernhardoj** [comment]
@flaviadefaria We have another issue where the [solution](https://github.com/Expensify/App/issues/64121#issuecomment-2968980427) I gave there will solve this issue and https://github.com/Expensify/App/issues/64121. We can reopen https://github.com/Expensify/App/issues/64121 and assign a C+ there to crosscheck and close this one once the C+ verified it.

**Comment by dmkt9** [comment]
@flaviadefaria These issues share the same root cause. Resolving this issue will also resolve the others. Additionally, fixing this will help prevent app crashes in the future. So we can go on.

Additionally, the other issue has also been closed.

**Comment by flaviadefaria** [comment]
I reopened the other issue as it shouldn't have been closed without a re-test. I'll keep this open until that fix is deployed to see if it fixes this issue.

**Comment by dmkt9** [comment]
> I reopened the other issue as it shouldn't have been closed without a re-test. I'll keep this open until that fix is deployed to see if it fixes this issue.

@flaviadefaria Please check [my comment](https://github.com/Expensify/App/issues/64123#issuecomment-2989950727). Fixing this issue is better than addressing others, as it helps prevent app crashes in the future

**Comment by flaviadefaria** [comment]
Asked for a re-test.

**Comment by flaviadefaria** [comment]
Thank you @IuliiaHerets. Closing it due to the above.
