### ISSUE TITLE
[$250] Expense - Unapproving expense that is exported to QBO show no warning on the first attempt.

### ISSUE THREAD

**Issue by jponikarchuk** [Expensify/App#64553]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.69-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/6314857
**Email or phone of affected tester (no customers):** applausetester+bm733@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Web, mweb, android
**App Component:** Money Requests

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a workspace with USD currency
3. Connect to QBO
4. Disable Auto-create entities if enabled.
5. Go to WS chat and create an expense
6. Submit and approve.
7. Export it to QBO
8. After the error message appears, go to Accounting > QBO advanced settings> enable Auto-create entities.
9. Go back to the report and export it again.
10. Click on More and unapprove it.

## Expected Result:
A warning should appear

## Actual Result:
No warning is shown when unapproving the expense for the first time, but does on subsequent ones.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a64c42b2-658e-4fb2-a6d1-3999380dada3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021937220205134125370</li>
        <li>Upwork Job ID: 1937220205134125370</li>
        <li>Last Price Increase: 2025-07-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by ikevin127** [comment]
Since there are no proposals, I'm assuming this is not reproducible. Will try to reproduce soon and come back with the report.

**Comment by ikevin127** [comment]
🟢 I was able to reproduce OP issue consistently - therefore we're open for proposals! 👈 

Moreover, the Unapprove warning dialog doesn't show **at all** if QBO `Auto-sync` is turned ON since in that case once expense is Approved the export sync starts automatically without user action.

☝ When this happens, even if we enable `Auto-create entities`, if `Auto-sync` is ON, the Unapprove warning dialog won't show up.

> [!important]
> I'd adjust issue OP step 4 to `Disable 'Auto-create entities' and `Auto-sync` if enabled.` to ensure correct reproduction, but also suggest having `Auto-sync` ON in an additional test step, for reproduction of the additional issue I found while reproducing OP issue.

**My take is that the issue originates from the following function:**

**Note**: When the return condition returns false, Unapprove warning dialog is not being shown (the code comment is crucial).

https://github.com/Expensify/App/blob/fd5c717d8371ec386f0fc7baa8eebad7e1d9aadb/src/libs/ReportUtils.ts#L10789-L10815

I'm not ruling out faulty logic on both BE / FE in terms of communication in this specific scenario. Anyhow, just posted the issue on Slack to alert that we're looking for proposals.

If there won't be any takers, I will most likely take on this myself and post a proposal 👍

**Comment by ikevin127** [comment]
**♻ Reviewing...**

**Comment by ikevin127** [comment]
⏳ Awaiting response on [this question](https://github.com/Expensify/App/issues/64591#issuecomment-3034130231) since a [HOLD] was suggested due to having a BE pull request in the works which could potentially address both issues without FE changes needed.

**Comment by sakluger** [comment]
FYI, HOLD in the title doesn't actually prevent the issue from going overdue, so I've changed the priority to Weekly for now.

**Comment by ikevin127** [comment]
@dangrous Just notified us in the [other issue](https://github.com/Expensify/App/issues/64591#issuecomment-3046060901) that the BE fix, which should fix this issue as well as the other one, was deployed to production. I retested the issue including the `Auto-sync` case mentioned in my [previous comment](https://github.com/Expensify/App/issues/64553#issuecomment-3030377604) and it seems to be fixed:

https://github.com/user-attachments/assets/5036928c-167b-4819-8526-b30ec0d3bbae

@sakluger Unless you'd like to have QA confirm the fix before closing, I'd say this issue can be closed as fixed by BE 👍

**Comment by sakluger** [comment]
Thanks for the heads up. Should we put this one on hold for https://github.com/Expensify/App/issues/64591?

**Comment by ikevin127** [comment]
☝️

**Comment by dangrous** [comment]
Hi! I thinkkkkk that this should be fixed as well, should we retest?

**Comment by ikevin127** [comment]
♻️ Attempting to reproduce, will report back soon.

**Comment by ikevin127** [comment]
🟢 Issue was fixed, just tried to reproduce and the **expected result is now reality**. The issue can be closed as fixed ✅ 

https://github.com/user-attachments/assets/d0c56c7b-2010-4342-a7b7-2e653c900312

cc @dangrous @sakluger

**Comment by nlemma** [comment]
@sakluger @ikevin127 this issue is still reproducible. Reopening so that you can check it. 


https://github.com/user-attachments/assets/80ea8e86-e2c2-4b07-bba2-c880cdfb12ad

**Comment by dangrous** [comment]
Hi! Lemme look today

**Comment by dangrous** [comment]
Wow I sure don't remember anything about this issue, haha. If we're still able to consistently reproduce, I'd think we should try to have some contributors take another look at it, it might still be front end? It's not incredibly common I don't think, but would be nice to be fixed. Maybe we post it in Slack to encourage some fresh eyes on it.
