### ISSUE TITLE
Default distance rate is not selected when creating distance expense

### ISSUE THREAD

**Issue by nlemma** [Expensify/App#72328]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.2.29-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/71529
**Email or phone of affected tester (no customers):** expensify416+da2@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** macOS chrome 14.2, mWeb, Android, Desktop
**App Component:** Money Requests

## Action Performed:
1. Create a new workspace 
2. Enable Distance Rates
3. Add two new rates 
4. Rename the two new rates to A, and B
5. Go to workspace chat 
4. Click + > Track distance > select start and end way points > Next 
5. Click on Rate

## Expected Result:
The default rate should be preselected

## Actual Result:
Rate "A" is preselected

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b384893a-6097-45df-80bc-86afdd4b0cd3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
This was fixed by the revert, so it seems like the next step is for @nyomanjyotisa back to https://github.com/Expensify/App/issues/70194 to come up with a different solution, right?

**Comment by nyomanjyotisa** [comment]
Just to clarify, the PR hasn't been reverted, and the behavior is still occurring. As mentioned in my [previous comment](https://github.com/Expensify/App/issues/72328#issuecomment-3393389783), I think we could consider adding an explicit `createdAt`, `sortOrder`, or `isDefault` field from the backend. I'd be curious to hear your thoughts on this approach @francoisl

**Comment by nyomanjyotisa** [comment]
Sounds good! I’ll raise the PR once the backend change is ready. Thanks for the update

**Comment by francoisl** [comment]
Backend PR is in review.

**Comment by francoisl** [comment]
Yeah sorry the change is merged but not deployed yet. I'll let you know when it's deployed.

**Comment by suneox** [comment]
## BugZero Checklist

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    https://github.com/Expensify/App/pull/71529#issuecomment-3581490286

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

    N/A: This isn’t an impactful bug, as it only changes the default selected distance rates.

**Comment by garrettmknight** [comment]
$250 approved for @suneox
