### ISSUE TITLE
[$250] Expense - Remove hold option is missing for the last split after deleting all the splits

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#73384]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.37-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/72086
**Email or phone of affected tester (no customers):** applausetester+jsndjdsj111@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.5 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Log in with Expensifail account.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense.
4. Open the transaction thread.
5. Click More > Hold.
6. Enter reason and save it. 
7. Click More > Split.
8. Click Save.
9. Open any split.
10. Click More > Edit splits.
11. Click on any split.
12. Click Remove split.
13. Click Save.
14. Click More.
→ Remove hold option is missing.
15. Go back to main workspace chat.
16. Right click on the expense preview.
→ Remove hold option is missing.

## Expected Result:
Remove hold option should be present for the last split after deleting all the splits.

## Actual Result:
Remove hold option is missing for the last split after deleting all the splits.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/20ceea1c-245e-4d34-ac40-bb9b5f03aaec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021985847979894946866</li>
        <li>Upwork Job ID: 1985847979894946866</li>
        <li>Last Price Increase: 2025-11-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Valforte</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove hold option is missing after split and then remove one of the splits.

### What is the root cause of that problem?
The Remove hold will only show in one transaction report if only a single IOU action is found.
https://github.com/Expensify/App/blob/8ebf129d767097bcec39bacf95b592d7b0eb57f4/src/libs/ReportActionsUtils.ts#L1361-L1374

However, the deleted IOU action is still included. It's because we include the deleted IOU action if it has a `originalMessage?.IOUTransactionID`.

### What changes do you think we should make in order to solve the problem?

I think what the logic is trying to do is that, it requires the IOU action to have `IOUTransactionID`, but in case it's a pending deleted action (and offline), then we will still include the IOU action even if it doesn't have `IOUTransactionID`. But this causes a deleted IOU action to be included.

So, we can update the logic to:
```
const isPendingDelete = action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE;
if (
    actionType &&
    iouRequestTypesSet.has(actionType) &&
    !!originalMessage?.IOUTransactionID &&
    (!isDeletedAction(action) || (isPendingDelete && (isOffline ?? isNetworkOffline)))
) {
```

**Comment by JmillsExpensify** [comment]
Opened up for proposals/review

**Comment by JmillsExpensify** [comment]
Done, so we should have a confirmation in the next day.

**Comment by bernhardoj** [comment]
The BE issue still happens https://github.com/Expensify/App/issues/73384#issuecomment-3532047565. The FE part is already fixed on this [PR](https://github.com/Expensify/App/pull/75953).

**Comment by Valforte** [comment]
Found the issue, BE PR on the works

**Comment by JmillsExpensify** [comment]
Looks like we're still working on resolving the BE issue.

**Comment by Valforte** [comment]
Back working on implementing the fix for this issue

**Comment by Valforte** [comment]
BE PR is open for review!

**Comment by Valforte** [comment]
Issue is fixed with the backend changes
