### ISSUE TITLE
[Hold for #73847] Expense - Expense receipt is not editable when added during Submit it to someone flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#73769]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://test-management.browserstack.com/projects/2219752/test-runs/TR-1556/folder/13176877/41237352/979827781
**Email or phone of affected tester (no customers):** ojsdoibojsodsid@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Account has self DM and a workspace
1. Go to staging.new.expensify.com
2. Go to self DM
3. Create a manual expense without receipt
4. Click Submit it to someone
5. Select the workspace
6. On confirm page, enter merchant and add a receipt
7. Click Create expense
8. Open the expense report
9. Click on the receipt

## Expected Result:
3-dot menu will be displayed with the options to delete, replace and download receipt

## Actual Result:
Only download option is shown. The receipt is read-only and not editable

## Workaround:
Unknown

## Platforms:
Select the officially supported platforms where the issue was reproduced:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

<details>
  <summary>Platforms Tested:</summary>
On which of our officially supported platforms was this issue tested:

- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

</details> 

https://github.com/user-attachments/assets/48aa1b42-ffcb-4e33-9617-c1a8c896fd50

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
> When i get to step 7 in the reproduction steps on staging, I am seeing this error. Is anyone else seeing the same? It prevents reproducing this bug.
> 
> <img alt="Image" width="1510" height="796" src="https://private-user-images.githubusercontent.com/54866469/507686193-df2b06be-7489-4ddb-9375-273ca119977a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE4MzQ5NDYsIm5iZiI6MTc2MTgzNDY0NiwicGF0aCI6Ii81NDg2NjQ2OS81MDc2ODYxOTMtZGYyYjA2YmUtNzQ4OS00ZGRiLTkzNzUtMjczY2ExMTk5NzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDMwVDE0MzA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwOGJjYmUzMjAxMTc4YWFhOWM0ZTcyZjZjYTMzNTNlZjIxMmQ5Y2FmNDg1M2EyNDNlNDdiZDkzODNhNzI5YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JO2dJtb6eSb4D9RTi70ibIUUR9I2XBb2VnC-RruxwTY">

Yeah I also encountered so I had to test it via new account 👍

**Comment by joekaufmanexpensify** [comment]
@FitseTLT Interesting. You are not seeing the error I had above in a new account? I tried creating two different new accounts and still can't get past that error.

**Comment by joekaufmanexpensify** [comment]
Retested and this is fixed now. Closing!

**Comment by FitseTLT** [comment]
It is still reproducible @joekaufmanexpensify now

https://github.com/user-attachments/assets/6c8adda0-2b41-482d-9f6f-ba0aa791e731
