### ISSUE TITLE
[Due for payment 2025-11-26] [$125] Reports-“Workspace” option and header not translated in Reports filter

### ISSUE THREAD

**Issue by nlemma** [Expensify/App#74598]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9.2.46-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** N
**Email or phone of affected tester (no customers):** Slottwo1alefish@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Redminote 10s android 13
**App Component:** User Settings

## Action Performed:
Pre-condition: Note: Issue is reproduced in all Languages. Bug is reproduced for French language for example.

Set language to French 
1. Go to https://staging.new.expensify.com/home
2. Login with a new gmail account 
3. Create a workspace
4. Go to reports - filters
5. In type section, note last option " workspace" is shown in English 
6. Tap on workspace
7. Note header text workspace also displayed in English

## Expected Result:
Both the option label and header should be translated to French as “Espace de travail.”

## Actual Result:
When the app language is set to French, the last option under the “Type” section and its header are still displayed as “Workspace” in English.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [x] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e2fb2b51-a321-442b-b2c8-d66ed7ef5ea3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021987519666508227723</li>
        <li>Upwork Job ID: 1987519666508227723</li>
        <li>Last Price Increase: 2025-11-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by mukhrr** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
“Workspace” option and header not translated in Reports filter
P.s: I couldn't reproduce issue other than Polish and Portuegese (BR)

### What is the root cause of that problem?
We write as is in English in Polish and Portugese lang. files

https://github.com/Expensify/App/blob/7c9e982b1338db360e6e906c1cf80f689be42566/src/languages/pt-BR.ts#L3545

https://github.com/Expensify/App/blob/7c9e982b1338db360e6e906c1cf80f689be42566/src/languages/pl.ts#L3543

### What changes do you think we should make in order to solve the problem?
Need to translate own language

### What alternative solutions did you explore? (Optional)

**Comment by daledah** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the app language is set to French, the last option under the “Type” section and its header are still displayed as “Workspace” in English.

### What is the root cause of that problem?

We don't translate workspace here

https://github.com/Expensify/App/blob/7c9e982b1338db360e6e906c1cf80f689be42566/src/languages/pl.ts#L3543

### What changes do you think we should make in order to solve the problem?


We should translate it into all languages

Note 1: In search filter action we also mistranslate the `payer` and `exporter` here (it should be `Payé` and `Exporté`) (we should also need to check all actions in search filter page)

<img width="299" height="232" alt="Image" src="https://github.com/user-attachments/assets/65dbd155-52ae-468d-806d-fa5eb686d294" />

https://github.com/Expensify/App/blob/7c9e982b1338db360e6e906c1cf80f689be42566/src/languages/fr.ts#L6334-L6339

Note 2: We also need to fix other languages that has the same problems

### What alternative solutions did you explore? (Optional)



**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by prolahcen** [comment]
I will make sure the strings related to "Workspace" should be in French for the FR version, this seems some strings left untranslated or bad calling strings.

**Comment by srikarparsi** [comment]
Yes, let's please fix the other translation issues in this PR as well.

**Comment by mukhrr** [comment]
[PR](https://github.com/Expensify/App/pull/74984) is ready

**Comment by mukhrr** [comment]
@mananjadhav we have new [PR](https://github.com/Expensify/App/pull/75521) after QA team [reproduced](https://github.com/Expensify/App/pull/74984#issuecomment-3549567734) original issue again

**Comment by mananjadhav** [comment]
@mukhrr I saw the new PR. Can you tell me why we need this PR? I also see we're moving the workspace nesting to the parent level. I am not sure why this is needed.

**Comment by mukhrr** [comment]
@mananjadhav sorry for late response. You can reproduce this when there is not workspace and you go to filters first, then create a new workspace -> go to preferences -> change language -> go to filters -> workspace is not translated.

(refreshing page resolves issue and you can re-reproduce by deleting workspace and re-creating)

My current [PR](https://github.com/Expensify/App/pull/75521) doesn't fix it. working on it now

**Comment by mananjadhav** [comment]
Not using the nested key shouldn't be the root cause of translation not working. @srikarparsi wdyt?

**Comment by mukhrr** [comment]
> [@srikarparsi](https://github.com/srikarparsi) May be we can treat this as a separate issue as it relates to the translation not working fine. The original issue dealt with the header and now we're talking about the filters in the RHP.

I agree! We fixed here another issue (which seems related to original issue here, but not) with minimal bounty. Original issue seems more confusing to fix. And we can address to it in a new PR? This just my opinion. Correct me, pls, if I am wrong. cc @srikarparsi

**Comment by elhassanmayn** [comment]
We understand that some sections still show untranslated text.
Let's deal with this in a separate issue.

**Comment by elhassanmayn** [comment]
Contributor details
Your Expensify account email: elhassanmayn@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/mayanel3

**Comment by mananjadhav** [comment]
Quick bump @srikarparsi on the previous comments.

**Comment by mananjadhav** [comment]
Thanks for confirming @srikarparsi .

@twisterdotcom Can you post the payout summary for this one?

I don't think a checklist is needed here. I think the automation failed for the translation, so offending PR. We already have the regression test for the translations.
