### ISSUE TITLE
[HOLD for payment 2022-10-05] [$250] Tapping on  receipts@expensify.com email hides the clipboard icon next to it - reported by @aswin-s

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9233]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to workspace settings.
2. Tap on reimburse expense menu and tap on [receipts@expensify.com](mailto:receipts@expensify.com) link below Capture receipts section
3. Notice that the clipboard icon next to the email gets hidden and the check mark icon is not shown.

## Expected Result:
Clipboard icon gets replaced with a check mark icon indicating email has successfully been copied to clipboard.

## Actual Result:
Tapping on  [receipts@expensify.com](mailto:receipts@expensify.com) email hides the clipboard icon next to it.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.169-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/171088428-74102ff6-5e69-4112-ba4c-5bbf4a113793.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aswin-s
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650894949713889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
I couldn't repro this on Android and on ios when I tap on [receipts@expensify.com](mailto:receipts@expensify.com) the app crashes.

https://user-images.githubusercontent.com/83179295/171180930-3f9b18e0-a58b-4e4b-9c5e-1e28a5290266.mov

**Comment by thesahindia** [comment]
@zanyrenney, no one is assigned here.

**Comment by dhairyasenjaliya** [comment]
**Proposal**

- We need to replace the `<Text>` component with `<TouchableOpacity>`  as we need to have an onPress event on the component in order a copy email to the clipboard 
- onPress on `<Text>` works as excepted on all the other platforms except the iOS app

https://github.com/Expensify/App/blob/d037a999e5e20993c6ee3537be338e215654a751/src/components/CopyTextToClipboard.js#L56-L70

**Results**

**iOS App**

https://user-images.githubusercontent.com/47522946/188895358-407e394e-16e4-439b-ac33-66e983891e99.mp4


**Mobile Safari**


https://user-images.githubusercontent.com/47522946/188895291-47282271-b0c2-47af-a719-cdb723ac2c85.mp4



**Chrome Web**

https://user-images.githubusercontent.com/47522946/188895220-c26cf1f2-3963-4c17-b3da-95d5c1e85361.mov



**Safari Web**

https://user-images.githubusercontent.com/47522946/188895175-b6a984b2-8632-4aff-9bac-43bc3bbbb0b4.mov

**Comment by dhairyasenjaliya** [comment]
@mvtglobally this issue is not assigned to anyone can we have a reviewer here?

**Comment by dhairyasenjaliya** [comment]
@michaelhaxhiu sorry to bump you here but can we also get a C+ reviewer here as well seems no one is assigned to issue

**Comment by pecanoro** [comment]
Oh actually, this seems to have been fixed and I can't reproduce it so I am going to close it.

Sorry for the trouble, I guess @zanyrenney didn't see the ping and forgot to assign engineering to it.

**Comment by dhairyasenjaliya** [comment]
@pecanoro still reproducible an issue in iOS app on the latest version notice click on mail hides the icon completely 

https://user-images.githubusercontent.com/47522946/191737700-97d9f572-cce4-435f-8126-cad1055f851a.MP4

<img src=https://user-images.githubusercontent.com/47522946/191737721-3353b9a2-1997-49b8-a872-7a953ebc53e1.PNG  width=50%>

**Comment by pecanoro** [comment]
Ok, I will reassign everyone then and reopen

**Comment by mananjadhav** [comment]
I agree with @aimane-chnaif analysis, thanks for the detailed explanation. Your proposal looks good to me @aimane-chnaif .

🎀 👀 🎀 
C+ reviewed

**Comment by dhairyasenjaliya** [comment]
@mananjadhav have you taken a look at my first proposal here https://github.com/Expensify/App/issues/9233#issuecomment-1239420695
or which analysis do you agree

**Comment by mananjadhav** [comment]
@dhairyasenjaliya I did, and I agreed with @aimane-chnaif analysis for most items. 

I don't recommend wrapping `TouchableOpacity` inside a `Text` and it generally causes problems with styling, wrapping of texts, etc. + this issue is only in iOS and I've used `supressedHighlighting` with 0 side effects. Another way to achieve this is to use Pressable which really requires us to rewrite multiple things, so I wouldn't recommend that either.

**Comment by dhairyasenjaliya** [comment]
alright, I was just confirming thank you @mananjadhav

**Comment by kadiealexander** [comment]
@roryabraham happy to proceed here?

**Comment by roryabraham** [comment]
PR merged

**Comment by mananjadhav** [comment]
@kadiealexander Quick bump on the upwork

**Comment by kadiealexander** [comment]
@mananjadhav @roryabraham could you please confirm this PR isn't linked to a regression?

**Comment by mananjadhav** [comment]
@kadiealexander I can confirm this isn't linked to the regression. Regression comment by the bot was due to this comment https://github.com/Expensify/App/issues/11430#issuecomment-1267974113

**Comment by kadiealexander** [comment]
Sorry team, I didn't realise an Upwork post never got created for this job. I've sent everyone a contract, please let me know once it's accepted and I'll issue payment.
https://www.upwork.com/ab/applicants/1578236341784473600/job-details
https://www.upwork.com/jobs/~01f99f997919d5ab90

**Comment by kadiealexander** [comment]
Manan and Aswin have been paid! Thanks to you both.

**Comment by kadiealexander** [comment]
Everyone is paid!
