### ISSUE TITLE
[$500] :pencil2: icon is shown for archived chats - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9408]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Navigate to the announce room for that workspace
3. Type something in the composer
4. Delete the workspace

## Expected Result:
The draft should get cleared and  :pencil2: icon shouldn't be shown

## Actual Result:
You will see :pencil2: icon

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.75-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/173274359-c5355328-7f33-4947-a58e-d8c87cee5a10.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652951524576589
Reported again here: https://expensify.slack.com/archives/C01GTK53T8Q/p1666204335556309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
Good one.

**Comment by srikarparsi** [comment]
changed to weekly, need to use the new API refactoring doc instead of just changing the front end.

**Comment by srikarparsi** [comment]
commented on N7 doc to include this change, on hold until it's finished

**Comment by srikarparsi** [comment]
^^

**Comment by srikarparsi** [comment]
^^

**Comment by srikarparsi** [comment]
^^

**Comment by srikarparsi** [comment]
^

**Comment by srikarparsi** [comment]
^

**Comment by srikarparsi** [comment]
^

**Comment by srikarparsi** [comment]
^

**Comment by srikarparsi** [comment]
^

**Comment by srikarparsi** [comment]
^

**Comment by srikarparsi** [comment]
Issue got fixed with the API refactor, closing it out.

<img width="377" alt="Screen Shot 2022-10-04 at 8 04 17 PM" src="https://user-images.githubusercontent.com/48188732/193952137-c4af6d27-0486-43d7-84f9-135ce29d4f82.png">

**Comment by thesahindia** [comment]
@srikarparsi, it's still reproducible. It was just reported [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1666204335556309)
cc: @adeel0202

**Comment by srikarparsi** [comment]
interesting, thanks for the heads up, reopening

**Comment by dhairyasenjaliya** [comment]
**Proposal**

- Reason why the pencil icon doesn't go away because we never add any validation to check if the room is archived or not 
- Based on the status we can show/hide the pencil icon
- Here we need to add one more validation like below

https://github.com/Expensify/App/blob/0c5642ff79fa174bdefb8033625882be71792596/src/components/LHNOptionsList/OptionRowLHN.js#L197-L201

 ```JS
  {optionItem.hasDraftComment && !optionItem.isArchivedRoom && (
       <View style={styles.ml2}>
           <Icon src={Expensicons.Pencil} height={16} width={16} />
       </View>
  )}
 ```
 
 
**Result**
<img width="1435" alt="Screenshot 2022-10-20 at 10 27 47 AM" src="https://user-images.githubusercontent.com/47522946/196860009-c94ccceb-5084-4192-92fb-8ff69799c3a3.png">


**Current Code**
<img width="1440" alt="Screenshot 2022-10-20 at 10 29 09 AM" src="https://user-images.githubusercontent.com/47522946/196860150-5c5c24d1-32d6-48f8-bce8-4026deaa0b7b.png">

**Comment by srikarparsi** [comment]
looks good, marking the issue as external and assigning you to the issue so you can get compensated.

**Comment by srikarparsi** [comment]
@parasharrajat, @dhairyasenjaliya's solution looks good to me so we don't need to review proposals.

**Comment by adeel0202** [comment]
This ticket was closed because the bug was supposed to be fixed. Yesterday, I encountered this bug and reported it [on slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1666204335556309). Its [ticket](https://github.com/Expensify/App/issues/12024) was also created but then it was closed because this one has been reopened. So I think along with @thesahindia, I'm eligible for the reporting bonus too. Thanks.
cc: @srikarparsi @tjferriss

**Comment by parasharrajat** [comment]
Generally, only one person is eligible for reporting. I am not sure how come two persons can contribute to the same bug report.

**Comment by adeel0202** [comment]
@parasharrajat had I not reported this bug, this ticket would still have been closed and the bug would still be there. 
Also, I'm sure you must've seen other similar cases where two persons were credited for the same bug. However, if others think I should not be compensated, I'm fine with it.

**Comment by parasharrajat** [comment]
That's why I said _Generally_.

**Comment by thesahindia** [comment]
I believe @adeel0202 is eligible for the compensation in this case. 
Asking internally to get some eyes on it.

**Comment by parasharrajat** [comment]
I don't like the [proposal](https://github.com/Expensify/App/issues/9408#issuecomment-1285018893) here. 

> Reason why the pencil icon doesn't go away because we never add any validation to check if the room is archived or not

The reason is simply that no one can add drafts to achieved chats.  Adding validations/check for cases that are not possible in the business logic is just not the correct approach.

**Comment by srikarparsi** [comment]
I didn't think about it that way @parasharrajat but I agree with you. Since we're storing at max one report comment for an archived chat in onyx which clears when the app is quit or signed out of, it seemed like an ok proposal. But you're right, good catch, we shouldn't be adding these checks for cases that are not possible so let's see if any other proposals come up. @dhairyasenjaliya, unassigning you for now.

**Comment by dhairyasenjaliya** [comment]
Agreed @parasharrajat will try to solve it with the correct approach 
sure @srikarparsi

**Comment by tjferriss** [comment]
Upworks post is live - https://www.upwork.com/jobs/~019dc712cf78819fe3

**Comment by thesahindia** [comment]
Just wanna inform that we both ( @adeel0202 and I ) are eligible for the reporting compensation. Confirmed it [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1666286567398999).

**Comment by parasharrajat** [comment]
No proposals.

**Comment by tjferriss** [comment]
💰Price Doubled to $500💰
Upworks post - https://www.upwork.com/jobs/~019dc712cf78819fe3

**Comment by dhairyasenjaliya** [comment]
**Proposal**

- Since we are checking the `hasDraft` key to show/hide the pencil icon from onyx we should add `false` to `hasDraft` when we are deleting the workspace 

- Here in `...map` we are getting all reports from a selected workspace with `hasDraft` value so adding `false` to  `hasDraft` will remove the pencil icon from all workspace reports 

https://github.com/Expensify/App/blob/e1e865027e021249130ef1185021ac0f21a74a32/src/libs/actions/Policy.js#L114-L132

```js
 ..._.map(reports, ({reportID}) => ({
            onyxMethod: CONST.ONYX.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
            value: {
                stateNum: CONST.REPORT.STATE_NUM.SUBMITTED,
                statusNum: CONST.REPORT.STATUS.CLOSED,
                ++ hasDraft: false,
            },
        })),
```
        
**Result**

https://user-images.githubusercontent.com/47522946/198696013-d17d1161-680d-4088-8c47-1cf07ebd47e9.mov

- I do think this should work since we are clearing the `hasDraft` value at the time of deleting @parasharrajat

**Comment by parasharrajat** [comment]
You forgot to add the handling for failure. But that is just the reverse of optimistic data. 

This will not delete the stored draft comment. But I think that is useful. In case of failure, we revert the archived state of the chat, thus it would be useful to show the previous draft as well. 

And bcz drafts are not saved on the backend, it won't create an issue in the long run. Logging out will clear the drafts etc. 

@dhairyasenjaliya's [proposal](https://github.com/Expensify/App/issues/9408#issuecomment-1295266098) looking good to me. 

cc: @srikarparsi 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by dhairyasenjaliya** [comment]
hm @parasharrajat  should we add `hasDraft` to `failureData` for restoring the old report's draft status, was having a bit of doubt so didn't add it in the proposal 

<img width="531" alt="Screenshot 2022-10-31 at 8 53 40 AM" src="https://user-images.githubusercontent.com/47522946/198925021-a070cb57-8909-4aab-837e-af100fa09a1b.png">

**Comment by parasharrajat** [comment]
yup, that is correct.

**Comment by parasharrajat** [comment]
This issue is still awaiting decision.

**Comment by srikarparsi** [comment]
yup, this is a lot better, thank you @dhairyasenjaliya and @parasharrajat

**Comment by tjferriss** [comment]
@dhairyasenjaliya and @srikarparsi can you please both apply to the job posting on Upworks? https://www.upwork.com/ab/applicants/1583574303161114624/job-details

**Comment by tjferriss** [comment]
Whoops tagged the person. @parasharrajat can you also please apply in Upworks? https://www.upwork.com/ab/applicants/1583574303161114624/job-details

**Comment by tjferriss** [comment]
@dhairyasenjaliya has been hired in Upworks.

**Comment by dhairyasenjaliya** [comment]
bump @tjferriss PR is in production for 8 days I think this is ready to close 

<img width="1306" alt="Screenshot 2022-11-13 at 9 58 45 AM" src="https://user-images.githubusercontent.com/47522946/201505745-dcff98b3-6125-4915-a70f-3f45b7e44bda.png">

**Comment by tjferriss** [comment]
@dhairyasenjaliya I've processed your payment. @parasharrajat can you apply to the Upworks job so I can process your payment as the C+?

**Comment by parasharrajat** [comment]
Could you please share the job link? the above link is internal.

**Comment by tjferriss** [comment]
Ah sorry, here you go https://www.upwork.com/jobs/~019dc712cf78819fe3

**Comment by thesahindia** [comment]
@tjferriss, I have applied to the job for the reporting compensation that was missed earlier. https://github.com/Expensify/App/issues/9408#issuecomment-1292657945

**Comment by parasharrajat** [comment]
Can't blame me, the issue should have been updated to have your name. :sweat_smile:

**Comment by tjferriss** [comment]
Sorry for the delay. I've hired you all for the job in Upworks so once you accept I can process the payment.

**Comment by tjferriss** [comment]
Thanks for catching that, my mistake. Ok I've paid everyone out and closed the job in Upworks so I think we can close this out.

**Comment by thesahindia** [comment]
@tjferriss, I just accepted the offer (missed earlier)

> you've sent me a $500 offer.

Same case

**Comment by dhairyasenjaliya** [comment]
@tjferriss can you close the Upwork contract it still shows  `Ongoing`

**Comment by tjferriss** [comment]
Ok payments have been sent and contracts ended.
